"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";

async function authorised(org: string) { const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return; const context = await resolveClubOrganisationContext(client, user.id, org); if (!context || !(await context.repository.hasCapability(org, user.id, "members.import"))) return; return { client, user }; }
export async function stageMemberImportAction(input: { organisationId: string; filename: string; checksum?: string; headers: string[]; mapping: Record<string, string | undefined>; rows: unknown[] }) { try { const value = await authorised(input.organisationId); if (!value || !input.filename.trim() || input.rows.length > 10000) return { ok: false, error: "Import access or file is invalid." }; const { data, error } = await value.client.rpc("club_create_member_import_batch", { p_organisation_id: input.organisationId, p_filename: input.filename, p_checksum: input.checksum ?? null, p_headers: input.headers, p_mapping: input.mapping, p_rows: input.rows }); if (error) return { ok: false, error: "The member file could not be staged." }; revalidatePath("/club/members/import"); return { ok: true, batch: data }; } catch { return { ok: false, error: "The member file could not be staged." }; } }
export async function authoriseMemberImportAction(organisationId: string, batchId: string) { try { const value = await authorised(organisationId); if (!value) return { ok: false, error: "Import access required." }; const { data, error } = await value.client.rpc("club_confirm_member_import_batch", { p_organisation_id: organisationId, p_batch_id: batchId }); if (error) return { ok: false, error: "Resolve blocking issues before authorising." }; revalidatePath("/club/members/import"); return { ok: true, batch: data }; } catch { return { ok: false, error: "Import could not be authorised." }; } }
export async function mapMemberImportPackageAction(input: { organisationId: string; batchId: string; sourcePackage: string; clubProductId: string }) { try { const value = await authorised(input.organisationId); if (!value) return { ok: false, error: "Import access required." }; const { error } = await value.client.rpc("club_map_member_import_package", { p_organisation_id: input.organisationId, p_batch_id: input.batchId, p_source_package: input.sourcePackage, p_club_product_id: input.clubProductId, p_status: "mapped" }); if (error) return { ok: false, error: "Package mapping could not be saved." }; revalidatePath("/club/members/import"); return { ok: true }; } catch { return { ok: false, error: "Package mapping could not be saved." }; } }
export async function executeMemberImportAction(organisationId: string, batchId: string) { try { const value = await authorised(organisationId); if (!value) return { ok: false, error: "Import access required." }; const { data, error } = await value.client.rpc("club_execute_member_import_batch", { p_organisation_id: organisationId, p_batch_id: batchId }); if (error) return { ok: false, error: "Import could not be completed." }; revalidatePath("/club/members"); revalidatePath("/club/members/import"); return { ok: true, batch: data }; } catch { return { ok: false, error: "Import could not be completed." }; } }
