/* eslint-disable react-hooks/error-boundaries */
import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { ClubSectionNav } from "@/components/club-shell";
import { AppShell, BackButton, EmptyState, PageHeader, Surface } from "@/components/ui";
import { resolveClubOrganisationContext, isClubStaffRole } from "@/lib/club-server-context";
import { serverSupabase } from "@/lib/supabase-server";
export default async function ClubServicesPage({ searchParams }: { searchParams?: Promise<{ org?: string }> }) {
  const supabase = await serverSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account?mode=signIn"); const context = await resolveClubOrganisationContext(supabase, user.id, (await searchParams)?.org);
  if (!context || !isClubStaffRole(context.role)) return <AppShell className="module-page club-page"><PageHeader title="Services" description="Service operations access is restricted." /><EmptyState title="Club access required">Choose an authorised organisation.</EmptyState><AppNav /></AppShell>;
  try { const [services, locations] = await Promise.all([context.repository.listServices(context.organisation.id), context.repository.listLocations(context.organisation.id)]); const locationById = new Map(locations.map(location => [location.id, location.name])); return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · SERVICES" title="Services" description="Venue-specific offerings, credits and fulfilment." /><ClubSectionNav organisation={context.organisation} role={context.role} contexts={context.availableContexts} />{services.length ? <Surface><div className="section-header"><div><span className="eyebrow">SERVICE CATALOGUE</span><h2>Configured services</h2></div></div>{services.map(service => <div className="club-detail-row" key={service.id}><div><strong>{service.name}</strong><span className="muted">{service.category} · {service.locationId ? locationById.get(service.locationId) ?? "Organisation location" : "All locations"}</span></div><span className="muted">{service.priceMinor === undefined ? "Rate on request" : `£${(service.priceMinor / 100).toFixed(2)} ${service.currency}`} · {service.active ? "Active" : "Inactive"}</span></div>)}</Surface> : <Surface className="club-empty-panel"><div className="empty-state"><span className="eyebrow">SERVICE OPERATIONS</span><strong>No services have been configured yet</strong><p>Services are set up for individual venues and can then be booked, paid for and fulfilled here.</p></div></Surface>}<BackButton href={`/club?org=${encodeURIComponent(context.organisation.id)}`}>Back to overview</BackButton><AppNav /></AppShell>; } catch { return <AppShell className="module-page club-page"><PageHeader title="Services" /><EmptyState title="Services couldn’t be loaded.">Try again shortly.</EmptyState><AppNav /></AppShell>; }
}
