"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
export async function saveClubPromotionAction(input: { organisationId:string; name:string; description?:string; startsAt:string; endsAt?:string; effectType:"percentage_discount"|"fixed_discount"|"waive_charge"; percentageBasisPoints?:number; amountMinor?:number; eligibility?:Record<string,unknown> }) { const client=await serverSupabase(); const {data:{user}}=await client.auth.getUser(); if(!user) return {ok:false,error:"Sign in required."}; const context=await resolveClubOrganisationContext(client,user.id,input.organisationId); if(!context || !(await context.repository.hasCapability(input.organisationId,user.id,"commerce.pricing_manage"))) return {ok:false,error:"Promotion management access required."}; try { const starts = new Date(input.startsAt); const status = starts.getTime() > Date.now() ? "draft" : "active"; await context.repository.savePromotion({organisationId:input.organisationId,name:input.name.trim(),description:input.description?.trim(),status,startsAt:input.startsAt,endsAt:input.endsAt,locationIds:[],eligibility:{stacking:"exclusive",priority:0,...(input.eligibility??{})},createdBy:user.id,effects:[{id:"",promotionId:"",effectType:input.effectType,percentageBasisPoints:input.percentageBasisPoints,amountMinor:input.amountMinor}]}); revalidatePath("/club/promotions"); return {ok:true}; } catch { return {ok:false,error:"Promotion could not be saved."}; } }

export async function configureGsnPotOGoldPromotionAction(input: { organisationId: string }) {
  const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return { ok: false, error: "Sign in required." };
  const context = await resolveClubOrganisationContext(client, user.id, input.organisationId);
  if (!context || !(await context.repository.hasCapability(input.organisationId, user.id, "commerce.pricing_manage"))) return { ok: false, error: "Promotion management access required." };
  const { data: products, error: productError } = await client.from("club_commerce_products").select("id").eq("organisation_id", input.organisationId).eq("brand", "GSN").like("category", "GSN:%");
  if (productError) return { ok: false, error: "GSN products could not be inspected." };
  const productIds = (products ?? []).map(row => String(row.id)); if (!productIds.length) return { ok: false, error: "Import current GSN products before configuring the promotion." };
  const eligibility = { stacking: "exclusive", priority: 100, bundle_groups: [{ group_id: "gsn-all-products", required_quantity: 10, product_ids: productIds }], bundle_price_minor: 3200, repeatable: true };
  const existing = (await client.from("club_promotions").select("id").eq("organisation_id", input.organisationId).eq("name", "GSN 10 Meals for £32").maybeSingle()).data;
  const { data: promotion, error } = await client.rpc("club_save_promotion", { p_id: existing?.id ?? null, p_organisation_id: input.organisationId, p_name: "GSN 10 Meals for £32", p_description: "Mix and match ten current GSN meals for £32.", p_status: "active", p_starts_at: new Date().toISOString(), p_ends_at: null, p_location_ids: [], p_eligibility: eligibility, p_effects: [{ effect_type: "fixed_discount", amount_minor: 800 }] });
  if (error || !promotion) return { ok: false, error: "GSN promotion could not be configured." };
  const promotionId = String((promotion as Record<string, unknown>).id); const { error: targetError } = await client.rpc("club_save_promotion_targets", { p_promotion_id: promotionId, p_targets: productIds.map(commerce_product_id => ({ target_type: "commerce_product", commerce_product_id })) }); if (targetError) return { ok: false, error: "GSN promotion eligibility could not be configured." };
  revalidatePath("/club/promotions"); revalidatePath("/member-hub/shop"); return { ok: true, promotionId, eligibleProducts: productIds.length };
}

export async function setClubPromotionStatusAction(input:{organisationId:string; promotionId:string; status:"active"|"paused"}) {
  const client=await serverSupabase(); const {data:{user}}=await client.auth.getUser(); if(!user) return {ok:false,error:"Sign in required."}; const context=await resolveClubOrganisationContext(client,user.id,input.organisationId); if(!context || !(await context.repository.hasCapability(input.organisationId,user.id,"commerce.pricing_manage"))) return {ok:false,error:"Promotion management access required."}; const {error}=await client.from("club_promotions").update({status:input.status}).eq("id",input.promotionId).eq("organisation_id",input.organisationId); if(error) return {ok:false,error:"Promotion status could not be updated."}; revalidatePath("/club/promotions"); revalidatePath("/club/shop"); return {ok:true};
}
