"use client";
import { useState } from "react";
import { defaultTrainingProfile, type TrainingProfile } from "@/lib/training-profile";
import { generateTrainingProgramme, type GeneratedProgramme } from "@/lib/programme-generator";
import { saveTrainingProfile } from "@/lib/storage";
import { loadActiveWorkout } from "@/lib/storage";
import { exerciseById } from "@/lib/workout";
import { activeWorkoutsFromPayload } from "@/lib/programme-activation";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { brand } from "@/lib/brand";
import { builderQuestions, questionOptions } from "@/lib/onboarding-questions";

export default function OnboardingPage() {
  const router = useRouter(); const [step, setStep] = useState(0); const [profile, setProfile] = useState<TrainingProfile>(defaultTrainingProfile); const [programme, setProgramme] = useState<GeneratedProgramme>(); const [message, setMessage] = useState(""); const [activating, setActivating] = useState(false);
  const question = builderQuestions[step]; const choose = (value: string | number | boolean) => { const key = question[0]; const arrayKey = key === "priorities" || key === "wantedExercises" || key === "avoidedExercises"; const nextValue = arrayKey ? (value ? [value] : []) : value; const availability = key === "availabilityMode" && value === "fixed_days" ? { availabilityMode: value, availableDays: [1, 2, 3, 4, 5] } : {}; const nextProfile = { ...profile, [key]: nextValue, ...availability } as TrainingProfile; setProfile(nextProfile); if (step < builderQuestions.length - 1) setStep(step + 1); else setProgramme(generateTrainingProgramme(nextProfile, undefined, crypto.randomUUID().slice(0, 8))); };
  if (programme) return <main className="shell module-page"><p className="eyebrow">YOUR STARTING PROGRAMME</p><h1>{programme.name}</h1><p>{programme.rationale}</p>{message && <p role="alert">{message}</p>}<section className="card">{programme.week.map(day => <div className="plan-row" key={day.id}><b>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"][day.day - 1]}</b><span>{day.name}<small>{day.exerciseIds.map(id => { const exercise = exerciseById(id); const override = day.exerciseOverrides?.[id]; return `${exercise?.name ?? id} · ${override?.target ?? exercise?.target ?? "planned"}`; }).join(" · ")}</small></span></div>)}</section><button className="primary big" type="button" disabled={activating} onClick={async () => { if (activating) return; setActivating(true); setMessage(""); try { const localActive = loadActiveWorkout(); const guardResponse = await fetch("/api/workouts", { credentials: "same-origin" }); if (!guardResponse.ok) { setMessage("We couldn’t check your current workout. Please try again."); return; } const serverPayload = await guardResponse.json().catch(() => null); if (localActive || activeWorkoutsFromPayload(serverPayload).length > 0) { setMessage("Finish or discard your current workout before switching programmes."); return; } const response = await fetch("/api/training-profile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ trainingProfile: profile, generatedProgramme: programme }) }); if (!response.ok) { setMessage("We couldn’t save this programme. Your current programme hasn’t changed."); return; } const persisted = await response.json().catch(() => null); if (!persisted?.generated_programme || persisted.active_programme_id !== programme.id) { setMessage("We couldn’t confirm this programme was saved. Your current programme hasn’t changed."); return; } saveTrainingProfile(profile, persisted.generated_programme); router.push("/"); } catch { setMessage("We couldn’t start this programme. Please try again."); } finally { setActivating(false); } }}>{activating ? "Starting programme…" : "Start programme"} {!activating && <span>→</span>}</button><button className="secondary full" type="button" onClick={() => { if (!activating) { setProgramme(undefined); setStep(0); } }}>Change answers</button><Link className="text-button" href="/training">Cancel</Link></main>;
  return <main className="shell module-page"><p className="eyebrow">{brand.name} · {step + 1} OF {builderQuestions.length}</p><h1>{question[1]}</h1>{question[0] === "conditioningPreference" && <p className="muted">Conditioning means cardio or fitness work such as walking, cycling, rowing or intervals.</p>}<div className="empty-grid">{questionOptions(question).map(([value, label]) => <button type="button" className="secondary" key={`${question[0]}-${String(value)}`} onClick={() => choose(value)}>{label}</button>)}</div><button type="button" className="text-button" disabled={step === 0} onClick={() => setStep(step - 1)}>‹ Back</button><Link className="text-button" href="/training">Cancel</Link></main>;
}
