import assert from "node:assert/strict";
import test from "node:test";
import { exerciseKnowledge, exerciseLibrary } from "../lib/exercise-library";
import { defaultWorkingRepRange, magnitudeLoad, progressionProfile, rampBudgetFor, rampLoad, rampRepTarget } from "../lib/progression";
import { exercisesForSession, mondayExercises } from "../lib/workout";
import { adaptSession, assessReadiness, rescheduleWeek, substitutionFor } from "../lib/adaptive-coach";
import { currentWeek } from "../lib/domain";
import { cardioRecommendation, evaluateSet, restFor, snapAvailableLoad } from "../lib/coach";
import { cardioModalities, prescribeCardio } from "../lib/cardio";
import { consumeState, createState, normalizeWhoop, connectionStatus, decryptToken, encryptToken, statesMatch, WHOOP_CONNECTION_WRITE, sanitizedPersistenceDiagnostic } from "../lib/whoop-server";
import { shouldSyncReadiness } from "../lib/whoop-sync";
import { guideForExercise } from "../lib/exercise-guide";

test("exercise knowledge preserves specific intent", () => { const item = exerciseKnowledge("incline-db-press"); assert.ok(item?.emphasis.includes("upper chest emphasis")); assert.ok(item?.substitutions.includes("incline-machine-press")); assert.equal(item?.stabilityDemand, "medium"); });
test("current programme exercises have reusable guide data with safe fallbacks", () => { const ids = ["trap-bar-deadlift", "hack-squat", "leg-press", "bulgarian-split-squat", "hamstring-curl", "leg-extension", "calves", "incline-db-press", "lat-pulldown", "barbell-row", "cable-lateral-raise", "incline-db-curl", "rope-triceps-pushdown"]; const exercises = exercisesForSession(ids); for (const exercise of exercises) { const guide = guideForExercise(exercise); assert.ok(guide?.setup); assert.ok(guide?.execution); assert.ok((guide?.cues.length ?? 0) >= 2); assert.ok((guide?.primaryMuscles.length ?? 0) >= 1); } assert.equal(guideForExercise({ ...exercises[0], id: "unknown" }), undefined); });
test("dumbbell magnitude can make more than one increment when clearly underloaded", () => { const result = magnitudeLoad(mondayExercises[0], 20, 20, 10, 5); assert.equal(result, 26); });
test("leg press uses proportional plate-style ramp jumps", () => { const leg = { ...mondayExercises[0], id: "leg-press", name: "Leg Press", equipment: "machine" as const, stackIncrement: 5, defaultWorkingWeight: 300 }; assert.equal(progressionProfile(leg).kind, "plate_loaded_machine"); assert.equal(rampLoad(leg, 120, 300), 160); });
test("loading profiles distinguish movement and load semantics", () => {
  const trap = exercisesForSession(["trap-bar-deadlift"])[0];
  const leg = exercisesForSession(["leg-press"])[0];
  const lat = exercisesForSession(["cable-lateral-raise"])[0];
  const pull = exercisesForSession(["lat-pulldown"])[0];
  const pullup = exercisesForSession(["pull-up-practice"])[0];
  const dbCompound = { ...mondayExercises[0], loadingProfile: "dumbbell_compound" as const, loadUnit: "per_hand" as const };
  assert.equal(progressionProfile(trap).category, "heavy_plate_compound");
  assert.equal(progressionProfile(trap).unit, "total");
  assert.equal(progressionProfile(leg).category, "heavy_machine_compound");
  assert.equal(progressionProfile(dbCompound).category, "dumbbell_compound");
  assert.equal(progressionProfile(dbCompound).unit, "per_hand");
  assert.equal(progressionProfile(lat).category, "cable_machine_isolation");
  assert.equal(progressionProfile(pull).category, "selectorised_compound");
  assert.equal(progressionProfile(pullup).category, "bodyweight_assisted");
  assert.equal(progressionProfile(pullup).unit, "assistance");
});
test("profile policies scale ramps, reps, rest and progression without rewriting prescriptions", () => {
  const trap = exercisesForSession(["trap-bar-deadlift"])[0];
  const lateral = exercisesForSession(["cable-lateral-raise"])[0];
  const dbCompound = { ...mondayExercises[0], loadingProfile: "dumbbell_compound" as const, loadUnit: "per_hand" as const };
  assert.ok(rampBudgetFor(trap) > rampBudgetFor(lateral));
  assert.ok(rampLoad(trap, 40, 140) - 40 > rampLoad(lateral, 9, 14) - 9);
  assert.equal(rampRepTarget(trap, 1), "5–8");
  assert.equal(rampRepTarget(trap, 2, true), "1–3");
  assert.equal(rampRepTarget(lateral, 1), "8–12");
  assert.ok(restFor(trap, "working") > restFor(lateral, "working"));
  assert.equal(defaultWorkingRepRange(trap), "5–6");
  assert.equal(defaultWorkingRepRange(lateral), "12–15");
  assert.ok(magnitudeLoad(dbCompound, 20, 20, 10, 5) - 20 <= 6);
});
test("substitution explains and preserves intent", () => { const result = substitutionFor("incline-db-press", "pain"); assert.equal(result?.replacement, "Incline Machine Press"); assert.equal(result?.temporary, true); });
test("recovery input changes session demand without fake data", () => { assert.equal(assessReadiness({}).level, "READY"); assert.equal(adaptSession({ fatigue: true, recovery: { id: "r", date: "today", origin: "real", source: "manual", fatigue: 5 }, plannedSets: 18 }).action, "reduce_demand"); });
test("missed sessions remain missed and later plans remain planned", () => { const result = rescheduleWeek(currentWeek, [], "tue"); assert.equal(result.find(item => item.id === "tue")?.status, "missed"); assert.equal(result.find(item => item.id === "wed")?.status, "planned"); });
test("exercise library has a substantive initial catalogue", () => { assert.ok(exerciseLibrary.length >= 80); assert.ok(exerciseLibrary.every(item => item.primaryMuscles.length && item.intent.length && item.progression.length)); });
test("live coach uses magnitude-aware dumbbell progression", () => { const exercise = mondayExercises[0]; const result = evaluateSet(exercise, [{ id: "s", exerciseId: exercise.id, exerciseName: exercise.name, weight: 20, reps: 20, rir: 5, kind: "working", createdAt: "now" }]); assert.equal(result.nextWeight, 26); });
test("normal upper-body cardio keeps the exact baseline", () => { const result = cardioRecommendation(12, 0); assert.deepEqual(result, { duration: 40, incline: 8, speed: 5, why: "Normal session demand: complete the standard conditioning block." }); });
test("configured machine loads always snap to valid stack values", () => { const machine = { ...mondayExercises[3], validLoads: [5, 9, 14] }; assert.equal(snapAvailableLoad(7.5, machine), 9); assert.equal(snapAvailableLoad(10, machine, "up"), 14); assert.equal(snapAvailableLoad(10, machine, "down"), 9); });
test("genuine historical machine loads remain unchanged", () => { const machine = { ...mondayExercises[3], validLoads: [5, 9, 14] }; assert.equal((machine.validLoads ?? []).includes(9), true); assert.equal(snapAvailableLoad(9, machine), 9); });
test("cardio modalities expose appropriate metric schemas", () => { assert.equal(cardioModalities.length, 6); assert.deepEqual(cardioModalities.find(item => item.id === "incline_treadmill")?.metrics, ["duration", "incline", "speed"]); assert.ok(cardioModalities.find(item => item.id === "rower")?.metrics.includes("pace500m")); });
test("cardio choice preserves modality-specific prescription", () => { assert.deepEqual(prescribeCardio("incline_treadmill"), { modality: "incline_treadmill", duration: 40, settings: { incline: 8, speed: 5 }, why: "Complete the standard conditioning block." }); assert.equal(prescribeCardio("stairmaster").settings.level, undefined); });
test("WHOOP OAuth state is cryptographic, stateless and normalization keeps missing metrics absent", () => { const state = createState(); assert.equal(consumeState(state), true); assert.equal(consumeState(state), true); assert.equal(statesMatch(state, state), true); assert.equal(statesMatch(state, `${state}x`), false); const normalized = normalizeWhoop({ id: "cycle-1", created_at: "2026-08-30T10:00:00Z", score: { recovery_score: 72, strain: 8.4, sleep_performance_percentage: 81 } }); assert.equal(normalized.recoveryScore, 72); assert.equal(normalized.sleepPerformance, 81); assert.equal(normalized.strain, 8.4); assert.equal(normalized.hrv, undefined); assert.equal(connectionStatus().connected, false); });
test("WHOOP tokens are encrypted and 64-character hex keys are accepted as 32 bytes", () => { const previous = process.env.WHOOP_TOKEN_ENCRYPTION_KEY; process.env.WHOOP_TOKEN_ENCRYPTION_KEY = "ab".repeat(32); const ciphertext = encryptToken("access-secret"); assert.notEqual(ciphertext, "access-secret"); assert.equal(decryptToken(ciphertext), "access-secret"); process.env.WHOOP_TOKEN_ENCRYPTION_KEY = previous; });
test("WHOOP connection persistence is one deterministic user upsert", () => { assert.equal(WHOOP_CONNECTION_WRITE.table, "whoop_connections"); assert.equal(WHOOP_CONNECTION_WRITE.conflictTarget, "user_id"); assert.ok(WHOOP_CONNECTION_WRITE.columns.includes("updated_at")); const diagnostic = sanitizedPersistenceDiagnostic({ code: "23505", message: "constraint failed", details: "safe structural details" }); assert.deepEqual(diagnostic, { stage: "connection_persistence_failed", operation: "upsert", table: "whoop_connections", code: "23505", message: "constraint failed", details: "safe structural details", hint: undefined }); const redacted = sanitizedPersistenceDiagnostic({ message: "access_token=access-secret" }); assert.equal(JSON.stringify(redacted).includes("access-secret"), false); });
test("WHOOP readiness sync triggers for missing metrics or stale data only", () => { const complete = { connected: true, lastSyncAt: "2026-08-30T20:00:00Z", latest: { id: "r", date: "2026-08-30", origin: "real" as const, source: "whoop" as const, recoveryScore: 80, sleepPerformance: 75, strain: 8 } }; const now = Date.parse("2026-08-30T20:30:00Z"); assert.equal(shouldSyncReadiness(complete, now), false); assert.equal(shouldSyncReadiness({ ...complete, latest: { ...complete.latest, recoveryScore: undefined } }, now), true); assert.equal(shouldSyncReadiness({ ...complete, latest: { ...complete.latest, sleepPerformance: undefined } }, now), true); assert.equal(shouldSyncReadiness({ ...complete, latest: { ...complete.latest, strain: undefined } }, now), true); assert.equal(shouldSyncReadiness({ ...complete, lastSyncAt: "2026-08-30T10:00:00Z" }, now), true); assert.equal(shouldSyncReadiness({ ...complete, connected: false }, now), false); });
test("WHOOP resources retain independent recovery, sleep and cycle scores", () => { const combined = normalizeWhoop({ id: "cycle-1", cycle_id: "cycle-1", created_at: "2026-08-30T10:00:00Z", score: { recovery_score: 72 }, _recoveryScore: 72, _sleepPerformance: 81, _cycleStrain: 8.436821 }); assert.equal(combined.recoveryScore, 72); assert.equal(combined.sleepPerformance, 81); assert.equal(combined.strain, 8.436821); const cycleLast = normalizeWhoop({ id: "cycle-1", score: { strain: 8.4 }, _recoveryScore: 72, _sleepPerformance: 81 }); assert.equal(cycleLast.recoveryScore, 72); assert.equal(cycleLast.sleepPerformance, 81); });
