import assert from "node:assert/strict";
import test from "node:test";
import { canAccess, canAccessGym, canConsume, clubAcceptanceFixtures, consumeAllowance, isValidAt, periodKey, remainingAllowance, resolveEntitlements, type EntitlementGrant, type EntitlementUsage } from "../lib/club";

const grant = (overrides: Partial<EntitlementGrant> = {}): EntitlementGrant => ({ id: "g", userId: "u", organisationId: "madhouse", entitlementKey: "class_access", scope: "organisation", validity: { startsAt: "2026-01-01T00:00:00Z" }, source: "purchase", allowance: { quantity: 4, period: "month" }, ...overrides });
test("validity windows and archived products do not revoke existing grants", () => { assert.equal(resolveEntitlements("u", [grant({ validity: { startsAt: "2026-01-01", endsAt: "2026-10-01" } })], "2026-09-01").length, 1); assert.equal(isValidAt({ startsAt: "2026-01-01", endsAt: "2026-02-01" }, "2026-09-01"), false); assert.equal(clubAcceptanceFixtures.goldenTicket.lifetime, true); });
test("organisation and location scopes are enforced", () => { const all = grant({ entitlementKey: "gym_access", scope: "future_locations" }); const selected = grant({ id: "s", entitlementKey: "gym_access", scope: "locations", locationIds: ["rotherham"] }); assert.equal(canAccessGym("u", "madhouse", "future", [all]), true); assert.equal(canAccessGym("u", "other", "future", [all]), false); assert.equal(canAccessGym("u", "madhouse", "rotherham", [selected]), true); assert.equal(canAccessGym("u", "madhouse", "carlton", [selected]), false); });
test("recurring allowance periods and idempotent usage shape are deterministic", () => { const at = "2026-09-02T12:00:00Z"; assert.equal(periodKey("month", at), "2026-09"); assert.equal(periodKey("week", at), "2026-08-31"); const g = grant(); const usage: EntitlementUsage[] = [consumeAllowance(g, 1, [], "class-1", at)]; assert.equal(remainingAllowance(g, usage, at), 3); assert.equal(canConsume(g, 3, usage, at), true); assert.equal(canConsume(g, 4, usage, at), false); });
test("manual and permanent benefits are entitlement grants, not billing assumptions", () => { const g = grant({ entitlementKey: "enhanced_training", allowance: undefined, source: "staff_assignment" }); assert.equal(canAccess("u", "enhanced_training", [g], "2026-09-02"), true); assert.equal(clubAcceptanceFixtures.dayPass.durationDays, 1); assert.equal(clubAcceptanceFixtures.bronze.ptPerWeek, 1); });
test("couples membership can grant two independent account holders", () => { const members = [grant({ id: "a", userId: "a", entitlementKey: "gym_access" }), grant({ id: "b", userId: "b", entitlementKey: "gym_access" })]; assert.equal(canAccess("a", "gym_access", members), true); assert.equal(canAccess("b", "gym_access", members), true); });
