import assert from "node:assert/strict";
import test from "node:test";
import { canAccess, canAccessGym, canConsume, clubAcceptanceFixtures, consumeAllowance, isValidAt, periodKey, remainingAllowance, resolveEntitlements, type EntitlementGrant, type EntitlementUsage } from "../lib/club";
import { MemoryClubRepository, madhouseFixture } from "../lib/club-repository";
import { resolveOrganisationTheme } from "../lib/club";

const grant = (overrides: Partial<EntitlementGrant> = {}): EntitlementGrant => ({ id: "g", userId: "u", organisationId: "madhouse", entitlementKey: "class_access", scope: "organisation", validity: { startsAt: "2026-01-01T00:00:00Z" }, source: "purchase", allowance: { quantity: 4, period: "month" }, ...overrides });
test("validity windows and archived products do not revoke existing grants", () => { assert.equal(resolveEntitlements("u", [grant({ validity: { startsAt: "2026-01-01", endsAt: "2026-10-01" } })], "2026-09-01").length, 1); assert.equal(isValidAt({ startsAt: "2026-01-01", endsAt: "2026-02-01" }, "2026-09-01"), false); assert.equal(clubAcceptanceFixtures.goldenTicket.lifetime, true); });
test("organisation and location scopes are enforced", () => { const all = grant({ entitlementKey: "gym_access", scope: "future_locations" }); const selected = grant({ id: "s", entitlementKey: "gym_access", scope: "locations", locationIds: ["rotherham"] }); assert.equal(canAccessGym("u", "madhouse", "future", [all]), true); assert.equal(canAccessGym("u", "other", "future", [all]), false); assert.equal(canAccessGym("u", "madhouse", "rotherham", [selected]), true); assert.equal(canAccessGym("u", "madhouse", "carlton", [selected]), false); });
test("recurring allowance periods and idempotent usage shape are deterministic", () => { const at = "2026-09-02T12:00:00Z"; assert.equal(periodKey("month", at), "2026-09"); assert.equal(periodKey("week", at), "2026-08-31"); const g = grant(); const usage: EntitlementUsage[] = [consumeAllowance(g, 1, [], "class-1", at)]; assert.equal(remainingAllowance(g, usage, at), 3); assert.equal(canConsume(g, 3, usage, at), true); assert.equal(canConsume(g, 4, usage, at), false); });
test("manual and permanent benefits are entitlement grants, not billing assumptions", () => { const g = grant({ entitlementKey: "enhanced_training", allowance: undefined, source: "staff_assignment" }); assert.equal(canAccess("u", "enhanced_training", [g], "2026-09-02"), true); assert.equal(clubAcceptanceFixtures.dayPass.durationDays, 1); assert.equal(clubAcceptanceFixtures.bronze.ptPerWeek, 1); });
test("couples membership can grant two independent account holders", () => { const members = [grant({ id: "a", userId: "a", entitlementKey: "gym_access" }), grant({ id: "b", userId: "b", entitlementKey: "gym_access" })]; assert.equal(canAccess("a", "gym_access", members), true); assert.equal(canAccess("b", "gym_access", members), true); });
test("memory repository is idempotent and organisation scoped", async () => { const repository = new MemoryClubRepository(); const products = await repository.listProducts(madhouseFixture.id); assert.equal(products.length, 12); const { id: _id, ...productWithoutId } = products[0]; const created = await repository.createProduct({ ...productWithoutId, name: "Gym Day Pass" }); assert.equal(created.id, products[0].id); assert.equal((await repository.listProducts("other-org")).length, 0); });
test("manual assignment materialises product benefits for every holder", async () => { const repository = new MemoryClubRepository(); const product = (await repository.listProducts(madhouseFixture.id)).find(item => item.name === "Couples Membership")!; const result = await repository.assignProduct({ organisationId: madhouseFixture.id, productId: product.id, userId: "u1", holderUserIds: ["u1", "u2"], source: "founding", validity: { startsAt: "2026-01-01" } }); assert.equal(result.membership.holderUserIds.length, 2); assert.equal(result.grants.filter(item => item.entitlementKey === "gym_access").length, 2); });
test("organisation themes are constrained and inactive organisations fall back to R12", () => { const themed = resolveOrganisationTheme({ ...madhouseFixture, branding: { coBranding: "co_branded", primaryAccent: "#123456", secondaryAccent: "not-a-colour" } }); assert.equal(themed.primaryAccent, "#123456"); assert.equal(themed.secondaryAccent, "#c084fc"); assert.equal(resolveOrganisationTheme({ ...madhouseFixture, active: false }).coBranding, "r12"); assert.equal(themed.platform, "R12"); });
