import test from "node:test";
import assert from "node:assert/strict";
import { collectionReady, fulfilmentForProduct, paidSupplierDemand, SupplierWorkflow } from "../lib/club-supplier-workflow";
import { parseSupplierCsvWithMapping } from "../lib/club-supplier";
test("supplier availability never masquerades as local stock", () => { const product = { stockTracked: true } as any; assert.equal(fulfilmentForProduct(product, undefined), "available_to_order"); assert.equal(fulfilmentForProduct(product, 2), "in_gym_now"); });
test("only paid orders create supplier demand", () => { const order = { id: "o1", status: "paid", items: [{ id: "i1", productId: "p1", quantity: 2 }] } as any; assert.equal(paidSupplierDemand(order, false, new Set(["p1"])).length, 0); assert.equal(paidSupplierDemand(order, true, new Set(["p1"]))[0].quantity, 2); });
test("collection is ready only after received and allocated", () => { assert.equal(collectionReady(2, 2, 1), false); assert.equal(collectionReady(2, 2, 2), true); });
test("supplier demand consolidates, receives, allocates, queues once, and collects", () => { const flow = new SupplierWorkflow(); const demand = flow.createDemand({ organisationId: "org", supplierId: "supplier", supplierProductId: "offer", orderId: "order", orderItemId: "item", userId: "member", quantityRequired: 3 }); assert.equal(flow.createDemand({ organisationId: "org", supplierId: "supplier", supplierProductId: "offer", orderId: "order", orderItemId: "item", quantityRequired: 3 }).id, demand.id); const batch = flow.consolidate("org", "supplier"); flow.markOrdered(batch.id); flow.receive(batch.id, { [demand.id]: 2 }); assert.equal(flow.demands[0].status, "ordered"); flow.receive(batch.id, { [demand.id]: 1 }); assert.equal(flow.demands[0].status, "awaiting_delivery"); flow.allocate(demand.id, 2); assert.equal(flow.demands[0].status, "awaiting_delivery"); flow.allocate(demand.id, 1); assert.equal(flow.demands[0].status, "ready_for_collection"); assert.equal(flow.notifications.length, 1); flow.collect(demand.id); assert.equal(flow.demands[0].status, "collected"); assert.throws(() => flow.collect(demand.id)); });
test("supplier mapping accepts arbitrary source headers", () => { const result = parseSupplierCsvWithMapping("Code,Title,Cost\n001,Creatine,10.00", "Supplier", { supplierSku: "Code", name: "Title", wholesaleCost: "Cost" }); assert.equal(result.rows[0].supplierSku, "001"); assert.equal(result.rows[0].name, "Creatine"); });
