import assert from "node:assert/strict";
import test from "node:test";
import { assessWorkingSession, calibrationConfidence, calibrationLoad, calibrationSignal, cardioRecommendation, effortSignal, evaluateSet, initialCoachPlan, nextExerciseRecommendation, practicalLoad, restFor, startingPrescription, workingWeight } from "../lib/coach";
import { formatWhoopExport } from "../components/whoop-export";
import type { LoggedSet, Workout } from "../lib/types";
import { exercisesForSession, mondayExercises } from "../lib/workout";
import { rampLoad } from "../lib/progression";

const db = mondayExercises[0]; const trap = exercisesForSession(["trap-bar-deadlift"])[0]; const machine = mondayExercises[1]; const cable = mondayExercises[3];
const s = (kind: LoggedSet["kind"], weight: number, reps: number, rir: number): LoggedSet => ({ id: crypto.randomUUID(), exerciseId: db.id, exerciseName: db.name, kind, weight, reps, rir, createdAt: new Date().toISOString() });
const sessionSets = (values: Array<[number, number, number]>) => values.map(([weight, reps, rir], index) => ({ id: String(index), exerciseId: db.id, exerciseName: db.name, weight, reps, rir, kind: "working" as const, createdAt: String(index) }));
test("session-level progression rewards strong top-range work", () => { assert.equal(assessWorkingSession(db, sessionSets([[75, 10, 2], [75, 10, 2], [75, 9, 1]])), "progress"); assert.equal(assessWorkingSession(db, sessionSets([[75, 8, 2], [75, 8, 2], [75, 8, 1]])), "hold"); assert.notEqual(assessWorkingSession(db, sessionSets([[75, 10, 1], [75, 7, 0], [70, 8, 1]])), "progress"); assert.equal(assessWorkingSession(db, sessionSets([[75, 10, 4], [75, 10, 4], [75, 10, 3]])), "very_easy"); });
test("starting weight uses the completed session assessment", () => {
  const strong = sessionSets([[75, 10, 2], [75, 10, 2], [75, 9, 1]]);
  const bottom = sessionSets([[75, 8, 2], [75, 8, 2], [75, 8, 1]]);
  assert.equal(startingPrescription(db, strong, 0).work, 78);
  assert.equal(startingPrescription(db, bottom, 0).work, 75);
});
test("reduce lowers the next start from the sustainable final load", () => {
  const failed = sessionSets([[75, 7, 0], [72.5, 7, 1], [70, 8, 1]]);
  assert.equal(assessWorkingSession(db, failed), "reduce");
  assert.equal(workingWeight(db, failed), 68);
  const cableFailure = failed.map((set, index) => ({ ...set, exerciseId: cable.id, exerciseName: cable.name, weight: [23, 18, 14][index], reps: [10, 11, 12][index] }));
  assert.equal(workingWeight(cable, cableFailure), 9);
});
test("equipment loads are selectable", () => { assert.equal(practicalLoad(27.25, "dumbbell"), 28); assert.equal(practicalLoad(82, "machine", 5), 80); assert.equal(practicalLoad(11.4, "cable", 2.5), 12.5); assert.equal(practicalLoad(62.5, "barbell"), 62.5); });
test("plate-loaded ramps use large early jumps and small top-end probes", () => {
  const deadlift = { ...db, id: "deadlift", equipment: "barbell" as const, defaultWorkingWeight: 150 };
  assert.deepEqual([rampLoad(deadlift, 60, 150), rampLoad(deadlift, 100, 150), rampLoad(deadlift, 120, 150), rampLoad(deadlift, 140, 150)], [100, 120, 140, 145]);
  const bench = { ...db, id: "bench", equipment: "barbell" as const, defaultWorkingWeight: 110 };
  assert.equal(rampLoad(bench, 85, 110), 105);
  assert.equal(rampLoad(bench, 105, 110), 110);
  const plateMachine = { ...machine, loadProfile: "plate_loaded" as const };
  assert.equal(rampLoad(plateMachine, 60, 120), 100);
  assert.equal(rampLoad(machine, 80, 120), 85);
  assert.equal(rampLoad(cable, 41, 55), 45);
});
test("Coach begins at exercise start and minimises later preparation", () => { assert.equal(initialCoachPlan(db, [], 0).kind, "warmup"); assert.equal(initialCoachPlan(machine, [], 1).kind, "ramp"); assert.equal(startingPrescription(cable, [], 3).ramps, 1); });
test("no-history baseline is experienced-lifter sensible", () => { assert.equal(nextExerciseRecommendation(machine, [], 1).weight, 80); assert.equal(nextExerciseRecommendation(cable, [], 3).weight, 14); });
test("warm-up adapts immediately when user chooses a much heavier load", () => { const d = evaluateSet(db, [s("warmup", 50, 12, 3)], "", [], 0); assert.equal(d.nextKind, "ramp"); assert.equal(d.nextWeight, 50); });
test("ramp uses actual heavier input to establish working load rapidly", () => { const d = evaluateSet(db, [s("ramp", 50, 12, 3)], "", [], 1); assert.equal(d.nextKind, "working"); assert.equal(d.nextWeight, 50); });
test("warm-up and ramp do not count as programme work", () => { const d = evaluateSet(db, [s("warmup", 16, 12, 4), s("ramp", 24, 8, 3)], "", [], 0); assert.equal(d.workingSetsCompleted, 0); });
test("working prescription completes automatically", () => { const d = evaluateSet(db, [s("working", 30, 10, 2), s("working", 30, 9, 1), s("working", 30, 8, 1), s("working", 30, 8, 1)]); assert.equal(d.completed, true); assert.equal(d.nextKind, "complete"); });
test("top-range work at appropriate RIR can earn the next load", () => { const d = evaluateSet(machine, [{ ...s("working", 80, 12, 2), exerciseId: machine.id }]); assert.equal(d.nextWeight, 85); });
test("very easy working set progresses one realistic increment", () => { const d = evaluateSet(machine, [{ ...s("working", 80, 12, 4), exerciseId: machine.id }]); assert.equal(d.nextWeight, 85); });
test("rest is short for preparation and extends with fatigue", () => { assert.equal(restFor(db, "warmup"), 45); assert.equal(restFor(cable, "ramp"), 60); assert.equal(restFor(machine, "working", true), 135); });
test("all actual sets are retained in Whoop export", () => { const workout: Workout = { id: "x", name: "x", startedAt: "x", substitutions: {}, notes: [], sets: [s("warmup", 12.5, 12, 4), s("ramp", 50, 8, 3), s("working", 70, 12, 2)], cardio: { duration: 34, incline: 7, speed: 5 } }; const value = formatWhoopExport(workout); assert.equal(value.split("\n").length, 4); assert.match(value, /12.5kg/); });
test("cardio is always 30–40 minutes and reduces intensity under fatigue", () => { const moderate = cardioRecommendation(14, 1); const hard = cardioRecommendation(18, 6); assert.ok(moderate.duration >= 30 && moderate.duration <= 40); assert.ok(hard.duration >= 30 && hard.duration <= 40); assert.ok(hard.incline < moderate.incline); });
test("preparation RIR cannot lower the expected first working load", () => { const first = evaluateSet(db, [s("warmup", 16, 12, 2)], "", [{ ...s("working", 38, 10, 2) }], 0); const ramp = evaluateSet(db, [s("ramp", 24, 8, 0)], "", [{ ...s("working", 38, 10, 2) }], 0); assert.equal(first.nextWeight, 28); assert.equal(ramp.nextWeight, 38); });
test("ramp records may omit RIR and still progress", () => { const d = evaluateSet(db, [{ ...s("ramp", 24, 8, 0), rir: undefined }], "", [{ ...s("working", 38, 10, 2) }], 1); assert.equal(d.nextKind, "working"); assert.equal(d.nextWeight, 38); });
test("low-confidence plate-loaded ramps discover load from easy feedback", () => { const first = evaluateSet(trap, [{ ...s("ramp", 60, 6, 0), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0); assert.equal(first.nextKind, "ramp"); assert.ok(first.nextWeight >= 80); const second = evaluateSet(trap, [{ ...s("ramp", 60, 6, 0), exerciseId: trap.id, exerciseName: trap.name }, { ...s("ramp", first.nextWeight, 6, 0), exerciseId: trap.id, exerciseName: trap.name }], "easy", [], 0); assert.equal(second.nextKind, "ramp"); assert.ok(second.nextWeight > first.nextWeight); });
test("effort feedback exposes deterministic coaching signals", () => { assert.equal(effortSignal("very easy"), "easy"); assert.equal(effortSignal("easy today"), "easy"); assert.equal(effortSignal("hard set"), "hard"); assert.equal(effortSignal("about right"), "about_right"); });
test("low-confidence heavy compounds converge within a bounded descending-rep ramp", () => { const sets: LoggedSet[] = []; let decision = evaluateSet(trap, [{ ...s("ramp", 60, 6, 0), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0); sets.push({ ...s("ramp", 60, 6, 0), exerciseId: trap.id, exerciseName: trap.name }); assert.match(decision.repTarget, /5–8|3–5|1–3/); for (let i = 0; i < 2; i++) { const next = { ...s("ramp", decision.nextWeight, i === 0 ? 5 : 3, 0), exerciseId: trap.id, exerciseName: trap.name }; sets.push(next); decision = evaluateSet(trap, sets, "very easy", [], 0); } assert.ok(sets.filter(set => set.kind === "ramp").length <= 3); assert.notEqual(decision.nextKind, "ramp"); });
test("working RIR is never assumed while preparation remains RIR-free", () => { const plan = initialCoachPlan(trap, [], 0); assert.equal(plan.kind, "warmup"); const ramp = evaluateSet(trap, [{ ...s("ramp", 100, 3, 0), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0); assert.equal(ramp.restSeconds <= 120, true); });
test("working-set RIR still drives adaptive decisions", () => { const easy = evaluateSet(machine, [{ ...s("working", 80, 12, 4), exerciseId: machine.id }]); const hard = evaluateSet(machine, [{ ...s("working", 80, 7, 0), exerciseId: machine.id }, { ...s("working", 80, 7, 0), exerciseId: machine.id }]); assert.equal(easy.nextWeight, 85); assert.equal(hard.nextWeight, 75); });
test("gross underload uses reps-above-range and genuine high RIR for recalibration", () => {
  const first = evaluateSet(trap, [{ ...s("working", 100, 6, 5), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0);
  const gross = evaluateSet(trap, [{ ...s("working", 110, 10, 5), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0);
  assert.equal(first.nextWeight, 110);
  assert.equal(gross.nextWeight, 140);
  assert.equal(gross.title, "Recalibrate working load");
});
test("normal plate-loaded progression remains smaller when effort is near target", () => {
  const decision = evaluateSet(trap, [{ ...s("working", 140, 6, 2), exerciseId: trap.id, exerciseName: trap.name }], "about right", [], 0);
  assert.equal(decision.nextWeight, 145);
  assert.notEqual(decision.title, "Recalibrate working load");
});
test("pain or failure feedback on a ramp can still stop progression", () => { const d = evaluateSet(db, [{ ...s("ramp", 24, 4, 0) }], "shoulder pain", [], 0); assert.equal(d.tone, "reduce"); assert.equal(d.nextKind, "complete"); });
test("calibration feedback is structured and confidence is exercise-history based", () => { assert.equal(calibrationSignal("very easy"), "very_easy"); assert.equal(calibrationSignal("starting to work"), "getting_close"); assert.equal(calibrationSignal("sharp knee pain"), "too_hard"); assert.equal(calibrationConfidence([]), "unknown"); assert.equal(calibrationConfidence([s("working", 80, 6, 2)]), "low"); });
test("low-confidence discovery uses meaningful profile-aware jumps and avoids same-load repeats", () => { const first = evaluateSet(trap, [{ ...s("ramp", 60, 8, 0), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0, "experienced"); const second = evaluateSet(trap, [{ ...s("ramp", 60, 8, 0), exerciseId: trap.id, exerciseName: trap.name }, { ...s("ramp", first.nextWeight, 5, 0), exerciseId: trap.id, exerciseName: trap.name }], "very easy", [], 0, "experienced"); assert.ok(first.nextWeight - 60 >= 20); assert.ok(second.nextWeight > first.nextWeight); assert.notEqual(first.nextWeight, 60); });
test("calibration jump scale remains conservative for beginners and smaller profiles", () => { assert.ok(calibrationLoad(trap, 80, "very_easy", 0, "beginner") < calibrationLoad(trap, 80, "very_easy", 0, "experienced")); assert.ok(calibrationLoad(cable, 14, "very_easy") - 14 < calibrationLoad(trap, 80, "very_easy") - 80); });
