import assert from "node:assert/strict";
import test from "node:test";
import { cardioRecommendation, evaluateSet, initialCoachPlan, nextExerciseRecommendation, practicalLoad, restFor, startingPrescription } from "../lib/coach";
import { formatWhoopExport } from "../components/whoop-export";
import type { LoggedSet, Workout } from "../lib/types";
import { mondayExercises } from "../lib/workout";

const db = mondayExercises[0]; const machine = mondayExercises[1]; const cable = mondayExercises[3];
const s = (kind: LoggedSet["kind"], weight: number, reps: number, rir: number): LoggedSet => ({ id: crypto.randomUUID(), exerciseId: db.id, exerciseName: db.name, kind, weight, reps, rir, createdAt: new Date().toISOString() });
test("equipment loads are selectable", () => { assert.equal(practicalLoad(27.25, "dumbbell"), 28); assert.equal(practicalLoad(82, "machine", 5), 80); assert.equal(practicalLoad(11.4, "cable", 2.5), 12.5); });
test("Coach begins at exercise start and minimises later preparation", () => { assert.equal(initialCoachPlan(db, [], 0).kind, "warmup"); assert.equal(initialCoachPlan(machine, [], 1).kind, "ramp"); assert.equal(startingPrescription(cable, [], 3).ramps, 1); });
test("no-history baseline is experienced-lifter sensible", () => { assert.equal(nextExerciseRecommendation(machine, [], 1).weight, 80); assert.equal(nextExerciseRecommendation(cable, [], 3).weight, 14); });
test("warm-up adapts immediately when user chooses a much heavier load", () => { const d = evaluateSet(db, [s("warmup", 50, 12, 3)], "", [], 0); assert.equal(d.nextKind, "ramp"); assert.equal(d.nextWeight, 50); });
test("ramp uses actual heavier input to establish working load rapidly", () => { const d = evaluateSet(db, [s("ramp", 50, 12, 3)], "", [], 1); assert.equal(d.nextKind, "working"); assert.equal(d.nextWeight, 50); });
test("warm-up and ramp do not count as programme work", () => { const d = evaluateSet(db, [s("warmup", 16, 12, 4), s("ramp", 24, 8, 3)], "", [], 0); assert.equal(d.workingSetsCompleted, 0); });
test("working prescription completes automatically", () => { const d = evaluateSet(db, [s("working", 30, 10, 2), s("working", 30, 9, 1), s("working", 30, 8, 1), s("working", 30, 8, 1)]); assert.equal(d.completed, true); assert.equal(d.nextKind, "complete"); });
test("top-range work at appropriate RIR does not force a load increase", () => { const d = evaluateSet(machine, [{ ...s("working", 80, 12, 2), exerciseId: machine.id }]); assert.equal(d.nextWeight, 80); });
test("very easy working set progresses one realistic increment", () => { const d = evaluateSet(machine, [{ ...s("working", 80, 12, 4), exerciseId: machine.id }]); assert.equal(d.nextWeight, 85); });
test("rest is short for preparation and extends with fatigue", () => { assert.equal(restFor(db, "warmup"), 45); assert.equal(restFor(cable, "ramp"), 60); assert.equal(restFor(machine, "working", true), 135); });
test("all actual sets are retained in Whoop export", () => { const workout: Workout = { id: "x", name: "x", startedAt: "x", substitutions: {}, notes: [], sets: [s("warmup", 12.5, 12, 4), s("ramp", 50, 8, 3), s("working", 70, 12, 2)], cardio: { duration: 34, incline: 7, speed: 5 } }; const value = formatWhoopExport(workout); assert.equal(value.split("\n").length, 4); assert.match(value, /12.5kg/); });
test("cardio is always 30–40 minutes and reduces intensity under fatigue", () => { const moderate = cardioRecommendation(14, 1); const hard = cardioRecommendation(18, 6); assert.ok(moderate.duration >= 30 && moderate.duration <= 40); assert.ok(hard.duration >= 30 && hard.duration <= 40); assert.ok(hard.incline < moderate.incline); });
test("preparation RIR cannot lower the expected first working load", () => { const first = evaluateSet(db, [s("warmup", 16, 12, 2)], "", [{ ...s("working", 38, 10, 2) }], 0); const ramp = evaluateSet(db, [s("ramp", 24, 8, 0)], "", [{ ...s("working", 38, 10, 2) }], 0); assert.equal(first.nextWeight, 28); assert.equal(ramp.nextWeight, 38); });
test("ramp records may omit RIR and still progress", () => { const d = evaluateSet(db, [{ ...s("ramp", 24, 8, 0), rir: undefined }], "", [{ ...s("working", 38, 10, 2) }], 1); assert.equal(d.nextKind, "working"); assert.equal(d.nextWeight, 38); });
test("working-set RIR still drives adaptive decisions", () => { const easy = evaluateSet(machine, [{ ...s("working", 80, 12, 4), exerciseId: machine.id }]); const hard = evaluateSet(machine, [{ ...s("working", 80, 7, 0), exerciseId: machine.id }, { ...s("working", 80, 7, 0), exerciseId: machine.id }]); assert.equal(easy.nextWeight, 85); assert.equal(hard.nextWeight, 75); });
test("pain or failure feedback on a ramp can still stop progression", () => { const d = evaluateSet(db, [{ ...s("ramp", 24, 4, 0) }], "shoulder pain", [], 0); assert.equal(d.tone, "reduce"); assert.equal(d.nextKind, "complete"); });
