import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { normalizeMemberRow, stageMemberCsv } from "@/lib/club-member-import";

const sql=readFileSync("supabase/migrations/2026-12-03-member-import-and-access.sql","utf8");
const api=readFileSync("app/api/club/access/decision/route.ts","utf8");
const reception=readFileSync("components/club-access-console.tsx","utf8");

test("new legacy members without Auth and missing email remain valid and claimable",()=>{const row=stageMemberCsv("legacy_member_reference,full_name,membership_name,membership_status\n12,Alex Member,Staff,active\n").rows[0];assert.equal(row.blockers.length,0);assert.match(row.warnings.join(" "),/claimable/);assert.match(sql,/insert into public\.club_customers\(organisation_id,user_id/);assert.match(sql,/if u is null then insert into public\.club_membership_holders/)});
test("normalisation handles verified-email candidates without creating Auth identities",()=>{assert.equal(normalizeMemberRow({email:"  PERSON@Example.COM  "}).email,"person@example.com");assert.match(sql,/email_confirmed_at is not null/);assert.doesNotMatch(sql,/insert into auth\.users/i)});
test("existing linked identities cannot be silently overwritten",()=>{assert.match(sql,/Existing customer is linked to a different identity/);assert.match(sql,/where id=c\.id and user_id is null/)});
test("duplicate and malformed emails are conflicts while one bad row does not reject valid rows",()=>{const staged=stageMemberCsv("full_name,email\nOne,one@example.com\nTwo,one@example.com\nBad,not-an-email\n");assert.equal(staged.rows[0].blockers.length,0);assert.match(staged.rows[1].blockers.join(" "),/Duplicate/);assert.match(staged.rows[2].blockers.join(" "),/malformed/);assert.match(sql,/where batch_id=b\.id and jsonb_array_length\(blockers\)=0/)});
test("staff and Coach roles are preserved when membership identity is added",()=>{assert.match(sql,/on conflict\(organisation_id,user_id\) do nothing/);assert.doesNotMatch(sql,/update public\.club_members set role='member'/);assert.doesNotMatch(sql,/coach_relationships|coach_permissions/)});
test("legacy active paid membership provenance does not fabricate billing",()=>{assert.match(sql,/'legacy_import'/);assert.match(sql,/'billing_evidence','not_imported'/);assert.doesNotMatch(sql,/insert into public\.club_membership_billing_arrangements/);assert.doesNotMatch(sql,/insert into public\.club_.*payments/)});
test("inactive, expired and cancelled source statuses map to canonical membership states",()=>{for(const [input,expected] of [["inactive","expired"],["expired","expired"],["cancelled","cancelled"],["staff","active"]])assert.equal(normalizeMemberRow({status:input}).membershipStatus,expected);assert.match(sql,/ms_status in \('active','expired','cancelled'\)|membershipStatus.*not in \('active','expired','cancelled'\)/s)});
test("import reruns and memberships are idempotent",()=>{assert.match(sql,/club_member_import_checksum_uq/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/member-import:'\|\|r\.id/);assert.match(sql,/on conflict\(organisation_id,assignment_idempotency_key\) do nothing/)});
test("package mapping conflicts block only affected rows",()=>{assert.match(sql,/Membership package mapping required/);assert.match(sql,/valid_count=0/);assert.match(sql,/outcome='rejected'/)});
test("access allows only active in-scope entitlements, including legitimate legacy and manual products",()=>{assert.match(sql,/pe\.entitlement_key='gym_access'/);assert.match(sql,/m\.status<>'active'/);assert.match(sql,/m\.ends_at is not null and m\.ends_at<=now\(\)/);assert.match(sql,/m\.scope='future_locations'/);assert.match(sql,/wrong_club_location/);assert.match(sql,/'wrong_club'/);assert.match(sql,/active_entitlement/);assert.doesNotMatch(sql,/m\.source='staff_assignment'/)});
test("billing suspension follows configured policy while grace is not invented as denial",()=>{assert.match(sql,/access_suspension_enabled/);assert.match(sql,/o\.state in \('overdue','cancelled'\)/);assert.match(sql,/payment_action_required/);assert.doesNotMatch(sql,/o\.state='grace'.*deny/s)});
test("stale, duplicate and unknown credentials cannot create unsafe access",()=>{assert.match(sql,/credential_hash=digest/);assert.match(sql,/abs\(extract\(epoch from \(now\(\)-p_presented_at\)\)\)>120/);assert.match(sql,/Device request replayed/);assert.match(sql,/unique\(device_id,request_nonce\)/);assert.match(sql,/credential_not_found/)});
test("every access decision is audited with scoped, non-secret metadata",()=>{assert.match(sql,/insert into public\.club_access_decisions/);assert.match(sql,/auditReference/);assert.doesNotMatch(sql,/club_access_decisions[\s\S]{0,800}p_secret/)});
test("door API rejects unauthenticated requests and delegates to the authoritative RPC",()=>{assert.match(api,/Device authentication required/);assert.match(api,/club_device_access_decision/);assert.match(api,/status:401/);assert.doesNotMatch(api,/allowed\s*=/)});
test("reception clearly presents allow, deny and operational reasons",()=>{assert.match(reception,/"ALLOW"/);assert.match(reception,/"DENY"/);for(const value of ["Membership inactive","Membership expired","Payment action required","No membership","does not include this venue"])assert.match(reception,new RegExp(value))});
test("migration is review-only and manifest ordered",()=>{assert.doesNotMatch(sql,/insert into public\.club_access_devices\s*\(/);assert.match(readFileSync("supabase/deployment/2026-11-22-madhouse-launch-migrations.txt","utf8"),/2026-12-03-member-import-and-access\.sql\s*$/)});
