import test from "node:test";
import assert from "node:assert/strict";
import { generateTrainingProgramme } from "../lib/programme-generator";
import type { TrainingProfile } from "../lib/training-profile";
import { exercisesForSession } from "../lib/workout";
import { exerciseRole, prescriptionForExercise } from "../lib/prescription";
import { exerciseById } from "../lib/workout";

const profile = (overrides: Partial<TrainingProfile> = {}): TrainingProfile => ({ goal: "muscle_gain", experience: "beginner", daysPerWeek: 3, sessionMinutes: 60, environment: "full_gym", limitations: [], includeCardio: false, ...overrides });

test("beginner three-day programme is complete, bounded and balanced", () => { const programme = generateTrainingProgramme(profile()); assert.equal(programme.week.length, 3); assert.ok(programme.week.every(day => day.exerciseIds.length >= 3 && day.exerciseIds.length <= 5)); assert.ok(programme.week.every(day => exercisesForSession(day.exerciseIds, day.exerciseOverrides).every(exercise => exercise.defaultWorkingWeight >= 0))); assert.ok(programme.week.flatMap(day => day.exerciseIds).some(id => id === "leg-press")); assert.ok(programme.week.flatMap(day => day.exerciseIds).some(id => id === "flat-bench")); });
test("availability and experience change split and volume", () => { const four = generateTrainingProgramme(profile({ daysPerWeek: 4, experience: "intermediate" })); const sixBeginner = generateTrainingProgramme(profile({ daysPerWeek: 6, experience: "beginner" })); assert.equal(four.week.length, 4); assert.ok(four.week.some(day => day.name === "Upper Body")); assert.ok(sixBeginner.week.every(day => day.exerciseIds.length <= 5)); });
test("limited equipment never prescribes cable or machine work", () => { const programme = generateTrainingProgramme(profile({ environment: "home_basic", daysPerWeek: 2, sessionMinutes: 45 })); assert.ok(programme.week.every(day => exercisesForSession(day.exerciseIds).every(exercise => exercise.equipment === "dumbbell" || exercise.equipment === "barbell"))); });
test("goal-sensitive prescriptions retain explicit sets and reps without starting weights", () => { const programme = generateTrainingProgramme(profile({ goal: "strength", experience: "intermediate", daysPerWeek: 4 })); const exercises = programme.week.flatMap(day => exercisesForSession(day.exerciseIds, day.exerciseOverrides)); assert.ok(exercises.some(exercise => exercise.target.includes("4–6"))); assert.ok(exercises.every(exercise => !Object.prototype.hasOwnProperty.call(exercise, "workingWeight"))); });
test("limitations are respected conservatively", () => { const programme = generateTrainingProgramme(profile({ limitations: ["knee"] })); assert.ok(programme.week.flatMap(day => day.exerciseIds).every(id => !["leg-press", "hack-squat", "leg-extension"].includes(id))); });
test("programme prescriptions are goal and role aware", () => { const trap = exerciseById("trap-bar-deadlift")!; const lateral = exerciseById("cable-lateral-raise")!; const strength = prescriptionForExercise(trap, profile({ goal: "strength", experience: "experienced" }), 0); const muscle = prescriptionForExercise(trap, profile({ goal: "muscle_gain" }), 0); const isolation = prescriptionForExercise(lateral, profile({ goal: "muscle_gain" }), 3); assert.equal(exerciseRole(trap, 0), "primary_compound"); assert.equal(strength.target, "4 × 4–6"); assert.notEqual(muscle.target, trap.target); assert.match(muscle.target, /6–10/); assert.match(isolation.target, /10–15/); });
test("explicit generated overrides win over catalogue prescriptions and remain stable", () => { const first = generateTrainingProgramme(profile({ goal: "muscle_gain" }), undefined, "stable"); const trapDay = first.week.find(day => day.exerciseIds.includes("trap-bar-deadlift"))!; const trap = exercisesForSession(trapDay.exerciseIds, trapDay.exerciseOverrides).find(exercise => exercise.id === "trap-bar-deadlift")!; assert.notEqual(trap.target, "3 × 5–6"); const second = generateTrainingProgramme(profile({ goal: "muscle_gain" }), undefined, "stable"); assert.deepEqual(second.week, first.week); });
test("prescription volume stays bounded and varies by role", () => { const programme = generateTrainingProgramme(profile({ experience: "experienced", daysPerWeek: 5, sessionMinutes: 75 })); for (const day of programme.week) { const exercises = exercisesForSession(day.exerciseIds, day.exerciseOverrides); assert.ok(exercises.length <= 7); assert.ok(exercises.reduce((sum, exercise) => sum + exercise.sets, 0) <= 28); assert.ok(new Set(exercises.map(exercise => exercise.target)).size > 1); } });
