import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { deserializeOverride, occurrencePersistenceKey, overrideIsActive, serializeOverride, SCHEDULE_PERSISTENCE_ENABLED } from "../lib/scheduling-persistence";

test("availability override serialization round-trips its scoped fields", () => { const value = { startDate: "2026-09-07", endDate: "2026-09-13", availableDays: [6, 7], sessionsPerWeek: 2, sessionMinutes: 45, environment: "hotel_gym", equipment: ["dumbbell"], reason: "Travel", source: "user" as const }; const restored = deserializeOverride(serializeOverride(value)); assert.equal(restored.startDate, value.startDate); assert.equal(restored.endDate, value.endDate); assert.deepEqual(restored.availableDays, value.availableDays); assert.deepEqual(restored.equipment, value.equipment); assert.equal(restored.reason, value.reason); assert.equal(overrideIsActive(value, "2026-09-10"), true); assert.equal(overrideIsActive(value, "2026-09-14"), false); });
test("occurrence persistence identity is user and occurrence scoped", () => { assert.equal(occurrencePersistenceKey("user-1", "active:tue:2026-09-01"), "user-1:active:tue:2026-09-01"); assert.notEqual(occurrencePersistenceKey("user-1", "active:tue:2026-09-01"), occurrencePersistenceKey("user-1", "active:tue:2026-09-08")); });
test("scheduling API is capability-gated before querying new tables", () => { const route = fs.readFileSync("app/api/training-schedule/route.ts", "utf8"); assert.match(route, /SCHEDULE_PERSISTENCE_ENABLED/); assert.match(route, /if \(!SCHEDULE_PERSISTENCE_ENABLED\)/); assert.equal(SCHEDULE_PERSISTENCE_ENABLED, false); });
test("reviewed scheduling migration includes ownership, uniqueness and RLS", () => { const sql = fs.readFileSync("supabase/migrations/2026-09-02-training-scheduling-persistence.sql", "utf8"); assert.match(sql, /unique \(user_id, occurrence_id\)/); assert.match(sql, /references auth\.users\(id\) on delete cascade/); assert.match(sql, /enable row level security/); assert.match(sql, /user_id = auth\.uid\(\)/); });
test("training profile API round-trips the canonical availability payload", () => { const route = fs.readFileSync("app/api/training-profile/route.ts", "utf8"); assert.match(route, /training_profile/); assert.match(route, /body\.trainingProfile/); });
