import test from "node:test";
import assert from "node:assert/strict";
import { resolveTodayOccurrence, resolveWeekSchedule } from "../lib/schedule-resolver";
import { currentWeek } from "../lib/domain";
import type { AppData } from "../lib/types";
import { legacyProgrammeSnapshot } from "../lib/legacy-programme";

const data = (extra: Partial<AppData> = {}): AppData => ({ version: 2, workouts: [], bodyMetrics: [], meals: [], ...extra });
test("canonical resolver returns dated Original occurrences without availability data", () => { const result = resolveWeekSchedule(currentWeek, data(), "Europe/London", new Date("2026-09-02T12:00:00Z")); assert.ok(result.occurrences.some(item => item.programmeSessionId === "tue" && item.scheduledDate === "2026-09-01")); assert.equal(resolveTodayOccurrence(currentWeek, data(), "Europe/London", new Date("2026-09-02T12:00:00Z"))?.programmeSessionId, "wed"); });
test("elapsed scheduled sessions become missed while today and future remain available", () => { const result = resolveWeekSchedule(currentWeek, data(), "Europe/London", new Date("2026-09-03T12:00:00Z")); assert.equal(result.occurrences.find(item => item.programmeSessionId === "tue")?.status, "missed"); assert.equal(result.occurrences.find(item => item.programmeSessionId === "wed")?.status, "missed"); assert.equal(resolveWeekSchedule(currentWeek, data(), "Europe/London", new Date("2026-09-08T12:00:00Z")).occurrences.find(item => item.programmeSessionId === "tue")?.status, "planned"); });
test("dated status applies only to its occurrence", () => { const result = resolveWeekSchedule(currentWeek, data({ sessionStatusOverrides: { "active:tue:2026-09-01": { status: "missed" } } }), "Europe/London", new Date("2026-09-08T12:00:00Z")); const next = result.occurrences.find(item => item.programmeSessionId === "tue"); assert.equal(next?.scheduledDate, "2026-09-08"); assert.equal(next?.status, "planned"); });
test("completed and partial workouts resolve through dated occurrence identity", () => { const result = resolveWeekSchedule(currentWeek, data({ workouts: [{ id: "w", name: "Heavy Lower", plannedSessionId: "tue", scheduledDate: "2026-09-01", status: "completed", completedAt: "2026-09-01", startedAt: "2026-09-01", sets: [], substitutions: {}, notes: [] }] }), "Europe/London", new Date("2026-09-02T12:00:00Z")); assert.equal(result.occurrences.find(item => item.programmeSessionId === "tue")?.status, "completed"); });
test("canonical week keeps past missed and future planned occurrences independent", () => { const missed = data({ sessionStatusOverrides: { "active:tue:2026-09-01": { status: "missed" } } }); const past = resolveWeekSchedule(currentWeek, missed, "Europe/London", new Date("2026-09-02T12:00:00Z")); const future = resolveWeekSchedule(currentWeek, missed, "Europe/London", new Date("2026-09-08T12:00:00Z")); assert.equal(past.occurrences.find(item => item.programmeSessionId === "tue")?.status, "missed"); assert.equal(future.occurrences.find(item => item.programmeSessionId === "tue")?.status, "planned"); });
test("canonical schedule applies a dated salvage adjustment only to its target occurrence", () => { const adjusted = data({ salvageAdjustments: [{ source: "tue", sessionId: "sat", exerciseId: "leg-press", scheduledDate: "2026-09-05", sets: 1 }] }); const week = resolveWeekSchedule(currentWeek, adjusted, "Europe/London", new Date("2026-09-02T12:00:00Z")); const next = resolveWeekSchedule(currentWeek, adjusted, "Europe/London", new Date("2026-09-09T12:00:00Z")); assert.ok(week.occurrences.find(item => item.programmeSessionId === "sat")?.session.exerciseIds.includes("leg-press")); assert.equal(next.occurrences.find(item => item.programmeSessionId === "sat")?.session.exerciseIds.includes("leg-press"), false); });
test("Original week preserves programmed rest days and Saturday catch-up scope", () => { const adjusted = data({ salvageAdjustments: [{ source: "tue", sessionId: "sat", exerciseId: "leg-press", scheduledDate: "2026-09-05", sets: 1 }] }); const week = resolveWeekSchedule(currentWeek, adjusted, "Europe/London", new Date("2026-09-02T12:00:00Z")); assert.deepEqual(week.occurrences.map(item => [item.programmeSessionId, item.scheduledDate]), [["mon", "2026-08-31"], ["tue", "2026-09-01"], ["wed", "2026-09-02"], ["fri", "2026-09-04"], ["sat", "2026-09-05"]]); assert.equal(week.occurrences.find(item => item.programmeSessionId === "sat")?.session.exerciseIds.includes("leg-press"), true); });
test("Original Friday and Saturday stay on their canonical dates despite a Thursday catch-up", () => { const catchUp = data({ workouts: [{ id: "catch-up", name: "Lower catch-up", status: "completed", completedAt: "2026-09-03T18:00:00Z", startedAt: "2026-09-03T17:00:00Z", sets: [], substitutions: {}, notes: [], origin: "real" }] }); const friday = resolveTodayOccurrence(currentWeek, catchUp, "Europe/London", new Date("2026-09-04T10:00:00Z")); const saturday = resolveTodayOccurrence(currentWeek, catchUp, "Europe/London", new Date("2026-09-05T10:00:00Z")); const thursday = resolveTodayOccurrence(currentWeek, catchUp, "Europe/London", new Date("2026-09-03T10:00:00Z")); assert.equal(friday?.session.name, "Chest + Shoulders + Arms"); assert.equal(friday?.scheduledDate, "2026-09-04"); assert.equal(saturday?.session.name, "Lat Width + Lower Accessories"); assert.equal(saturday?.scheduledDate, "2026-09-05"); assert.equal(thursday?.session.status, "rest"); });
test("hydrated legacy Original programme metadata does not repack Friday into Saturday", () => { const legacy = legacyProgrammeSnapshot(); const profile = { ...legacy.profile, availabilityMode: "fixed_days" as const, availableDays: [1, 2, 3, 4, 5], daysPerWeek: 5 as const }; const hydrated = data({ generatedProgramme: legacy, activeProgrammeId: "legacy-personal-programme", trainingProfile: profile }); const friday = resolveTodayOccurrence(legacy.week, hydrated, "Europe/London", new Date("2026-09-04T10:00:00Z")); const saturday = resolveTodayOccurrence(legacy.week, hydrated, "Europe/London", new Date("2026-09-05T10:00:00Z")); assert.equal(friday?.programmeSessionId, "fri"); assert.equal(saturday?.programmeSessionId, "sat"); assert.equal(resolveWeekSchedule(legacy.week, hydrated, "Europe/London", new Date("2026-09-04T10:00:00Z")).occurrences.filter(item => item.session.exerciseIds.length).length, 5); });
test("missing active occurrence never falls back to another day's workout", () => { const onlyFriday = currentWeek.filter(session => session.id === "fri"); assert.equal(resolveTodayOccurrence(onlyFriday, data(), "Europe/London", new Date("2026-09-05T10:00:00Z")), undefined); });
