/* eslint-disable react-hooks/error-boundaries, react-hooks/purity */
import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { AppShell, EmptyState, NavigationRow, PageHeader, Surface } from "@/components/ui";
import { serverSupabase } from "@/lib/supabase-server";
import { clubRepository } from "@/lib/club-repository";
import { listClubOrganisationContexts, isClubStaffRole } from "@/lib/club-server-context";
import { resolveOrganisationTheme } from "@/lib/club";

export default async function ClubPage({ searchParams }: { searchParams?: Promise<{ org?: string }> }) {
  const supabase = await serverSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account?mode=signIn");
  try {
    clubRepository(supabase);
    const contexts = await listClubOrganisationContexts(supabase, user.id); const orgId = (await searchParams)?.org; const context = orgId ? contexts.find(item => item.organisation.id === orgId) : contexts.length === 1 ? contexts[0] : undefined;
    if (!context) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Choose your organisation" description="Select the gym workspace you want to use." />{contexts.length ? <Surface>{contexts.map(item => <NavigationRow key={item.organisation.id} href={`/club?org=${encodeURIComponent(item.organisation.id)}`} label={item.organisation.name} detail={`${item.role.replace("_", " ")} · Select workspace`} />)}</Surface> : <EmptyState title="Club access required">Your account is not linked to an active Club organisation.</EmptyState>}<AppNav /></AppShell>;
    const theme = resolveOrganisationTheme(context.organisation); const role = context.role;
    if (!isClubStaffRole(role)) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title={theme.organisationName} description="Your Club member workspace." /><Surface><span className="eyebrow">YOUR CLUB</span><NavigationRow href={`/club/classes?org=${encodeURIComponent(context.organisation.id)}`} label="Classes" detail="View the timetable and availability" /><NavigationRow href={`/club/shop?org=${encodeURIComponent(context.organisation.id)}`} label="Shop" detail="Browse products and your orders" /></Surface><AppNav /></AppShell>;
    const [members, locations, products, services, declarations, sessions, orders] = await Promise.all([context.repository.listMembers(context.organisation.id), context.repository.listLocations(context.organisation.id), context.repository.listCommerceProducts(context.organisation.id), context.repository.listServices(context.organisation.id), context.repository.listCashDeclarations(context.organisation.id), context.repository.listClassSessions(context.organisation.id), context.repository.listOrders(context.organisation.id)]);
    const now = Date.now(); const upcoming = sessions.filter(session => session.status === "scheduled" && new Date(session.startsAt).getTime() >= now).sort((a, b) => a.startsAt.localeCompare(b.startsAt)).slice(0, 3); const awaiting = declarations.filter(item => item.status === "declared").length; const disputes = declarations.filter(item => item.status === "discrepancy").length;
    return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · OPERATIONS" title={theme.organisationName} description="The operational view for today." /><Surface><span className="eyebrow">NEEDS ATTENTION</span>{awaiting || disputes ? <NavigationRow href={`/club/shop?org=${encodeURIComponent(context.organisation.id)}`} label={`${awaiting} cash ${awaiting === 1 ? "declaration" : "declarations"} to verify`} detail={disputes ? `${disputes} cash dispute${disputes === 1 ? "" : "s"} needs review` : "Reception review"} /> : <p className="muted">Nothing needs attention right now.</p>}</Surface><Surface><span className="eyebrow">OPERATIONS</span><NavigationRow href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`} label="Members" detail={`${members.length} active members`} /><NavigationRow href={`/club/classes?org=${encodeURIComponent(context.organisation.id)}`} label="Classes" detail={upcoming.length ? `${upcoming.length} upcoming session${upcoming.length === 1 ? "" : "s"}` : "No upcoming classes"} /><NavigationRow href={`/club/shop?org=${encodeURIComponent(context.organisation.id)}`} label="Reception · Shop" detail={`${products.length} products · ${orders.length} orders`} /><NavigationRow href={`/club/services?org=${encodeURIComponent(context.organisation.id)}`} label="Services" detail={`${services.filter(service => service.active).length} active services`} /></Surface><Surface><span className="eyebrow">TODAY · LOCATION CONTEXT</span>{locations.map(location => <div className="club-detail-row" key={location.id}><span>{location.name}</span><span className="muted">{location.active ? "Active" : "Inactive"}</span></div>)}{upcoming.map(session => <div className="club-detail-row" key={session.id}><span>{session.title ?? "Scheduled class"}</span><span className="muted">{new Date(session.startsAt).toLocaleString("en-GB", { weekday: "short", hour: "2-digit", minute: "2-digit" })}</span></div>)}</Surface><AppNav /></AppShell>;
  } catch { return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Club" description="Operational workspace." /><EmptyState title="Club couldn’t be loaded.">Try again shortly.</EmptyState><AppNav /></AppShell>; }
}
