import { redirect } from "next/navigation";
import Link from "next/link";
import { AppNav } from "@/components/app-nav";
import { ClubSectionNav } from "@/components/club-shell";
import { AppShell, EmptyState, PageHeader, Surface } from "@/components/ui";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
import { londonDateTime, type MemberScheduleItem } from "@/lib/club-scheduling";
import { serverSupabase } from "@/lib/supabase-server";
import { markScheduleNotificationSeenAction } from "./actions";
import type { MemberScheduleNotification } from "@/lib/club-scheduling";

export default async function MemberSchedulePage({searchParams}:{searchParams?:Promise<{org?:string}>}){
 const supabase=await serverSupabase();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/account?mode=signIn&next=%2Fmember-hub%2Fschedule");
 const context=await resolveClubOrganisationContext(supabase,user.id,(await searchParams)?.org);if(!context||!["member","trainer","gym_staff","gym_admin","owner"].includes(context.role))return <AppShell className="module-page member-area-page"><PageHeader title="My schedule"/><EmptyState title="Member schedule unavailable">Sign in with the R12 account linked to your gym membership.</EmptyState><AppNav/></AppShell>;
 const [scheduleResult,noticeResult]=await Promise.all([supabase.rpc("club_list_my_schedule",{p_organisation_id:context.organisation.id}),supabase.rpc("club_list_my_schedule_notifications",{p_organisation_id:context.organisation.id})]);const items=!scheduleResult.error&&Array.isArray(scheduleResult.data)?scheduleResult.data as MemberScheduleItem[]:[];const notices=!noticeResult.error&&Array.isArray(noticeResult.data)?noticeResult.data as MemberScheduleNotification[]:[];
 return <AppShell className="module-page member-area-page"><PageHeader eyebrow={context.organisation.name.toUpperCase()} title="My schedule" description="Your upcoming PT appointments and booked classes."/><ClubSectionNav organisation={context.organisation} role={context.role} contexts={context.availableContexts}/>{notices.length?<Surface className="member-hub-section"><span className="eyebrow">SCHEDULE UPDATES</span><h2>Recent updates</h2>{notices.slice(0,5).map(notice=><div key={notice.id} className="club-detail-row"><span><strong>{notice.action==="booked"?"Booked":notice.action==="cancelled"?"Cancelled":"Updated"}: {notice.title}</strong><small>{notice.startsAt?londonDateTime(notice.startsAt,{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Schedule change"}{notice.location?` · ${notice.location}`:""}</small></span>{notice.seenAt?<span className="muted">Seen</span>:<form action={markScheduleNotificationSeenAction.bind(null,context.organisation.id,notice.id)}><button className="secondary" type="submit">Mark seen</button></form>}</div>)}</Surface>:null}<Surface className="member-hub-section">{scheduleResult.error?<EmptyState title="Schedule couldn’t be loaded">Try again shortly.</EmptyState>:items.length?items.map(item=><article key={`${item.eventType}-${item.id}`} className="club-detail-row"><span><strong>{item.title}</strong><small>{londonDateTime(item.startsAt,{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"})}{item.staffName?` · with ${item.staffName}`:""}{item.locationName?` · ${item.locationName}`:""}</small></span><span className="muted">{item.eventType==="pt_session"?"PT session":"Class"}</span></article>):<EmptyState title="Nothing booked yet">Your PT appointments and confirmed class bookings will appear here.</EmptyState>}</Surface><Link className="member-hub-link" href={`/member-hub?org=${encodeURIComponent(context.organisation.id)}`}>Back to Member Area</Link><AppNav/></AppShell>;
}
