import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { AppShell, EmptyState, PageHeader, Surface } from "@/components/ui";
import { ClubSectionNav } from "@/components/club-shell";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOperationalContext } from "@/lib/club-server-context";
import { submitWorkAction, reviewWorkAction } from "./actions";

export default async function ClubWorkPage({ searchParams }: { searchParams?: Promise<{ org?: string }> }) {
  const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) redirect("/account?mode=signIn"); const context = await resolveClubOperationalContext(client, user.id, (await searchParams)?.org);
  if (!context) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="My Work" /><EmptyState title="Club staff access required">Your own work submissions are available to authorised Club staff.</EmptyState><AppNav /></AppShell>;
  const { data } = await client.rpc("club_finance_list_work", { p_organisation_id: context.organisation.id, p_staff_user_id: context.role === "gym_admin" || context.role === "owner" ? null : user.id }); const rows = Array.isArray(data) ? data as Array<Record<string, unknown>> : []; const manager = context.role === "gym_admin" || context.role === "owner";
  return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · STAFF" title="My Work" description="Submit hours and staff-delivered work for review." /><ClubSectionNav organisation={context.organisation} role={context.role} contexts={context.availableContexts} /><Surface><form action={submitWorkAction} className="club-detail-row"><input type="hidden" name="organisationId" value={context.organisation.id}/><label>Work type<select name="workType"><option value="hours">Hours</option><option value="pt">PT session</option><option value="transformation">Transformation/coaching</option><option value="class">Class delivery</option></select></label><label>Date<input type="date" name="workDate" required/></label><label>Duration (minutes)<input type="number" name="duration" min="1"/></label><label>Amount (£)<input type="number" name="amount" min="0" step="0.01"/></label><label>Note<input name="note" maxLength={240}/></label><button className="primary" type="submit">Submit for approval</button></form></Surface><Surface><span className="eyebrow">{manager ? "WORK TO REVIEW" : "MY SUBMISSIONS"}</span>{rows.length ? rows.map(row => <div className="club-detail-row" key={String(row.id)}><div><strong>{String(row.work_type).replaceAll("_", " ")}</strong><span className="muted">{String(row.work_date)} · {String(row.duration_minutes ?? "")} {row.amount_minor ? `· £${(Number(row.amount_minor)/100).toFixed(2)}` : ""}</span></div><span className="status-pill">{String(row.status).replaceAll("_", " ")}</span>{manager && row.status === "pending_approval" ? <form action={reviewWorkAction}><input type="hidden" name="organisationId" value={context.organisation.id}/><input type="hidden" name="id" value={String(row.id)}/><input type="hidden" name="status" value="approved"/><button className="secondary" type="submit">Approve</button></form> : null}</div>) : <p className="muted">No work submissions yet.</p>}</Surface><AppNav /></AppShell>;
}
