import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { AppShell, BackButton, EmptyState, PageHeader, Surface } from "@/components/ui";
import { ClubSectionNav } from "@/components/club-shell";
import { ClubMembershipAssignment } from "@/components/club-membership-assignment";
import { ClubCustomerLink } from "@/components/club-customer-link";
import { ClubMembershipCashPayment } from "@/components/club-membership-cash-payment";
import { ClubMembershipAccessStatus } from "@/components/club-membership-access-status";
import { ClubMembershipHousehold } from "@/components/club-membership-household";
import { ClubMemberInductionCompletion } from "@/components/club-member-induction-completion";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext, isClubStaffRole } from "@/lib/club-server-context";

export default async function ClubCustomerProfilePage({ params, searchParams }: { params: Promise<{ customerId: string }>; searchParams?: Promise<{ org?: string }> }) {
  const supabase = await serverSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account?mode=signIn");
  const context = await resolveClubOrganisationContext(supabase, user.id, (await searchParams)?.org);
  if (!context || !isClubStaffRole(context.role)) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Customer" description="This profile is not available." /><EmptyState title="Club access required">Ask an organisation owner to confirm your operational role.</EmptyState><AppNav /></AppShell>;
  const route = await params;
  const customer = (await context.repository.listCustomers(context.organisation.id)).find(item => item.id === decodeURIComponent(route.customerId));
  if (!customer) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Customer" description="Operational profile." /><EmptyState title="Customer not found">This person is not part of the selected organisation.</EmptyState><BackButton href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`}>Back to members</BackButton><AppNav /></AppShell>;
  const [products, locations, billingResult, membershipResult, canChangeMembershipAccess, customers, canManageHousehold, canPerformInduction] = await Promise.all([context.repository.listProducts(context.organisation.id, true), context.repository.listLocations(context.organisation.id), supabase.rpc("club_list_customer_billing", { p_organisation_id: context.organisation.id, p_customer_id: customer.id }), supabase.rpc("club_list_customer_memberships", { p_organisation_id: context.organisation.id, p_customer_id: customer.id }), context.repository.hasCapability(context.organisation.id, user.id, "memberships.end_immediately"), context.repository.listCustomers(context.organisation.id), context.repository.hasCapability(context.organisation.id, user.id, "memberships.assign"), context.repository.hasCapability(context.organisation.id, user.id, "induction.perform")]);
  const customerMemberships = Array.isArray(membershipResult.data) ? membershipResult.data as Array<{ id: string; product_name: string; status: string; starts_at: string; ends_at?: string }> : [];
  const householdRows = await Promise.all(customerMemberships.map(async membership => {
    const { data } = await supabase.rpc("club_get_membership_household", { p_organisation_id: context.organisation.id, p_membership_id: membership.id });
    return [membership.id, Array.isArray(data) ? data as Array<{ customerId: string; displayName?: string; billingContact?: boolean }> : []] as const;
  }));
  const householdByMembership = new Map(householdRows);
  const safetyResult = await supabase.rpc("club_get_member_access_safety", { p_organisation_id: context.organisation.id, p_customer_id: customer.id, p_location_id: null });
  const safety = safetyResult.data && typeof safetyResult.data === "object" ? safetyResult.data as { ageState?: string; inductionState?: string; inductionRequired?: boolean; twentyFourHourEligible?: boolean; inductionBooking?: { id?: string; startsAt?: string } | null } : undefined;
  const billingRows = Array.isArray(billingResult.data) ? billingResult.data as Array<{ id: string; amount_minor: number; currency: string; state: string; next_due_at: string; payment_method_family?: string; cash_channel?: string }> : [];
  const physicalLocations = locations.filter(location => location.active);
  const locationId = physicalLocations.length === 1 ? physicalLocations[0].id : undefined;
  return <AppShell className="module-page club-page">
    <PageHeader eyebrow="R12 CLUB · CUSTOMER" title={customer.displayName} description={customer.email ?? "Customer record"} />
    <ClubSectionNav organisation={context.organisation} role={context.role} contexts={context.availableContexts} />
    <div className="club-profile-grid">
      <Surface><span className="eyebrow">IDENTITY</span><h2>{customer.displayName}</h2><p className="muted">{customer.email ?? "No email recorded"}</p><p className="muted">{customer.userId ? "R12 account linked" : "No R12 account linked"}</p>{!customer.userId ? <><p className="muted">Linking preserves any existing membership and requires an independently verified personal account.</p><ClubCustomerLink organisationId={context.organisation.id} customerId={customer.id} /></> : null}</Surface>
      <Surface><span className="eyebrow">MEMBERSHIP</span><h2>Membership record</h2>{customerMemberships.length ? customerMemberships.map(item => { const holders = householdByMembership.get(item.id) ?? []; return <div className="club-membership-row" key={item.id}><div className="club-detail-row"><span>{item.product_name}<small>{item.status.replace(/_/g, " ")} · {new Date(item.starts_at).toLocaleDateString("en-GB")}{item.ends_at ? ` → ${new Date(item.ends_at).toLocaleDateString("en-GB")}` : " · Open-ended"}{holders.length > 1 ? ` · Shared with ${holders.filter(holder => holder.customerId !== customer.id).map(holder => `${holder.displayName ?? "Family member"}${holder.billingContact ? " (payer on file)" : ""}`).join(", ")}` : ""}</small></span>{canChangeMembershipAccess ? <ClubMembershipAccessStatus organisationId={context.organisation.id} membershipId={item.id} status={item.status} /> : null}</div><ClubMembershipHousehold organisationId={context.organisation.id} membershipId={item.id} holders={holders.map(holder => ({ customerId: holder.customerId, displayName: holder.displayName ?? "Family member", billingContact: holder.billingContact === true }))} candidates={customers.map(person => ({ id: person.id, displayName: person.displayName }))} canManage={canManageHousehold} /></div>; }) : <p className="muted">No membership is currently recorded.</p>}<p className="muted">Commercial membership can be recorded without an R12 account. Pausing access does not change recurring billing.</p>{["gym_admin", "owner"].includes(context.role) ? <ClubMembershipAssignment organisationId={context.organisation.id} organisationSlug={context.organisation.slug} customerId={customer.id} products={products} /> : null}</Surface>
      <Surface><span className="eyebrow">ACCESS ELIGIBILITY</span><p className="muted">Age: {({ adult: "18 or over", under_18: "Under 18 — no 24-hour door access", under_16: "Under 16 — restricted; staff review required", missing_date_of_birth: "Date of birth missing — access eligibility needs review", date_of_birth_conflict: "Date of birth conflict — resolve before access" } as Record<string, string>)[safety?.ageState ?? ""] ?? "Age not verified"}</p><p className="muted">Induction: {safety?.inductionRequired ? (safety.inductionState === "complete" ? "Complete" : safety.inductionState === "overdue" ? "Overdue" : safety.inductionState === "due" ? "Due — within grace" : safety.inductionState === "booked" ? "Booked" : "Required") : "Not required"}</p><ClubMemberInductionCompletion organisationId={context.organisation.id} customerId={customer.id} bookingId={safety?.inductionBooking?.id} startsAt={safety?.inductionBooking?.startsAt} locations={physicalLocations.map(location => ({ id: location.id, name: location.name }))} canPerform={canPerformInduction} required={safety?.inductionRequired === true} /><p className="muted">24-hour door access: {safety?.twentyFourHourEligible ? "Eligible" : "Not eligible or requires review"}</p></Surface>
      <Surface><span className="eyebrow">BILLING</span><h2>Membership payments</h2>{billingRows.length ? billingRows.map(row => <div className="club-detail-row" key={row.id}><span>{row.state.replace(/_/g, " ")}<small>{row.payment_method_family === "cash" ? "Cash arrangement" : "Payment arrangement"} · Due {new Date(row.next_due_at).toLocaleDateString("en-GB")}</small></span><strong>£{(row.amount_minor / 100).toFixed(2)}</strong></div>) : <p className="muted">No billing obligations recorded.</p>}{billingRows.length ? <ClubMembershipCashPayment organisationId={context.organisation.id} locationId={locationId} rows={billingRows} /> : null}</Surface>
    </div>
    <BackButton href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`}>Back to members</BackButton><AppNav />
  </AppShell>;
}
