"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { browserSupabase } from "@/lib/supabase-browser";
import { AppNav } from "@/components/app-nav";
import { AppShell, NavigationRow, PageHeader, Surface } from "@/components/ui";
import { loadData, loadGeneratedProgramme } from "@/lib/storage";
import { BrandLockup } from "@/components/brand-lockup";

type Account = { id: string; email?: string; profile?: { first_name?: string; last_name?: string; display_name?: string } };
type AuthMode = "signIn" | "signUp" | "forgot";

export default function AccountPage() {
  const router = useRouter(); const [supabase, setSupabase] = useState<ReturnType<typeof browserSupabase> | null>(null); const [account, setAccount] = useState<Account | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [authMode, setAuthMode] = useState<AuthMode>("signIn"); const [editing, setEditing] = useState(false); const [whoop, setWhoop] = useState<{ connected?: boolean; lastSyncAt?: string }>({});
  const refresh = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) { setAccount(null); setLoading(false); return; } const profileResponse = await fetch("/api/account"); const profile = profileResponse.ok ? await profileResponse.json() : undefined; setAccount({ id: user.id, email: user.email, profile: profile?.profile }); setFirstName(profile?.profile?.first_name ?? ""); setLastName(profile?.profile?.last_name ?? ""); setWhoop(await fetch("/api/integrations/whoop/status").then(response => response.ok ? response.json() : {}).catch(() => ({}))); setLoading(false); const trainingResponse = await fetch("/api/training-profile"); if (trainingResponse.ok) { const training = await trainingResponse.json(); const legacy = training?.active_programme_id === "legacy-personal-programme"; if (!training?.training_profile || (!training?.generated_programme && !legacy)) router.replace("/onboarding"); } };
  // Auth client initialization and subscription intentionally update state from an external session source.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { setSupabase(browserSupabase()); const mode = new URLSearchParams(window.location.search).get("mode"); if (mode === "signUp" || mode === "signIn" || mode === "forgot") setAuthMode(mode); }, []); useEffect(() => { if (!supabase) return; void refresh(); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { if (session?.user) void refresh(); else { setAccount(null); setLoading(false); } }); return () => listener.subscription.unsubscribe(); }, [supabase]);
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || (process.env.NODE_ENV === "development" ? window.location.origin : "https://the-road-to-12.vercel.app");
  const submit = async () => { if (!supabase) return; setMessage(""); if (authMode === "forgot") { const result = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${siteUrl}/account/reset` }); setMessage(result.error ? "We couldn't send reset instructions. Please try again." : "If an account exists for that email, we've sent password reset instructions."); return; } const result = authMode === "signIn" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { first_name: firstName.trim(), last_name: lastName.trim(), display_name: [firstName, lastName].filter(Boolean).join(" ") }, emailRedirectTo: `${siteUrl}/account?mode=signIn` } }); if (result.error) setMessage(authMode === "signIn" ? "We couldn't sign you in. Check your email and password and try again." : "We couldn't create your account. Check your details and try again."); else if (authMode === "signUp") setMessage("Check your email to confirm your account, then continue to R12."); else { await refresh(); router.push("/"); } };
  const saveProfile = async () => { const response = await fetch("/api/account", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ first_name: firstName, last_name: lastName }) }); if (!response.ok) { setMessage("We couldn't update your details. Please try again."); return; } setEditing(false); await refresh(); setMessage("Profile updated."); };
  if (loading) return <main className="shell auth-splash" aria-busy="true"><BrandLockup /><p>Resolving your session…</p></main>;
  if (!account) return <main className="legal-page account-page auth-page"><BrandLockup /><header><div><h1>{authMode === "forgot" ? "Reset password" : "Account"}</h1></div></header><p>{authMode === "signUp" ? "Create your profile to keep your training data private and synced." : authMode === "forgot" ? "Enter your email and we&apos;ll send secure reset instructions." : "Sign in to keep your training data private and synced."}</p>{authMode === "signUp" && <><label>First name<input value={firstName} onChange={event => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={event => setLastName(event.target.value)} /></label></>}<label>Email<input type="email" autoComplete="username" value={email} onChange={event => setEmail(event.target.value)} /></label>{authMode !== "forgot" && <label>Password<input type="password" autoComplete={authMode === "signUp" ? "new-password" : "current-password"} value={password} onChange={event => setPassword(event.target.value)} /></label>}<button className="primary" onClick={() => void submit()}>{authMode === "signIn" ? "Sign in" : authMode === "signUp" ? "Create account" : "Send reset email"}</button>{authMode === "signIn" && <button className="text-button" onClick={() => setAuthMode("forgot")}>Forgot password?</button>}<button className="text-button" onClick={() => setAuthMode(authMode === "signUp" ? "signIn" : "signUp")}>{authMode === "signUp" ? "I already have an account" : "Create account"}</button>{authMode === "forgot" && <button className="text-button" onClick={() => setAuthMode("signIn")}>Back to sign in</button>}{message && <p role="status">{message}{authMode === "signUp" && <><br /><Link href="/account?mode=signIn">Continue to R12</Link></>}</p>}<p><Link href="/">‹ Back</Link></p></main>;
  const fullName = [account.profile?.first_name, account.profile?.last_name].filter(Boolean).join(" ") || account.profile?.display_name || "Your account";
  const profile = loadData().trainingProfile;
  const programme = loadGeneratedProgramme();
  const profileSummary = profile ? `${profile.goal.replaceAll("_", " ")} · ${profile.experience} · ${profile.daysPerWeek} days · ${profile.sessionMinutes} min` : "Not set up yet";
  return <AppShell className="module-page account-page"><PageHeader eyebrow="ACCOUNT" title={fullName} />
    <Surface><span className="eyebrow">PROFILE</span><NavigationRow label="Personal details" detail={account.email ?? "Account email"} onClick={() => setEditing(value => !value)}><b>›</b></NavigationRow>{editing && <div className="inline-form"><label>First name<input value={firstName} onChange={event => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={event => setLastName(event.target.value)} /></label><button className="primary" onClick={() => void saveProfile()}>Save details</button></div>}</Surface>
    <Surface><span className="eyebrow">TRAINING</span><NavigationRow href="/training" label="Current programme" detail={programme?.name ?? "View your training plan"} /><NavigationRow href="/onboarding" label={programme ? "Build a new programme" : "Build my programme"} detail={programme ? "Create a proposal without changing your current plan" : "Answer a few questions to get started"} /><NavigationRow href="/onboarding" label="Training preferences" detail={profile ? profileSummary : "Set your training profile"} /></Surface>
    <Surface><span className="eyebrow">CONNECTIONS</span><div className="settings-row"><span>WHOOP<small>{whoop.connected ? `Connected${whoop.lastSyncAt ? ` · Last synced ${new Date(whoop.lastSyncAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : ""}` : "Not connected"}</small></span><b aria-hidden="true">›</b></div><div className="settings-row"><span>Apple Health<small>Not connected</small></span></div></Surface>
    <Surface><span className="eyebrow">SUPPORT</span><NavigationRow href="/privacy" label="Privacy" /><NavigationRow href="/terms" label="Terms" /></Surface>
    {message && <p role="status">{message}</p>}<button className="secondary account-signout" onClick={() => void supabase?.auth.signOut()}>Sign out</button><AppNav />
  </AppShell>;
}
