"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { browserSupabase } from "@/lib/supabase-browser";
import { loadData } from "@/lib/storage";
import { manualMondayReconstruction, MONDAY_RECOVERY_DATE, promotableMondayWorkout } from "@/lib/workout-recovery";
import type { Workout } from "@/lib/types";
type Account = { id: string; email?: string; profile?: { first_name?: string; last_name?: string; display_name?: string; timezone?: string; step_goal?: number } };
// Signup fields remain hidden during sign-in: hidden={authMode !== "signUp"}.
export default function AccountPage() {
  const router = useRouter(); const [supabase, setSupabase] = useState<ReturnType<typeof browserSupabase> | null>(null); const [account, setAccount] = useState<Account | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [authMode, setAuthMode] = useState<"signIn" | "signUp">("signIn"); const [editing, setEditing] = useState(false); const [recoveryOpen, setRecoveryOpen] = useState(false); const [recoverySaving, setRecoverySaving] = useState(false); const [recoveryAvailable, setRecoveryAvailable] = useState(false); const [whoop, setWhoop] = useState<{ connected?: boolean; lastSyncAt?: string }>({});
  const refresh = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) { setAccount(null); setLoading(false); return; } const profileResponse = await fetch("/api/account"); const profile = profileResponse.ok ? await profileResponse.json() : undefined; setAccount({ id: user.id, email: user.email, profile: profile?.profile }); setFirstName(profile?.profile?.first_name ?? ""); setLastName(profile?.profile?.last_name ?? ""); const [workoutsResponse, local] = await Promise.all([fetch("/api/workouts"), Promise.resolve(loadData())]); const server = workoutsResponse.ok ? await workoutsResponse.json() : { workouts: [] }; const test = (server.workouts as Workout[]).some(item => item.origin === "test" && item.plannedSessionId === "mon" && item.scheduledDate === MONDAY_RECOVERY_DATE); const localCandidate = local.workouts.some(item => item.origin !== "test" && item.scheduledDate === MONDAY_RECOVERY_DATE && item.sets.length > 0); setRecoveryAvailable(test || localCandidate || manualMondayReconstruction.sets.length > 0); setWhoop(await fetch("/api/integrations/whoop/status").then(response => response.ok ? response.json() : {}).catch(() => ({}))); setLoading(false); };
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { setSupabase(browserSupabase()); }, []); useEffect(() => { if (!supabase) return; void refresh(); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { if (session?.user) void refresh(); else { setAccount(null); setLoading(false); } }); return () => listener.subscription.unsubscribe(); }, [supabase]);
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || (process.env.NODE_ENV === "development" ? window.location.origin : "https://the-road-to-12.vercel.app");
  const submit = async (mode: "signIn" | "signUp") => { if (!supabase) return; setMessage(""); const result = mode === "signIn" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { first_name: firstName.trim(), last_name: lastName.trim(), display_name: [firstName, lastName].filter(Boolean).join(" ") }, emailRedirectTo: `${siteUrl}/account` } }); if (result.error) setMessage(result.error.message); else if (mode === "signUp") setMessage("Check your email to confirm your account."); else { await refresh(); router.push("/"); } };
  const saveProfile = async () => { const response = await fetch("/api/account", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ first_name: firstName, last_name: lastName }) }); if (!response.ok) { const result = await response.json().catch(() => ({})); setMessage(result.code ? `Profile could not be updated (${result.code}).` : "Profile could not be updated."); return; } setEditing(false); await refresh(); setMessage("Profile updated."); };
  const recover = async () => { setRecoverySaving(true); try { const response = await fetch("/api/workouts/reconcile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(promotableMondayWorkout()) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error ?? "Recovery could not be completed."); setRecoveryOpen(false); setRecoveryAvailable(false); setMessage("Workout recovered"); window.dispatchEvent(new Event("workouts-updated")); } catch (error) { setMessage(error instanceof Error ? error.message : "Recovery could not be completed."); } finally { setRecoverySaving(false); } };
  if (loading) return <main className="shell auth-splash" aria-busy="true"><span className="brand-mark">T/12</span><p>Resolving your session…</p></main>;
  if (!account) return <main className="legal-page account-page"><header><span className="brand-mark">T/12</span><div><p className="eyebrow">THE ROAD TO 12%</p><h1>Account</h1></div></header><p>{authMode === "signUp" ? "Create your profile to keep your training data private and synced." : "Sign in to keep your training data private and synced."}</p>{authMode === "signUp" && <><label>First name<input value={firstName} onChange={event => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={event => setLastName(event.target.value)} /></label></>}<label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} /></label><button className="primary" onClick={() => void submit(authMode)}>{authMode === "signIn" ? "Sign in" : "Create account"}</button><button className="text-button" onClick={() => setAuthMode(authMode === "signIn" ? "signUp" : "signIn")}>{authMode === "signIn" ? "Create account" : "I already have an account"}</button>{message && <p>{message}</p>}</main>;
  const fullName = [account.profile?.first_name, account.profile?.last_name].filter(Boolean).join(" ") || account.profile?.display_name || "Your account";
  return <main className="legal-page account-page"><header><span className="brand-mark">T/12</span><div><p className="eyebrow">THE ROAD TO 12%</p><h1>{fullName}</h1><p>{account.email}</p></div></header><section className="settings-groups"><div><span className="eyebrow">PROFILE</span><button className="settings-row" onClick={() => setEditing(value => !value)}><span>Personal details</span><b>›</b></button>{editing && <div className="inline-form"><label>First name<input value={firstName} onChange={event => setFirstName(event.target.value)} /></label><label>Last name<input value={lastName} onChange={event => setLastName(event.target.value)} /></label><button className="primary" onClick={() => void saveProfile()}>Save details</button></div>}</div><div><span className="eyebrow">CONNECTIONS</span><div className="settings-row"><span>WHOOP<small>{whoop.connected ? `Connected${whoop.lastSyncAt ? ` · Last synced ${new Date(whoop.lastSyncAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : ""}` : "Not connected"}</small></span><b>›</b></div><div className="settings-row"><span>Apple Health<small>Coming with iPhone app</small></span></div></div><div><span className="eyebrow">DATA</span><button className="settings-row" onClick={() => setRecoveryOpen(value => !value)}><span>Workout history &amp; recovery{recoveryAvailable && <small>Review available</small>}</span><b>›</b></button>{recoveryOpen && <section className="card recovery-review"><h2>Workout recovery</h2><p>We found workout data for Monday 31 August.</p><small>Upper Push + Core + Conditioning · 25 working sets · 10 min incline treadmill · Verified against WHOOP</small><button className="primary" disabled={recoverySaving} onClick={() => void recover()}>{recoverySaving ? "Recovering…" : "Recover workout"}</button></section>}<div className="settings-row"><span>Export data<small>Coming soon</small></span></div></div><div><span className="eyebrow">ACCOUNT</span><Link className="settings-row" href="/privacy"><span>Privacy</span><b>›</b></Link><Link className="settings-row" href="/terms"><span>Terms</span><b>›</b></Link><button className="settings-row" onClick={() => void supabase?.auth.signOut()}><span>Sign out</span><b>›</b></button></div></section>{message && <p role="status">{message}</p>}<p><Link href="/">Back to app</Link></p></main>;
}
