"use client";
import { useState } from "react";
import { composeAthleteProfile, type AvailabilityMode } from "@/lib/athlete-profile";
import { loadData, saveData } from "@/lib/storage";

const labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export function AvailabilitySettings() {
  const [data, setData] = useState(() => loadData()); const [open, setOpen] = useState(false); const [temporary, setTemporary] = useState(false); const [today] = useState(() => new Date()); const profile = data.athleteProfile ?? (data.trainingProfile ? composeAthleteProfile(data.trainingProfile) : undefined); if (!profile) return null;
  const mode = profile.availability.mode; const days = profile.availability.weekdays ?? [];
  const save = (nextMode: AvailabilityMode, nextDays: number[], isTemporary: boolean) => { const nextProfile = { ...profile, availability: { ...profile.availability, mode: nextMode, weekdays: nextDays } }; const next = isTemporary ? { ...data, athleteProfile: { ...profile, temporaryOverrides: [{ startDate: today.toISOString().slice(0, 10), endDate: new Date(today.getTime() + 6 * 86400000).toISOString().slice(0, 10), availableDays: nextDays, sessionsPerWeek: nextDays.length }] } } : { ...data, athleteProfile: nextProfile }; saveData(next); setData(next); setOpen(false); setTemporary(false); };
  return <><section className="surface"><span className="eyebrow">TRAINING AVAILABILITY</span><h3>{mode === "fixed_days" ? "Fixed availability" : mode === "flexible_week" ? "Flexible schedule" : mode === "rotating_pattern" ? "Rotating schedule" : "Variable schedule"}</h3><p>{days.length ? days.map(day => labels[day - 1]).join(" · ") : `Up to ${profile.training.daysPerWeek} sessions per week`}</p>{profile.temporaryOverrides?.[0] && <p className="muted">THIS WEEK · {profile.temporaryOverrides[0].availableDays?.map(day => labels[day - 1]).join(" · ") ?? "Updated availability"}</p>}<div className="availability-actions"><button className="secondary" onClick={() => { setTemporary(false); setOpen(true); }}>Edit availability</button><button className="text-button" onClick={() => { setTemporary(true); setOpen(true); }}>Update this week</button></div></section>{open && <div className="modal" role="dialog" aria-modal="true" aria-label="Training availability"><section className="programme-action-sheet"><div className="sheet-heading"><div><span className="eyebrow">{temporary ? "THIS WEEK" : "NORMAL AVAILABILITY"}</span><h2>{temporary ? "Update this week" : "Edit availability"}</h2></div><button className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><div className="status-options">{(["fixed_days", "flexible_week", "variable_week", "rotating_pattern", "work_away"] as AvailabilityMode[]).map(item => <button key={item} className="secondary" onClick={() => save(item, days, temporary)}>{item === "fixed_days" ? "Same days every week" : item === "flexible_week" ? "Any days are fine" : item === "variable_week" ? "Days change week to week" : item === "rotating_pattern" ? "Rotating pattern" : "Travel / work away"}</button>)}</div><p className="eyebrow">AVAILABLE DAYS</p><div className="status-options">{labels.map((label, index) => <button key={label} className={days.includes(index + 1) ? "primary" : "secondary"} onClick={() => save(temporary ? mode : "fixed_days", days.includes(index + 1) ? days.filter(day => day !== index + 1) : [...days, index + 1].sort((a, b) => a - b), temporary)}>{label}</button>)}</div>{temporary && <button className="text-button" onClick={() => { const next = { ...data, athleteProfile: { ...profile, temporaryOverrides: [] } }; saveData(next); setData(next); setOpen(false); }}>Clear this week&apos;s changes</button>}</section></div>}</>;
}
