"use client";
import { useState } from "react";
import { composeAthleteProfile, type AvailabilityMode } from "@/lib/athlete-profile";
import { loadData, saveData } from "@/lib/storage";
const labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
export function AvailabilitySettings() {
  const [data, setData] = useState(() => loadData()); const [open, setOpen] = useState(false); const [temporary, setTemporary] = useState(false); const [draftMode, setDraftMode] = useState<AvailabilityMode>("flexible_week"); const [draftDays, setDraftDays] = useState<number[]>([]); const [today] = useState(() => new Date());
  const profile = data.athleteProfile ?? (data.trainingProfile ? composeAthleteProfile(data.trainingProfile) : undefined); if (!profile) return null;
  const mode = profile.availability.mode; const days = profile.availability.weekdays ?? [];
  const begin = (isTemporary: boolean) => { setTemporary(isTemporary); setDraftMode(profile.availability.mode); setDraftDays(isTemporary ? profile.temporaryOverrides?.[0]?.availableDays ?? days : days); setOpen(true); };
  const save = () => { const nextProfile = { ...profile, availability: { ...profile.availability, mode: draftMode, weekdays: draftDays } }; const next = temporary ? { ...data, athleteProfile: { ...profile, temporaryOverrides: [{ startDate: today.toISOString().slice(0, 10), endDate: new Date(today.getTime() + 6 * 86400000).toISOString().slice(0, 10), availableDays: draftDays, sessionsPerWeek: draftDays.length }] } } : { ...data, athleteProfile: nextProfile }; saveData(next); setData(next); setOpen(false); };
  const modeLabel = (value: AvailabilityMode) => value === "fixed_days" ? "Same days every week" : value === "flexible_week" ? "Any days are fine" : value === "variable_week" ? "Days change week to week" : value === "rotating_pattern" ? "Rotating pattern" : "Travel / work away";
  return <><section className="surface"><span className="eyebrow">TRAINING AVAILABILITY</span><h3>{mode === "fixed_days" ? "Fixed availability" : mode === "flexible_week" ? "Flexible schedule" : mode === "rotating_pattern" ? "Rotating schedule" : "Variable schedule"}</h3><p>{days.length ? days.map(day => labels[day - 1]).join(" · ") : `Up to ${profile.training.daysPerWeek} sessions per week`}</p>{profile.temporaryOverrides?.[0] && <p className="muted">THIS WEEK · {profile.temporaryOverrides[0].availableDays?.map(day => labels[day - 1]).join(" · ") ?? "Updated availability"}</p>}<div className="availability-actions"><button type="button" className="secondary" onClick={() => begin(false)}>Manage availability</button></div></section>{open && <div className="modal" role="dialog" aria-modal="true" aria-label="Training availability"><section className="programme-action-sheet"><div className="sheet-heading"><div><span className="eyebrow">{temporary ? "THIS WEEK" : "NORMAL AVAILABILITY"}</span><h2>{temporary ? "Update this week" : "Manage availability"}</h2></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div>{!temporary && <button type="button" className="text-button" onClick={() => begin(true)}>Make a change for this week</button>}<div className="status-options">{(["fixed_days", "flexible_week", "variable_week", "rotating_pattern", "work_away"] as AvailabilityMode[]).map(item => <button type="button" key={item} className={draftMode === item ? "primary" : "secondary"} onClick={() => setDraftMode(item)}>{modeLabel(item)}</button>)}</div><p className="eyebrow">AVAILABLE DAYS</p><div className="status-options">{labels.map((label, index) => <button type="button" key={label} className={draftDays.includes(index + 1) ? "primary" : "secondary"} onClick={() => setDraftDays(current => current.includes(index + 1) ? current.filter(day => day !== index + 1) : [...current, index + 1].sort((a, b) => a - b))}>{label}</button>)}</div>{temporary && <button type="button" className="text-button" onClick={() => { const next = { ...data, athleteProfile: { ...profile, temporaryOverrides: [] } }; saveData(next); setData(next); setOpen(false); }}>Clear this week&apos;s changes</button>}<button type="button" className="primary" onClick={save}>Save changes</button></section></div>}</>;
}
