"use client";
import { useMemo, useState, useTransition } from "react";
import { parseRetailPriceCsv, exportRetailPriceCsv } from "@/lib/club-retail-pricing-csv";
import { parseCatalogueEnrichmentCsv } from "@/lib/club-catalogue-enrichment";
import { parseStockCountCsv, previewStockCount } from "@/lib/club-stock-count";
import { adjustStockAction } from "@/app/club/shop/actions";

type Product = { id:string; name:string; brand?:string; sku?:string; barcode?:string; sellPriceMinor:number; stockTracked:boolean };
export function ClubCatalogueOperations({ organisationId, locationId, products, balances }:{organisationId:string;locationId?:string;products:Product[];balances:Array<{productId:string;onHand:number}>}) {
 const [tab,setTab]=useState<"pricing"|"enrichment"|"stock">("pricing"); const [file,setFile]=useState(""); const [preview,setPreview]=useState<unknown>(); const [selected,setSelected]=useState<Product>(); const [count,setCount]=useState(""); const [pending,startTransition]=useTransition();
 const priceRows=useMemo(()=>products.map(p=>({variantId:p.id,supplier:"",brand:p.brand,parentProduct:p.name,supplierSku:p.sku,barcode:p.barcode,retailPriceMinor:p.sellPriceMinor})),[products]);
 const stockMap=useMemo(()=>new Map(balances.map(b=>[b.productId,b.onHand])),[balances]);
 const load=(text:string)=>{setFile(text); setPreview(tab==="pricing"?parseRetailPriceCsv(text):tab==="enrichment"?parseCatalogueEnrichmentCsv(text):parseStockCountCsv(text));};
 const applyCount=()=>{if(!selected||!locationId)return;const n=Number(count);if(!Number.isInteger(n)||n<0)return;startTransition(async()=>{await adjustStockAction({organisationId,locationId,productId:selected.id,countedQuantity:n,reason:"Stock count"});setSelected(undefined);setCount("");});};
 return <section aria-label="Catalogue operations" className="catalogue-operations"><div className="toolbar-actions"><button type="button" className={tab==="pricing"?"primary":"secondary"} onClick={()=>setTab("pricing")}>Retail pricing CSV</button><button type="button" className={tab==="enrichment"?"primary":"secondary"} onClick={()=>setTab("enrichment")}>Product enrichment</button><button type="button" className={tab==="stock"?"primary":"secondary"} onClick={()=>setTab("stock")}>Stock count</button></div>{tab==="pricing"?<><button type="button" className="secondary" onClick={()=>{const blob=new Blob([exportRetailPriceCsv(priceRows)],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="madhouse-retail-prices.csv";a.click();URL.revokeObjectURL(url);}}>Export retail prices</button><label>Upload edited pricing CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(load)}}/></label>{preview&&"rows" in (preview as object)?<p className="hint">{(preview as {rows:unknown[]}).rows.length} rows parsed · {(preview as {errors?:unknown[]}).errors?.length??0} errors · blank prices mean no change.</p>:null}</>:null}{tab==="enrichment"?<><p className="hint">PRODUCT INFORMATION ONLY — does not change stock, availability, pricing or supplier data.</p><label>Upload enrichment CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(load)}}/></label>{preview&&"rows" in (preview as object)?<p className="hint">{(preview as {rows:unknown[]}).rows.length} metadata rows matched for review · {(preview as {errors?:unknown[]}).errors?.length??0} validation errors.</p>:null}</>:null}{tab==="stock"?<><label>Scan/search exact product<input placeholder="Barcode, SKU or product" onChange={e=>{const q=e.target.value.toLowerCase();setSelected(products.find(p=>[p.name,p.sku,p.barcode].some(v=>v?.toLowerCase().includes(q))))}}/></label>{selected?<div className="club-detail-row"><span><strong>{selected.brand?`${selected.brand} · `:""}{selected.name}</strong><small>Current on-hand: {stockMap.get(selected.id)??0}</small></span><input aria-label="Counted quantity" type="number" min="0" step="1" value={count} onChange={e=>setCount(e.target.value)}/><button type="button" className="primary" disabled={pending} onClick={applyCount}>Record count</button></div>:null}<label>Upload stock-count CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(load)}}/></label>{preview&&"rows" in (preview as object)?<p className="hint">{(preview as {rows:unknown[]}).rows.length} counts parsed · {(preview as {errors?:unknown[]}).errors?.length??0} errors · blank = no change.</p>:null}</>:null}</section>;
}
