"use client";
import { useState, useTransition } from "react";
import { parseSupplierCsv, type SupplierImportResult } from "@/lib/club-supplier";
import { importSupplierCatalogueAction } from "@/app/club/shop/actions";
export function ClubCatalogueImport({ organisationId }: { organisationId: string; products: Array<{ id: string; name: string }> }) {
 const [supplierName,setSupplierName]=useState(""); const [fileName,setFileName]=useState(""); const [preview,setPreview]=useState<SupplierImportResult>(); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 const rows=preview?.rows.map(row=>({...row,wholesaleCostMinor:row.wholesaleCost?Math.round(Number(row.wholesaleCost.replace("£",""))*100):undefined,rrpMinor:row.rrp?Math.round(Number(row.rrp.replace("£",""))*100):undefined}));
 const importRows=()=>{if(!rows?.length)return;startTransition(async()=>{const result=await importSupplierCatalogueAction({organisationId,supplierName:supplierName||"Supplier",fileName:fileName||"supplier.csv",rows});setMessage(result.ok?`Imported ${result.created} new offers and updated ${result.updated}.` : result.error);});};
 return <section className="catalogue-import" aria-label="Supplier catalogue import"><details open><summary>Import supplier catalogue</summary><p className="muted">Upload CSV, review the mapped rows, then persist supplier offers. Supplier availability never changes gym stock.</p><label>Supplier name<input value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="Supplier" /></label><label>CSV file<input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file){setFileName(file.name);void file.text().then(text=>setPreview(parseSupplierCsv(text,supplierName||"Supplier")));}}}/></label>{preview?<div className="catalogue-import-review" aria-live="polite"><div className="club-detail-row"><span><strong>{preview.rows.length} valid rows</strong><small>{preview.invalid.length} invalid · {preview.duplicates.length} duplicate rows</small></span><span className="muted">Review before import</span></div>{preview.invalid.map(item=><p className="error-text" key={item.row}>Row {item.row}: {item.reason}</p>)}{preview.rows.slice(0,8).map((row,index)=><div className="club-detail-row" key={`${row.supplierSku||row.barcode||row.name}-${index}`}><span><strong>{row.brand?`${row.brand} · `:""}{row.name}</strong><small>{row.variant||row.size||row.category||"No variant"} · {row.barcode||"No barcode"}</small></span><span className="muted">{row.supplierSku||"No SKU"}<small>{row.availability?`Supplier availability ${row.availability}`:"Availability not supplied"}</small></span></div>)}</div>:null}<button type="button" className="primary" disabled={pending||!rows?.length||!supplierName.trim()} onClick={importRows}>{pending?"Importing…":"Confirm import"}</button>{message?<p className="message" role="status">{message}</p>:null}</details></section>;
}
