"use client";
import { useEffect, useState, useTransition, type ReactNode } from "react";
import { recordSunbedUseAction, searchGlowCustomersAction, getGlowBalanceAction, getGlowAgeAction, verifyGlowAgeAction, adjustGlowMinutesAction, removeGlowMinutesAction, getGlowHistoryAction, getGlowLoyaltyAction } from "@/app/club/sunbeds/actions";
import { glowZonePackages } from "@/lib/glow-zone";

type Customer={userId:string;name:string;email:string};
export function ClubSunbedOperations({organisationId,locations}:{organisationId:string;locations:Array<{id:string;name:string}>}){
 const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Customer|null>(null); const [results,setResults]=useState<Customer[]>([]); const [minutes,setMinutes]=useState(""); const [reason,setReason]=useState(""); const [dob,setDob]=useState(""); const [age,setAge]=useState("required"); const [balance,setBalance]=useState<number|null>(null); const [nextExpiry,setNextExpiry]=useState<string|null>(null); const [loyalty,setLoyalty]=useState(0); const [history,setHistory]=useState<Array<Record<string,unknown>>>([]); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 const locationId=locations.find(x=>x.name.toLowerCase().includes("carlton"))?.id??locations[0]?.id;
 const refresh=(userId:string)=>startTransition(async()=>{const [b,a,h,l]=await Promise.all([getGlowBalanceAction({organisationId,userId}),getGlowAgeAction({organisationId,userId}),getGlowHistoryAction({organisationId,userId}),getGlowLoyaltyAction({organisationId,userId})]);if(b.ok){setBalance(b.balance.minutes);setNextExpiry(b.balance.next_expiry)}if(a.ok)setAge(a.age?.status??"required");if(h.ok)setHistory(h.history);if(l.ok)setLoyalty(l.qualifyingSessions)});
 const choose=(x:Customer)=>{setSelected(x);setResults([]);refresh(x.userId)};
 const search=()=>startTransition(async()=>{const r=await searchGlowCustomersAction({organisationId,query});setResults(r.ok?r.results:[])});
 useEffect(()=>{const timer=setTimeout(()=>{if(query.trim().length<2){setResults([]);return}void search()},300);return()=>clearTimeout(timer)},[query]);
 const verify=()=>selected&&dob&&startTransition(async()=>{const r=await verifyGlowAgeAction({organisationId,userId:selected.userId,locationId:locationId!,dateOfBirth:dob});setMessage(r.ok?"Age verified and retained for future visits.":(r.error??"Verification failed"));if(r.ok)refresh(selected.userId)});
 const use=()=>selected&&locationId&&startTransition(async()=>{const r=await recordSunbedUseAction({organisationId,userId:selected.userId,locationId,minutes:Number(minutes),idempotencyKey:`glow-use-${selected.userId}-${Date.now()}`});setMessage(r.ok?`${minutes} minutes used. Issue the physical token now.`:(r.error??"Use could not be recorded."));if(r.ok)refresh(selected.userId)});
 const adjust=(remove:boolean)=>selected&&locationId&&startTransition(async()=>{const fn=remove?removeGlowMinutesAction:adjustGlowMinutesAction;const r=await fn({organisationId,userId:selected.userId,locationId,minutes:Number(minutes),reason,idempotencyKey:`glow-adjust-${selected.userId}-${remove?"remove":"add"}-${Date.now()}`});setMessage(r.ok?"Adjustment recorded and balance refreshed.":(r.error??"Adjustment failed"));if(r.ok)refresh(selected.userId)});
 return <div><h2>GLOW ZONE · Carlton</h2><p className="muted">Staffed operation only. Search a customer, verify age and record usage before issuing the physical token.</p><div className="actions"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email"/><button className="secondary" onClick={search} disabled={pending||query.trim().length<2}>Search customer</button></div>{results.map(x=><button className="club-detail-row" key={x.userId} onClick={()=>choose(x)}><strong>{x.name}</strong><small>{x.email}</small></button>)}{selected?<SurfaceCard><strong>{selected.name}</strong><p>Age: {age==="verified"?"AGE VERIFIED ✓":age==="under_18"?"UNDER 18 — NOT ELIGIBLE":"AGE VERIFICATION REQUIRED"}</p>{age!=="verified"&&age!=="under_18"?<div><label>Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)}/></label><button className="secondary" onClick={verify} disabled={pending||!dob}>Verify age (proof checked)</button></div>:null}<p>Available: {balance===null?"Loading…":`${balance} minutes`}</p>{nextExpiry?<p className="muted">Next expiry: {new Date(nextExpiry).toLocaleDateString("en-GB")}</p>:null}<p>GLOW LOYALTY: {loyalty>=9?"FREE-SESSION REWARD EARNED · Ask reception":`${loyalty} of 9 qualifying sessions`}</p><label>Minutes<input type="number" min="1" step="1" value={minutes} onChange={e=>setMinutes(e.target.value)}/></label><div className="actions"><button className="primary" disabled={pending||age!=="verified"||!minutes||!locationId} onClick={use}>Confirm usage</button><button className="secondary" disabled={pending||!minutes||!reason||!locationId} onClick={()=>adjust(false)}>Add minutes</button><button className="secondary" disabled={pending||!minutes||!reason||!locationId} onClick={()=>adjust(true)}>Remove minutes</button></div><label>Adjustment reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for adjustments"/></label><h3>Recent history</h3>{history.slice(0,8).map((e,i)=><p className="muted" key={i}>{String(e.kind)==="usage"?`-${e.minutes?String(Math.abs(Number(e.minutes))):""} min · GLOW ZONE session`: `${Number(e.minutes)>=0?"+":""}${String(e.minutes)} min · ${String(e.source??"Activity")}`}</p>)}</SurfaceCard>:null}{message?<p role="status">{message}</p>:null}<p className="muted">Available location: Carlton</p></div>}
function SurfaceCard({children}:{children:ReactNode}){return <div className="surface-card">{children}</div>}
