"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { OrganisationLocation } from "@/lib/club";
import { localDateTimeToIso, londonDateKey, londonDateTime, londonLocalInput, type ScheduleEvent, type ScheduleEventType, type ScheduleStatus, type WeeklyWorkingHours } from "@/lib/club-scheduling";
import { createSchedulePrivateClientAction, saveScheduleEventAction, saveStaffWeeklyWorkingHoursAction, searchScheduleMembersAction, searchSchedulePrivateClientsAction } from "@/app/club/schedule/actions";
import styles from "./club-schedule-calendar.module.css";
import extra from "./club-schedule-extra.module.css";

type Staff = { userId: string; name: string };
type Member = { id: string; name: string };
const kinds: Array<{ value: Exclude<ScheduleEventType,"class">; label: string }> = [{value:"pt_session",label:"PT session"},{value:"unavailable",label:"Unavailable"},{value:"other_location",label:"Other location"},{value:"leave",label:"Holiday / leave"},{value:"admin_time",label:"Admin time"}];
function shiftDay(key: string, amount: number) { const date = new Date(`${key}T12:00:00Z`); date.setUTCDate(date.getUTCDate()+amount); return londonDateKey(date); }
function rangeDay(key: string) { return Array.from({length:7},(_,index)=>shiftDay(key,index-3)); }
function localIsoInput(dateKey: string, hour = 9) { return `${dateKey}T${String(hour).padStart(2,"0")}:00`; }

export function ClubScheduleCalendar({ organisationId, events: initialEvents, staff, locations, initialDate, workingHours, currentUserId, canManageTeamHours, canOverrideHours }: { organisationId: string; events: ScheduleEvent[]; staff: Staff[]; locations: OrganisationLocation[]; initialDate: string; workingHours: WeeklyWorkingHours[]; currentUserId: string; canManageTeamHours: boolean; canOverrideHours: boolean }) {
  const router = useRouter(); const [date, setDate] = useState(initialDate); const [typeFilter, setTypeFilter] = useState("all"); const [locationFilter, setLocationFilter] = useState("all"); const [staffFilter, setStaffFilter] = useState("all");
  const [editing, setEditing] = useState<ScheduleEvent | undefined>(); const [open, setOpen] = useState(false); const [hoursOpen, setHoursOpen] = useState(false); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  const days = useMemo(()=>rangeDay(date),[date]);
  const visible = initialEvents.filter(event=>londonDateKey(new Date(event.startsAt))===date && (typeFilter==="all"||event.eventType===typeFilter) && (locationFilter==="all"||event.locationId===locationFilter) && (staffFilter==="all"||event.staffUserId===staffFilter)).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
  const today = londonDateKey(new Date());
  const selectedWeekday = new Date(`${date}T12:00:00Z`).getUTCDay() || 7;
  const selectedHours = workingHours.filter(item=>item.weekday===selectedWeekday&&(staffFilter==="all"||item.staffUserId===staffFilter));
  const navigate = (next:string) => { setDate(next); router.push(`/club/schedule?org=${encodeURIComponent(organisationId)}&date=${encodeURIComponent(next)}`); };
  const openCreate = () => { setEditing(undefined); setOpen(true); setMessage(""); };
  const save = (form: FormData) => startTransition(async () => {
    const start = String(form.get("startsAt")); const end = String(form.get("endsAt"));
    try {
      const result = await saveScheduleEventAction(organisationId,{ id:editing?.id, eventType:String(form.get("eventType")) as Exclude<ScheduleEventType,"class">, staffUserId:String(form.get("staffUserId")), customerId:String(form.get("customerId")||"")||undefined, privateClientId:String(form.get("privateClientId")||"")||undefined, workingHoursOverride:form.get("workingHoursOverride")==="on", workingHoursOverrideReason:String(form.get("workingHoursOverrideReason")||"")||undefined, locationId:String(form.get("locationId")||"")||undefined, externalLocation:String(form.get("externalLocation")||"")||undefined, title:String(form.get("title")), notes:String(form.get("notes")||"")||undefined, startsAt:localDateTimeToIso(start), endsAt:localDateTimeToIso(end), status:String(form.get("status")) as ScheduleStatus });
      if (!result.ok) { setMessage(result.error); return; }
      setOpen(false); router.refresh();
    } catch { setMessage("Choose a valid UK date and time."); }
  });
  return <section className={styles.workspace} aria-label="Shared staff schedule">
    <div className={styles.heading}><div><span className="eyebrow">MADHOUSE · TEAM CALENDAR</span><h2>Shared schedule</h2><p>One live view for PT sessions, classes and staff availability.</p></div><div className={styles.dateControls}>{(canManageTeamHours||staff.some(item=>item.userId===currentUserId))?<button className="secondary" type="button" onClick={()=>setHoursOpen(true)}>Working hours</button>:null}<button className="primary" type="button" onClick={openCreate}>＋ Add to schedule</button></div></div>
    <div className={styles.toolbar}><div className={styles.dateControls}><button className="secondary" type="button" aria-label="Previous week" onClick={()=>navigate(shiftDay(date,-7))}>‹</button><button className="secondary" type="button" onClick={()=>navigate(today)}>Today</button><button className="secondary" type="button" aria-label="Next week" onClick={()=>navigate(shiftDay(date,7))}>›</button><strong>{londonDateTime(`${date}T12:00:00Z`,{month:"long",year:"numeric"})}</strong></div><div className={styles.filters}><label>PT<select value={staffFilter} onChange={e=>setStaffFilter(e.target.value)}><option value="all">All PTs</option>{staff.map(item=><option key={item.userId} value={item.userId}>{item.name}</option>)}</select></label><label>Location<select value={locationFilter} onChange={e=>setLocationFilter(e.target.value)}><option value="all">All locations</option>{locations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Type<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">All items</option><option value="pt_session">PT sessions</option><option value="class">Classes</option><option value="unavailable">Unavailable</option><option value="other_location">Other location</option><option value="leave">Leave</option><option value="admin_time">Admin time</option></select></label></div></div>
    <div className={styles.dateStrip} aria-label="Choose a day">{days.map(day=><button key={day} type="button" className={`${styles.dateCell} ${day===date?styles.selected:""} ${day===today?styles.today:""}`} aria-pressed={day===date} onClick={()=>navigate(day)}><small>{londonDateTime(`${day}T12:00:00Z`,{weekday:"short"})}</small><strong>{Number(day.slice(-2))}</strong></button>)}</div>
    <div className={styles.agendaHead}><div><span className="eyebrow">{date===today?"TODAY":"DAY AGENDA"}</span><h3>{londonDateTime(`${date}T12:00:00Z`,{weekday:"long",day:"numeric",month:"long"})}</h3></div><button className="secondary" type="button" onClick={()=>router.push(`/club/classes?org=${encodeURIComponent(organisationId)}`)}>Manage classes ↗</button></div>
    <div className={extra.hoursHint}><strong>Usual hours</strong><span>{staffFilter==="all"?(selectedHours.length?`${selectedHours.length} PT${selectedHours.length===1?"":"s"} working`:`No PT working hours set`):(selectedHours.length?`${selectedHours[0].startsAt}–${selectedHours[0].endsAt}`:"No normal hours — appointments need an authorised override")}</span></div>
    {visible.length ? <div className={styles.agenda}>{visible.map(event=><article key={`${event.eventType}-${event.id}`} className={`${styles.event} ${styles[event.eventType]}`}><time>{londonDateTime(event.startsAt,{hour:"2-digit",minute:"2-digit"})}<small>{londonDateTime(event.endsAt,{hour:"2-digit",minute:"2-digit"})}</small></time><div className={styles.eventBody}><span className={styles.eventKind}>{event.eventType.replaceAll("_"," ")}</span><h4>{event.eventType==="pt_session"?event.memberName??event.title:event.title}</h4><p>{event.eventType==="pt_session"?`with ${event.staffName??"PT"}`:event.staffName??"Team schedule"}{event.locationName?` · ${event.locationName}`:""}{event.externalLocation?` · ${event.externalLocation}`:""}{event.capacity?` · Capacity ${event.capacity}`:""}</p>{event.description?<small className={styles.notes}>{event.description}</small>:null}{event.notes?<small className={styles.notes}>{event.notes}</small>:null}</div><div className={styles.eventActions}><span className={styles.status}>{event.status.replaceAll("_"," ")}</span>{event.eventType!=="class"?<button type="button" className="secondary" onClick={()=>{setEditing(event);setOpen(true);setMessage("");}}>Edit</button>:null}</div></article>)}</div> : <div className={styles.empty}><strong>A clear day, so far.</strong><p>No calendar items match this day and filter.</p><button className="secondary" type="button" onClick={openCreate}>Add a PT session or staff block</button></div>}
    <p className={styles.note}>Times shown in UK local time. Class bookings and capacity remain managed in Classes.</p>
    {open?<ScheduleEditor key={editing?.id??"new"} initial={editing} staff={staff} locations={locations} onClose={()=>setOpen(false)} onSubmit={save} pending={pending} message={message} organisationId={organisationId} canOverrideHours={canOverrideHours}/>:null}
    {hoursOpen?<HoursEditor organisationId={organisationId} staff={staff} currentUserId={currentUserId} canManageTeamHours={canManageTeamHours} workingHours={workingHours} onClose={()=>setHoursOpen(false)} onSaved={()=>{setHoursOpen(false);router.refresh();}}/>:null}
  </section>;
}

function ScheduleEditor({ initial, staff, locations, onClose, onSubmit, pending, message, organisationId, canOverrideHours }: { initial?: ScheduleEvent; staff: Staff[]; locations: OrganisationLocation[]; onClose:()=>void; onSubmit:(form:FormData)=>void; pending:boolean; message:string; organisationId:string; canOverrideHours:boolean }) {
  const [query,setQuery]=useState(initial?.memberName??""); const [members,setMembers]=useState<Member[]>([]); const [customerId,setCustomerId]=useState(initial?.customerId??""); const [privateClientId,setPrivateClientId]=useState(initial?.privateClientId??""); const [clientKind,setClientKind]=useState<"member"|"private">(initial?.privateClientId?"private":"member"); const [searching,setSearching]=useState(false); const [newPrivateName,setNewPrivateName]=useState(""); const [override,setOverride]=useState(initial?.workingHoursOverride??false); const [clientError,setClientError]=useState("");
  async function search(value:string){setQuery(value);setCustomerId("");setPrivateClientId("");if(value.trim().length<2){setMembers([]);return;}setSearching(true);const result=clientKind==="member"?await searchScheduleMembersAction(organisationId,value):await searchSchedulePrivateClientsAction(organisationId,value);setMembers(result);setSearching(false);}
  async function createPrivate(){const result=await createSchedulePrivateClientAction(organisationId,newPrivateName);if(!result.ok){setClientError(result.error);return;}setPrivateClientId(result.client.id);setCustomerId("");setQuery(result.client.name);setMembers([]);setNewPrivateName("");setClientError("");}
  const start=initial?londonLocalInput(initial.startsAt):localIsoInput(londonDateKey(new Date()),9); const end=initial?londonLocalInput(initial.endsAt):localIsoInput(londonDateKey(new Date()),10);
  return <div className={styles.overlay} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className={styles.sheet} role="dialog" aria-modal="true" aria-labelledby="schedule-editor-title"><header><div><span className="eyebrow">TEAM CALENDAR</span><h3 id="schedule-editor-title">{initial?"Edit schedule item":"Add to schedule"}</h3></div><button type="button" className="secondary" onClick={onClose} aria-label="Close">×</button></header><form onSubmit={event=>{event.preventDefault();onSubmit(new FormData(event.currentTarget));}}>
    <label>Type<select name="eventType" defaultValue={initial?.eventType??"pt_session"}>{kinds.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select></label>
    <label>PT / staff<select name="staffUserId" required defaultValue={initial?.staffUserId??staff[0]?.userId}>{staff.map(person=><option key={person.userId} value={person.userId}>{person.name}</option>)}</select></label>
    <fieldset className={extra.clientPicker}><legend>PT client</legend><div className={styles.dateControls}><button type="button" className={clientKind==="member"?"primary":"secondary"} onClick={()=>{setClientKind("member");setMembers([]);setCustomerId("");setPrivateClientId("");setQuery("");}}>R12 member</button><button type="button" className={clientKind==="private"?"primary":"secondary"} onClick={()=>{setClientKind("private");setMembers([]);setCustomerId("");setPrivateClientId("");setQuery("");}}>Private client</button></div><label>{clientKind==="member"?"Find a member":"Find a private client"}<input value={query} onChange={event=>void search(event.target.value)} placeholder={clientKind==="member"?"Search members":"Search private clients"} autoComplete="off"/><input type="hidden" name="customerId" value={customerId}/><input type="hidden" name="privateClientId" value={privateClientId}/>{searching?<small>Searching…</small>:null}{members.length&&!customerId&&!privateClientId?<div className={styles.results}>{members.map(member=><button type="button" key={member.id} onClick={()=>{setQuery(member.name);if(clientKind==="member")setCustomerId(member.id);else setPrivateClientId(member.id);setMembers([]);}}>{member.name}</button>)}</div>:null}</label>{clientKind==="private"&&!privateClientId?<div className={styles.dateControls}><input aria-label="New private client name" value={newPrivateName} onChange={event=>setNewPrivateName(event.target.value)} placeholder="New client name" maxLength={120}/><button type="button" className="secondary" onClick={()=>void createPrivate()}>Add private client</button></div>:null}{clientError?<small role="alert" className={styles.error}>{clientError}</small>:null}</fieldset>
    <label>Title<input name="title" required defaultValue={initial?.title??"Personal training"} maxLength={120}/></label>
    <div className={styles.two}><label>Location<select name="locationId" defaultValue={initial?.locationId??""}><option value="">No location</option>{locations.map(location=><option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Other location<input name="externalLocation" defaultValue={initial?.externalLocation??""} placeholder="Optional site name" maxLength={100}/></label></div>
    <div className={styles.two}><label>Starts<input type="datetime-local" name="startsAt" required defaultValue={start}/></label><label>Ends<input type="datetime-local" name="endsAt" required defaultValue={end}/></label></div>
    {canOverrideHours?<fieldset className={extra.clientPicker}><label className={extra.check}><input type="checkbox" name="workingHoursOverride" checked={override} onChange={event=>setOverride(event.target.checked)}/>Authorised working-hours override</label>{override?<label>Reason (recorded in the audit log)<input name="workingHoursOverrideReason" required maxLength={300} placeholder="Why is this appointment outside normal hours?"/></label>:null}</fieldset>:null}
    <label>Internal notes<textarea name="notes" defaultValue={initial?.notes??""} rows={3} maxLength={2000}/></label>
    {initial?<label>Status<select name="status" defaultValue={initial.status}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No show</option></select></label>:<input type="hidden" name="status" value="scheduled"/>}
    {message?<p role="alert" className={styles.error}>{message}</p>:null}<footer><button type="button" className="secondary" onClick={onClose}>Close</button><button type="submit" className="primary" disabled={pending}>{pending?"Saving…":"Save schedule item"}</button></footer>
  </form></section></div>;
}

function HoursEditor({ organisationId, staff, currentUserId, canManageTeamHours, workingHours, onClose, onSaved }: { organisationId:string; staff:Staff[]; currentUserId:string; canManageTeamHours:boolean; workingHours:WeeklyWorkingHours[]; onClose:()=>void; onSaved:()=>void }) {
  const [target,setTarget]=useState(canManageTeamHours?staff[0]?.userId??currentUserId:currentUserId);const [error,setError]=useState("");const [pending,startTransition]=useTransition();const existing=workingHours.filter(item=>item.staffUserId===target);const names=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
  const save=(form:FormData)=>startTransition(async()=>{const rows=names.flatMap((_,index)=>form.get(`enabled-${index+1}`)==="on"?[{weekday:index+1,startsAt:String(form.get(`start-${index+1}`)),endsAt:String(form.get(`end-${index+1}`))}]:[]);const result=await saveStaffWeeklyWorkingHoursAction(organisationId,target,rows);if(!result.ok){setError(result.error);return;}onSaved();});
  return <div className={styles.overlay} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className={styles.sheet} role="dialog" aria-modal="true" aria-labelledby="hours-editor-title"><header><div><span className="eyebrow">RECURRING AVAILABILITY · UK TIME</span><h3 id="hours-editor-title">Normal working hours</h3></div><button className="secondary" type="button" onClick={onClose} aria-label="Close">×</button></header><p>These weekly hours guide bookings; they don’t create calendar events. Leave a day unticked to mark it as off.</p><form key={target} onSubmit={event=>{event.preventDefault();save(new FormData(event.currentTarget));}}>{canManageTeamHours?<label>Coach<select value={target} onChange={event=>setTarget(event.target.value)}>{staff.map(item=><option key={item.userId} value={item.userId}>{item.name}</option>)}</select></label>:null}{names.map((name,index)=>{const day=index+1;const row=existing.find(item=>item.weekday===day);return <div className={extra.hoursRow} key={day}><label className={extra.check}><input type="checkbox" name={`enabled-${day}`} defaultChecked={!!row}/>{name}</label><label>From<input type="time" name={`start-${day}`} defaultValue={row?.startsAt??"09:00"}/></label><label>Until<input type="time" name={`end-${day}`} defaultValue={row?.endsAt??"17:00"}/></label></div>;})}{error?<p role="alert" className={styles.error}>{error}</p>:null}<footer><button className="secondary" type="button" onClick={onClose}>Close</button><button className="primary" disabled={pending}>{pending?"Saving…":"Save working hours"}</button></footer></form></section></div>;
}
