"use client";
import { useState, useTransition } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { recordStockRemovalAction } from "@/app/club/shop/actions";

export function ClubStockRemoval({ organisationId, locationId, products }: { organisationId: string; locationId?: string; products: ClubCommerceProduct[] }) {
  const [open, setOpen] = useState(false); const [productId, setProductId] = useState(products.find(p => p.stockTracked && p.active)?.id ?? ""); const [quantity, setQuantity] = useState("1"); const [reason, setReason] = useState("staff_consumption"); const [note, setNote] = useState(""); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  if (!locationId) return null;
  const submit = () => startTransition(async () => { const result = await recordStockRemovalAction({ organisationId, locationId, productId, quantity: Number(quantity), reason, note }); setMessage(result.ok ? "Stock removal recorded." : result.error); if (result.ok) { setOpen(false); setNote(""); } });
  return <section aria-label="Remove stock"><button className="secondary" type="button" onClick={() => setOpen(true)}>Remove / comp stock</button>{open ? <div className="modal" role="dialog" aria-modal="true"><form className="sheet" onSubmit={e => { e.preventDefault(); submit(); }}><h2>Remove stock</h2><p className="muted">Use for consumption, giveaways, samples, damage or waste. No payment is created.</p><label>Product<select value={productId} onChange={e => setProductId(e.target.value)}>{products.filter(p => p.stockTracked && p.active).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Quantity<input type="number" min="1" step="1" value={quantity} onChange={e => setQuantity(e.target.value)} /></label><label>Reason<select value={reason} onChange={e => setReason(e.target.value)}><option value="staff_consumption">Staff consumption</option><option value="complimentary">Complimentary giveaway</option><option value="promotion_sample">Promotion sample</option><option value="damaged">Damaged</option><option value="waste">Waste / spoilage</option><option value="other">Other</option></select></label><label>Note (optional)<input value={note} onChange={e => setNote(e.target.value)} /></label>{message ? <p role="alert" className="error-text">{message}</p> : null}<button className="primary full" disabled={pending || !productId} type="submit">{pending ? "Recording…" : "Record removal"}</button><button className="secondary full" type="button" onClick={() => setOpen(false)}>Cancel</button></form></div> : null}</section>;
}
