"use client";
import { useState, useTransition, type TransitionStartFunction } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { createAndPublishSupplierProductAction, publishSupplierOfferAction } from "@/app/club/shop/supplier-catalogue/actions";

const money = (minor: unknown) => typeof minor === "number" ? `£${(minor / 100).toFixed(2)}` : "Price required";
export function ClubSupplierCatalogue({ organisationId, offers, products }: { organisationId: string; offers: Array<Record<string, unknown>>; products: ClubCommerceProduct[] }) {
  const [query, setQuery] = useState(""); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string>(); const [create, setCreate] = useState<Record<string, unknown>>();
  const groups = new Map<string, Record<string, unknown>[]>(); offers.forEach(offer => { const key = `${String(offer.supplier ?? "")}|${String(offer.brand ?? "")}|${String(offer.name ?? "")}`; groups.set(key, [...(groups.get(key) ?? []), offer]); });
  const visible = [...groups.entries()].map(([key, variants]) => ({ key, variants })).filter(group => group.variants.some(offer => [offer.name, offer.brand, offer.category, offer.variant, offer.size, offer.supplier_sku, offer.barcode].some(value => String(value ?? "").toLowerCase().includes(query.toLowerCase()))));
  return <section aria-label="Supplier catalogue"><div className="section-heading"><div><span className="eyebrow">SUPPLIER CATALOGUE</span><h2>Grouped parent products</h2><small className="muted">{visible.length} parents · {offers.length} exact variants</small></div><input aria-label="Search supplier catalogue" placeholder="Brand, product, flavour, size, SKU or barcode" value={query} onChange={event => setQuery(event.target.value)} /></div>{visible.length ? <div className="club-catalogue-list">{visible.map(group => { const first = group.variants[0]; const priced = group.variants.map(v => Number(v.retail_price_minor)).filter(v => Number.isFinite(v) && v > 0); const summary = priced.length === 0 ? "Unpriced" : new Set(priced).size === 1 ? money(priced[0]) : `From ${money(Math.min(...priced))}`; return <details className="club-catalogue-row" key={group.key}><summary><div><strong>{first.brand ? `${String(first.brand)} · ` : ""}{String(first.name)}</strong><small>{String(first.category ?? "Uncategorised")} · {group.variants.length} variants · {summary}</small></div><span>{group.variants.filter(v => v.supplier_availability === "available").length} supplier available</span></summary><div className="club-catalogue-variants">{group.variants.map(offer => { const linked = products.find(product => product.id === String(offer.club_product_id)); const retail = Number(offer.retail_price_minor); return <div className="club-detail-row" key={String(offer.id)}><span><strong>{[offer.size, offer.variant].filter(Boolean).join(" · ") || "Exact variant"}</strong><small>{offer.supplier_sku ? `SKU ${offer.supplier_sku}` : "No SKU"}{offer.barcode ? ` · Barcode ${offer.barcode}` : ""} · Supplier {String(offer.supplier_availability ?? "unknown")}</small></span><span>{Number.isFinite(retail) && retail > 0 ? money(retail) : "Unpriced"}{linked ? <button type="button" className="secondary" disabled={pending || offer.sellable === true} onClick={() => startTransition(async () => { const result = await publishSupplierOfferAction({ organisationId, offerId: String(offer.id), productId: linked.id, retailPriceMinor: retail }); setMessage(result.ok ? "Published to the member Shop." : result.error); })}>{offer.sellable ? "Published" : "Publish"}</button> : <button type="button" className="secondary" disabled={pending} onClick={() => setCreate(offer)}>Create product</button>}</span></div>; })}</div></details>; })}</div> : <p className="muted">No supplier products match this search.</p>}{message ? <p className="message" role="status">{message}</p> : null}{create ? <CreateProductDialog organisationId={organisationId} offer={create} pending={pending} close={() => setCreate(undefined)} onDone={setMessage} startTransition={startTransition} /> : null}</section>;
}
function CreateProductDialog({ organisationId, offer, pending, close, onDone, startTransition }: { organisationId: string; offer: Record<string, unknown>; pending: boolean; close: () => void; onDone: (message: string) => void; startTransition: TransitionStartFunction }) {
  const [price, setPrice] = useState(offer.retail_price_minor ? (Number(offer.retail_price_minor) / 100).toFixed(2) : "");
  return <div className="modal" role="dialog" aria-modal="true"><form className="sheet" onSubmit={event => { event.preventDefault(); const retailPriceMinor = Math.round(Number(price) * 100); startTransition(async () => { const result = await createAndPublishSupplierProductAction({ organisationId, offerId: String(offer.id), name: String(offer.name), brand: String(offer.brand ?? ""), category: String(offer.category ?? ""), barcode: String(offer.barcode ?? ""), retailPriceMinor }); onDone(result.ok ? "Created and published to the member Shop." : result.error ?? "Could not publish product."); if (result.ok) close(); }); }}><h2>Create Madhouse product</h2><p>Review the supplier details, then approve the customer price.</p><label>Product name<input defaultValue={String(offer.name)} required /></label><label>Retail price (£)<input inputMode="decimal" value={price} onChange={event => setPrice(event.target.value)} required /></label><button type="submit" className="primary full" disabled={pending}>Create and publish</button><button type="button" className="secondary full" onClick={close}>Cancel</button></form></div>;
}
