"use client";
import { useState, useTransition } from "react";
import { parseRetailPriceCsv, exportRetailPriceCsv } from "@/lib/club-retail-pricing-csv";
import { parseCatalogueEnrichmentCsv } from "@/lib/club-catalogue-enrichment";
import { parseStockCountCsv } from "@/lib/club-stock-count";
import { adjustStockAction } from "@/app/club/shop/actions";
import { commitCatalogueEnrichmentAction, commitRetailPriceCsvAction } from "@/app/club/shop/supplier-catalogue/actions";
type Product={id:string;name:string;brand?:string;sku?:string;barcode?:string;sellPriceMinor:number;stockTracked:boolean};
export function ClubCatalogueOperations({organisationId,locationId,products,balances}:{organisationId:string;locationId?:string;products:Product[];balances:Array<{productId:string;onHand:number}>}){
 const [tab,setTab]=useState<"pricing"|"enrichment"|"stock">("pricing"); const [preview,setPreview]=useState<any>(); const [selected,setSelected]=useState<Product>(); const [count,setCount]=useState(""); const [pending,startTransition]=useTransition();
 const read=(text:string)=>setPreview(tab==="pricing"?parseRetailPriceCsv(text):tab==="enrichment"?parseCatalogueEnrichmentCsv(text):parseStockCountCsv(text));
 const commit=()=>{if(!preview)return;startTransition(async()=>{const r=tab==="pricing"?await commitRetailPriceCsvAction({organisationId,rows:preview.rows}):await commitCatalogueEnrichmentAction({organisationId,rows:preview.rows});window.alert(r.ok?`Updated ${r.updated}.`:r.error);});};
 const record=()=>{if(!selected||!locationId)return;const n=Number(count);if(!Number.isInteger(n)||n<0)return;startTransition(async()=>{await adjustStockAction({organisationId,locationId,productId:selected.id,countedQuantity:n,reason:"Stock count"});setSelected(undefined);setCount("");});};
 return <section aria-label="Catalogue operations" className="catalogue-operations"><div className="toolbar-actions"><button type="button" className={tab==="pricing"?"primary":"secondary"} onClick={()=>setTab("pricing")}>Retail pricing CSV</button><button type="button" className={tab==="enrichment"?"primary":"secondary"} onClick={()=>setTab("enrichment")}>Product enrichment</button><button type="button" className={tab==="stock"?"primary":"secondary"} onClick={()=>setTab("stock")}>Stock count</button></div>{tab==="pricing"&&<><button type="button" className="secondary" onClick={()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([exportRetailPriceCsv(products.map(p=>({variantId:p.id,supplier:"",parentProduct:p.name,brand:p.brand,supplierSku:p.sku,barcode:p.barcode,retailPriceMinor:p.sellPriceMinor})))]));a.download="retail-prices.csv";a.click();}}>Export retail prices</button><label>Upload pricing CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(read)}}/></label>{preview&&<><p className="hint">{preview.rows.length} rows · {preview.errors.length} errors · blank prices are no change.</p><button className="primary" disabled={pending||preview.errors.length>0} onClick={commit}>Confirm pricing import</button></>}</>}{tab==="enrichment"&&<><p className="hint">PRODUCT INFORMATION ONLY — stock, availability and pricing are unchanged.</p><label>Upload enrichment CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(read)}}/></label>{preview&&<><p className="hint">{preview.rows.length} metadata rows · {preview.errors.length} errors.</p><button className="primary" disabled={pending||preview.errors.length>0} onClick={commit}>Confirm enrichment</button></>}</>}{tab==="stock"&&<><label>Scan/search exact variant<input placeholder="Barcode, SKU, brand or product" onChange={e=>{const q=e.target.value.toLowerCase();setSelected(products.find(p=>[p.name,p.brand,p.sku,p.barcode].some(v=>v?.toLowerCase().includes(q))))}}/></label>{selected&&<div className="club-detail-row"><span><strong>{selected.name}</strong><small>Current on-hand: {balances.find(b=>b.productId===selected.id)?.onHand??0}</small></span><input aria-label="Counted quantity" type="number" min="0" step="1" value={count} onChange={e=>setCount(e.target.value)}/><button className="primary" onClick={record} disabled={pending}>Record count</button></div>}<label>Upload stock-count CSV<input type="file" accept=".csv" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(read)}}/></label>{preview&&<p className="hint">{preview.rows.length} counts · {preview.errors.length} errors · blank is no change.</p>}</>}</section>;
}
