"use client";

import { useState, useTransition } from "react";
import { startClubJoiningAction, type JoiningActionResult } from "@/app/club/join/actions";
import styles from "@/components/club-members-directory.module.css";
type JoinableProduct = { id: string; name: string; priceMinor: number; billing: string; durationDays?: number };

export function ClubJoiningForm({ organisationId, products }: { organisationId: string; products: JoinableProduct[] }) {
  const [productId, setProductId] = useState(products[0]?.id ?? ""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [message, setMessage] = useState<JoiningActionResult>(); const [pending, startTransition] = useTransition(); const [key] = useState(() => crypto.randomUUID());
  const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(undefined); startTransition(async () => { setMessage(await startClubJoiningAction({ organisationId, productId, displayName: name, email: email || undefined, phone: phone || undefined, idempotencyKey: key })); }); };
  if (message?.ok) return <section className={styles.onboarding}><span className="eyebrow">DETAILS RECORDED</span><h2>{message.productName}</h2><p>Amount: £{(message.amountMinor / 100).toFixed(2)} · {message.billing === "recurring" ? "Recurring" : "One-off"}{message.durationDays ? ` · ${message.durationDays} days` : ""}</p><p className={styles.hint}>Your joining request is recorded. Payment setup and membership activation still require the authoritative Madhouse staff/provider step.</p><p className="muted">Status: {message.status.replace(/_/g, " ")}</p></section>;
  return <section className={styles.onboarding}><div className={styles.onboardingHead}><div><span className="eyebrow">START JOINING</span><h2>Choose your membership</h2><p className="muted">Your details are recorded securely for this Club organisation.</p></div></div><form className={styles.onboardingForm} onSubmit={submit}><label>Membership<select required value={productId} onChange={event => setProductId(event.target.value)}>{products.map(product => <option key={product.id} value={product.id}>{product.name} · £{(product.priceMinor / 100).toFixed(2)} · {product.billing}{product.durationDays ? ` · ${product.durationDays} days` : ""}</option>)}</select></label><label>Name<input required value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label>Email<input required type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="email" /></label><label>Phone <span className="muted">(optional)</span><input type="tel" value={phone} onChange={event => setPhone(event.target.value)} autoComplete="tel" /></label><button className="primary" type="submit" disabled={pending || !productId}>{pending ? "Recording details…" : "Continue joining"}</button>{message && !message.ok ? <p className="error-text" role="alert">{message.error}</p> : null}</form></section>;
}
