"use client";

import { useState } from "react";
import { saveInductionPolicyAction } from "@/app/club/induction/actions";

export function InductionPolicyForm({ organisationId }: { organisationId: string }) {
  const [requirement, setRequirement] = useState<"none" | "online_or_in_person" | "in_person">("none");
  const [graceDays, setGraceDays] = useState(14); const [overdueAccess, setOverdueAccess] = useState<"allow" | "hold">("hold"); const [extension, setExtension] = useState(false); const [maxExtension, setMaxExtension] = useState(7); const [reack, setReack] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const result = await saveInductionPolicyAction({ organisationId, requirement, graceDays, overdueAccess, appointmentExtensionEnabled: extension, maxAppointmentExtensionDays: extension ? maxExtension : undefined, requiresReacknowledgement: reack }); setMessage(result.ok ? "Induction policy saved." : result.error); }
  return <form onSubmit={submit} className="club-form"><label>Requirement<select value={requirement} onChange={event => setRequirement(event.target.value as typeof requirement)}><option value="none">No induction required</option><option value="online_or_in_person">Online or in-person</option><option value="in_person">In-person induction</option></select></label><label>Grace period (days)<input type="number" min="0" value={graceDays} onChange={event => setGraceDays(Number(event.target.value))} /></label><label>After grace period<select value={overdueAccess} onChange={event => setOverdueAccess(event.target.value as typeof overdueAccess)}><option value="hold">Hold gym access</option><option value="allow">Allow access with reminder</option></select></label><label className="club-checkbox"><input type="checkbox" checked={extension} onChange={event => setExtension(event.target.checked)} /> Allow booked appointment extension</label>{extension ? <label>Maximum extension (days)<input type="number" min="0" value={maxExtension} onChange={event => setMaxExtension(Number(event.target.value))} /></label> : null}<label className="club-checkbox"><input type="checkbox" checked={reack} onChange={event => setReack(event.target.checked)} /> Require acknowledgement for each new version</label><button type="submit">Save induction policy</button>{message ? <p className="muted" role="status">{message}</p> : null}</form>;
}
