"use client";
import { useMemo, useState, useTransition } from "react";
import type { ClubCommerceProduct, ClubStockBalance } from "@/lib/club-commerce";
import { adjustStockAction } from "@/app/club/shop/actions";

type Location = { id: string; name: string; active: boolean };
export function ClubStockPanel({ organisationId, products, locations, balances, locationId, canAdjust }: { organisationId: string; products: ClubCommerceProduct[]; locations: Location[]; balances: ClubStockBalance[]; locationId?: string; canAdjust: boolean }) {
  const [query, setQuery] = useState(""); const [barcode, setBarcode] = useState(""); const [selected, setSelected] = useState<ClubCommerceProduct>(); const [delta, setDelta] = useState(""); const [reason, setReason] = useState("Opening stock"); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  const rows = useMemo(() => products.filter(product => product.stockTracked && product.name.toLowerCase().includes(query.toLowerCase())).map(product => { const entries = balances.filter(item => item.productId === product.id); return { product, entries }; }), [balances, products, query]);
  const locationName = (id: string) => locations.find(location => location.id === id)?.name ?? "Location";
  const submit = () => { if (!selected || !locationId) return; const quantityDelta = Number(delta); if (!Number.isInteger(quantityDelta) || quantityDelta === 0) return setMessage("Enter a whole-number stock movement."); startTransition(async () => { const result = await adjustStockAction({ organisationId, locationId, productId: selected.id, quantityDelta, reason }); setMessage(result.ok ? "Stock movement recorded." : result.error); if (result.ok) { setSelected(undefined); setDelta(""); } }); };
  return <section aria-label="Stock control" data-testid="stock-panel"><div className="section-heading"><div><span className="eyebrow">STOCK</span><h2>{locationId ? `${locationName(locationId)} stock` : "Stock across locations"}</h2></div><div className="toolbar-actions"><input aria-label="Search stock" placeholder="Search products" value={query} onChange={event => setQuery(event.target.value)} /><input aria-label="Scan or enter barcode" placeholder="Scan barcode" value={barcode} onChange={event => { const value = event.target.value.trim(); setBarcode(value); const match = products.find(product => product.stockTracked && product.barcode === value); if (match) { setSelected(match); setMessage(undefined); } }} />{locationId ? <span className="muted">Unknown until counted</span> : null}</div></div>{rows.length ? <div className="club-stock-grid">{rows.map(({ product, entries }) => <article className="club-stock-row" key={product.id}><div><strong>{product.name}</strong>{product.barcode ? <small>Barcode {product.barcode}</small> : null}</div>{entries.length ? entries.map(entry => <span key={entry.locationId}><b>{entry.onHand ?? "—"}</b><small>{locationName(entry.locationId)} · {entry.availableToSell ?? "Stock not counted"} available</small></span>) : <span><b>—</b><small>Stock not counted</small></span>}{canAdjust && locationId ? <button type="button" className="secondary" onClick={() => setSelected(product)}>Adjust</button> : null}</article>)}</div> : <p className="muted">No stock-tracked products are configured.</p>}{selected ? <div className="modal" role="dialog" aria-modal="true"><form className="sheet" onSubmit={event => { event.preventDefault(); submit(); }}><div className="sheet-heading"><div><span className="eyebrow">STOCK MOVEMENT</span><h2>{selected.name}</h2></div><button type="button" className="text-button" onClick={() => setSelected(undefined)}>Cancel</button></div><label>Quantity change<input type="number" step={1} value={delta} onChange={event => setDelta(event.target.value)} placeholder="e.g. 12 or -1" required /></label><label>Reason<select value={reason} onChange={event => setReason(event.target.value)}><option>Opening stock</option><option>Delivery received</option><option>Stock count</option><option>Damage / wastage</option><option>Correction</option><option>Return</option></select></label>{message ? <p role="alert" className="error-text">{message}</p> : null}<button className="primary full" type="submit" disabled={pending}>{pending ? "Saving…" : "Record movement"}</button></form></div> : null}</section>;
}
