"use client";
import { useState, useTransition } from "react";
import { prepareSupplierCycleAction, markSupplierOrderedAction, exportSupplierOrderAction, updateReplenishmentLineAction } from "@/app/club/shop/supplier-orders/actions";
type Line = Record<string, unknown>;
export function ClubSupplierOrders({ organisationId, demand, batches, replenishmentLines = [] }: { organisationId: string; demand: Line[]; batches: Line[]; replenishmentLines?: Line[] }) {
 const [pending,startTransition]=useTransition();
 const [edits,setEdits]=useState<Record<string,{quantity:number;allocations:Array<{locationId:string;quantity:number}>}>>({});
 const supplierGroups=[...new Map(demand.map(item=>[String(item.supplier_id),{id:String(item.supplier_id),name:String(item.supplier)}])).values()];
 const download=(reference:string,csv:string)=>{const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`${reference}.csv`;a.click();URL.revokeObjectURL(url);};
 return <section aria-label="Supplier orders"><div className="club-catalogue-list">{supplierGroups.map(supplier=>{const lines=demand.filter(item=>String(item.supplier_id)===supplier.id);return <article className="club-catalogue-row" key={supplier.id}><div><strong>{supplier.name}</strong><small>{lines.length} paid member demand lines · {lines.reduce((sum,item)=>sum+Number(item.quantity_required||0),0)} units</small></div><button type="button" className="primary" disabled={pending} onClick={()=>startTransition(async()=>{await prepareSupplierCycleAction(organisationId,supplier.id);})}>Prepare current supplier cycle</button></article>;})}</div>{replenishmentLines.length?<><h2>Replenishment quantities</h2><div className="club-catalogue-list">{replenishmentLines.map(line=>{const id=String(line.id);const base=Array.isArray(line.allocations)?line.allocations as Line[]:[];const edit=edits[id]??{quantity:Number(line.quantity_ordered),allocations:base.map(a=>({locationId:String(a.location_id),quantity:Number(a.quantity)}))};return <article className="club-catalogue-row" key={id}><div><strong>{String(line.product)}</strong><small>{String(line.supplier)} · {String(line.supplier_sku??"SKU")}</small></div><label>Final quantity<input type="number" min={1} value={edit.quantity} onChange={e=>setEdits({...edits,[id]:{...edit,quantity:Number(e.target.value)}})}/></label><label>Destination quantities<input value={edit.allocations.map(a=>`${a.locationId}:${a.quantity}`).join(",")} onChange={e=>{const allocations=e.target.value.split(",").map(value=>{const [locationId,quantity]=value.split(":");return {locationId,quantity:Number(quantity)}}).filter(a=>a.locationId&&a.quantity>0);setEdits({...edits,[id]:{...edit,allocations}})}}/></label><button type="button" className="primary" disabled={pending} onClick={()=>startTransition(async()=>{await updateReplenishmentLineAction(organisationId,id,edit.quantity,edit.allocations);})}>Save quantity</button></article>;})}</div></>:null}<h2>Supplier order history</h2><div className="club-catalogue-list">{batches.map(batch=><article className="club-catalogue-row" key={String(batch.id)}><div><strong>{String(batch.reference)}</strong><small>{String(batch.supplier)} · {String(batch.lines)} lines · {String(batch.units)} units · {Number(batch.member_units||0)} member / {Number(batch.replenishment_units||0)} replenishment</small></div><em>{String(batch.status)}</em>{batch.status==="draft"?<button type="button" className="primary" disabled={pending} onClick={()=>startTransition(async()=>{await markSupplierOrderedAction(organisationId,String(batch.id));})}>Mark ordered</button>:null}<button type="button" className="secondary" disabled={pending} onClick={()=>startTransition(async()=>{const result=await exportSupplierOrderAction(organisationId,String(batch.id));if(result.ok&&result.reference&&result.csv)download(result.reference,result.csv);})}>Export CSV</button></article>)}</div></section>;
}
