"use client";
import { useState } from "react";
import type { ClubBalanceAccount, ClubCommerceProduct, ClubOrder } from "@/lib/club-commerce";
import type { ClubProductFamily } from "@/lib/club-product-families";
import { groupProductFamilies } from "@/lib/club-product-families";
import { ClubMemberShop } from "./club-member-shop";
import styles from "./club-shop.module.css";
import { purchaseAction } from "@/app/club/shop/actions";
type Props = { organisationId:string; userId:string; products:ClubCommerceProduct[]; families?:ClubProductFamily[]; locations:{id:string;name:string;active:boolean}[]; balance?:ClubBalanceAccount; orders:ClubOrder[]; accent:string; currentLocationId?:string; };
const money=(n:number)=>`£${(n/100).toFixed(2)}`;
export function ClubMemberShopShell({ organisationId,userId,products,families=[],locations,balance,orders,accent,currentLocationId }:Props) {
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [barcode,setBarcode]=useState(""); const [basket,setBasket]=useState<Record<string,number>>({}); const [message,setMessage]=useState<string>(); const [payment,setPayment]=useState<"balance"|"cash_box">("balance"); const [locationId,setLocationId]=useState(currentLocationId ?? locations.find(l=>l.active)?.id ?? "");
 const add=(p:ClubCommerceProduct)=>setBasket(b=>({...b,[p.id]:(b[p.id]??0)+1})); const change=(id:string,d:number)=>setBasket(b=>{const n={...b},q=(n[id]??0)+d;if(q>0)n[id]=q;else delete n[id];return n;});
 const categoryFor=(p:ClubCommerceProduct)=>{const c=(p.category??"").toLowerCase();return /supplement|protein|creatine/.test(c)?"Supplements":/merch|apparel|clothing/.test(c)?"Merch & Apparel":/pt|service|coach/.test(c)?"Services":"Food & Drinks";};
 const filtered=products.filter(p=>(category==="All"||categoryFor(p)===category)&&[p.name,p.brand,p.category,p.description,p.barcode,...Object.values(p.variantOptions??{})].some(v=>v?.toLowerCase().includes(query.toLowerCase()))); const cards=groupProductFamilies(filtered,families,organisationId); const lines=products.filter(p=>basket[p.id]); const total=lines.reduce((s,p)=>s+p.sellPriceMinor*basket[p.id],0);
 const scan=()=>{const hit=products.filter(p=>p.active&&p.barcode&&p.barcode===barcode.trim());if(hit.length===1){add(hit[0]);setMessage(`${hit[0].name} added.`);setBarcode("");}else setMessage(hit.length?"Barcode needs staff review.":"Product not found.");};
 const submit=async()=>{const r=await purchaseAction({organisationId,items:lines.map(p=>({productId:p.id,quantity:basket[p.id]})),locationId:locationId||undefined,payment,idempotencyKey:crypto.randomUUID()});setMessage(r.ok?"Order placed. Cash orders remain pending until verified.":r.error);if(r.ok)setBasket({});};
 return <div className={styles.shop} style={{"--club-accent":accent} as React.CSSProperties}><div className={styles.balance}><span>MADHOUSE BALANCE</span><strong>{balance?money(balance.balanceMinor):"Not set up"}</strong></div><section><div className={styles.sectionHead}><div><span className="eyebrow">MADHOUSE SHOP</span><h2>Food, fitness and services</h2></div><span className={styles.hint}>{Object.values(basket).reduce((a,b)=>a+b,0)} items</span></div><div className={styles.actions}><input aria-label="Search products" placeholder="Search products" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="Scan barcode" placeholder="Scan or enter barcode" value={barcode} onChange={e=>setBarcode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&scan()}/><button type="button" className="secondary" onClick={scan}>Add barcode</button></div><div className={styles.actions}>{["All","Food & Drinks","Merch & Apparel","Supplements","Services"].map(c=><button type="button" className={category===c?"primary":"secondary"} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>{!products.length?<div className={styles.empty}>No products are currently available.</div>:!cards.length?<p className={styles.empty}>No products match your search.</p>:<ClubMemberShop add={add} cards={cards}/>}</section>{lines.length?<section aria-label="Basket"><div className={styles.sectionHead}><h2>Your basket</h2></div>{lines.map(p=><div className={styles.order} key={p.id}><span><strong>{p.name}</strong><small>{money(p.sellPriceMinor)} each</small></span><span className={styles.actions}><button type="button" onClick={()=>change(p.id,-1)}>−</button><b>{basket[p.id]}</b><button type="button" onClick={()=>change(p.id,1)}>+</button></span></div>)}<div className={styles.checkoutTotal}><span>Total</span><strong>{money(total)}</strong></div><label>Payment<select value={payment} onChange={e=>setPayment(e.target.value as typeof payment)}><option value="balance">Madhouse Balance</option><option value="cash_box">Cash at reception</option></select></label><button type="button" className="primary full" onClick={submit}>Checkout</button></section>:null}{orders.length?<section><div className={styles.sectionHead}><h2>Recent purchases</h2></div>{orders.slice(0,8).map(o=><div className={styles.order} key={o.id}><span>{new Date(o.createdAt).toLocaleDateString("en-GB")}</span><strong>{money(o.totalMinor)}</strong><em>{o.status}</em></div>)}</section>:null}{message?<p className={styles.message} role="status">{message}</p>:null}</div>;
}
