"use client";
import { useState, useTransition, type FormEvent } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { saveCatalogueProductAction } from "@/app/club/shop/actions";
import { parseMinorUnits } from "@/lib/club-money";

export function ClubCatalogue({ organisationId, products }: { organisationId: string; products: ClubCommerceProduct[] }) {
  const [editing, setEditing] = useState<ClubCommerceProduct>(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  const visible = products.filter(product => product.name.toLowerCase().includes(query.toLowerCase()));
  const begin = (product?: ClubCommerceProduct) => { setEditing(product); setMessage(undefined); setOpen(true); };
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { organisationId, ...(editing ? { id: editing.id } : {}), name: String(form.get("name") ?? ""), category: String(form.get("category") ?? ""), price: String(form.get("price") ?? ""), barcode: String(form.get("barcode") ?? ""), sku: String(form.get("sku") ?? ""), stockTracked: form.get("stockTracked") === "on", active: form.get("active") === "on", mediaUrl: String(form.get("mediaUrl") ?? "") }; if (parseMinorUnits(input.price) === undefined) return setMessage("Enter a GBP price with up to two decimal places."); startTransition(async () => { const result = await saveCatalogueProductAction(input); setMessage(result.ok ? `${result.productName} saved.` : result.error); if (result.ok) setOpen(false); }); };
  return <section aria-label="Catalogue" data-testid="catalogue-panel"><div className="section-heading"><div><span className="eyebrow">CATALOGUE</span><h2>Retail products</h2></div><div className="toolbar-actions"><input aria-label="Search catalogue" placeholder="Search products" value={query} onChange={event => setQuery(event.target.value)} /><button type="button" className="primary" onClick={() => begin()}>Add product</button></div></div>{visible.length ? <div className="club-catalogue-list">{visible.map(product => <article className="club-catalogue-row" key={product.id}><div><strong>{product.name}</strong><small>{product.category ?? "Uncategorised"}{product.sku ? ` · SKU ${product.sku}` : ""}{product.barcode ? ` · Barcode ${product.barcode}` : ""}</small></div><span>£{(product.sellPriceMinor / 100).toFixed(2)}</span><em>{product.stockTracked ? "Stock tracked" : "Non-stock"} · {product.active ? "Sellable" : "Inactive"}</em><button type="button" className="secondary" onClick={() => begin(product)}>Edit</button></article>)}</div> : <p className="muted">{products.length ? "No products match your search." : "No retail products have been added yet."}</p>}{message ? <p className="message" role="status">{message}</p> : null}{open ? <div className="modal" role="dialog" aria-modal="true"><form className="sheet" onSubmit={save}><div className="sheet-heading"><div><span className="eyebrow">CATALOGUE</span><h2>{editing ? "Edit product" : "Add product"}</h2></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><label>Name<input name="name" defaultValue={editing?.name} required /></label><label>Category<input name="category" defaultValue={editing?.category} placeholder="Protein, Creatine, Wellness…" /></label><label>GBP selling price<input name="price" inputMode="decimal" placeholder="22.00" defaultValue={editing ? (editing.sellPriceMinor / 100).toFixed(2) : ""} required /></label><label>Barcode<input name="barcode" inputMode="numeric" defaultValue={editing?.barcode} placeholder="Optional — scan or type" /></label><label>SKU<input name="sku" defaultValue={editing?.sku} placeholder="Optional" /></label><label>Media URL<input name="mediaUrl" type="url" defaultValue={typeof editing?.media?.url === "string" ? editing.media.url : ""} placeholder="Optional managed asset URL" /></label><label className="check-row"><input name="stockTracked" type="checkbox" defaultChecked={editing?.stockTracked ?? true} /> Physical stock tracked</label><label className="check-row"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} /> Sellable and active</label>{message ? <p className="error-text" role="alert">{message}</p> : null}<button className="primary full" type="submit" disabled={pending}>{pending ? "Saving…" : "Save product"}</button></form></div> : null}</section>;
}
