"use client";
import { useMemo, useState } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { parseMinorUnits } from "@/lib/club-money";
import { pricingMath, recommendedPriceMinor, type RoundingMode } from "@/lib/club-pricing";

export function ClubPricingPanel({ products }: { products: ClubCommerceProduct[] }) {
  const [productId, setProductId] = useState(products[0]?.id ?? "");
  const [cost, setCost] = useState(""); const [vat, setVat] = useState("0"); const [fee, setFee] = useState("0"); const [target, setTarget] = useState("30"); const [kind, setKind] = useState<"markup" | "margin">("margin"); const [rounding, setRounding] = useState<RoundingMode>("exact");
  const product = products.find(item => item.id === productId);
  const math = useMemo(() => product ? pricingMath(parseMinorUnits(cost) ?? product.costPriceMinor ?? 0, product.sellPriceMinor, Number(vat), Number(fee)) : undefined, [cost, fee, product, vat]);
  const recommendation = product ? recommendedPriceMinor(parseMinorUnits(cost) ?? product.costPriceMinor ?? 0, { kind, percent: Number(target) }, rounding, Number(vat), Number(fee)) : undefined;
  return <section className="club-pricing-panel" aria-label="Product pricing"><div className="section-heading"><div><span className="eyebrow">PRICING</span><h2>Pricing &amp; margin</h2></div><span className="muted">Planning estimate — not provider settlement data</span></div><div className="pricing-controls"><label>Product<select value={productId} onChange={event => setProductId(event.target.value)}>{products.filter(item => item.stockTracked).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Cost price<input inputMode="decimal" placeholder="Optional" value={cost} onChange={event => setCost(event.target.value)} /></label><label>VAT rate %<input inputMode="decimal" value={vat} onChange={event => setVat(event.target.value)} /></label><label>Merchant fee allowance %<input inputMode="decimal" value={fee} onChange={event => setFee(event.target.value)} /></label><label>Target<select value={kind} onChange={event => setKind(event.target.value as "markup" | "margin")}><option value="margin">Gross margin</option><option value="markup">Markup</option></select></label><label>Target %<input inputMode="decimal" value={target} onChange={event => setTarget(event.target.value)} /></label><label>Rounding<select value={rounding} onChange={event => setRounding(event.target.value as RoundingMode)}><option value="exact">Exact</option><option value="5p">Nearest 5p</option><option value="10p">Nearest 10p</option><option value="50p">Nearest 50p</option><option value="£1">Nearest £1</option></select></label></div>{product && math ? <div className="pricing-summary"><span>Current price <b>£{(product.sellPriceMinor / 100).toFixed(2)}</b></span><span>Estimated fee <b>£{(math.feeMinor / 100).toFixed(2)}</b></span><span>Profit after fee <b>£{(math.profitAfterFeeMinor / 100).toFixed(2)}</b></span><span>Markup <b>{math.markupPercent?.toFixed(1) ?? "—"}%</b></span><span>Margin <b>{math.marginPercent?.toFixed(1) ?? "—"}%</b></span><span>Margin after allowance <b>{math.marginAfterFeePercent?.toFixed(1) ?? "—"}%</b></span>{recommendation !== undefined ? <span>Recommended price <b>£{(recommendation / 100).toFixed(2)}</b></span> : null}</div> : <p className="muted">Select a stock-tracked product to review pricing.</p>}</section>;
}
