"use client";
import { useState, useTransition, type TransitionStartFunction } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { createAndPublishSupplierProductAction, publishSupplierOfferAction } from "@/app/club/shop/supplier-catalogue/actions";

const money = (minor: unknown) => typeof minor === "number" ? `£${(minor / 100).toFixed(2)}` : "Price required";
export function ClubSupplierCatalogue({ organisationId, offers, products }: { organisationId: string; offers: Array<Record<string, unknown>>; products: ClubCommerceProduct[] }) {
  const [query, setQuery] = useState(""); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string>(); const [create, setCreate] = useState<Record<string, unknown>>();
  const visible = offers.filter(offer => [offer.name, offer.brand, offer.category, offer.supplier_sku, offer.barcode].some(value => String(value ?? "").toLowerCase().includes(query.toLowerCase())));
  return <section aria-label="Supplier offers"><div className="section-heading"><div><span className="eyebrow">SUPPLIER OFFERS</span><h2>Review before members see them</h2></div><input aria-label="Search supplier offers" placeholder="Search name, brand or SKU" value={query} onChange={event => setQuery(event.target.value)} /></div>{visible.length ? <div className="club-catalogue-list">{visible.map(offer => { const linked = products.find(product => product.id === String(offer.club_product_id)); const retail = Number(offer.retail_price_minor); return <article className="club-catalogue-row" key={String(offer.id)}><div><strong>{offer.brand ? `${String(offer.brand)} · ` : ""}{String(offer.name)}</strong><small>{String(offer.supplier)} · {String(offer.supplier_sku ?? "No supplier SKU")} · {String(offer.fulfilment_type)}</small><span>{linked ? `Linked to ${linked.name}` : "Product review required"} · {offer.discontinued ? "Discontinued" : offer.sellable ? "Published" : "Not published"}</span></div><div><strong>{money(offer.wholesale_cost_minor)}</strong><small>Supplier cost · RRP {money(offer.supplier_rrp_minor)}</small><span>{Number.isFinite(retail) && retail > 0 ? `Retail ${money(retail)}` : "Retail price required"}</span></div>{linked ? <button type="button" className="primary" disabled={pending || offer.sellable === true} onClick={() => startTransition(async () => { const result = await publishSupplierOfferAction({ organisationId, offerId: String(offer.id), productId: linked.id, retailPriceMinor: retail }); setMessage(result.ok ? "Published to the member Shop." : result.error); })}>{offer.sellable ? "Published" : "Publish"}</button> : <button type="button" className="secondary" disabled={pending} onClick={() => setCreate(offer)}>Create product</button>}</article>; })}</div> : <p className="muted">No supplier products yet.</p>}{message ? <p className="message" role="status">{message}</p> : null}{create ? <CreateProductDialog organisationId={organisationId} offer={create} pending={pending} close={() => setCreate(undefined)} onDone={setMessage} startTransition={startTransition} /> : null}</section>;
}
function CreateProductDialog({ organisationId, offer, pending, close, onDone, startTransition }: { organisationId: string; offer: Record<string, unknown>; pending: boolean; close: () => void; onDone: (message: string) => void; startTransition: TransitionStartFunction }) {
  const [price, setPrice] = useState(offer.retail_price_minor ? (Number(offer.retail_price_minor) / 100).toFixed(2) : "");
  return <div className="modal" role="dialog" aria-modal="true"><form className="sheet" onSubmit={event => { event.preventDefault(); const retailPriceMinor = Math.round(Number(price) * 100); startTransition(async () => { const result = await createAndPublishSupplierProductAction({ organisationId, offerId: String(offer.id), name: String(offer.name), brand: String(offer.brand ?? ""), category: String(offer.category ?? ""), barcode: String(offer.barcode ?? ""), retailPriceMinor }); onDone(result.ok ? "Created and published to the member Shop." : result.error ?? "Could not publish product."); if (result.ok) close(); }); }}><h2>Create Madhouse product</h2><p>Review the supplier details, then approve the customer price.</p><label>Product name<input defaultValue={String(offer.name)} required /></label><label>Retail price (£)<input inputMode="decimal" value={price} onChange={event => setPrice(event.target.value)} required /></label><button type="submit" className="primary full" disabled={pending}>Create and publish</button><button type="button" className="secondary full" onClick={close}>Cancel</button></form></div>;
}
