"use client";
import { useState, useTransition } from "react";
import { resolveClubCapabilities } from "@/lib/club-capabilities";
import { replaceStaffLocations, setStaffPermission, setStaffRole } from "@/app/club/staff/actions";
type Props = { organisationId: string; userId: string; role: "gym_staff" | "trainer" | "gym_admin"; locationIds: string[]; locations: Array<{ id: string; name: string }>; overrides: Array<{ capability: string; decision: "allow" | "deny" }> };
export function ClubStaffManageAccess({ organisationId, userId, role: initialRole, locationIds: initialLocations, locations, overrides }: Props) {
  const [role, setRole] = useState<Props["role"]>(initialRole); const [selected, setSelected] = useState(initialLocations); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  const effective = resolveClubCapabilities(role, overrides); const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const save = () => startTransition(async () => { const roleResult = await setStaffRole({ organisationId, userId, role }); if (!roleResult.ok) return setMessage(roleResult.error); const locationResult = await replaceStaffLocations({ organisationId, userId, locationIds: selected }); setMessage(locationResult.ok ? "Access updated." : locationResult.error); });
  return <details className="staff-access-editor"><summary>Manage access</summary><div className="staff-access-editor-body"><label>Role<select value={role} onChange={event => setRole(event.target.value as Props["role"])}><option value="gym_staff">Staff</option><option value="trainer">Trainer</option><option value="gym_admin">Manager</option></select></label><fieldset><legend>Authorised locations</legend>{locations.map(location => <label key={location.id}><input type="checkbox" checked={selected.includes(location.id)} onChange={() => toggle(location.id)} />{location.name}</label>)}</fieldset><p className="muted">Effective permissions: {effective.length}</p><div className="permission-groups">{["members.","payments.","classes.","services.","induction.","supplier.","commerce.collections"].map(prefix => <span key={prefix}>{effective.filter(capability => capability.startsWith(prefix)).map(capability => capability.replace(/[._]/g, " ")).join(" · ") || "None"}</span>)}</div><button className="primary" type="button" disabled={pending} onClick={save}>{pending ? "Saving…" : "Save access"}</button>{message ? <p className="muted" role="status">{message}</p> : null}</div></details>;
}
