"use client";
import { useState } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { groupProductFamilies, memberVariantChoices, money, type ClubProductFamily, type FamilyCard } from "@/lib/club-product-families";
import { memberAvailabilityLabel, type MemberAvailabilityState } from "@/lib/club-member-availability";
import { ClubProductMedia, productImageUrl, sharedProductImage } from "./club-product-media";

type Props = { products: ClubCommerceProduct[]; families?: ClubProductFamily[]; organisationId: string; availability?: Record<string, MemberAvailabilityState>; onAdd: (product: ClubCommerceProduct) => void; title?: string };
const stateFor = (product: ClubCommerceProduct, availability: Record<string, MemberAvailabilityState>): MemberAvailabilityState => availability[product.id] ?? (product.stockTracked ? "IN_GYM" : product.supplierAvailabilityStatus === "available" ? "SUPPLIER_ORDER" : "UNAVAILABLE");
const familyState = (card: FamilyCard, availability: Record<string, MemberAvailabilityState>) => card.variants.some(p => stateFor(p, availability) === "IN_GYM") ? "IN_GYM" : card.variants.some(p => stateFor(p, availability) === "SUPPLIER_ORDER") ? "SUPPLIER_ORDER" : "UNAVAILABLE";
export function ClubProductFamilySelector({ products, families = [], organisationId, availability = {}, onAdd }: Props) {
  const [picked, setPicked] = useState<FamilyCard>(); const [selection, setSelection] = useState<Record<string, string>>({});
  const cards = groupProductFamilies(products, families, organisationId);
  const choices = picked ? memberVariantChoices(picked.variants, selection, p => stateFor(p, availability) !== "UNAVAILABLE" && p.sellPriceMinor > 0) : undefined;
  const resolved = choices?.resolved;
  const controls = choices?.controls.filter(control => control.key !== "orderUnit");
  const image = resolved?.variantImageReference ? { ...resolved, media: { url: resolved.variantImageReference } } : picked?.variants.find(variant => productImageUrl(variant));
  const price = picked ? (() => { const values = picked.variants.filter(p => stateFor(p, availability) !== "UNAVAILABLE" && p.sellPriceMinor > 0).map(p => p.sellPriceMinor).sort((a,b)=>a-b); return values.length > 1 ? `From ${money(values[0])}` : values.length ? money(values[0]) : ""; })() : "";
  return <><div className="club-family-grid checkout-products">{cards.map(card => { const cardImage = card.variants.find(variant => productImageUrl(variant)) ?? card.variants[0]; return <article className="club-family-card" key={card.family?.id ?? card.label}><button className="club-family-select" type="button" onClick={() => { setPicked(card); setSelection({}); }}><div className="club-family-image">{sharedProductImage(card.variants) ? <ClubProductMedia product={cardImage} /> : null}</div>{card.family?.brand || card.variants[0].brand ? <small>{card.family?.brand ?? card.variants[0].brand}</small> : null}<strong>{card.label}</strong>{priceFor(card, availability) !== "" ? <span>{priceFor(card, availability)}</span> : null}{familyState(card, availability) !== "UNAVAILABLE" ? <small>{memberAvailabilityLabel(familyState(card, availability))}</small> : null}</button></article>; })}</div>{picked ? <div className="club-family-modal" role="dialog" aria-modal="true"><div className="club-family-sheet"><button type="button" className="text-button" onClick={() => setPicked(undefined)}>Close</button>{image ? <ClubProductMedia product={image} className="club-product-large" /> : null}<h2>{picked.label}</h2>{picked.family?.brand || picked.variants[0].brand ? <p>{picked.family?.brand ?? picked.variants[0].brand}</p> : null}{resolved || price !== "" ? <p><strong>{resolved ? money(resolved.sellPriceMinor) : price}</strong></p> : null}{controls?.map(({ key, values }, index) => <fieldset key={key}><legend>{key === "size" ? "Size" : key === "flavour" ? "Flavour" : key}</legend><div className="variant-options">{values.map(({ value, disabled }) => <button type="button" key={value} disabled={disabled} aria-pressed={selection[key] === value} onClick={() => setSelection({ ...Object.fromEntries((controls ?? []).slice(0, index).map(control => [control.key, selection[control.key]])), [key]: value })}>{value}</button>)}</div></fieldset>)}{resolved && stateFor(resolved, availability) !== "UNAVAILABLE" ? <p>{memberAvailabilityLabel(stateFor(resolved, availability))}</p> : null}<button type="button" className="primary full" disabled={!resolved || stateFor(resolved, availability) === "UNAVAILABLE"} onClick={() => { if (resolved) { onAdd(resolved); setPicked(undefined); } }}>Add to basket</button></div></div> : null}</>;
}
function priceFor(card: FamilyCard, availability: Record<string, MemberAvailabilityState>) { const values = card.variants.filter(p => stateFor(p, availability) !== "UNAVAILABLE" && p.sellPriceMinor > 0).map(p => p.sellPriceMinor).sort((a,b)=>a-b); return values.length > 1 ? `From ${money(values[0])}` : values.length ? money(values[0]) : ""; }
