"use client";
import { useState, useTransition } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { staffCashSaleAction } from "@/app/club/shop/actions";
export function ClubStaffCheckout({ products, locations }: { products: ClubCommerceProduct[]; locations: { id: string; name: string; active: boolean }[] }) {
  const [productId, setProductId] = useState(products[0]?.id ?? ""); const [locationId, setLocationId] = useState(locations.find(item => item.active)?.id ?? ""); const [quantity, setQuantity] = useState(1); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  const submit = () => startTransition(async () => { const result = await staffCashSaleAction({ productId, locationId, quantity }); setMessage(result.ok ? "Cash sale recorded and stock updated." : result.error); });
  return <section><span className="eyebrow">RECEPTION CHECKOUT</span><div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", marginTop: 12 }}><label>Product<select value={productId} onChange={event => setProductId(event.target.value)}>{products.map(product => <option value={product.id} key={product.id}>{product.name} · £{(product.sellPriceMinor / 100).toFixed(2)}</option>)}</select></label><label>Location<select value={locationId} onChange={event => setLocationId(event.target.value)}>{locations.filter(item => item.active).map(location => <option value={location.id} key={location.id}>{location.name}</option>)}</select></label><label>Quantity<input type="number" min={1} value={quantity} onChange={event => setQuantity(Math.max(1, Number(event.target.value) || 1))} /></label></div><button type="button" className="primary" onClick={submit} disabled={pending || !productId || !locationId} style={{ marginTop: 14 }}>{pending ? "Recording…" : "Record cash sale"}</button>{message ? <p role="status" style={{ marginTop: 12 }}>{message}</p> : null}</section>;
}
