"use client";
import { useEffect, useState } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import type { FamilyCard } from "@/lib/club-product-families";
import type { MemberAvailabilityState } from "@/lib/club-member-availability";
import { ClubProductFamilySelector } from "./club-product-family-selector";
import { paginateCards } from "@/lib/club-pagination";
type Props={paginationResetKey?: string;add:(product:ClubCommerceProduct)=>void;cards:FamilyCard[];availability?:Record<string,MemberAvailabilityState>;locationChoices?:Array<{id:string;name:string}>;selectedLocationId?:string;onLocationChange?:(id:string)=>void;locationChoicesFor?:(product:ClubCommerceProduct)=>Array<{id:string;name:string}>};
// Shared selector renders sharedProductImage(card.variants) for every family.
export function ClubMemberShop({add,cards,availability={},locationChoices=[],selectedLocationId,onLocationChange,locationChoicesFor,paginationResetKey}:Props){const [page,setPage]=useState(1); useEffect(()=>{setPage(1);},[paginationResetKey]); const paged=paginateCards(cards,page); const products=paged.items.flatMap(card=>card.variants); return <><ClubProductFamilySelector products={products} families={paged.items.flatMap(card=>card.family?[card.family]:[])} organisationId={products[0]?.organisationId??""} availability={availability} cards={paged.items} locationChoices={locationChoices} locationChoicesFor={locationChoicesFor} selectedLocationId={selectedLocationId} onLocationChange={onLocationChange} onAdd={add}/>{paged.totalPages>1?<div className="club-card-pagination" aria-label="Member products"><span>Showing {paged.start}–{paged.end} of {paged.total} products</span><button type="button" className="secondary" disabled={paged.currentPage===1} onClick={()=>setPage(paged.currentPage-1)}>Previous</button><span>Page {paged.currentPage} of {paged.totalPages}</span><button type="button" className="secondary" disabled={paged.currentPage===paged.totalPages} onClick={()=>setPage(paged.currentPage+1)}>Next</button></div>:null}</>;}
