"use client";
import { useEffect, useState, useTransition } from "react";
import { recordSunbedUseAction, searchGlowCustomersAction, getGlowBalanceAction, getGlowAgeAction, verifyGlowAgeAction, adjustGlowMinutesAction, removeGlowMinutesAction, getGlowHistoryAction, getGlowLoyaltyAction, completeGlowSaleAction } from "@/app/club/sunbeds/actions";
import { glowZonePackages } from "@/lib/glow-zone";

type Customer = { userId: string; name: string; email: string; isActiveMember: boolean };
type Props = { organisationId: string; locations: Array<{ id: string; name: string }>; canAdjust?: boolean };

export function ClubSunbedOperations({ organisationId, locations, canAdjust = false }: Props) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Customer | null>(null); const [results, setResults] = useState<Customer[]>([]);
  const [minutes, setMinutes] = useState(""); const [reason, setReason] = useState(""); const [dob, setDob] = useState(""); const [age, setAge] = useState<"verified" | "under_18" | "required" | "error">("required");
  const [balance, setBalance] = useState<number | null>(null); const [next, setNext] = useState<string | null>(null); const [loyalty, setLoyalty] = useState(0); const [history, setHistory] = useState<Array<Record<string, unknown>>>([]);
  const [packageId, setPackageId] = useState("payg"); const [tender, setTender] = useState<"cash" | "external_card">("cash"); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const locationId = locations.find(x => x.name.toLowerCase().includes("carlton"))?.id ?? locations[0]?.id;
  const refresh = (userId: string) => startTransition(async () => { const [b, a, h, l] = await Promise.all([getGlowBalanceAction({ organisationId, userId }), getGlowAgeAction({ organisationId, userId }), getGlowHistoryAction({ organisationId, userId }), getGlowLoyaltyAction({ organisationId, userId })]); if (b.ok) { setBalance(b.balance.minutes); setNext(b.balance.next_expiry); } if (a.ok) { setAge(a.age?.status === "verified" ? "verified" : a.age?.status === "under_18" ? "under_18" : "required"); setDob(a.age?.date_of_birth ?? ""); } else setAge("error"); if (h.ok) setHistory(h.history); if (l.ok) setLoyalty(l.qualifyingSessions); });
  useEffect(() => { const timer = setTimeout(() => { if (query.trim().length < 2) { setResults([]); return; } startTransition(async () => { const found = await searchGlowCustomersAction({ organisationId, query }); setResults(found.ok ? found.results : []); }); }, 300); return () => clearTimeout(timer); }, [query, organisationId]);
  const packages = selected?.isActiveMember ? glowZonePackages.filter(x => x.membersOnly) : glowZonePackages.filter(x => !x.membersOnly);
  const selectedPackage = glowZonePackages.find(x => x.id === packageId); const saleMinutes = packageId === "payg" ? Number(minutes) : selectedPackage?.minutes ?? 0; const saleTotal = packageId === "payg" ? saleMinutes * 100 : selectedPackage?.priceMinor ?? 0;
  const choose = (customer: Customer) => { setSelected(customer); setResults([]); setPackageId(customer.isActiveMember ? "member-30" : "quick-30"); setMessage(""); refresh(customer.userId); };
  const verify = () => selected && dob && startTransition(async () => { const result = await verifyGlowAgeAction({ organisationId, userId: selected.userId, locationId: locationId!, dateOfBirth: dob }); setMessage(result.ok ? "Age verified and retained for future visits." : (result.error ?? "Verification failed")); if (result.ok) refresh(selected.userId); });
  const use = () => selected && locationId && startTransition(async () => { const n = Number(minutes); const result = await recordSunbedUseAction({ organisationId, userId: selected.userId, locationId, minutes: n, idempotencyKey: `glow-use-${selected.userId}-${Date.now()}` }); setMessage(result.ok ? `${n} minutes used. Issue the required physical token(s).` : (result.error ?? "Use could not be recorded.")); if (result.ok) refresh(selected.userId); });
  const adjust = (remove: boolean) => selected && locationId && startTransition(async () => { const fn = remove ? removeGlowMinutesAction : adjustGlowMinutesAction; const result = await fn({ organisationId, userId: selected.userId, locationId, minutes: Number(minutes), reason, idempotencyKey: `glow-adjust-${selected.userId}-${Date.now()}` }); setMessage(result.ok ? "Adjustment recorded." : (result.error ?? "Adjustment failed")); if (result.ok) refresh(selected.userId); });
  const sell = () => selected && locationId && startTransition(async () => { const result = await completeGlowSaleAction({ organisationId, userId: selected.userId, locationId, packageId, minutes: saleMinutes, tenderType: tender, idempotencyKey: `glow-sale-${selected.userId}-${Date.now()}` }); setMessage(result.ok ? "PAYMENT RECORDED · Minutes added to the customer." : (result.error ?? "Sale could not be completed.")); if (result.ok) refresh(selected.userId); });
  const validUse = age === "verified" && Number.isInteger(Number(minutes)) && Number(minutes) > 0 && balance !== null && Number(minutes) <= balance;
  return <div><h2>GLOW ZONE · Carlton</h2><p className="muted">Staffed operation only. Search a customer, confirm age and balance, then issue the physical token.</p><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name or email" aria-label="Search customer" />{results.map(customer => <button className="club-detail-row" key={customer.userId} onClick={() => choose(customer)}><strong>{customer.name}</strong><small>{customer.email}</small></button>)}{selected ? <SurfaceCard><strong>{selected.name}</strong><p>AGE: {age === "verified" ? "Verified 18+ ✓" : age === "under_18" ? "UNDER 18 — NOT ELIGIBLE" : age === "error" ? "AGE STATUS UNAVAILABLE — Try again" : "AGE VERIFICATION REQUIRED"}</p>{age === "required" ? <>{dob ? <p className="muted">DOB on file: {new Date(dob).toLocaleDateString("en-GB")}</p> : <label>Date of birth<input type="date" value={dob} onChange={e => setDob(e.target.value)} /></label>}<button className="secondary" onClick={verify} disabled={pending || !dob}>Verify age (proof checked)</button></> : null}<p>AVAILABLE: {balance === null ? "Loading…" : `${balance} minutes`}</p>{next ? <p className="muted">Next expiry: {new Date(next).toLocaleDateString("en-GB")}</p> : null}<p>GLOW LOYALTY: {loyalty >= 9 ? "FREE-SESSION REWARD EARNED · Ask reception" : `${loyalty} of 9 qualifying sessions`}</p>
    <section><h3>USE MINUTES</h3><label>How many minutes?<input type="number" min="1" step="1" value={minutes} onChange={e => setMinutes(e.target.value)} /></label><button className="primary" disabled={pending || !validUse} onClick={use}>CONFIRM &amp; ISSUE TOKEN(S)</button>{age !== "verified" && <p className="muted">{age === "error" ? "Age status unavailable. Try again." : age === "under_18" ? "Customer is under 18." : "Age verification required."}</p>}{age === "verified" && balance === 0 && <p className="muted">No usable minutes available.</p>}</section>
    <details><summary>BUY / TOP UP</summary><section className="surface-card"><label>Package<select value={packageId} onChange={e => setPackageId(e.target.value)}><option value="payg">PAY AS YOU GO · £1/minute</option>{packages.map(p => <option key={p.id} value={p.id}>{p.name} · {p.minutes} min · £{(p.priceMinor / 100).toFixed(2)}</option>)}</select></label>{packageId === "payg" && <label>Minutes<input type="number" min="1" step="1" value={minutes} onChange={e => setMinutes(e.target.value)} /></label>}<p>TOTAL: £{(saleTotal / 100).toFixed(2)}</p><select value={tender} onChange={e => setTender(e.target.value as typeof tender)}><option value="cash">Cash</option><option value="external_card">Card terminal</option></select><p className="muted">{tender === "cash" ? "Confirm cash received before completing sale." : "Take payment on the card terminal first, then confirm approval."}</p><button className="primary" disabled={pending || !saleMinutes || !locationId} onClick={sell}>{tender === "cash" ? "CONFIRM CASH RECEIVED" : "CONFIRM CARD PAYMENT APPROVED"}</button></section></details>
    <h3>History</h3>{history.length ? history.slice(0, 8).map((event, i) => <p className="muted" key={i}>{Number(event.minutes) >= 0 ? "+" : ""}{String(event.minutes)} min · {String(event.kind) === "usage" ? "GLOW ZONE session" : String(event.source ?? "Activity")}</p>) : <p className="muted">No GLOW ZONE activity yet.</p>}
    {canAdjust ? <details><summary>ADJUST BALANCE</summary><label>Reason<input value={reason} onChange={e => setReason(e.target.value)} placeholder="Required for adjustments" /></label><div className="actions"><button className="secondary" disabled={pending || !minutes || !reason.trim()} onClick={() => adjust(false)}>ADD MINUTES</button><button className="secondary" disabled={pending || !minutes || !reason.trim()} onClick={() => adjust(true)}>REMOVE MINUTES</button></div></details> : null}
  </SurfaceCard> : null}{message ? <p role="status">{message}</p> : null}</div>;
}
function SurfaceCard({ children }: { children: React.ReactNode }) { return <div className="surface-card">{children}</div>; }
