"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { BrandLockup } from "@/components/brand-lockup";
import type { ClubRole, Organisation } from "@/lib/club";
import styles from "./club-shell.module.css";
type ClubContextOption = { organisation: Organisation; role: ClubRole };
const labelRole = (role: ClubRole) => ({ gym_staff: "Staff", gym_admin: "Admin", owner: "Owner", trainer: "Trainer", member: "Member", guest: "Guest" }[role] ?? role);
export function ClubSectionNav({ organisation, role, contexts = [], locations = [], locationId, branding = false }: { organisation: Organisation; role: ClubRole; contexts?: ClubContextOption[]; locations?: Array<{ id: string; name: string; active: boolean }>; locationId?: string; branding?: boolean }) {
  const router = useRouter(); const pathname = usePathname(); const [mobileOpen,setMobileOpen]=useState(false);
  const query = (nextLocationId = locationId) => `?org=${encodeURIComponent(organisation.id)}${nextLocationId ? `&location=${encodeURIComponent(nextLocationId)}` : ""}`;
  const operational = ["gym_staff", "gym_admin", "owner"].includes(role); const admin = ["gym_admin", "owner"].includes(role); const activeVenues = locations.filter(location => location.active);
  const links = operational ? [["Overview", `/club${query()}`], ["Reception", `/club/reception${query()}`], ["Members", `/club/members${query()}`], ["Shop", `/club/shop${query()}`], ["Classes", `/club/classes${query()}`], ["Services", `/club/services${query()}`], ["Finance", `/club/payments${query()}`], ...(admin ? [["More", `/club/locations${query()}`]] : [])] : role === "trainer" ? [["Classes", `/club/classes${query()}`]] : [["Classes", `/club/classes${query()}`], ["Shop", `/club/shop${query()}`], ["Membership payments", `/club/membership-billing${query()}`]];
  const canAggregate = role === "gym_admin" || role === "owner"; const isActive = (href:string) => { const path=href.split("?")[0]; return path === "/club" ? pathname === "/club" : pathname.startsWith(path); };
  const renderLinks = (mobile=false) => links.map(([label,href]) => <Link href={href} key={href} aria-current={isActive(href) ? "page" : undefined} className={isActive(href) ? styles.active : undefined} onClick={()=>mobile&&setMobileOpen(false)}>{label}</Link>);
  return <nav className={styles.nav} aria-label="Club navigation"><div className={styles.identity}><div className={styles.tenant}><span className={styles.tenantMark}><BrandLockup compact /></span><span aria-hidden="true" className={styles.multiply}>×</span><div><span className="eyebrow">CLUB OPERATIONS</span><strong>{organisation.name}</strong></div></div><span className={styles.role}>{labelRole(role)}</span><button type="button" className={styles.menuButton} aria-expanded={mobileOpen} aria-controls="club-mobile-menu" onClick={()=>setMobileOpen(open=>!open)}>{mobileOpen ? "Close" : "Menu"}</button></div><div className={styles.links}>{renderLinks()}</div><div className={styles.contextControls}>{contexts.length > 1 ? <label className={styles.switcher}>Organisation<select aria-label="Choose organisation" defaultValue={organisation.id} onChange={event => router.push(`/club?org=${encodeURIComponent(event.target.value)}`)}>{contexts.map(context => <option key={context.organisation.id} value={context.organisation.id}>{context.organisation.name}</option>)}</select></label> : null}{activeVenues.length ? <label className={styles.switcher}>Venue<select aria-label="Choose operational venue" value={locationId ?? (canAggregate ? "all" : activeVenues[0]?.id)} onChange={event => router.push(`${pathname}${query(event.target.value === "all" ? undefined : event.target.value)}`)}>{canAggregate ? <option value="all">All locations</option> : null}{activeVenues.map(location => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label> : null}</div>{mobileOpen ? <div id="club-mobile-menu" className={styles.mobileMenu}>{renderLinks(true)}</div> : null}</nav>;
}
