"use client";
import { useState, useTransition } from "react";
import { parseSupplierCsv, type SupplierImportResult } from "@/lib/club-supplier";
import { parseClubCsv, type ClubImportRow } from "@/lib/club-csv";
import { saveCatalogueProductAction } from "@/app/club/shop/actions";
export function ClubCatalogueImport({ organisationId, products }: { organisationId: string; products: Array<{ id: string; name: string; sku?: string; barcode?: string; sellPriceMinor: number; stockTracked: boolean; active: boolean; category?: string }> }) {
 const [rows,setRows]=useState<ClubImportRow[]>([]); const [supplier,setSupplier]=useState<SupplierImportResult>(); const [message,setMessage]=useState(""); const [pending,startTransition]=useTransition();
 const review=(text:string)=>{const parsed=parseClubCsv(text);setRows(parsed.map(row=>{const barcode=row.barcode&&products.find(p=>p.barcode===row.barcode);const sku=row.sku&&products.find(p=>p.sku===row.sku);const name=products.find(p=>p.name.trim().toLowerCase()===row.name.trim().toLowerCase());return {...row,status:row.status==="INVALID"||row.status==="REVIEW REQUIRED"?row.status:barcode?"EXISTING BARCODE":sku?"EXISTING SKU":name?"POSSIBLE NAME MATCH":"NEW",reason:row.reason??(barcode?"Barcode already exists":sku?"SKU already exists":name?"Review possible duplicate":undefined)};}))};
 const importRows=()=>startTransition(async()=>{const eligible=rows.filter(r=>r.status==="NEW");let success=0;for(const row of eligible){const result=await saveCatalogueProductAction({organisationId,name:row.name,category:row.category,price:row.price,barcode:row.barcode,sku:row.sku,stockTracked:row.stockTracked,active:row.active});if(result.ok)success+=1;}setMessage(`Imported ${success} of ${eligible.length} new products. Review rows were not changed.`)});
 return <section className="catalogue-import" aria-label="Catalogue imports"><details open><summary>Import catalogue CSV</summary><p className="muted">Review matches before importing. No stock is created.</p><textarea aria-label="Paste catalogue CSV" rows={4} placeholder="name,category,price,barcode,sku,stockTracked,active" onChange={e=>review(e.target.value)}/>{rows.length?<div className="catalogue-import-review"><strong>{rows.length} rows ready for review</strong>{rows.map((row,i)=><div className="club-detail-row" key={`${row.name}-${i}`}><span>{row.name||"Unnamed product"}<small>{row.category||"Uncategorised"} · {row.barcode||"No barcode"}</small></span><span className="muted">{row.status}<small>{row.reason}</small></span></div>)}</div>:null}<button type="button" className="primary" disabled={pending||!rows.some(r=>r.status==="NEW")} onClick={importRows}>{pending?"Importing…":"Import new products"}</button></details><details><summary>Review supplier catalogue</summary><p className="muted">Supplier availability remains separate from Madhouse on-hand stock.</p><input type="file" accept=".csv,text/csv" aria-label="Supplier CSV" onChange={e=>{const file=e.target.files?.[0];if(file)void file.text().then(text=>setSupplier(parseSupplierCsv(text,"Supplier")))}}/>{supplier?<p className="message" role="status">{supplier.rows.length} rows reviewed · {supplier.duplicates.length} duplicate keys flagged. No rows imported.</p>:null}</details>{message?<p className="message" role="status">{message}</p>:null}</section>;
}
