import Link from "next/link";
import { AppShell, EmptyState, PageHeader, Surface } from "@/components/ui";
import { ClubSectionNav } from "@/components/club-shell";
import styles from "@/components/club-operations.module.css";
import type { ClubMemberOperationalRead } from "@/lib/club-operational";
import type { ClubBalanceAccount, ClubOrder } from "@/lib/club-commerce";
import type { ClubClassSession } from "@/lib/club-operations";
import type { ClubRole, Organisation, OrganisationLocation } from "@/lib/club";

type BillingRow = { state?: string; amount_minor?: number; currency?: string; next_due_at?: string };
const money = (minor: number | undefined, currency = "GBP") => typeof minor === "number" ? new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(minor / 100) : undefined;
const date = (value?: string) => value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)) : undefined;
const stateLabel = (value?: string) => ({ active: "Active", needs_attention: "Needs attention", unavailable: "Unavailable", paid: "Paid", due: "Due", failed: "Payment failed", grace: "Needs attention", overdue: "Overdue" } as Record<string, string>)[value ?? ""] ?? value;

export function ClubMemberHome({ organisation, role, contexts, profile, balance, locations, sessions, orders, billing, bookings, serviceTransactions }: {
  organisation: Organisation; role: ClubRole; contexts: Array<{ organisation: Organisation; role: ClubRole }>;
  profile: ClubMemberOperationalRead; balance?: ClubBalanceAccount; locations: OrganisationLocation[]; sessions: ClubClassSession[]; orders: ClubOrder[]; billing: BillingRow[]; bookings: Array<{ sessionId: string; status: string }>; serviceTransactions: Array<{ customerId?: string; fulfilmentStatus: string; occurredAt: string }>;
}) {
  const query = `?org=${encodeURIComponent(organisation.id)}`;
  const activeMemberships = profile.memberships.filter(item => item.status === "active");
  const inductionNeedsAttention = profile.induction?.state.required && profile.induction.state.state !== "complete";
  const accessState = profile.access?.state ?? (activeMemberships.length ? "needs_attention" : "unavailable");
  const visibleSessions = sessions.filter(item => item.status === "scheduled").slice(0, 4);
  const ownOrders = orders.filter(order => order.userId === profile.member.userId || (!!profile.customer?.id && order.customerId === profile.customer.id)).slice(0, 5);
  const activeLocations = locations.filter(item => item.active && (!profile.access?.permittedLocationIds?.length || profile.access.permittedLocationIds.includes(item.id)));
  const attention = [accessState !== "active" ? { label: "Access needs attention", detail: profile.access?.reason ?? "Membership access is not currently active" } : null, inductionNeedsAttention ? { label: "Induction needs completing", detail: "Complete the required induction before access can be confirmed" } : null, billing.some(item => ["due", "failed", "grace", "overdue"].includes(item.state ?? "")) ? { label: "Membership payment needs attention", detail: "Review the latest billing obligation" } : null].filter(Boolean) as Array<{ label: string; detail: string }>;
  const golden = profile.entitlements.find(item => item.entitlementKey === "golden_ticket");
  return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · MEMBER" title={organisation.name} description="Your membership, access and Club services." /><ClubSectionNav organisation={organisation} role={role} contexts={contexts} />
    <div className={styles.overview}>
      <Surface className={attention.length ? styles.attention : ""}><span className="eyebrow">NEEDS ATTENTION</span>{attention.length ? <div className={styles.attentionList}>{attention.map(item => <div className={styles.attentionItem} key={item.label}><span><strong>{item.label}</strong><small>{item.detail}</small></span></div>)}</div> : <p className="muted" style={{ marginTop: 12 }}>Nothing needs attention right now.</p>}</Surface>
      <Surface><span className="eyebrow">MEMBERSHIP & ACCESS</span>{activeMemberships.length ? activeMemberships.map(item => <div className="club-detail-row" key={item.id}><span><strong>{item.productName ?? "Membership"}</strong><small>{stateLabel(item.status)} · {date(item.startsAt)}{item.endsAt ? ` – ${date(item.endsAt)}` : ""}</small></span></div>) : <p className="muted" style={{ marginTop: 12 }}>No active membership is linked to this account.</p>}<div className="club-detail-row"><span>Gym access</span><strong>{stateLabel(accessState)}</strong></div>{profile.access?.reason ? <p className="muted">{profile.access.reason}</p> : null}</Surface>
      <Surface><span className="eyebrow">MEMBERSHIP & ACCESS</span>{activeMemberships.length ? activeMemberships.map(item => <div className="club-detail-row" key={item.id}><span><strong>{item.productName ?? "Membership"}</strong><small>{stateLabel(item.status)} · {date(item.startsAt)}{item.endsAt ? ` – ${date(item.endsAt)}` : ""}</small></span></div>) : <p className="muted" style={{ marginTop: 12 }}>No active membership is linked to this account.</p>}<div className="club-detail-row"><span>Gym access</span><strong>{stateLabel(accessState)}</strong></div>{profile.access?.reason ? <p className="muted">{profile.access.reason}</p> : null}<Link href={`/club/join${query}`}>View membership options</Link></Surface>
      <Surface><span className="eyebrow">BILLING</span>{billing.length ? billing.slice(0, 3).map((item, index) => <div className="club-detail-row" key={`${item.next_due_at ?? "obligation"}-${index}`}><span>{item.next_due_at ? `Next payment ${date(item.next_due_at)}` : "Membership payment"}</span><strong>{money(item.amount_minor, item.currency ?? "GBP") ?? stateLabel(item.state)}</strong></div>) : <p className="muted" style={{ marginTop: 12 }}>No membership billing obligation is currently available.</p>}<Link href={`/club/membership-billing${query}`}>View membership payments</Link></Surface>
      <Surface><span className="eyebrow">ENTITLEMENTS & CREDITS</span>{profile.entitlements.length || profile.serviceCredits.length ? <>{profile.entitlements.map(item => <div className="club-detail-row" key={item.id}><span>{item.entitlementKey.replace(/[_-]+/g, " ")}</span><span className="muted">{item.allowance ? `${item.allowance.quantity} per ${item.allowance.period}` : "Active"}</span></div>)}{profile.serviceCredits.map(item => <div className="club-detail-row" key={item.id}><span>{item.creditKey.replace(/[_-]+/g, " ")}</span><strong>{item.balanceQuantity} {item.unit}{item.balanceQuantity === 1 ? "" : "s"}</strong></div>)}</> : <p className="muted" style={{ marginTop: 12 }}>No additional credits are currently available.</p>}{golden ? <p className="muted">Golden Ticket entitlement active; monthly availability is checked at checkout.</p> : null}</Surface>
      <Surface><span className="eyebrow">MADHOUSE BALANCE</span>{balance ? <><div className="club-detail-row"><span>Available balance</span><strong>{money(balance.balanceMinor, balance.currency)}</strong></div><Link href={`/club/shop/balance${query}`}>View Balance activity</Link></> : <p className="muted" style={{ marginTop: 12 }}>No Madhouse Balance account is linked to this Club profile.</p>}</Surface>
      <Surface><span className="eyebrow">CLASSES</span>{visibleSessions.length ? visibleSessions.map(session => <div className="club-detail-row" key={session.id}><span>{session.title ?? "Scheduled class"}<small>{date(session.startsAt)}</small></span><span className="muted">{bookings.some(item => item.sessionId === session.id && item.status !== "cancelled") ? "Booked" : "View"}</span></div>) : <p className="muted" style={{ marginTop: 12 }}>No upcoming classes are scheduled.</p>}<Link href={`/club/classes${query}`}>View classes</Link></Surface>
      <Surface><span className="eyebrow">SERVICES</span>{profile.serviceCredits.length ? profile.serviceCredits.map(item => <div className="club-detail-row" key={item.id}><span>{item.creditKey.replace(/[_-]+/g, " ")}</span><strong>{item.balanceQuantity} remaining</strong></div>) : <p className="muted" style={{ marginTop: 12 }}>No service credits are linked to this account.</p>}{serviceTransactions.length ? <p className="muted">Recent service activity is available on your member record.</p> : null}</Surface>
      <Surface><span className="eyebrow">ORDERS & RECEIPTS</span>{ownOrders.length ? ownOrders.map(order => <div className="club-detail-row" key={order.id}><span>{date(order.createdAt)}<small>{order.items.map(item => `${item.productName} ×${item.quantity}`).join(", ")}</small></span><strong>{money(order.totalMinor, order.currency)}</strong></div>) : <p className="muted" style={{ marginTop: 12 }}>No orders are linked to this account.</p>}<Link href={`/club/shop${query}`}>View shop and orders</Link></Surface>
      <Surface><span className="eyebrow">LOCATIONS</span>{activeLocations.length ? <p className="muted" style={{ marginTop: 12 }}>{activeLocations.map(item => item.name).join(" · ")}</p> : <p className="muted" style={{ marginTop: 12 }}>No active Club location coverage is recorded.</p>}</Surface>
    </div>
  </AppShell>;
}

export function MemberClubUnavailable() { return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Club" description="Your Madhouse membership workspace." /><EmptyState title="Club account not linked">This login is not linked to a Club member record yet. Ask the Madhouse team to confirm your account link.</EmptyState></AppShell>; }
