"use client";
import { useState, useTransition } from "react";
import { parseClubCsv, type ClubImportRow } from "@/lib/club-csv";
import { saveCatalogueProductAction } from "@/app/club/shop/actions";

export function ClubCatalogueImport({ organisationId, products }: { organisationId: string; products: Array<{ id: string; name: string; sku?: string; barcode?: string; sellPriceMinor: number; stockTracked: boolean; active: boolean; category?: string }> }) {
  const [rows, setRows] = useState<ClubImportRow[]>([]); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const review = (text: string) => { const parsed = parseClubCsv(text); setRows(parsed.map(row => { const barcode = row.barcode && products.find(product => product.barcode === row.barcode); const sku = row.sku && products.find(product => product.sku === row.sku); const name = products.find(product => product.name.trim().toLowerCase() === row.name.trim().toLowerCase()); return { ...row, status: row.status === "INVALID" || row.status === "REVIEW REQUIRED" ? row.status : barcode ? "EXISTING BARCODE" : sku ? "EXISTING SKU" : name ? "POSSIBLE NAME MATCH" : "NEW", reason: row.reason ?? (barcode ? "Barcode already exists" : sku ? "SKU already exists" : name ? "Review possible duplicate" : undefined) }; })); setMessage(parsed.length ? `${parsed.length} rows ready for review.` : "Paste a CSV file to begin."); };
  const importRows = () => startTransition(async () => { const eligible = rows.filter(row => row.status === "NEW"); let success = 0; for (const row of eligible) { const result = await saveCatalogueProductAction({ organisationId, name: row.name, category: row.category, price: row.price, barcode: row.barcode, sku: row.sku, stockTracked: row.stockTracked, active: row.active }); if (result.ok) success += 1; } setMessage(`Imported ${success} of ${eligible.length} new products. Existing and review rows were not changed.`); });
  return <details className="catalogue-import"><summary>Import products</summary><p className="muted">Paste CSV, review each row, then import new catalogue products. No stock is created.</p><textarea aria-label="Paste catalogue CSV" rows={5} placeholder="name,category,price,barcode,sku,stockTracked,active,notes" onChange={event => review(event.target.value)} />{rows.length ? <div className="catalogue-import-review">{rows.map((row, index) => <div className="club-detail-row" key={`${row.name}-${index}`}><span><strong>{row.name || "Unnamed product"}</strong><small>{row.category ?? "Uncategorised"} · {row.barcode ?? "No barcode"}</small></span><span className={row.status === "NEW" ? "" : "muted"}>{row.status}<small>{row.reason}</small></span></div>)}</div> : null}<button type="button" className="primary" disabled={pending || !rows.some(row => row.status === "NEW")} onClick={importRows}>{pending ? "Importing…" : "Import new products"}</button>{message ? <p className="message" role="status">{message}</p> : null}</details>;
}
