"use client";
import { useState, useTransition } from "react";
import type { ClubCommerceProduct } from "@/lib/club-commerce";
import { receiveDeliveryAction } from "@/app/club/shop/actions";

export function ClubDeliveryReceipt({ organisationId, locationId, products }: { organisationId: string; locationId?: string; products: ClubCommerceProduct[] }) {
  const [open, setOpen] = useState(false); const [productId, setProductId] = useState(products.find(product => product.stockTracked)?.id ?? ""); const [quantity, setQuantity] = useState("1"); const [unitCost, setUnitCost] = useState(""); const [supplier, setSupplier] = useState(""); const [reference, setReference] = useState(""); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const submit = () => { if (!locationId) return setMessage("Choose an operational venue first."); startTransition(async () => { const result = await receiveDeliveryAction({ organisationId, locationId, supplierName: supplier || undefined, supplierReference: reference || undefined, lines: [{ productId, quantityReceived: Number(quantity), unitCost: unitCost || undefined }] }); setMessage(result.ok ? "Delivery received and stock updated at this venue." : result.error); if (result.ok) setOpen(false); }); };
  return <section className="delivery-receipt"><button className="primary" type="button" onClick={() => setOpen(true)}>Receive delivery</button>{open ? <div className="modal" role="dialog" aria-modal="true" aria-label="Receive delivery"><form className="sheet" onSubmit={event => { event.preventDefault(); submit(); }}><div className="sheet-heading"><div><span className="eyebrow">STOCK INTAKE</span><h2>Receive delivery</h2></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><p className="muted">Stock will be added to the selected venue only.</p><label>Supplier<input value={supplier} onChange={event => setSupplier(event.target.value)} /></label><label>Delivery note / invoice reference<input value={reference} onChange={event => setReference(event.target.value)} /></label><label>Product<select value={productId} onChange={event => setProductId(event.target.value)}>{products.filter(product => product.stockTracked && product.active).map(product => <option value={product.id} key={product.id}>{product.name}</option>)}</select></label><label>Quantity received<input type="number" min={1} step={1} value={quantity} onChange={event => setQuantity(event.target.value)} required /></label><label>Unit cost (optional)<input inputMode="decimal" placeholder="0.00" value={unitCost} onChange={event => setUnitCost(event.target.value)} /></label>{message ? <p role="alert" className="error-text">{message}</p> : null}<button className="primary full" type="submit" disabled={pending}>{pending ? "Receiving…" : "Confirm delivery"}</button></form></div> : null}</section>;
}
