"use client";
import { useState, useTransition } from "react";
import { confirmShelfReadyAction, scanShelfReminderAction } from "@/app/club/shop/collections/actions";

export function ClubCollections({ organisationId, collections, locationId }: { organisationId: string; collections: Array<Record<string, unknown>>; locationId?: string }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string>();
  const [code, setCode] = useState("");
  return <section aria-label="Collection shelf"><div className="club-catalogue-list">{collections.map(item => <article className="club-catalogue-row" key={String(item.id ?? item.order_id)}><div><strong>{String(item.member_name ?? "Member")} · {String(item.order_reference ?? item.collection_code ?? "Order")}</strong><small>{String(item.collection_location ?? "Collection area")} · ready {new Date(String(item.ready_at)).toLocaleString("en-GB")}</small><span>{String(item.items_summary ?? "Bagged customer items")}</span></div>{item.shelf_confirmed_at ? <span className="muted">On shelf · check after 3 days</span> : <button type="button" className="primary" disabled={pending} onClick={() => startTransition(async () => { const result = await confirmShelfReadyAction(organisationId, String(item.id)); setMessage(result.ok ? "Shelf placement recorded. Member notification queued." : result.error); })}>Confirm on shelf</button>}</article>)}</div><div className="card" style={{ marginTop: 16 }}><strong>Shelf reminder scan</strong><p className="muted">Only scan parcels you physically find on the shelf after 3 days.</p><form onSubmit={event => { event.preventDefault(); startTransition(async () => { const result = await scanShelfReminderAction(organisationId, code, locationId ?? String(collections[0]?.location_id ?? "")); setMessage(result.ok ? "Reminder queued." : result.error); if (result.ok) setCode(""); }); }}><label>Collection code<input value={code} onChange={event => setCode(event.target.value)} placeholder="Scan or enter COL-…" /></label><button className="secondary" type="submit" disabled={pending || !code.trim() || !(locationId ?? collections[0]?.location_id)}>Queue reminder</button></form></div>{message ? <p role="status">{message}</p> : null}</section>;
}
