import Link from "next/link";
import type { ReactNode } from "react";

export type CoachWorkspaceSection = "overview" | "programme" | "checkins" | "progress" | "history";

type Client = { clientUserId: string; organisationId: string | null; assignmentId: string; relationshipId?: string; name: string; relationship: "primary" | "cover"; programmeName: string; programmeOwnerName: string; contextName?: string };
type PlannedDay = { id?: string; name?: string; exerciseIds?: string[]; exerciseOverrides?: Record<string, { name?: string; target?: string; sets?: number }> };
type Detail = Client & { programme: { id?: string; name?: string; rationale?: string; week?: PlannedDay[] }; completedWorkouts: Array<{ id: string; name: string; completedAt?: string; sets: number }>; sessions: Array<{ id: string; status: string; session_date?: string; notes: string; adaptations: string; substitutions: unknown[] }> };
type CheckinDay = { date: string; adherence?: "followed" | "mostly" | "no" | null; clientNote?: string | null; extrasCount?: number };
export type NutritionSummary = { activePlan?: { title?: string; status?: string; reviewDate?: string } | null; draftPlan?: { title?: string; updatedAt?: string } | null; checkinDays?: CheckinDay[]; feedback?: Array<{ id: string; message: string; privateNote?: boolean; clientVisible?: boolean }>; canManage?: boolean };

function dateLabel(value?: string) {
  if (!value) return "Date not recorded";
  return new Date(value.length === 10 ? `${value}T00:00:00` : value).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

function adherenceLabel(value?: CheckinDay["adherence"]) {
  return value === "followed" ? "Yes" : value === "mostly" ? "Mostly" : value === "no" ? "No" : "Missing";
}

function adherenceMark(value?: CheckinDay["adherence"]) {
  return value === "followed" ? "✓" : value === "mostly" ? "~" : value === "no" ? "×" : "—";
}

export function CoachClientWorkspace({ detail, section, onSectionChange, nutrition, nutritionState, programmeContent }: { detail: Detail; section: CoachWorkspaceSection; onSectionChange: (section: CoachWorkspaceSection) => void; nutrition: NutritionSummary | null; nutritionState: "loading" | "ready" | "unavailable"; programmeContent: ReactNode }) {
  const days = nutrition?.checkinDays ?? [];
  const followed = days.filter(day => day.adherence === "followed").length;
  const mostly = days.filter(day => day.adherence === "mostly").length;
  const no = days.filter(day => day.adherence === "no").length;
  const latestWorkout = detail.completedWorkouts[0];
  const latestSession = detail.sessions[0];
  const latestTrainingTitle = latestWorkout?.name ?? (latestSession?.status === "completed" ? "Coached session" : "No completed training yet");
  const programme = detail.programme;
  const nav = (label: string, value: CoachWorkspaceSection) => <button type="button" className={section === value ? "coach-workspace-tab selected" : "coach-workspace-tab"} aria-current={section === value ? "page" : undefined} onClick={() => onSectionChange(value)}>{label}</button>;

  return <>
    <header className="card coach-client-hero"><div><span className="eyebrow">CLIENT WORKSPACE</span><h2>{detail.name}</h2><p className="muted">{detail.relationship === "cover" ? `Cover PT · programme owned by ${detail.programmeOwnerName}` : "Primary PT · programme owner"}{detail.contextName ? ` · ${detail.contextName}` : ""}</p></div><span className="coach-lock">Authorised client</span></header>
    <nav className="coach-workspace-nav" aria-label={`${detail.name} workspace sections`}>{nav("Overview", "overview")}{nav("Programme", "programme")}<Link href={`/coach/nutrition?client=${encodeURIComponent(detail.clientUserId)}`} className="coach-workspace-tab">Nutrition</Link>{nav("Check-ins", "checkins")}{nav("Progress", "progress")}{nav("History", "history")}</nav>
    {section === "overview" ? <section className="coach-workspace-panel" aria-labelledby="coach-overview-title"><div className="coach-section-heading"><div><span className="eyebrow">AT A GLANCE</span><h2 id="coach-overview-title">What matters now</h2></div></div><div className="coach-overview-grid"><article className="coach-overview-card"><span className="eyebrow">PROGRAMME</span><h3>{programme?.name ?? detail.programmeName}</h3><p className="muted">{detail.relationship === "cover" ? `Read-only · owned by ${detail.programmeOwnerName}` : "Primary PT owned"}</p><button type="button" className="secondary" onClick={() => onSectionChange("programme")}>Open programme</button></article><article className="coach-overview-card"><span className="eyebrow">LATEST TRAINING</span><h3>{latestTrainingTitle}</h3><p className="muted">{latestWorkout ? `${dateLabel(latestWorkout.completedAt)} · ${latestWorkout.sets} logged sets` : latestSession ? dateLabel(latestSession.session_date) : "Completed workouts and coached sessions will appear here."}</p><button type="button" className="secondary" onClick={() => onSectionChange("history")}>View history</button></article><article className="coach-overview-card"><span className="eyebrow">NUTRITION</span><h3>{nutritionState === "loading" ? "Loading plan…" : nutritionState === "unavailable" ? "Nutrition unavailable" : nutrition?.activePlan?.title ?? "No active plan"}</h3><p className="muted">{nutrition?.draftPlan && nutrition.canManage ? `Draft ready · ${nutrition.draftPlan.title ?? "Untitled draft"}` : nutrition?.activePlan?.reviewDate ? `Review ${dateLabel(nutrition.activePlan.reviewDate)}` : "Plan and accountability status"}</p><Link className="secondary" href={`/coach/nutrition?client=${encodeURIComponent(detail.clientUserId)}`}>Open nutrition</Link></article><article className="coach-overview-card"><span className="eyebrow">LAST 7 DAYS</span><h3>{nutritionState === "ready" ? `${followed} followed · ${mostly} mostly` : "No check-in summary"}</h3><p className="muted">{nutritionState === "ready" ? `${no} marked no · ${days.filter(day => !day.adherence).length} missing` : "Accountability will appear when available."}</p><button type="button" className="secondary" onClick={() => onSectionChange("checkins")}>Review check-ins</button></article></div>{nutrition?.feedback?.[0] ? <article className="coach-overview-note"><span className="eyebrow">LATEST FEEDBACK</span><p>{nutrition.feedback[0].message}</p></article> : null}</section> : null}
    {section === "programme" ? <section className="coach-workspace-panel" aria-labelledby="coach-programme-title"><div className="coach-section-heading"><div><span className="eyebrow">PROGRAMME</span><h2 id="coach-programme-title">Current training plan</h2></div><span className="coach-lock">{detail.relationship === "cover" ? "Read only" : "Primary PT owned"}</span></div><p className="muted">{programme?.rationale ?? "Inspect the current programme and run an authorised session. Session logs do not change the prescription."}</p>{programmeContent}</section> : null}
    {section === "checkins" ? <section className="coach-workspace-panel" aria-labelledby="coach-checkins-title"><div className="coach-section-heading"><div><span className="eyebrow">ACCOUNTABILITY</span><h2 id="coach-checkins-title">Check-ins</h2></div><Link className="secondary" href={`/coach/nutrition?client=${encodeURIComponent(detail.clientUserId)}`}>Open nutrition</Link></div>{nutritionState === "loading" ? <p className="muted">Loading recent check-ins…</p> : nutritionState === "unavailable" ? <p className="muted">Check-ins are temporarily unavailable.</p> : <><div className="coach-checkin-strip" aria-label="Last seven days of check-ins">{days.map(day => <span key={day.date} title={`${dateLabel(day.date)} · ${adherenceLabel(day.adherence)}`}>{adherenceMark(day.adherence)}</span>)}</div><div className="coach-checkin-summary"><span>{followed} Yes</span><span>{mostly} Mostly</span><span>{no} No</span><span>{days.filter(day => !day.adherence).length} Missing</span></div>{days.map(day => <article className="coach-checkin-row" key={day.date}><div><strong>{dateLabel(day.date)}</strong><small>{adherenceLabel(day.adherence)}{day.extrasCount ? ` · ${day.extrasCount} extra${day.extrasCount === 1 ? "" : "s"}` : ""}</small></div><p>{day.clientNote || (day.adherence ? "No note" : "No submission")}</p></article>)}</>}</section> : null}
    {section === "progress" ? <section className="coach-workspace-panel" aria-labelledby="coach-progress-title"><div className="coach-section-heading"><div><span className="eyebrow">PROGRESS</span><h2 id="coach-progress-title">Training progress</h2></div></div>{detail.completedWorkouts.length ? <><div className="coach-progress-summary"><article><strong>{detail.completedWorkouts.length}</strong><span>completed workouts</span></article><article><strong>{detail.completedWorkouts.reduce((total, workout) => total + workout.sets, 0)}</strong><span>logged sets</span></article><article><strong>{latestWorkout ? dateLabel(latestWorkout.completedAt) : "—"}</strong><span>latest workout</span></article></div><div className="coach-history-list">{detail.completedWorkouts.slice(0, 12).map(workout => <div className="coach-history-row" key={workout.id}><div><strong>{workout.name}</strong><small>{dateLabel(workout.completedAt)}</small></div><span>{workout.sets} sets</span></div>)}</div></> : <div className="coach-empty-panel"><h3>Progress will build here</h3><p className="muted">Completed member workouts and coached sessions will appear as this client trains.</p></div>}</section> : null}
    {section === "history" ? <section className="coach-workspace-panel" aria-labelledby="coach-history-title"><div className="coach-section-heading"><div><span className="eyebrow">HISTORY</span><h2 id="coach-history-title">Client history</h2></div></div>{detail.sessions.length ? <><h3 className="coach-subheading">Coached sessions</h3>{detail.sessions.slice(0, 12).map(coachSession => <div className="coach-history-row" key={coachSession.id}><div><strong>{coachSession.status === "completed" ? "Completed coached session" : "Session log in progress"}</strong><small>{dateLabel(coachSession.session_date)} · Delivered by you · {detail.relationship === "cover" ? "cover PT" : "primary PT"}</small></div><small>{[coachSession.substitutions.length ? "Substitutions" : "", coachSession.adaptations ? "Adaptation" : "", coachSession.notes ? "Notes" : ""].filter(Boolean).join(" · ") || "No additional notes"}</small></div>)}</> : <div className="coach-empty-panel"><h3>No coached sessions yet</h3><p className="muted">Sessions you deliver will be attributed to you here while programme ownership stays separate.</p></div>}{detail.completedWorkouts.length ? <><h3 className="coach-subheading">Member workouts</h3>{detail.completedWorkouts.slice(0, 12).map(workout => <div className="coach-history-row" key={workout.id}><div><strong>{workout.name}</strong><small>{dateLabel(workout.completedAt)} · Member workout</small></div><span>{workout.sets} sets</span></div>)}</> : null}</section> : null}
  </>;
}
