"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { recoveryGuidance } from "@/lib/recovery-guidance";
import { currentBlock, currentWeek, latestWhoopSnapshot, type PlannedSession, type RecoverySnapshot, type SessionStatus } from "@/lib/domain";
import { loadData, loadGeneratedProgramme, saveData } from "@/lib/storage";
import { dayLabel, localDateParts, occurrenceKey, resolveToday, upcomingAfterToday } from "@/lib/schedule";
import { programmeSnapshot } from "@/lib/programme-progress";
import { shouldSyncReadiness } from "@/lib/whoop-sync";
import { coachGreeting } from "@/lib/greeting";
import type { Workout } from "@/lib/types";
import { ProgressBar } from "@/components/ui";
import Link from "next/link";
import { MissedSessionAction } from "./missed-session-action";
import { resolveWeekSchedule, resolveTodayOccurrence } from "@/lib/schedule-resolver";
import { legacyProgrammeSnapshot } from "@/lib/legacy-programme";

type WhoopState = { configured?: boolean; connected?: boolean; lastSyncAt?: string; latest?: RecoverySnapshot | null; error?: string };
const checkInFields = [["energy", "Energy"], ["sleepQuality", "Sleep quality"], ["soreness", "Muscle soreness"], ["motivation", "Motivation"], ["fatigue", "General fatigue"]] as const;
function DailyCheckInSheet({ onClose, onSave }: { onClose: () => void; onSave: (values: Record<string, number>) => void }) {
  const [values, setValues] = useState<Record<string, number>>({});
  return <div className="modal" role="dialog" aria-modal="true" aria-label="Daily check-in"><section className="check-in-sheet"><div className="sheet-heading"><div><span className="eyebrow">DAILY CHECK-IN</span><h2>How are you feeling?</h2></div><button className="text-button" type="button" onClick={onClose}>Cancel</button></div><p className="muted">A quick five-point check keeps today&apos;s guidance grounded in how you feel.</p>{checkInFields.map(([key, label]) => <fieldset className="check-in-field" key={key}><legend>{label}</legend><div className="check-in-options" role="group" aria-label={label}>{[1, 2, 3, 4, 5].map(value => <button type="button" key={value} className={values[key] === value ? "selected" : ""} aria-pressed={values[key] === value} onClick={() => setValues(current => ({ ...current, [key]: value }))}>{value}</button>)}</div></fieldset>)}<div className="check-in-actions"><button className="secondary" type="button" onClick={onClose}>Not now</button><button className="primary" type="button" disabled={Object.keys(values).length !== checkInFields.length} onClick={() => onSave(values)}>Save check-in</button></div></section></div>;
}
export function DashboardFoundation({ workoutHistory }: { workoutHistory?: Workout[] } = {}) {
  const [data, setData] = useState(() => loadData());
  const [statusMenu, setStatusMenu] = useState<(PlannedSession & { scheduledDate: string }) | null>(null);
  const [blockOpen, setBlockOpen] = useState(false);
  const [whoop, setWhoop] = useState<WhoopState>({});
  const [displayName, setDisplayName] = useState<string>();
  const [memberOrganisations, setMemberOrganisations] = useState<Array<{ id: string; name: string; slug?: string }>>([]);
  const [syncing, setSyncing] = useState(false);
  const [checkInOpen, setCheckInOpen] = useState(false);
  const syncingRef = useRef(false);
  const lastAttemptRef = useRef(0);
  const whoopRef = useRef<WhoopState>({});
  const [timezone] = useState(() => data.timezone ?? (typeof window === "undefined" ? "Europe/London" : (Intl.DateTimeFormat().resolvedOptions().timeZone || "Europe/London")));
  const now = new Date();
  const localToday = localDateParts(now, timezone);
  const generated = loadGeneratedProgramme(); const legacy = legacyProgrammeSnapshot(data.trainingProfile); const programmeWeek = generated?.week ?? currentWeek; const programmeBlock = generated?.block ?? currentBlock; const programmeName = generated?.name ?? legacy.name; const productSchedule = resolveWeekSchedule(programmeWeek, data, timezone, now); const todayOccurrence = resolveTodayOccurrence(programmeWeek, data, timezone, now); const today = { ...localToday, session: todayOccurrence?.session ?? resolveToday(programmeWeek, timezone, now).session };
  const localSnapshot = useMemo(() => latestWhoopSnapshot(data.recoverySnapshots ?? [], localToday.date)?.record, [data.recoverySnapshots, localToday.date]);
  const recoverySnapshot = whoop.latest ?? localSnapshot;
  const isToday = recoverySnapshot?.date === localToday.date;
  const programmeSummary = programmeSnapshot(programmeName, programmeBlock, programmeWeek, workoutHistory ?? data.workouts, Boolean(generated), productSchedule.occurrences);
  const snapshot = { ...programmeSummary, ...(recoverySnapshot ?? {}) };
  const completedInBlock = programmeSummary.completedSessions;
  const applySnapshots = (snapshots: RecoverySnapshot[]) => { if (!snapshots.length) return; const byId = new Map((data.recoverySnapshots ?? []).map(item => [item.id, item])); snapshots.forEach(item => byId.set(item.id, item)); const next = { ...data, recoverySnapshots: [...byId.values()] }; saveData(next); setData(next); setWhoop(value => ({ ...value, latest: snapshots.at(-1) })); };
  const sync = async () => { if (syncingRef.current) return; syncingRef.current = true; lastAttemptRef.current = Date.now(); setSyncing(true); setWhoop(value => ({ ...value, error: undefined })); try { const response = await fetch("/api/integrations/whoop/sync", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "WHOOP sync failed"); applySnapshots(result.snapshots ?? []); setWhoop(value => ({ ...value, connected: true, lastSyncAt: result.syncedAt })); const refreshed = await fetch("/api/integrations/whoop/status"); if (refreshed.ok) { const status = await refreshed.json(); whoopRef.current = status; setWhoop(status); if (status.latest) applySnapshots([status.latest]); } } catch (error) { setWhoop(value => ({ ...value, error: error instanceof Error ? error.message : "WHOOP sync failed" })); } finally { syncingRef.current = false; setSyncing(false); } };
  useEffect(() => { if (!data.timezone) saveData({ ...data, timezone }); fetch("/api/account").then(response => response.ok ? response.json() : undefined).then(result => setDisplayName(result?.profile?.first_name)).catch(() => undefined); fetch("/api/member-hub").then(response => response.ok ? response.json() : undefined).then(result => setMemberOrganisations(result?.organisations ?? [])).catch(() => undefined); fetch("/api/integrations/whoop/status").then(response => response.json()).then(result => { whoopRef.current = result; setWhoop(result); if (result.latest) applySnapshots([result.latest]); if (shouldSyncReadiness(result, Date.now(), 5 * 60 * 1000) && Date.now() - lastAttemptRef.current > 5 * 60 * 1000) void sync(); }).catch(() => undefined); const refreshOnReturn = () => { const current = whoopRef.current; if (shouldSyncReadiness(current, Date.now(), 5 * 60 * 1000) && Date.now() - lastAttemptRef.current > 5 * 60 * 1000) void sync(); }; window.addEventListener("focus", refreshOnReturn); document.addEventListener("visibilitychange", refreshOnReturn); return () => { window.removeEventListener("focus", refreshOnReturn); document.removeEventListener("visibilitychange", refreshOnReturn); }; // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  const addRecovery = () => setCheckInOpen(true);
  const saveCheckIn = (values: Record<string, number>) => { const next = { ...data, recoverySnapshots: [...(data.recoverySnapshots ?? []), { id: crypto.randomUUID(), date: localToday.date, origin: "real" as const, source: "manual" as const, userReported: true, energy: values.energy, sleepQuality: values.sleepQuality, soreness: values.soreness, motivation: values.motivation, fatigue: values.fatigue }] }; saveData(next); setData(next); setCheckInOpen(false); };
  const updateStatus = (id: string, scheduledDate: string, status: SessionStatus) => { const next = { ...data, sessionStatusOverrides: { ...(data.sessionStatusOverrides ?? {}), [occurrenceKey(id, scheduledDate)]: { status } } }; saveData(next); setData(next); };
  const guidance = recoveryGuidance(data.recoverySnapshots ?? [], localToday.date, isToday ? recoverySnapshot : null);
  const metric = (label: string, value: number | undefined, suffix = "", decimals = 0) => <span className="readiness-metric" key={label}><b>{label}</b><strong>{value === undefined ? "—" : `${value.toFixed(decimals)}${suffix}`}</strong></span>;
  const hasUsableRecovery = Boolean(whoop.connected && snapshot?.recoveryScore !== undefined && isToday);
  return <><section className="today-greeting" aria-label="Today"><h1>{coachGreeting(displayName, timezone, now)}</h1></section>{hasUsableRecovery && <section className="card dashboard readiness-card" aria-label="Recovery"><span className="eyebrow readiness-label">RECOVERY</span><strong>{guidance.band.toUpperCase()}</strong><p className="readiness-advice">{syncing ? "Updating readiness…" : guidance.message}</p><div className="readiness-rings">{metric("RECOVERY", snapshot.recoveryScore, "%")}{metric("SLEEP", snapshot.sleepPerformance, "%")}{metric("STRAIN", snapshot.strain, "", 1)}</div><small className="whoop-date">{whoop.lastSyncAt ? `Last sync - ${new Date(whoop.lastSyncAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : ""}</small>{whoop.error && <p className="error-text">{whoop.error}</p>}</section>}<section className="card dashboard manual-recovery"><span className="eyebrow">DAILY CHECK-IN</span>{data.recoverySnapshots?.find(item => item.userReported) ? <small>User-reported check-in is available to Coach.</small> : <small>No check-in logged today.</small>}<button className="secondary" aria-label="Log recovery check-in" onClick={addRecovery}>How do you feel?</button></section>{memberOrganisations.length > 0 && <section className="card dashboard member-gym-shortcut" aria-label="My gym">{memberOrganisations.map(org => <div className="member-gym-row" key={org.id}><div><span className="eyebrow">MY GYM</span><strong>{org.name}</strong><small>Membership active</small></div><Link className="secondary" href="/member-hub">Open my gym</Link></div>)}</section>}<MissedSessionAction />
    <section className="card dashboard upcoming-card"><span className="eyebrow">UPCOMING</span>{upcomingAfterToday(programmeWeek, timezone, now).map(day => { const state = data.sessionStatusOverrides?.[occurrenceKey(day.id, day.scheduledDate)]?.status ?? day.status ?? "planned"; const label = state === "rest" || state === "recovery_rest" ? "Rest" : state === "completed" ? "Completed" : state === "planned" ? "Planned" : String(state).replaceAll("_", " "); return <div className="plan-row upcoming-row" key={`${day.id}:${day.scheduledDate}`}><b>{dayLabel(day, today.day)}</b><span>{day.name}<small>{state === "rest" ? "Recovery day" : "Training session"}</small></span><button className={`status-pill status-${state}`} onClick={() => setStatusMenu(day)} aria-label={`Manage ${day.name} status`}>{label}</button></div>; })}</section>
    {(data.dailyActivity?.at(-1)?.steps !== undefined || data.dailyActivity?.at(-1)?.activeCalories !== undefined) && <section className="card dashboard activity-card"><span className="eyebrow">DAILY ACTIVITY</span><div className="activity-grid"><span><b>STEPS</b><strong>{data.dailyActivity?.at(-1)?.steps ?? "—"}</strong><small>/ 10,000 goal</small></span><span><b>ACTIVE CALORIES</b><strong>{data.dailyActivity?.at(-1)?.activeCalories ?? "—"}</strong><small>kcal</small></span></div></section>}<section className="card dashboard block-card"><span className="eyebrow">CURRENT BLOCK</span><strong>{programmeName}</strong><p>Week {generated ? snapshot.currentWeek : programmeBlock.weekNumber} of {snapshot.totalWeeks} · {Math.min(completedInBlock, snapshot.totalSessions)} of {snapshot.totalSessions} sessions</p><ProgressBar value={snapshot.progressPercent} label="Current block progress" /><button className="secondary" onClick={() => setBlockOpen(true)}>View Block</button></section>
    {statusMenu && <div className="modal" role="dialog" aria-modal="true" aria-label="Update session status"><section><div className="sheet-heading"><div><span className="eyebrow">SESSION STATUS</span><h2>{statusMenu.name}</h2></div><button className="text-button" onClick={() => setStatusMenu(null)}>Close</button></div><p>Update this scheduled day without shifting the rest of the week.</p><div className="status-options">{([["planned", "Planned"], ["completed", "Completed"], ["missed", "Missed"], ["recovery_rest", "Recovery Rest"], ["rest", "Planned Rest"], ["unplanned_activity", "Unplanned Activity"], ["illness_injury", "Illness / Injury"], ["other", "Other"]] as Array<[SessionStatus, string]>).map(([value, label]) => <button key={value} className="secondary" onClick={() => { updateStatus(statusMenu.id, statusMenu.scheduledDate, value); setStatusMenu(null); }}>{label}</button>)}</div></section></div>}
    {blockOpen && <div className="modal" role="dialog" aria-modal="true" aria-label="Current block details"><section className="block-sheet"><div className="sheet-heading"><div><span className="eyebrow">CURRENT BLOCK</span><h2>{programmeName}</h2></div><button className="text-button" onClick={() => setBlockOpen(false)}>Close</button></div><p className="block-progress">{completedInBlock} of {snapshot.totalSessions} sessions complete</p>{Array.from({ length: snapshot.totalWeeks }, (_, index) => index + 1).map(week => <div className="block-week" key={week}><div><b>Week {week}</b><small>{week === snapshot.currentWeek ? "Current" : week < snapshot.currentWeek ? "Completed" : "Planned"}</small></div>{programmeWeek.map(day => { const done = week === snapshot.currentWeek && (workoutHistory ?? data.workouts).some(workout => workout.origin !== "test" && workout.origin !== "historical" && workout.status === "completed" && workout.plannedSessionId === day.id && workout.scheduledDate); const state = done ? "Completed" : day.status === "rest" ? "Recovery" : week === snapshot.currentWeek && day.day === today.day ? "Current" : "Planned"; return <span key={day.id}><strong>{day.name}</strong><em>{state}</em></span>; })}</div>)}</section></div>}
    {checkInOpen && <DailyCheckInSheet onClose={() => setCheckInOpen(false)} onSave={saveCheckIn} />}
    </>;
}
