"use client";
import { useState } from "react";
import { currentBlock, currentWeek, weightTrend } from "@/lib/domain";
import { loadData, saveData } from "@/lib/storage";
export function DashboardFoundation() {
  const [data, setData] = useState(() => loadData()); const trend = weightTrend(data.bodyMetrics);
  const addMetric = (field: "bodyweight" | "waist") => { const value = window.prompt(`${field === "bodyweight" ? "Bodyweight" : "Waist"} in kg/cm`); if (!value || Number.isNaN(Number(value))) return; const next = { ...data, bodyMetrics: [...data.bodyMetrics, { id: crypto.randomUUID(), date: new Date().toISOString().slice(0, 10), time: new Date().toTimeString().slice(0, 5), [field]: Number(value), source: "manual" as const, origin: "real" as const }] }; saveData(next); setData(next); };
  const addRecovery = () => { const values = ["Energy", "Sleep quality", "Muscle soreness", "Motivation", "General fatigue"].map(label => Number(window.prompt(`${label} (1–5)`))); if (values.some(value => !Number.isFinite(value) || value < 1 || value > 5)) return; const next = { ...data, recoverySnapshots: [...(data.recoverySnapshots ?? []), { id: crypto.randomUUID(), date: new Date().toISOString().slice(0, 10), origin: "real" as const, source: "manual" as const, userReported: true, energy: values[0], sleepQuality: values[1], soreness: values[2], motivation: values[3], fatigue: values[4] }] }; saveData(next); setData(next); };
  return <><section className="card dashboard"><span className="eyebrow">UPCOMING</span>{currentWeek.slice(1).map(day => <div className="plan-row" key={day.id}><b>{["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"][day.day - 1]}</b><span>{day.name}<small>{day.status === "rest" ? "Recovery day" : "Planned session"}</small></span></div>)}</section><section className="card dashboard block-card"><span className="eyebrow">CURRENT BLOCK</span><strong>Strength + Fat Loss</strong><p>Week {currentBlock.weekNumber} of 3 · 0 / 18 sessions</p><button className="secondary">View Block</button></section><section className="card dashboard readiness-card"><span className="eyebrow">READINESS</span><strong>Connect WHOOP</strong><p>Get recovery, sleep and strain data here.</p><button className="secondary">Connect WHOOP</button><button className="secondary" onClick={addRecovery}>Log user-reported recovery</button><button className="text-button">Apple Health</button></section><section className="quick-log"><button className="secondary" onClick={() => addMetric("bodyweight")}>{trend.current ? `${trend.current} kg` : "Log today’s weight"}</button><button className="secondary" onClick={() => addMetric("waist")}>Log waist</button></section></>;
}
