import Link from "next/link";
import { AppShell, EmptyState, PageHeader, Surface } from "@/components/ui";
import type { ClubMemberOperationalRead } from "@/lib/club-operational";
import type { ClubBalanceAccount, ClubOrder } from "@/lib/club-commerce";
import type { ClubClassSession } from "@/lib/club-operations";
import type { Organisation } from "@/lib/club";
export type MemberHubData={organisation:Organisation;profile:ClubMemberOperationalRead;balance?:ClubBalanceAccount;sessions:ClubClassSession[];bookings:Array<{sessionId:string;status:string}>;orders:ClubOrder[]};
export function MemberHub({data}:{data:MemberHubData[]}){if(!data.length)return <AppShell className="module-page member-hub-page member-area-page"><PageHeader title="Member Area"/><Surface><span className="eyebrow">GLOW ZONE</span><h2>Sunbeds at Madhouse Carlton</h2><p className="muted">GLOW ZONE customers can view minutes, packages and safety information.</p><Link className="member-hub-link primary" href="/member-hub/glow-zone"><strong>Open GLOW ZONE</strong><small>View your Glow Zone account</small></Link></Surface><Surface><EmptyState title="Connect your gym">Already a member? Link your membership to R12, or join an onboarded gym to get started.</EmptyState><div className="quick-grid"><Link className="member-hub-link" href="/member-hub/link"><strong>Link existing membership</strong><small>Verify the email held by your gym</small></Link><Link className="member-hub-link" href="/join"><strong>Join a gym</strong><small>Choose an onboarded gym</small></Link></div></Surface></AppShell>;
return <AppShell className="module-page member-hub-page member-area-page"><PageHeader title="Member Area"/><Surface className="member-hub-section"><span className="eyebrow">GLOW ZONE</span><h2>Sunbeds at Madhouse Carlton</h2><p className="muted">Your minutes, packages and safety information.</p><Link className="member-hub-link primary" href={`/member-hub/glow-zone?org=${encodeURIComponent(data[0].organisation.id)}`}><strong>Open GLOW ZONE</strong><small>View Glow Zone</small></Link></Surface>{data.map(item=><Surface className="member-hub-section" key={item.organisation.id}><span className="eyebrow">MEMBERSHIP & ACCESS</span><div className="club-detail-row"><span>{item.organisation.name}</span><strong>{item.profile.memberships.find(m=>m.status==="active")?.productName??"Not currently active"}</strong></div><Link className="member-hub-link" href={`/member-hub/shop?org=${encodeURIComponent(item.organisation.id)}`}>Open member shop</Link></Surface>)}</AppShell>}
