"use client";
import { useState } from "react";
import { applyProgrammeEdit, detectProgrammeEditIntent, planProgrammeEdit, type ProgrammeEditPlan } from "@/lib/programming-v2";
import type { GeneratedProgramme } from "@/lib/programme-generator";
import { saveTrainingProfile } from "@/lib/storage";

export function ProgrammeCoachActions({ programme }: { programme: GeneratedProgramme }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [plan, setPlan] = useState<ProgrammeEditPlan>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const propose = () => { const intent = detectProgrammeEditIntent(query); setPlan(intent ? planProgrammeEdit(programme, intent) : undefined); setMessage(intent ? "" : "Tell Coach what you want to change, for example “more glute work” or “use the rower”."); };
  const apply = async () => { if (!plan || busy) return; setBusy(true); setMessage(""); const next = applyProgrammeEdit(programme, plan); if (!next) { setMessage("That change would leave the programme unbalanced, so it wasn’t applied."); setBusy(false); return; } const edited = { ...next, id: `${programme.id}-edit-${Date.now()}`, name: programme.isLegacy ? "My Personal Programme" : next.name, isLegacy: false }; try { const response = await fetch("/api/training-profile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ trainingProfile: edited.profile, generatedProgramme: edited }) }); const persisted = await response.json().catch(() => null); if (!response.ok || !persisted?.generated_programme) throw new Error(); saveTrainingProfile(edited.profile, persisted.generated_programme); setOpen(false); setPlan(undefined); setQuery(""); window.location.reload(); } catch { setMessage("We couldn’t apply that change. Your current programme is unchanged."); } finally { setBusy(false); } };
  return <>{<button className="secondary" onClick={() => { setOpen(true); setMessage(""); }}>Ask Coach to adjust programme</button>}{open && <div className="modal" role="dialog" aria-modal="true" aria-label="Programme Coach actions"><section><div className="sheet-heading"><div><span className="eyebrow">COACH</span><h2>Adjust your programme</h2></div><button className="text-button" onClick={() => setOpen(false)}>Close</button></div><p>Changes are proposed first and only applied after you approve them.</p><label className="sheet-input">What would you like to change?<input autoFocus value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter") propose(); }} placeholder="More glute work, add hip thrusts…" /></label><button className="secondary" disabled={!query.trim()} onClick={propose}>Review proposal</button>{message && <p role="alert" className="error-text">{message}</p>}{plan && <div className="coach-callout"><span>PERMANENT CHANGE</span><strong>{plan.summary}</strong><small>{plan.rationale}</small><button className="primary" disabled={busy} onClick={() => void apply()}>{busy ? "Applying…" : "Apply change"}</button></div>}</section></div>}</>;
}
