"use client";
import { useEffect, useRef, useState } from "react";
type AlertMode = "silent" | "beep" | "countdown";
function beep() { try { const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); gain.gain.value = 0.04; oscillator.frequency.value = 880; oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.08); } catch { /* optional device capability */ } }
export function RestTimer({ seconds, onSkip }: { seconds: number; onSkip: () => void }) {
  const [target, setTarget] = useState(() => Date.now() + seconds * 1000); const [remaining, setRemaining] = useState(seconds); const [running, setRunning] = useState(true); const [mode, setMode] = useState<AlertMode>(() => { if (typeof window === "undefined") return "beep"; const saved = localStorage.getItem("road-to-12-rest-alert"); return saved === "silent" || saved === "beep" || saved === "countdown" ? saved : "beep"; }); const announced = useRef(false); const countdown = useRef(4);
  const refresh = () => setRemaining(Math.max(0, Math.ceil((target - Date.now()) / 1000)));
  // Timer state is reset when a new rest interval is created by the workout interaction.
  useEffect(() => { queueMicrotask(() => { setTarget(Date.now() + seconds * 1000); setRemaining(seconds); setRunning(true); announced.current = false; countdown.current = 4; }); }, [seconds]);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (!running) return; const tick = () => { const next = Math.max(0, Math.ceil((target - Date.now()) / 1000)); setRemaining(next); if (mode === "countdown" && next > 0 && next <= 3 && next < countdown.current) { beep(); countdown.current = next; } if (next === 0 && !announced.current) { announced.current = true; if (mode !== "silent") beep(); } }; tick(); const id = window.setInterval(tick, 250); const onVisibility = () => { if (document.visibilityState === "visible") refresh(); }; window.addEventListener("focus", refresh); document.addEventListener("visibilitychange", onVisibility); return () => { clearInterval(id); window.removeEventListener("focus", refresh); document.removeEventListener("visibilitychange", onVisibility); }; }, [running, target, mode]);
  const min = Math.floor(remaining / 60); const sec = String(remaining % 60).padStart(2, "0"); const setAlert = (value: AlertMode) => { setMode(value); localStorage.setItem("road-to-12-rest-alert", value); };
  return <section className={`timer ${remaining === 0 ? "timer-complete" : ""}`} aria-live="polite"><div><span className="eyebrow">REST {remaining === 0 ? "COMPLETE" : "TIMER"}</span><strong>{min}:{sec}</strong></div><div className="timer-actions"><button type="button" className="secondary" onClick={() => { setTarget(value => value + 30000); setRemaining(value => value + 30); }}>+30 sec</button><button type="button" className="secondary" onClick={() => { if (running) refresh(); setRunning(value => !value); }}>{running ? "Pause" : "Resume"}</button><button type="button" className="danger" onClick={onSkip}>Skip</button><select aria-label="Rest alert" value={mode} onChange={event => setAlert(event.target.value as AlertMode)}><option value="silent">Silent</option><option value="beep">Beep</option><option value="countdown">Countdown</option></select></div></section>;
}
