"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
type SupplierCapability = "supplier.orders_manage" | "supplier.receive";
async function authorised(org:string,cap:SupplierCapability) { const client=await serverSupabase(); const {data:{user}}=await client.auth.getUser(); if(!user)return; const context=await resolveClubOrganisationContext(client,user.id,org); if(!context||!(await context.repository.hasCapability(org,user.id,cap)))return; return {client,context,user}; }
export async function createSupplierOrderAction(org:string,supplierId:string){const v=await authorised(org,"supplier.orders_manage");if(!v)return {ok:false,error:"Supplier-order access required."};const {data,error}=await v.client.rpc("club_create_supplier_order_batch",{p_organisation_id:org,p_supplier_id:supplierId});if(error)return {ok:false,error:"No outstanding demand could be batched."};revalidatePath("/club/shop/supplier-orders");return {ok:true,batch:data};}
export async function prepareSupplierCycleAction(org:string,supplierId:string){const v=await authorised(org,"supplier.orders_manage");if(!v)return {ok:false,error:"Supplier-order access required."};const {data,error}=await v.client.rpc("club_prepare_supplier_cycle",{p_organisation_id:org,p_supplier_id:supplierId});if(error)return {ok:false,error:"Supplier cycle could not be prepared."};revalidatePath("/club/shop/supplier-orders");return {ok:true,batch:data};}
export async function markSupplierOrderedAction(org:string,batchId:string){const v=await authorised(org,"supplier.orders_manage");if(!v)return {ok:false,error:"Supplier-order access required."};const {data,error}=await v.client.rpc("club_mark_supplier_ordered",{p_organisation_id:org,p_batch_id:batchId});if(error)return {ok:false,error:"Supplier order could not be marked ordered."};revalidatePath("/club/shop/supplier-orders");return {ok:true,batch:data};}
export async function exportSupplierOrderAction(org:string,batchId:string){const v=await authorised(org,"supplier.orders_manage");if(!v)return {ok:false,error:"Supplier-order access required."};const {data,error}=await v.client.rpc("club_get_supplier_order_batch",{p_organisation_id:org,p_batch_id:batchId});if(error||!data)return {ok:false,error:"Supplier order could not be exported."};const payload=data as {batch:{reference:string};supplier:string;lines:Array<Record<string,unknown>>};const esc=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`;const csv=["supplier SKU,barcode,brand,product,variant,size,quantity",...payload.lines.map(line=>[line.supplier_sku,line.barcode,line.brand,line.product,line.variant,line.size,line.quantity].map(esc).join(","))].join("\n");return {ok:true,reference:payload.batch.reference,supplier:payload.supplier,csv};}
export async function receiveSupplierDeliveryAction(org:string,batchId:string,idempotencyKey:string,lines:Array<{batchLineId:string;quantityReceived:number;notes?:string}>){const v=await authorised(org,"supplier.receive");if(!v)return {ok:false,error:"Receiving access required."};const {data,error}=await v.client.rpc("club_receive_supplier_delivery",{p_organisation_id:org,p_batch_id:batchId,p_idempotency_key:idempotencyKey,p_lines:lines});if(error)return {ok:false,error:"Delivery could not be received."};revalidatePath("/club/shop/supplier-orders");revalidatePath("/club/shop/collections");return {ok:true,receipt:data};}
export async function allocateSupplierUnitsAction(org:string,receiptLineId:string,demandId:string,quantity:number){const v=await authorised(org,"supplier.receive");if(!v)return {ok:false,error:"Receiving access required."};const {data,error}=await v.client.rpc("club_allocate_supplier_units",{p_organisation_id:org,p_receipt_line_id:receiptLineId,p_demand_id:demandId,p_quantity:quantity});if(error)return {ok:false,error:"Units could not be allocated."};revalidatePath("/club/shop/supplier-orders");revalidatePath("/club/shop/collections");return {ok:true,demand:data};}
export async function updateReplenishmentLineAction(org:string,lineId:string,quantity:number,allocations:Array<{locationId:string;quantity:number}>){const v=await authorised(org,"supplier.orders_manage");if(!v)return {ok:false,error:"Supplier-order access required."};const {data,error}=await v.client.rpc("club_update_replenishment_line",{p_organisation_id:org,p_batch_line_id:lineId,p_quantity_ordered:quantity,p_allocations:allocations});if(error)return {ok:false,error:"Check the final quantity and destination split."};revalidatePath("/club/shop/supplier-orders");return {ok:true,result:data};}
