import { type ClubProduct, type EntitlementGrant, type Membership, type Organisation, type OrganisationLocation, type OrganisationMember, type GrantSource, type Validity } from "./club";
import type { SupabaseClient } from "@supabase/supabase-js";
import { SupabaseClubRepository, type ClubRepositoryError } from "./supabase-club-repository";
import { madhouseCatalogue, materialiseCatalogueProduct } from "./madhouse-catalogue";
import type { ClubAttendanceState, ClubClassAvailability, ClubClassBooking, ClubClassSession, ClubClassType, ClubCustomer, ClubService, ClubServiceTransaction, CreateClubCustomerInput, CreateClubServiceTransactionInput, SaveClubClassSessionInput, SaveClubClassTypeInput, SaveClubServiceInput, UpdateClubServiceTransactionInput } from "./club-operations";

export type ClubRepository = {
  listOrganisations(): Promise<Organisation[]>; listLocations(organisationId: string): Promise<OrganisationLocation[]>; listProducts(organisationId: string, includeArchived?: boolean): Promise<ClubProduct[]>; listMembers(organisationId: string): Promise<OrganisationMember[]>;
  createProduct(product: Omit<ClubProduct, "id">): Promise<ClubProduct>; updateProduct(id: string, patch: Partial<ClubProduct>): Promise<ClubProduct>; assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }): Promise<{ membership: Membership; grants: EntitlementGrant[] }>;
  listCustomers(organisationId: string): Promise<ClubCustomer[]>; createCustomer(input: CreateClubCustomerInput): Promise<ClubCustomer>; linkCustomerUser(customerId: string, userId: string): Promise<ClubCustomer>;
  listClassTypes(organisationId: string): Promise<ClubClassType[]>; saveClassType(input: SaveClubClassTypeInput): Promise<ClubClassType>;
  listClassSessions(organisationId: string): Promise<ClubClassSession[]>; getClassAvailability(sessionId: string): Promise<ClubClassAvailability>; saveClassSession(input: SaveClubClassSessionInput): Promise<ClubClassSession>;
  listClassBookings(organisationId: string, sessionId?: string): Promise<ClubClassBooking[]>; createClassBooking(input: { sessionId: string; customerId: string; status?: "confirmed" | "waitlisted" }): Promise<ClubClassBooking>; cancelClassBooking(bookingId: string): Promise<ClubClassBooking>; setBookingAttendance(bookingId: string, attendanceState: ClubAttendanceState): Promise<ClubClassBooking>;
  listServices(organisationId: string): Promise<ClubService[]>; saveService(input: SaveClubServiceInput): Promise<ClubService>;
  listServiceTransactions(organisationId: string): Promise<ClubServiceTransaction[]>; createServiceTransaction(input: CreateClubServiceTransactionInput): Promise<ClubServiceTransaction>; updateServiceTransaction(transactionId: string, input: UpdateClubServiceTransactionInput): Promise<ClubServiceTransaction>;
};

export const madhouseFixture: Organisation = { id: "org-madhouse", name: "Madhouse Gym", slug: "madhouse-gym", active: true, branding: { coBranding: "co_branded" } };
export const madhouseLocations: OrganisationLocation[] = [{ id: "loc-rotherham", organisationId: madhouseFixture.id, name: "Rotherham", active: true }, { id: "loc-carlton", organisationId: madhouseFixture.id, name: "Carlton", active: true }];
const fixtureProducts = (): ClubProduct[] => madhouseCatalogue.map((definition, index) => materialiseCatalogueProduct(definition, madhouseFixture.id, `product-${index + 1}`));

export class MemoryClubRepository implements ClubRepository {
  organisations = [madhouseFixture]; locations = [...madhouseLocations]; products = fixtureProducts(); members: OrganisationMember[] = []; memberships: Membership[] = []; grants: EntitlementGrant[] = [];
  customers: ClubCustomer[] = []; classTypes: ClubClassType[] = []; classSessions: ClubClassSession[] = []; classBookings: ClubClassBooking[] = []; services: ClubService[] = []; serviceTransactions: ClubServiceTransaction[] = [];
  async listOrganisations() { return this.organisations.filter(item => item.active); }
  async listLocations(organisationId: string) { return this.locations.filter(item => item.organisationId === organisationId); }
  async listProducts(organisationId: string, includeArchived = false) { return this.products.filter(item => item.organisationId === organisationId && (includeArchived || item.sellable)); }
  async listMembers(organisationId: string) { return this.members.filter(item => item.organisationId === organisationId && item.active); }
  async createProduct(product: Omit<ClubProduct, "id">) { const existing = this.products.find(item => item.organisationId === product.organisationId && item.name === product.name); if (existing) return existing; const created = { ...product, id: `product-${this.products.length + 1}` }; this.products.push(created); return created; }
  async updateProduct(id: string, patch: Partial<ClubProduct>) { const index = this.products.findIndex(item => item.id === id); if (index < 0) throw new Error("product_not_found"); this.products[index] = { ...this.products[index], ...patch }; return this.products[index]; }
  async assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }) { const product = this.products.find(item => item.id === input.productId && item.organisationId === input.organisationId); if (!product) throw new Error("product_not_found"); const holderUserIds = input.holderUserIds?.length ? [...new Set(input.holderUserIds)] : [input.userId]; const membership: Membership = { id: `membership-${this.memberships.length + 1}`, organisationId: input.organisationId, productId: product.id, status: "active", validity: input.validity, source: input.source, holderUserIds }; this.memberships.push(membership); const grants = holderUserIds.flatMap(userId => (product.entitlements ?? []).map((benefit, index) => ({ id: `${membership.id}-${userId}-${index}`, userId, organisationId: input.organisationId, membershipId: membership.id, entitlementKey: benefit.entitlementKey, scope: benefit.scope, locationIds: benefit.locationIds, validity: input.validity, source: input.source, allowance: benefit.allowance, discount: benefit.discount }))); this.grants.push(...grants); return { membership, grants }; }
  async listCustomers(organisationId: string) { return this.customers.filter(item => item.organisationId === organisationId); }
  async createCustomer(input: CreateClubCustomerInput) { const now = new Date().toISOString(); const customer: ClubCustomer = { ...input, id: `customer-${this.customers.length + 1}`, createdAt: now, updatedAt: now }; this.customers.push(customer); return customer; }
  async linkCustomerUser(customerId: string, userId: string) { const customer = this.customers.find(item => item.id === customerId); if (!customer) throw new Error("customer_not_found"); if (customer.userId || this.customers.some(item => item.organisationId === customer.organisationId && item.userId === userId)) throw new Error("customer_link_invalid"); customer.userId = userId; customer.updatedAt = new Date().toISOString(); return customer; }
  async listClassTypes(organisationId: string) { return this.classTypes.filter(item => item.organisationId === organisationId); }
  async saveClassType(input: SaveClubClassTypeInput) { const now = new Date().toISOString(); const existing = input.id ? this.classTypes.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("class_type_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubClassType = { ...input, id: `class-type-${this.classTypes.length + 1}`, createdAt: now, updatedAt: now }; this.classTypes.push(created); return created; }
  async listClassSessions(organisationId: string) { return this.classSessions.filter(item => item.organisationId === organisationId); }
  async getClassAvailability(sessionId: string) { const session = this.classSessions.find(item => item.id === sessionId); if (!session) throw new Error("class_session_not_found"); const confirmedCount = this.classBookings.filter(item => item.sessionId === sessionId && item.status === "confirmed").length; const waitlistedCount = this.classBookings.filter(item => item.sessionId === sessionId && item.status === "waitlisted").length; const spacesRemaining = session.capacity === undefined ? undefined : Math.max(session.capacity - confirmedCount, 0); return { sessionId, ...(session.capacity === undefined ? {} : { capacity: session.capacity }), confirmedCount, ...(spacesRemaining === undefined ? {} : { spacesRemaining }), waitlistedCount, isFull: session.capacity !== undefined && confirmedCount >= session.capacity }; }
  async saveClassSession(input: SaveClubClassSessionInput) { if (!this.locations.some(item => item.id === input.locationId && item.organisationId === input.organisationId) || !this.classTypes.some(item => item.id === input.classTypeId && item.organisationId === input.organisationId)) throw new Error("session_reference_invalid"); const now = new Date().toISOString(); const existing = input.id ? this.classSessions.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("class_session_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubClassSession = { ...input, id: `class-session-${this.classSessions.length + 1}`, createdAt: now, updatedAt: now }; this.classSessions.push(created); return created; }
  async listClassBookings(organisationId: string, sessionId?: string) { return this.classBookings.filter(item => item.organisationId === organisationId && (!sessionId || item.sessionId === sessionId)); }
  async createClassBooking(input: { sessionId: string; customerId: string; status?: "confirmed" | "waitlisted" }) { const session = this.classSessions.find(item => item.id === input.sessionId); const customer = this.customers.find(item => item.id === input.customerId); if (!session || !customer || session.organisationId !== customer.organisationId || session.status !== "scheduled") throw new Error("booking_invalid"); if (this.classBookings.some(item => item.sessionId === input.sessionId && item.customerId === input.customerId && item.status !== "cancelled")) throw new Error("booking_duplicate"); const status = input.status ?? "confirmed"; if (status === "confirmed" && session.capacity !== undefined && this.classBookings.filter(item => item.sessionId === session.id && item.status === "confirmed").length >= session.capacity) throw new Error("booking_capacity"); const now = new Date().toISOString(); const booking: ClubClassBooking = { id: `booking-${this.classBookings.length + 1}`, organisationId: session.organisationId, sessionId: session.id, customerId: customer.id, status, bookedAt: now, attendanceState: "pending", createdAt: now, updatedAt: now }; this.classBookings.push(booking); return booking; }
  async cancelClassBooking(bookingId: string) { const booking = this.classBookings.find(item => item.id === bookingId); if (!booking) throw new Error("booking_not_found"); booking.status = "cancelled"; booking.cancelledAt = new Date().toISOString(); booking.updatedAt = booking.cancelledAt; return booking; }
  async setBookingAttendance(bookingId: string, attendanceState: ClubAttendanceState) { const booking = this.classBookings.find(item => item.id === bookingId); if (!booking || booking.status !== "confirmed") throw new Error("attendance_invalid"); booking.attendanceState = attendanceState; booking.updatedAt = new Date().toISOString(); return booking; }
  async listServices(organisationId: string) { return this.services.filter(item => item.organisationId === organisationId); }
  async saveService(input: SaveClubServiceInput) { if (input.locationId && !this.locations.some(item => item.id === input.locationId && item.organisationId === input.organisationId)) throw new Error("service_location_invalid"); const now = new Date().toISOString(); const existing = input.id ? this.services.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("service_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubService = { ...input, id: `service-${this.services.length + 1}`, createdAt: now, updatedAt: now }; this.services.push(created); return created; }
  async listServiceTransactions(organisationId: string) { return this.serviceTransactions.filter(item => item.organisationId === organisationId); }
  async createServiceTransaction(input: CreateClubServiceTransactionInput) { const service = this.services.find(item => item.id === input.serviceId && item.organisationId === input.organisationId); const location = this.locations.find(item => item.id === input.locationId && item.organisationId === input.organisationId); const customerValid = !input.customerId || this.customers.some(item => item.id === input.customerId && item.organisationId === input.organisationId); if (!service || !location || !customerValid || (service.locationId && service.locationId !== input.locationId)) throw new Error("service_transaction_invalid"); const now = new Date().toISOString(); const transaction: ClubServiceTransaction = { ...input, id: `service-transaction-${this.serviceTransactions.length + 1}`, createdAt: now, updatedAt: now }; this.serviceTransactions.push(transaction); return transaction; }
  async updateServiceTransaction(transactionId: string, input: UpdateClubServiceTransactionInput) { const transaction = this.serviceTransactions.find(item => item.id === transactionId); if (!transaction) throw new Error("service_transaction_not_found"); Object.assign(transaction, input, { updatedAt: new Date().toISOString() }); return transaction; }
}
let memoryInstance: MemoryClubRepository | undefined;
export function memoryClubRepository(): MemoryClubRepository { if (!memoryInstance) memoryInstance = new MemoryClubRepository(); return memoryInstance; }
export function selectClubRepository(options: { client?: SupabaseClient; nodeEnv?: string; schemaEnabled?: string }): ClubRepository {
  if (options.nodeEnv !== "production") return memoryClubRepository();
  if (options.schemaEnabled !== "true" || !options.client) { const error = new Error("Club data is unavailable") as ClubRepositoryError; error.code = "UNAVAILABLE"; error.operation = "select_repository"; throw error; }
  return new SupabaseClubRepository(options.client);
}
export function clubRepository(client?: SupabaseClient): ClubRepository { return selectClubRepository({ client, nodeEnv: process.env.NODE_ENV, schemaEnabled: process.env.R12_CLUB_SCHEMA_ENABLED }); }
export { SupabaseClubRepository } from "./supabase-club-repository";
