import { parseCsvRecords } from "./club-csv";

export type SupplierProduct = { supplier: string; supplierSku?: string; barcode?: string; brand?: string; name: string; variant?: string; size?: string; description?: string; category?: string; wholesaleCost?: string; rrp?: string; availability?: string; imageUrl?: string; supplierUrl?: string; discontinued: boolean };
export type SupplierImportResult = { rows: SupplierProduct[]; invalid: Array<{ row: number; reason: string }>; duplicates: number[] };

const text = (value: string | undefined) => value?.trim() || undefined;
export function parseSupplierCsv(input: string, supplier: string): SupplierImportResult {
  const parsed = parseCsvRecords(input);
  const rows: SupplierProduct[] = []; const invalid: SupplierImportResult["invalid"] = []; const duplicates: number[] = []; const seen = new Set<string>();
  parsed.forEach((raw, index) => { const row = raw as unknown as Record<string, string>; const name = text(row.name ?? row.product ?? row.product_name); const sku = text(row.supplier_sku ?? row.sku ?? row.supplier_product_code); const barcode = text(row.barcode ?? row.ean ?? row.upc); if (!name) { invalid.push({ row: index + 2, reason: "Product name is required" }); return; } const key = sku ? `sku:${sku}` : barcode ? `barcode:${barcode}` : `name:${name.toLowerCase()}`; if (seen.has(key)) duplicates.push(index + 2); seen.add(key); rows.push({ supplier, ...(sku ? { supplierSku: sku } : {}), ...(barcode ? { barcode } : {}), ...(text(row.brand) ? { brand: text(row.brand) } : {}), name, ...(text(row.variant ?? row.flavour) ? { variant: text(row.variant ?? row.flavour) } : {}), ...(text(row.size) ? { size: text(row.size) } : {}), ...(text(row.description) ? { description: text(row.description) } : {}), ...(text(row.category) ? { category: text(row.category) } : {}), ...(text(row.wholesale_cost ?? row.cost ?? row.net_cost) ? { wholesaleCost: text(row.wholesale_cost ?? row.cost ?? row.net_cost) } : {}), ...(text(row.rrp ?? row.recommended_retail_price) ? { rrp: text(row.rrp ?? row.recommended_retail_price) } : {}), ...(text(row.availability ?? row.stock) ? { availability: text(row.availability ?? row.stock) } : {}), ...(text(row.image_url) ? { imageUrl: text(row.image_url) } : {}), ...(text(row.supplier_url ?? row.product_url) ? { supplierUrl: text(row.supplier_url ?? row.product_url) } : {}), discontinued: /^(true|yes|1)$/i.test(row.discontinued ?? "") }); });
  return { rows, invalid, duplicates };
}

export type PaymentEligibility = { configured: boolean; enabledChannels: string[]; currency: string; minimumMinor?: number; maximumMinor?: number; allowedCategories?: string[] };
export function paymentMethodEligible(rule: PaymentEligibility, input: { amountMinor: number; channel: string; currency: string; category?: string }) { return rule.configured && rule.currency === input.currency && rule.enabledChannels.includes(input.channel) && (rule.minimumMinor === undefined || input.amountMinor >= rule.minimumMinor) && (rule.maximumMinor === undefined || input.amountMinor <= rule.maximumMinor) && (!rule.allowedCategories?.length || Boolean(input.category && rule.allowedCategories.includes(input.category))); }
