export type ReconciliationOrder = { id: string; created_at: string; location_id?: string | null; status: string; subtotal_minor: number; discount_minor: number; total_minor: number; currency: string; channel?: string };
export type ReconciliationPayment = { id: string; order_id: string; created_at: string; method: string; amount_minor: number; status: string };
export type ReconciliationSummary = { grossMinor: number; discountMinor: number; netMinor: number; paidMinor: number; cashMinor: number; balanceMinor: number; externalMinor: number; refundMinor: number; unpaidMinor: number; pendingMinor: number; failedMinor: number; compValueMinor: number };
export function summariseReconciliation(orders: ReconciliationOrder[], payments: ReconciliationPayment[], refunds: Array<{ amount_minor: number; order_id: string }> = []): ReconciliationSummary {
  const summary: ReconciliationSummary = { grossMinor: 0, discountMinor: 0, netMinor: 0, paidMinor: 0, cashMinor: 0, balanceMinor: 0, externalMinor: 0, refundMinor: 0, unpaidMinor: 0, pendingMinor: 0, failedMinor: 0, compValueMinor: 0 };
  const byOrder = new Map(orders.map(order => [order.id, order]));
  for (const order of orders) { summary.grossMinor += order.subtotal_minor; summary.discountMinor += order.discount_minor; summary.netMinor += order.total_minor; if (order.total_minor === 0 && order.discount_minor > 0) summary.compValueMinor += order.discount_minor; if (order.status === "pending_payment" || order.status === "draft") summary.unpaidMinor += order.total_minor; }
  for (const payment of payments) { if (payment.status === "paid" && byOrder.has(payment.order_id)) { summary.paidMinor += payment.amount_minor; if (payment.method === "cash") summary.cashMinor += payment.amount_minor; else if (payment.method === "balance") summary.balanceMinor += payment.amount_minor; else summary.externalMinor += payment.amount_minor; } else if (payment.status === "pending") summary.pendingMinor += payment.amount_minor; else if (payment.status === "failed") summary.failedMinor += payment.amount_minor; }
  summary.refundMinor = refunds.reduce((sum, refund) => sum + (byOrder.has(refund.order_id) ? refund.amount_minor : 0), 0);
  return summary;
}
export function reconciliationState(order: ReconciliationOrder, payments: ReconciliationPayment[]): "reconciled" | "unpaid" | "pending" | "failed" | "comp" { if (order.total_minor === 0 && order.discount_minor > 0) return "comp"; const related = payments.filter(payment => payment.order_id === order.id); if (related.some(payment => payment.status === "paid")) return "reconciled"; if (related.some(payment => payment.status === "pending")) return "pending"; if (related.some(payment => payment.status === "failed")) return "failed"; return "unpaid"; }
export function reconciliationCsv(orders: ReconciliationOrder[], payments: ReconciliationPayment[]): string { const lines = ["timestamp,reference,location,transaction_type,gross,discount,net,payment_method,payment_state,reconciliation_state"]; return lines.concat(orders.map(order => { const payment = payments.find(item => item.order_id === order.id); return [order.created_at,order.id,order.location_id ?? "", "sale",(order.subtotal_minor/100).toFixed(2),(order.discount_minor/100).toFixed(2),(order.total_minor/100).toFixed(2),payment?.method ?? "",payment?.status ?? "unpaid",reconciliationState(order,payments)].map(value => `"${String(value).replaceAll('"','""')}"`).join(","); })).join("\n"); }
