import { type ClubProduct, type EntitlementGrant, type Membership, type Organisation, type OrganisationLocation, type OrganisationMember, type ClubRole, type GrantSource, type Validity } from "./club";
import type { SupabaseClient } from "@supabase/supabase-js";
import { SupabaseClubRepository, type ClubRepositoryError } from "./supabase-club-repository";
import { madhouseCatalogue, materialiseCatalogueProduct } from "./madhouse-catalogue";
import type { ClubAttendanceState, ClubClassAvailability, ClubClassBooking, ClubClassSession, ClubClassType, ClubCustomer, ClubService, ClubServiceTransaction, CreateClubCustomerInput, CreateClubServiceTransactionInput, SaveClubClassSessionInput, SaveClubClassTypeInput, SaveClubServiceInput, UpdateClubServiceTransactionInput } from "./club-operations";
import type { ClubBalanceAccount, ClubBalanceEntry, ClubCommerceProduct, ClubOrder, ClubPayment, ClubStockMovement, SaveClubCommerceProductInput } from "./club-commerce";
import type { ClubCashDeclaration, ClubCashDeclarationPurpose, ClubMembershipInitialCharge, ClubPromotion, ClubPromotionEffect, ClubPromotionRedemption, ClubServiceCreditAccount, ClubServiceCreditEntry } from "./club-commercial-rules";

export type ClubRepository = {
  listOrganisations(): Promise<Organisation[]>; listLocations(organisationId: string): Promise<OrganisationLocation[]>; listProducts(organisationId: string, includeArchived?: boolean): Promise<ClubProduct[]>; listMembers(organisationId: string): Promise<OrganisationMember[]>;
  createProduct(product: Omit<ClubProduct, "id">): Promise<ClubProduct>; updateProduct(id: string, patch: Partial<ClubProduct>): Promise<ClubProduct>; assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }): Promise<{ membership: Membership; grants: EntitlementGrant[] }>;
  listCustomers(organisationId: string): Promise<ClubCustomer[]>; createCustomer(input: CreateClubCustomerInput): Promise<ClubCustomer>; linkCustomerUser(customerId: string, userId: string): Promise<ClubCustomer>;
  listClassTypes(organisationId: string): Promise<ClubClassType[]>; saveClassType(input: SaveClubClassTypeInput): Promise<ClubClassType>;
  listClassSessions(organisationId: string): Promise<ClubClassSession[]>; getClassAvailability(sessionId: string): Promise<ClubClassAvailability>; saveClassSession(input: SaveClubClassSessionInput): Promise<ClubClassSession>;
  listClassBookings(organisationId: string, sessionId?: string): Promise<ClubClassBooking[]>; createClassBooking(input: { sessionId: string; customerId: string; status?: "confirmed" | "waitlisted" }): Promise<ClubClassBooking>; cancelClassBooking(bookingId: string): Promise<ClubClassBooking>; setBookingAttendance(bookingId: string, attendanceState: ClubAttendanceState): Promise<ClubClassBooking>;
  listServices(organisationId: string): Promise<ClubService[]>; saveService(input: SaveClubServiceInput): Promise<ClubService>;
  listServiceTransactions(organisationId: string): Promise<ClubServiceTransaction[]>; createServiceTransaction(input: CreateClubServiceTransactionInput): Promise<ClubServiceTransaction>; updateServiceTransaction(transactionId: string, input: UpdateClubServiceTransactionInput): Promise<ClubServiceTransaction>;
  listCommerceProducts(organisationId: string): Promise<ClubCommerceProduct[]>; saveCommerceProduct(input: SaveClubCommerceProductInput): Promise<ClubCommerceProduct>; listOrders(organisationId: string): Promise<ClubOrder[]>; getBalanceAccount(organisationId: string, userId: string): Promise<ClubBalanceAccount | undefined>;
  createCommerceOrder(input: { organisationId: string; locationId?: string; customerId?: string; userId?: string; channel: string; currency: string; items: Array<{ productId: string; quantity: number }>; idempotencyKey?: string }): Promise<ClubOrder>;
  recordCashPayment(orderId: string, amountMinor: number, idempotencyKey?: string): Promise<ClubPayment>; creditBalance(input: { organisationId: string; customerId?: string; userId?: string; currency: string; amountMinor: number; entryType?: string; reason?: string; idempotencyKey?: string; actorRole?: ClubRole }): Promise<ClubBalanceEntry>; spendBalance(orderId: string, amountMinor: number, idempotencyKey: string): Promise<ClubBalanceEntry>; adjustInventory(input: { organisationId: string; locationId: string; productId: string; movementType: string; quantityDelta: number; reason?: string; idempotencyKey?: string }): Promise<ClubStockMovement>;
  declareCash(input: { organisationId: string; locationId?: string; purpose: string; userId?: string; customerId?: string; orderId?: string; membershipId?: string; amountMinor: number; currency: string; idempotencyKey: string }): Promise<ClubCashDeclaration>;
  reconcileCash(id: string, status: "confirmed" | "rejected" | "discrepancy", notes?: string, discrepancyMinor?: number): Promise<ClubCashDeclaration>;
  grantServiceCredit(input: { organisationId: string; userId?: string; customerId?: string; creditKey: string; unit: string; quantity: number; entryType?: string; idempotencyKey?: string }): Promise<ClubServiceCreditEntry>;
  spendServiceCredit(input: { accountId: string; quantity: number; serviceId?: string; idempotencyKey: string }): Promise<ClubServiceCreditEntry>;
  saveMembershipInitialCharge(input: Omit<ClubMembershipInitialCharge, "id" | "createdAt" | "updatedAt"> & { id?: string }): Promise<ClubMembershipInitialCharge>;
  savePromotion(input: Omit<ClubPromotion, "id" | "createdAt" | "updatedAt"> & { id?: string; effects?: ClubPromotionEffect[] }): Promise<ClubPromotion>;
  listPromotionRedemptions(organisationId: string, promotionId?: string): Promise<ClubPromotionRedemption[]>;
};

export const madhouseFixture: Organisation = { id: "org-madhouse", name: "Madhouse Gym", slug: "madhouse-gym", active: true, branding: { coBranding: "co_branded" } };
export const madhouseLocations: OrganisationLocation[] = [{ id: "loc-rotherham", organisationId: madhouseFixture.id, name: "Rotherham", active: true }, { id: "loc-carlton", organisationId: madhouseFixture.id, name: "Carlton", active: true }];
const fixtureProducts = (): ClubProduct[] => madhouseCatalogue.map((definition, index) => materialiseCatalogueProduct(definition, madhouseFixture.id, `product-${index + 1}`));

export class MemoryClubRepository implements ClubRepository {
  organisations = [madhouseFixture]; locations = [...madhouseLocations]; products = fixtureProducts(); members: OrganisationMember[] = []; memberships: Membership[] = []; grants: EntitlementGrant[] = [];
  customers: ClubCustomer[] = []; classTypes: ClubClassType[] = []; classSessions: ClubClassSession[] = []; classBookings: ClubClassBooking[] = []; services: ClubService[] = []; serviceTransactions: ClubServiceTransaction[] = []; commerceProducts: ClubCommerceProduct[] = []; orders: ClubOrder[] = []; payments: ClubPayment[] = []; balanceAccounts: ClubBalanceAccount[] = []; balanceEntries: ClubBalanceEntry[] = []; stockMovements: ClubStockMovement[] = [];
  cashDeclarations: ClubCashDeclaration[] = []; serviceCreditAccounts: ClubServiceCreditAccount[] = []; serviceCreditEntries: ClubServiceCreditEntry[] = []; membershipInitialCharges: ClubMembershipInitialCharge[] = []; promotions: ClubPromotion[] = []; promotionEffects: ClubPromotionEffect[] = []; promotionRedemptions: ClubPromotionRedemption[] = [];
  async listOrganisations() { return this.organisations.filter(item => item.active); }
  async listLocations(organisationId: string) { return this.locations.filter(item => item.organisationId === organisationId); }
  async listProducts(organisationId: string, includeArchived = false) { return this.products.filter(item => item.organisationId === organisationId && (includeArchived || item.sellable)); }
  async listMembers(organisationId: string) { return this.members.filter(item => item.organisationId === organisationId && item.active); }
  async createProduct(product: Omit<ClubProduct, "id">) { const existing = this.products.find(item => item.organisationId === product.organisationId && item.name === product.name); if (existing) return existing; const created = { ...product, id: `product-${this.products.length + 1}` }; this.products.push(created); return created; }
  async updateProduct(id: string, patch: Partial<ClubProduct>) { const index = this.products.findIndex(item => item.id === id); if (index < 0) throw new Error("product_not_found"); this.products[index] = { ...this.products[index], ...patch }; return this.products[index]; }
  async assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }) { const product = this.products.find(item => item.id === input.productId && item.organisationId === input.organisationId); if (!product) throw new Error("product_not_found"); const holderUserIds = input.holderUserIds?.length ? [...new Set(input.holderUserIds)] : [input.userId]; const membership: Membership = { id: `membership-${this.memberships.length + 1}`, organisationId: input.organisationId, productId: product.id, status: "active", validity: input.validity, source: input.source, holderUserIds }; this.memberships.push(membership); const grants = holderUserIds.flatMap(userId => (product.entitlements ?? []).map((benefit, index) => ({ id: `${membership.id}-${userId}-${index}`, userId, organisationId: input.organisationId, membershipId: membership.id, entitlementKey: benefit.entitlementKey, scope: benefit.scope, locationIds: benefit.locationIds, validity: input.validity, source: input.source, allowance: benefit.allowance, discount: benefit.discount }))); this.grants.push(...grants); return { membership, grants }; }
  async listCustomers(organisationId: string) { return this.customers.filter(item => item.organisationId === organisationId); }
  async createCustomer(input: CreateClubCustomerInput) { const now = new Date().toISOString(); const customer: ClubCustomer = { ...input, id: `customer-${this.customers.length + 1}`, createdAt: now, updatedAt: now }; this.customers.push(customer); return customer; }
  async linkCustomerUser(customerId: string, userId: string) { const customer = this.customers.find(item => item.id === customerId); if (!customer) throw new Error("customer_not_found"); if (customer.userId || this.customers.some(item => item.organisationId === customer.organisationId && item.userId === userId)) throw new Error("customer_link_invalid"); customer.userId = userId; customer.updatedAt = new Date().toISOString(); return customer; }
  async listClassTypes(organisationId: string) { return this.classTypes.filter(item => item.organisationId === organisationId); }
  async saveClassType(input: SaveClubClassTypeInput) { const now = new Date().toISOString(); const existing = input.id ? this.classTypes.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("class_type_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubClassType = { ...input, id: `class-type-${this.classTypes.length + 1}`, createdAt: now, updatedAt: now }; this.classTypes.push(created); return created; }
  async listClassSessions(organisationId: string) { return this.classSessions.filter(item => item.organisationId === organisationId); }
  async getClassAvailability(sessionId: string) { const session = this.classSessions.find(item => item.id === sessionId); if (!session) throw new Error("class_session_not_found"); const confirmedCount = this.classBookings.filter(item => item.sessionId === sessionId && item.status === "confirmed").length; const waitlistedCount = this.classBookings.filter(item => item.sessionId === sessionId && item.status === "waitlisted").length; const spacesRemaining = session.capacity === undefined ? undefined : Math.max(session.capacity - confirmedCount, 0); return { sessionId, ...(session.capacity === undefined ? {} : { capacity: session.capacity }), confirmedCount, ...(spacesRemaining === undefined ? {} : { spacesRemaining }), waitlistedCount, isFull: session.capacity !== undefined && confirmedCount >= session.capacity }; }
  async saveClassSession(input: SaveClubClassSessionInput) { if (!this.locations.some(item => item.id === input.locationId && item.organisationId === input.organisationId) || !this.classTypes.some(item => item.id === input.classTypeId && item.organisationId === input.organisationId)) throw new Error("session_reference_invalid"); const now = new Date().toISOString(); const existing = input.id ? this.classSessions.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("class_session_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubClassSession = { ...input, id: `class-session-${this.classSessions.length + 1}`, createdAt: now, updatedAt: now }; this.classSessions.push(created); return created; }
  async listClassBookings(organisationId: string, sessionId?: string) { return this.classBookings.filter(item => item.organisationId === organisationId && (!sessionId || item.sessionId === sessionId)); }
  async createClassBooking(input: { sessionId: string; customerId: string; status?: "confirmed" | "waitlisted" }) { const session = this.classSessions.find(item => item.id === input.sessionId); const customer = this.customers.find(item => item.id === input.customerId); if (!session || !customer || session.organisationId !== customer.organisationId || session.status !== "scheduled") throw new Error("booking_invalid"); if (this.classBookings.some(item => item.sessionId === input.sessionId && item.customerId === input.customerId && item.status !== "cancelled")) throw new Error("booking_duplicate"); const status = input.status ?? "confirmed"; if (status === "confirmed" && session.capacity !== undefined && this.classBookings.filter(item => item.sessionId === session.id && item.status === "confirmed").length >= session.capacity) throw new Error("booking_capacity"); const now = new Date().toISOString(); const booking: ClubClassBooking = { id: `booking-${this.classBookings.length + 1}`, organisationId: session.organisationId, sessionId: session.id, customerId: customer.id, status, bookedAt: now, attendanceState: "pending", createdAt: now, updatedAt: now }; this.classBookings.push(booking); return booking; }
  async cancelClassBooking(bookingId: string) { const booking = this.classBookings.find(item => item.id === bookingId); if (!booking) throw new Error("booking_not_found"); booking.status = "cancelled"; booking.cancelledAt = new Date().toISOString(); booking.updatedAt = booking.cancelledAt; return booking; }
  async setBookingAttendance(bookingId: string, attendanceState: ClubAttendanceState) { const booking = this.classBookings.find(item => item.id === bookingId); if (!booking || booking.status !== "confirmed") throw new Error("attendance_invalid"); booking.attendanceState = attendanceState; booking.updatedAt = new Date().toISOString(); return booking; }
  async listServices(organisationId: string) { return this.services.filter(item => item.organisationId === organisationId); }
  async saveService(input: SaveClubServiceInput) { if (input.locationId && !this.locations.some(item => item.id === input.locationId && item.organisationId === input.organisationId)) throw new Error("service_location_invalid"); const now = new Date().toISOString(); const existing = input.id ? this.services.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("service_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubService = { ...input, id: `service-${this.services.length + 1}`, createdAt: now, updatedAt: now }; this.services.push(created); return created; }
  async listServiceTransactions(organisationId: string) { return this.serviceTransactions.filter(item => item.organisationId === organisationId); }
  async createServiceTransaction(input: CreateClubServiceTransactionInput) { const service = this.services.find(item => item.id === input.serviceId && item.organisationId === input.organisationId); const location = this.locations.find(item => item.id === input.locationId && item.organisationId === input.organisationId); const customerValid = !input.customerId || this.customers.some(item => item.id === input.customerId && item.organisationId === input.organisationId); if (!service || !location || !customerValid || (service.locationId && service.locationId !== input.locationId)) throw new Error("service_transaction_invalid"); const now = new Date().toISOString(); const transaction: ClubServiceTransaction = { ...input, id: `service-transaction-${this.serviceTransactions.length + 1}`, createdAt: now, updatedAt: now }; this.serviceTransactions.push(transaction); return transaction; }
  async updateServiceTransaction(transactionId: string, input: UpdateClubServiceTransactionInput) { const transaction = this.serviceTransactions.find(item => item.id === transactionId); if (!transaction) throw new Error("service_transaction_not_found"); Object.assign(transaction, input, { updatedAt: new Date().toISOString() }); return transaction; }
  async listCommerceProducts(organisationId: string) { return this.commerceProducts.filter(item => item.organisationId === organisationId && item.active); }
  async saveCommerceProduct(input: SaveClubCommerceProductInput) { const now = new Date().toISOString(); const existing = input.id ? this.commerceProducts.find(item => item.id === input.id && item.organisationId === input.organisationId) : undefined; if (input.id && !existing) throw new Error("commerce_product_not_found"); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubCommerceProduct = { ...input, id: `retail-${this.commerceProducts.length + 1}`, createdAt: now, updatedAt: now }; this.commerceProducts.push(created); return created; }
  async listOrders(organisationId: string) { return this.orders.filter(item => item.organisationId === organisationId); }
  async getBalanceAccount(organisationId: string, userId: string) { return this.balanceAccounts.find(item => item.organisationId === organisationId && item.userId === userId); }
  async createCommerceOrder(input: { organisationId: string; locationId?: string; customerId?: string; userId?: string; channel: string; currency: string; items: Array<{ productId: string; quantity: number }>; idempotencyKey?: string }) { const existing = input.idempotencyKey && this.orders.find(item => item.organisationId === input.organisationId && item.idempotencyKey === input.idempotencyKey); if (existing) { const sameItems = existing.items.length === input.items.length && existing.items.every((item, index) => item.productId === input.items[index]?.productId && item.quantity === input.items[index]?.quantity); if (existing.userId !== input.userId || existing.customerId !== input.customerId || existing.locationId !== input.locationId || existing.channel !== input.channel || existing.currency !== input.currency || !sameItems) throw new Error("idempotency_conflict"); return existing; } if (input.userId && input.customerId && !this.customers.some(customer => customer.id === input.customerId && customer.organisationId === input.organisationId && customer.userId === input.userId)) throw new Error("customer_not_owned"); const products = input.items.map(item => { const product = this.commerceProducts.find(candidate => candidate.id === item.productId && candidate.organisationId === input.organisationId && candidate.active); if (!product || item.quantity <= 0) throw new Error("commerce_order_invalid"); return { product, quantity: item.quantity }; }); const now = new Date().toISOString(); const orderId = `order-${this.orders.length + 1}`; const orderItems = products.map((item, index) => ({ id: `${orderId}-item-${index + 1}`, orderId, productId: item.product.id, productName: item.product.name, ...(item.product.sku ? { sku: item.product.sku } : {}), quantity: item.quantity, unitPriceMinor: item.product.sellPriceMinor, lineTotalMinor: item.product.sellPriceMinor * item.quantity, stockTracked: item.product.stockTracked })); const subtotalMinor = orderItems.reduce((sum, item) => sum + item.lineTotalMinor, 0); const order: ClubOrder = { id: orderId, organisationId: input.organisationId, ...(input.locationId ? { locationId: input.locationId } : {}), ...(input.customerId ? { customerId: input.customerId } : {}), ...(input.userId ? { userId: input.userId } : {}), channel: input.channel as ClubOrder["channel"], status: "pending_payment", currency: input.currency, subtotalMinor, discountMinor: 0, totalMinor: subtotalMinor, ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), items: orderItems, createdAt: now, updatedAt: now }; this.orders.push(order); return order; }
  async recordCashPayment(orderId: string, amountMinor: number, idempotencyKey?: string) { const order = this.orders.find(item => item.id === orderId); if (!order) throw new Error("order_not_found"); const existing = idempotencyKey ? this.payments.find(item => item.organisationId === order.organisationId && item.externalReference === idempotencyKey) : undefined; if (existing) { if (existing.orderId !== orderId) throw new Error("idempotency_conflict"); return existing; } if (order.status !== "pending_payment") throw new Error("order_not_awaiting_settlement"); if (amountMinor !== order.totalMinor) throw new Error("payment_amount_invalid"); const now = new Date().toISOString(); const payment: ClubPayment = { id: `payment-${orderId}`, orderId, organisationId: order.organisationId, method: "cash", ...(idempotencyKey ? { externalReference: idempotencyKey } : {}), amountMinor, currency: order.currency, status: "paid", createdAt: now, updatedAt: now }; this.payments.push(payment); order.status = "paid"; for (const item of order.items.filter(item => item.stockTracked)) this.stockMovements.push({ id: `stock-${this.stockMovements.length + 1}`, organisationId: order.organisationId, locationId: order.locationId ?? "", productId: item.productId, movementType: "sale", quantityDelta: -item.quantity, orderId: order.id, ...(idempotencyKey ? { idempotencyKey: `${idempotencyKey}:${item.id}` } : {}), occurredAt: now }); return payment; }
  async creditBalance(input: { organisationId: string; customerId?: string; userId?: string; currency: string; amountMinor: number; entryType?: string; reason?: string; idempotencyKey?: string; actorRole?: ClubRole }) { if (!input.actorRole || !["gym_staff", "gym_admin", "owner"].includes(input.actorRole)) throw new Error("balance_credit_forbidden"); let account = this.balanceAccounts.find(item => item.organisationId === input.organisationId && ((input.userId && item.userId === input.userId) || (input.customerId && item.customerId === input.customerId))); if (!account) { account = { id: `balance-${this.balanceAccounts.length + 1}`, organisationId: input.organisationId, ...(input.customerId ? { customerId: input.customerId } : {}), ...(input.userId ? { userId: input.userId } : {}), currency: input.currency, status: "active", balanceMinor: 0 }; this.balanceAccounts.push(account); } account.balanceMinor += input.amountMinor; const entry: ClubBalanceEntry = { id: `balance-entry-${this.balanceEntries.length + 1}`, accountId: account.id, organisationId: input.organisationId, entryType: (input.entryType ?? "top_up") as ClubBalanceEntry["entryType"], amountDeltaMinor: input.amountMinor, balanceAfterMinor: account.balanceMinor, ...(input.reason ? { reason: input.reason } : {}), createdAt: new Date().toISOString() }; this.balanceEntries.push(entry); return entry; }
  async spendBalance(orderId: string, amountMinor: number, idempotencyKey: string) { const order = this.orders.find(item => item.id === orderId); if (!order) throw new Error("order_not_found"); const account = this.balanceAccounts.find(item => item.organisationId === order.organisationId && item.userId === order.userId); const existing = this.balanceEntries.find(item => item.organisationId === order.organisationId && item.idempotencyKey === idempotencyKey); if (existing) { if (!account || existing.accountId !== account.id || existing.orderId !== orderId || existing.entryType !== "purchase") throw new Error("idempotency_conflict"); return existing; } if (order.status !== "pending_payment") throw new Error("order_not_awaiting_settlement"); if (amountMinor !== order.totalMinor) throw new Error("balance_amount_invalid"); if (!account || account.balanceMinor < amountMinor) throw new Error("insufficient_balance"); const now = new Date().toISOString(); account.balanceMinor -= amountMinor; const entry: ClubBalanceEntry = { id: `balance-entry-${this.balanceEntries.length + 1}`, accountId: account.id, organisationId: order.organisationId, entryType: "purchase", amountDeltaMinor: -amountMinor, balanceAfterMinor: account.balanceMinor, orderId, idempotencyKey, createdAt: now }; this.balanceEntries.push(entry); order.status = "paid"; for (const item of order.items.filter(item => item.stockTracked)) this.stockMovements.push({ id: `stock-${this.stockMovements.length + 1}`, organisationId: order.organisationId, locationId: order.locationId ?? "", productId: item.productId, movementType: "sale", quantityDelta: -item.quantity, orderId: order.id, idempotencyKey: `${idempotencyKey}:${item.id}`, occurredAt: now }); return entry; }
  async adjustInventory(input: { organisationId: string; locationId: string; productId: string; movementType: string; quantityDelta: number; reason?: string; idempotencyKey?: string }) { const existing = input.idempotencyKey && this.stockMovements.find(item => item.organisationId === input.organisationId && item.idempotencyKey === input.idempotencyKey); if (existing) return existing; const movement: ClubStockMovement = { id: `stock-${this.stockMovements.length + 1}`, ...input, movementType: input.movementType as ClubStockMovement["movementType"], ...(input.reason ? { reason: input.reason } : {}), ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), occurredAt: new Date().toISOString() }; this.stockMovements.push(movement); return movement; }
  async declareCash(input: Parameters<ClubRepository["declareCash"]>[0]) { const existing = this.cashDeclarations.find(item => item.organisationId === input.organisationId && item.idempotencyKey === input.idempotencyKey); if (existing) return existing; if (!input.userId && !input.customerId) throw new Error("cash_declaration_identity_required"); const now = new Date().toISOString(); const declaration: ClubCashDeclaration = { id: `cash-declaration-${this.cashDeclarations.length + 1}`, organisationId: input.organisationId, ...(input.locationId ? { locationId: input.locationId } : {}), purpose: input.purpose as ClubCashDeclarationPurpose, ...(input.userId ? { userId: input.userId } : {}), ...(input.customerId ? { customerId: input.customerId } : {}), ...(input.orderId ? { orderId: input.orderId } : {}), ...(input.membershipId ? { membershipId: input.membershipId } : {}), declaredAmountMinor: input.amountMinor, currency: input.currency, status: "declared", declaredAt: now, ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), createdAt: now, updatedAt: now }; this.cashDeclarations.push(declaration); return declaration; }
  async reconcileCash(id: string, status: "confirmed" | "rejected" | "discrepancy", notes?: string, discrepancyMinor?: number) { const declaration = this.cashDeclarations.find(item => item.id === id); if (!declaration || declaration.status !== "declared") throw new Error("cash_declaration_invalid"); declaration.status = status; declaration.confirmedAt = new Date().toISOString(); declaration.confirmedBy = "staff"; if (notes) declaration.notes = notes; if (discrepancyMinor !== undefined) declaration.discrepancyMinor = discrepancyMinor; declaration.updatedAt = declaration.confirmedAt; return declaration; }
  async grantServiceCredit(input: Parameters<ClubRepository["grantServiceCredit"]>[0]) { if (!input.userId && !input.customerId || input.quantity <= 0) throw new Error("service_credit_invalid"); const existing = input.idempotencyKey && this.serviceCreditEntries.find(item => item.organisationId === input.organisationId && item.idempotencyKey === input.idempotencyKey); if (existing) return existing; let account = this.serviceCreditAccounts.find(item => item.organisationId === input.organisationId && item.creditKey === input.creditKey && ((input.userId && item.userId === input.userId) || (input.customerId && item.customerId === input.customerId))); if (!account) { account = { id: `service-credit-${this.serviceCreditAccounts.length + 1}`, organisationId: input.organisationId, ...(input.userId ? { userId: input.userId } : {}), ...(input.customerId ? { customerId: input.customerId } : {}), creditKey: input.creditKey, unit: input.unit as ClubServiceCreditAccount["unit"], status: "active" }; this.serviceCreditAccounts.push(account); } const balance = this.serviceCreditEntries.filter(item => item.accountId === account!.id).reduce((sum, item) => sum + item.quantityDelta, 0); const entry: ClubServiceCreditEntry = { id: `service-credit-entry-${this.serviceCreditEntries.length + 1}`, accountId: account.id, organisationId: input.organisationId, entryType: (input.entryType ?? "grant") as ClubServiceCreditEntry["entryType"], quantityDelta: input.quantity, balanceAfter: balance + input.quantity, ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), occurredAt: new Date().toISOString() }; this.serviceCreditEntries.push(entry); return entry; }
  async spendServiceCredit(input: Parameters<ClubRepository["spendServiceCredit"]>[0]) { const account = this.serviceCreditAccounts.find(item => item.id === input.accountId); const existing = this.serviceCreditEntries.find(item => item.accountId === input.accountId && item.idempotencyKey === input.idempotencyKey); if (existing) return existing; const balance = account && this.serviceCreditEntries.filter(item => item.accountId === account.id).reduce((sum, item) => sum + item.quantityDelta, 0); if (!account || input.quantity <= 0 || (balance ?? 0) < input.quantity) throw new Error("service_credit_insufficient"); const entry: ClubServiceCreditEntry = { id: `service-credit-entry-${this.serviceCreditEntries.length + 1}`, accountId: account.id, organisationId: account.organisationId, entryType: "usage", quantityDelta: -input.quantity, balanceAfter: balance! - input.quantity, ...(input.serviceId ? { serviceId: input.serviceId } : {}), idempotencyKey: input.idempotencyKey, occurredAt: new Date().toISOString() }; this.serviceCreditEntries.push(entry); return entry; }
  async saveMembershipInitialCharge(input: Parameters<ClubRepository["saveMembershipInitialCharge"]>[0]) { const now = new Date().toISOString(); const existing = input.id && this.membershipInitialCharges.find(item => item.id === input.id); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubMembershipInitialCharge = { ...input, id: `initial-charge-${this.membershipInitialCharges.length + 1}`, createdAt: now, updatedAt: now }; this.membershipInitialCharges.push(created); return created; }
  async savePromotion(input: Parameters<ClubRepository["savePromotion"]>[0]) { const now = new Date().toISOString(); const existing = input.id && this.promotions.find(item => item.id === input.id); if (existing) { Object.assign(existing, input, { updatedAt: now }); return existing; } const created: ClubPromotion = { ...input, id: `promotion-${this.promotions.length + 1}`, createdAt: now, updatedAt: now }; this.promotions.push(created); if (input.effects) this.promotionEffects.push(...input.effects.map((effect, index) => ({ ...effect, id: effect.id ?? `${created.id}-effect-${index + 1}`, promotionId: created.id }))); return created; }
  async listPromotionRedemptions(organisationId: string, promotionId?: string) { return this.promotionRedemptions.filter(item => item.organisationId === organisationId && (!promotionId || item.promotionId === promotionId)); }
}
let memoryInstance: MemoryClubRepository | undefined;
export function memoryClubRepository(): MemoryClubRepository { if (!memoryInstance) memoryInstance = new MemoryClubRepository(); return memoryInstance; }
export function selectClubRepository(options: { client?: SupabaseClient; nodeEnv?: string; schemaEnabled?: string }): ClubRepository {
  if (options.nodeEnv !== "production") return memoryClubRepository();
  if (options.schemaEnabled !== "true" || !options.client) { const error = new Error("Club data is unavailable") as ClubRepositoryError; error.code = "UNAVAILABLE"; error.operation = "select_repository"; throw error; }
  return new SupabaseClubRepository(options.client);
}
export function clubRepository(client?: SupabaseClient): ClubRepository { return selectClubRepository({ client, nodeEnv: process.env.NODE_ENV, schemaEnabled: process.env.R12_CLUB_SCHEMA_ENABLED }); }
export { SupabaseClubRepository } from "./supabase-club-repository";
