import { type ClubProduct, type EntitlementGrant, type Membership, type Organisation, type OrganisationLocation, type OrganisationMember, type GrantSource, type Validity, type ProductEntitlement } from "./club";

export type ClubRepository = { listOrganisations(): Promise<Organisation[]>; listLocations(organisationId: string): Promise<OrganisationLocation[]>; listProducts(organisationId: string, includeArchived?: boolean): Promise<ClubProduct[]>; listMembers(organisationId: string): Promise<OrganisationMember[]>; createProduct(product: Omit<ClubProduct, "id">): Promise<ClubProduct>; updateProduct(id: string, patch: Partial<ClubProduct>): Promise<ClubProduct>; assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }): Promise<{ membership: Membership; grants: EntitlementGrant[] }>; };

export const madhouseFixture: Organisation = { id: "org-madhouse", name: "Madhouse Gym", slug: "madhouse-gym", active: true, branding: { coBranding: "co_branded" } };
export const madhouseLocations: OrganisationLocation[] = [{ id: "loc-rotherham", organisationId: madhouseFixture.id, name: "Rotherham", active: true }, { id: "loc-carlton", organisationId: madhouseFixture.id, name: "Carlton", active: true }];
const benefits = (id: string, productId: string): ProductEntitlement[] => { const access: ProductEntitlement = { productId, entitlementKey: "gym_access", scope: "future_locations" }; if (id === "standard-monthly") return [access, { productId, entitlementKey: "class_access", scope: "organisation", allowance: { quantity: 4, period: "month" } }]; if (id === "yearly") return [access, { productId, entitlementKey: "class_access", scope: "organisation", allowance: { quantity: 1, period: "week" } }]; if (id === "bronze" || id === "silver" || id === "gold") return [access, { productId, entitlementKey: "enhanced_training", scope: "organisation" }, { productId, entitlementKey: "nutrition", scope: "organisation" }, { productId, entitlementKey: "trainer_managed", scope: "organisation" }, { productId, entitlementKey: "pt_session_credit", scope: "organisation", allowance: { quantity: id === "bronze" ? 1 : id === "silver" ? 2 : 3, period: "week" } }]; if (id === "single-pt") return [{ productId, entitlementKey: "pt_session_credit", scope: "organisation", allowance: { quantity: 1, period: "block" } }]; if (id === "pt-block") return [{ productId, entitlementKey: "pt_session_credit", scope: "organisation", allowance: { quantity: 10, period: "block" } }]; if (id === "golden-ticket") return [access, { productId, entitlementKey: "discount", scope: "organisation", discount: { percent: 20, period: "month", maxUses: 1 } }]; return [access]; };
const fixtureProducts = (): ClubProduct[] => [
  ["day-pass", "Gym Day Pass", "membership", 500, "one_off", 1], ["week-pass", "Week Pass", "membership", 1200, "one_off", 7], ["concession-monthly", "Concession Monthly", "membership", 2200, "recurring"], ["standard-monthly", "Standard Monthly", "membership", 2700, "recurring"], ["couples", "Couples Membership", "membership", 4500, "recurring"], ["yearly", "Yearly Membership", "membership", 25000, "recurring"], ["bronze", "Transformation Bronze", "transformation", 25000, "one_off", 70], ["silver", "Transformation Silver", "transformation", 40000, "one_off", 70], ["gold", "Transformation Gold", "transformation", 52500, "one_off", 70], ["single-pt", "Single PT Session", "pt", 3000, "one_off"], ["pt-block", "10 PT Session Block", "pt", 20000, "one_off"], ["golden-ticket", "Golden Ticket Founding Membership", "membership", 50000, "one_off"],
].map(([id, name, kind, priceMinor, billing, durationDays]) => { const productId = `product-${id}`; return { id: productId, organisationId: madhouseFixture.id, name: name as string, kind: kind as ClubProduct["kind"], priceMinor: priceMinor as number, currency: "GBP", billing: billing as ClubProduct["billing"], durationDays: durationDays as number | undefined, sellable: true, entitlements: benefits(id as string, productId) }; });

export class MemoryClubRepository implements ClubRepository {
  organisations = [madhouseFixture]; locations = [...madhouseLocations]; products = fixtureProducts(); members: OrganisationMember[] = []; memberships: Membership[] = []; grants: EntitlementGrant[] = [];
  async listOrganisations() { return this.organisations.filter(item => item.active); }
  async listLocations(organisationId: string) { return this.locations.filter(item => item.organisationId === organisationId); }
  async listProducts(organisationId: string, includeArchived = false) { return this.products.filter(item => item.organisationId === organisationId && (includeArchived || item.sellable)); }
  async listMembers(organisationId: string) { return this.members.filter(item => item.organisationId === organisationId && item.active); }
  async createProduct(product: Omit<ClubProduct, "id">) { const existing = this.products.find(item => item.organisationId === product.organisationId && item.name === product.name); if (existing) return existing; const created = { ...product, id: `product-${this.products.length + 1}` }; this.products.push(created); return created; }
  async updateProduct(id: string, patch: Partial<ClubProduct>) { const index = this.products.findIndex(item => item.id === id); if (index < 0) throw new Error("product_not_found"); this.products[index] = { ...this.products[index], ...patch }; return this.products[index]; }
  async assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: Validity; holderUserIds?: string[] }) { const product = this.products.find(item => item.id === input.productId && item.organisationId === input.organisationId); if (!product) throw new Error("product_not_found"); const holderUserIds = input.holderUserIds?.length ? [...new Set(input.holderUserIds)] : [input.userId]; const membership: Membership = { id: `membership-${this.memberships.length + 1}`, organisationId: input.organisationId, productId: product.id, status: "active", validity: input.validity, source: input.source, holderUserIds }; this.memberships.push(membership); const grants = holderUserIds.flatMap(userId => (product.entitlements ?? []).map((benefit, index) => ({ id: `${membership.id}-${userId}-${index}`, userId, organisationId: input.organisationId, membershipId: membership.id, entitlementKey: benefit.entitlementKey, scope: benefit.scope, locationIds: benefit.locationIds, validity: input.validity, source: input.source, allowance: benefit.allowance, discount: benefit.discount }))); this.grants.push(...grants); return { membership, grants }; }
}
export function clubRepository(): ClubRepository { if (process.env.NODE_ENV === "production" && process.env.R12_CLUB_REPOSITORY !== "memory") throw new Error("club_repository_unavailable"); return new MemoryClubRepository(); }
