import { parseCsvRecords } from "./club-csv";

export type MemberImportMapping = Record<string, string | undefined>;
export type MemberImportRow = { firstName?: string; lastName?: string; fullName?: string; email?: string; mobile?: string; legacyReference?: string; membershipName?: string; membershipStatus?: string; startDate?: string; nextPaymentDate?: string; endDate?: string; homeLocation?: string; billingMethod?: string; notes?: string };
export type StagedMemberImportRow = { rowNumber: number; raw: Record<string, string>; normalized: MemberImportRow; warnings: string[]; blockers: string[]; action: "new" | "exact_match" | "possible_match" | "invalid" };
export type MemberImportResult = { rows: MemberImportRow[]; invalid: Array<{ row: number; reason: string }>; duplicateKeys: string[] };
const clean = (value: string | undefined) => value?.trim() || undefined;
const pick = (row: Record<string, string>, mapping: MemberImportMapping, key: string) => clean(mapping[key] ? row[mapping[key]!] : undefined);
export function normalizePhone(value?: string) { return clean(value)?.replace(/[^\d+]/g, "").replace(/^00/, "+"); }
export function normalizeEmail(value?: string) { return clean(value)?.toLocaleLowerCase(); }
export function normalizeMemberRow(raw: Record<string, string>, mapping: MemberImportMapping = {}): MemberImportRow {
  const firstName = pick(raw, mapping, "firstName") ?? clean(raw.first_name ?? raw.firstname); const lastName = pick(raw, mapping, "lastName") ?? clean(raw.last_name ?? raw.surname); const fullName = pick(raw, mapping, "fullName") ?? clean(raw.full_name ?? raw.name); const email = normalizeEmail(pick(raw, mapping, "email") ?? raw.email); const mobile = normalizePhone(pick(raw, mapping, "phone") ?? raw.mobile ?? raw.phone); const legacyReference = pick(raw, mapping, "legacyReference") ?? clean(raw.legacy_member_reference ?? raw.member_number ?? raw.member_id ?? raw["member id"] ?? raw.id); const value = (key: string, ...fallback: string[]) => pick(raw, mapping, key) ?? fallback.map(name => clean(raw[name])).find(Boolean);
  return { ...(firstName ? { firstName } : {}), ...(lastName ? { lastName } : {}), ...(fullName ? { fullName } : {}), ...(email ? { email } : {}), ...(mobile ? { mobile } : {}), ...(legacyReference ? { legacyReference } : {}), ...(value("membershipName", "membership_type", "membership", "package") ? { membershipName: value("membershipName", "membership_type", "membership", "package") } : {}), ...(value("membershipStatus", "membership_status", "status") ? { membershipStatus: value("membershipStatus", "membership_status", "status") } : {}), ...(value("startDate", "start_date", "join_date") ? { startDate: value("startDate", "start_date", "join_date") } : {}), ...(value("nextPaymentDate", "next_payment_date") ? { nextPaymentDate: value("nextPaymentDate", "next_payment_date") } : {}), ...(value("endDate", "end_date", "expiry_date") ? { endDate: value("endDate", "end_date", "expiry_date") } : {}), ...(value("homeLocation", "home_gym", "home_location") ? { homeLocation: value("homeLocation", "home_gym", "home_location") } : {}), ...(value("billingMethod", "payment_method", "billing_method") ? { billingMethod: value("billingMethod", "payment_method", "billing_method") } : {}), ...(value("notes", "notes") ? { notes: value("notes", "notes") } : {}) };
}
export function stageMemberCsv(input: string, mapping: MemberImportMapping = {}): { headers: string[]; rows: StagedMemberImportRow[] } {
  const parsed = parseCsvRecords(input); const headers = parsed.length ? Object.keys(parsed[0]) : []; const seen = new Set<string>();
  const rows = parsed.map((raw, index) => { const normalized = normalizeMemberRow(raw, mapping); const warnings: string[] = []; const blockers: string[] = []; const identity = normalized.legacyReference ? `legacy:${normalized.legacyReference}` : normalized.email ? `email:${normalized.email}` : normalized.mobile ? `phone:${normalized.mobile}` : normalized.fullName ? `name:${normalized.fullName.toLocaleLowerCase()}` : ""; if (!identity) blockers.push("A name, email, phone or ClubManager reference is required"); if (identity && seen.has(identity)) blockers.push("Duplicate source person in this batch"); if (identity) seen.add(identity); if (!normalized.email) warnings.push("Email is missing"); if (!normalized.mobile) warnings.push("Phone is missing"); for (const value of [normalized.nextPaymentDate, normalized.startDate, normalized.endDate]) if (value && (value.includes("/") || Number.isNaN(Date.parse(value)))) blockers.push("Date format requires confirmation"); if (normalized.billingMethod?.toLocaleLowerCase().includes("gocardless")) warnings.push("GoCardless reference requires provider reconciliation"); if (!normalized.membershipName) warnings.push("Membership package is missing"); const action: StagedMemberImportRow["action"] = blockers.length ? "invalid" : "new"; return { rowNumber: index + 2, raw, normalized, warnings, blockers, action }; });
  return { headers, rows };
}
export function parseMemberCsv(input: string): MemberImportResult { const staged = stageMemberCsv(input); return { rows: staged.rows.filter(row => !row.blockers.length).map(row => row.normalized), invalid: staged.rows.filter(row => row.blockers.length).flatMap(row => row.blockers.map(reason => ({ row: row.rowNumber, reason }))), duplicateKeys: staged.rows.filter(row => row.blockers.some(reason => reason.includes("Duplicate"))).map(row => row.normalized.legacyReference ? `legacy:${row.normalized.legacyReference}` : row.normalized.email ? `email:${row.normalized.email}` : row.normalized.fullName ?? "") }; }
