import type { CoachDecision, Equipment, Exercise, LoggedSet } from "./types";
import { parseRange } from "./workout";

export function loadIncrement(equipment: Equipment, configured?: number) { if (equipment === "dumbbell") return 2; if (equipment === "barbell") return 2.5; return configured ?? (equipment === "machine" ? 5 : 2.5); }
export function practicalLoad(raw: number, equipment: Equipment, configured?: number, direction: "nearest" | "up" | "down" = "nearest") { const increment = loadIncrement(equipment, configured); const units = raw / increment; const rounded = direction === "up" ? Math.ceil(units) : direction === "down" ? Math.floor(units) : Math.round(units); return Math.max(increment, Math.round(rounded * increment * 100) / 100); }
export function nextPracticalLoad(current: number, exercise: Exercise, direction: "up" | "down") { return practicalLoad(current + (direction === "up" ? loadIncrement(exercise.equipment, exercise.stackIncrement) : -loadIncrement(exercise.equipment, exercise.stackIncrement)), exercise.equipment, exercise.stackIncrement, direction); }

export function workingWeight(exercise: Exercise, previous: LoggedSet[]) { const reference = previous.find(set => set.kind === "working"); return practicalLoad(reference?.weight ?? exercise.defaultWorkingWeight, exercise.equipment, exercise.stackIncrement); }
export function startingPrescription(exercise: Exercise, previous: LoggedSet[]) { const work = workingWeight(exercise, previous); return { warmup: practicalLoad(work * .5, exercise.equipment, exercise.stackIncrement, "down"), rampOne: practicalLoad(work * .7, exercise.equipment, exercise.stackIncrement), rampTwo: practicalLoad(work * .85, exercise.equipment, exercise.stackIncrement), work }; }
export function nextExerciseRecommendation(exercise: Exercise, previous: LoggedSet[]) { const weight = workingWeight(exercise, previous); const previousLine = previous[0] ? `${previous[0].weight}kg × ${previous[0].reps}` : "No logged performance yet"; return { weight, previousLine, reason: previous[0] ? `Your last working reference was ${previousLine}; it is the sensible starting point, not an automatic progression.` : `This is a conservative, practical ${exercise.equipment} starting load. Ramp sets will calibrate it before work begins.` }; }

export function evaluateSet(exercise: Exercise, logged: LoggedSet[], feedback = "", previous: LoggedSet[] = []): CoachDecision {
  const latest = logged.at(-1); if (!latest) throw new Error("A logged set is required");
  const { low, high } = parseRange(exercise.target); const f = feedback.toLowerCase(); const working = logged.filter(set => set.kind === "working"); const base = { repTarget: `${low}–${high}`, restSeconds: exercise.restSeconds, workingSetsCompleted: working.length };
  if (f.includes("shoulder") || f.includes("pain")) return { ...base, title: "Protect the joint", detail: "Stop this movement today. Choose a pain-free substitute; pressing through shoulder pain is not productive training.", nextWeight: latest.weight, tone: "reduce", nextKind: "complete", completed: false };
  if (latest.kind === "warmup") { const plan = startingPrescription(exercise, previous); return { ...base, title: "Warm-up complete", detail: `Ramp next: ${plan.rampOne}kg × 8. This prepares you without spending working-set fatigue.`, nextWeight: plan.rampOne, repTarget: "8", tone: "hold", nextKind: "ramp", completed: false }; }
  if (latest.kind === "ramp") { const ramps = logged.filter(set => set.kind === "ramp"); const target = workingWeight(exercise, previous); if (ramps.length < 2) return { ...base, title: "Keep ramping", detail: `One more calibration set: ${practicalLoad(target * .85, exercise.equipment, exercise.stackIncrement)}kg × 5–6, then we establish the working load.`, nextWeight: practicalLoad(target * .85, exercise.equipment, exercise.stackIncrement), repTarget: "5–6", tone: "hold", nextKind: "ramp", completed: false }; const adjusted = latest.rir <= 0 ? nextPracticalLoad(target, exercise, "down") : latest.rir >= 5 ? nextPracticalLoad(target, exercise, "up") : target; return { ...base, title: "Working weight established", detail: `${adjusted}kg is a practical ${exercise.equipment} load based on your ramp. Working set 1 of ${exercise.sets}: aim for ${low}–${high} controlled reps.`, nextWeight: adjusted, tone: "hold", nextKind: "working", completed: false }; }
  if (working.length >= exercise.sets) return { ...base, title: "Exercise complete", detail: `${exercise.sets}/${exercise.sets} working sets completed. Quality volume is banked—move to the next programmed exercise.`, nextWeight: latest.weight, tone: "hold", nextKind: "complete", completed: true };
  let restSeconds = exercise.restSeconds; if (f.includes("hard") || f.includes("brutal") || f.includes("fatigue")) restSeconds += 45;
  const nextNumber = working.length + 1;
  if (latest.reps >= high && latest.rir >= 4) return { ...base, restSeconds, title: "Load is clearly light", detail: `Increase by one practical ${loadIncrement(exercise.equipment, exercise.stackIncrement)}kg increment to ${nextPracticalLoad(latest.weight, exercise, "up")}kg. Keep the rep quality high for working set ${nextNumber} of ${exercise.sets}.`, nextWeight: nextPracticalLoad(latest.weight, exercise, "up"), tone: "progress", nextKind: "working", completed: false };
  if (latest.reps < low && latest.rir <= 1 && working.length > 1) return { ...base, restSeconds, title: "Manage the fatigue", detail: `The drop is meaningful after earlier work. Reduce one practical increment to ${nextPracticalLoad(latest.weight, exercise, "down")}kg and finish with clean reps; this is fatigue management, not failure.`, nextWeight: nextPracticalLoad(latest.weight, exercise, "down"), tone: "reduce", nextKind: "working", completed: false };
  if (latest.reps >= high && latest.rir <= 3) return { ...base, restSeconds, title: "Keep the working weight", detail: `Top-range reps at the right effort mean ${latest.weight}kg is productive. Accumulate quality volume rather than forcing a jump. Working set ${nextNumber} of ${exercise.sets}.`, nextWeight: latest.weight, tone: "hold", nextKind: "working", completed: false };
  return { ...base, restSeconds, title: "Stay controlled", detail: `Keep ${latest.weight}kg and aim for ${low}–${high} clean reps on working set ${nextNumber} of ${exercise.sets}.`, nextWeight: latest.weight, tone: "hold", nextKind: "working", completed: false };
}

export function cardioRecommendation(workingSets: number, difficultSets: number) { if (difficultSets >= 5) return { duration: 12, incline: 6, speed: 4.8, why: "Weights were demanding, so keep conditioning recovery-friendly." }; if (workingSets >= 16) return { duration: 16, incline: 8, speed: 5, why: "A moderate finish supports conditioning without turning today into maximal cardio." }; return { duration: 20, incline: 8, speed: 5, why: "The weights session left room for a steady conditioning block." }; }
