import type { CoachDecision, Equipment, Exercise, LoggedSet, SetKind } from "./types";
import { parseRange } from "./workout";

export function loadIncrement(equipment: Equipment, configured?: number) { if (equipment === "dumbbell") return 2; if (equipment === "barbell") return 2.5; return configured ?? (equipment === "machine" ? 5 : 2.5); }
export function practicalLoad(raw: number, equipment: Equipment, configured?: number, direction: "nearest" | "up" | "down" = "nearest") { const increment = loadIncrement(equipment, configured); const units = raw / increment; const rounded = direction === "up" ? Math.ceil(units) : direction === "down" ? Math.floor(units) : Math.round(units); return Math.max(increment, Math.round(rounded * increment * 100) / 100); }
export function nextPracticalLoad(current: number, exercise: Exercise, direction: "up" | "down") { return practicalLoad(current + (direction === "up" ? loadIncrement(exercise.equipment, exercise.stackIncrement) : -loadIncrement(exercise.equipment, exercise.stackIncrement)), exercise.equipment, exercise.stackIncrement, direction); }
export function restFor(exercise: Exercise, kind: SetKind, hard = false) { const base = kind === "warmup" ? 45 : kind === "ramp" ? 60 : exercise.restSeconds; return hard ? Math.min(base + 30, 180) : base; }

export function workingWeight(exercise: Exercise, previous: LoggedSet[]) { const reference = previous.find(set => set.kind === "working"); return practicalLoad(reference?.weight ?? exercise.defaultWorkingWeight, exercise.equipment, exercise.stackIncrement); }
export function startingPrescription(exercise: Exercise, previous: LoggedSet[], position = 0) { const work = workingWeight(exercise, previous); const isolation = exercise.purpose === "isolation" || exercise.purpose === "core"; const warmupRequired = !isolation && position === 0; const ramps = isolation ? 1 : position === 0 && previous.length === 0 ? 2 : 1; return { warmupRequired, ramps, warmup: practicalLoad(work * .5, exercise.equipment, exercise.stackIncrement, "down"), rampOne: practicalLoad(work * .75, exercise.equipment, exercise.stackIncrement), rampTwo: practicalLoad(work * .9, exercise.equipment, exercise.stackIncrement), work }; }
export function initialCoachPlan(exercise: Exercise, previous: LoggedSet[], position = 0) { const plan = startingPrescription(exercise, previous, position); const kind: SetKind = plan.warmupRequired ? "warmup" : "ramp"; const weight = kind === "warmup" ? plan.warmup : plan.rampOne; return { kind, weight, reps: kind === "warmup" ? "10–12" : "6–8", detail: plan.warmupRequired ? `Start with ${weight}kg for 10–12 easy reps, then we will calibrate the ramp.` : `Start with ${weight}kg for a brief calibration set. We are keeping preparation efficient.` }; }
export function nextExerciseRecommendation(exercise: Exercise, previous: LoggedSet[], position = 0) { const weight = workingWeight(exercise, previous); const previousLine = previous[0] ? `${previous[0].weight}kg × ${previous[0].reps}` : "No logged performance yet"; const plan = startingPrescription(exercise, previous, position); return { weight, previousLine, firstStep: initialCoachPlan(exercise, previous, position), reason: previous[0] ? `Your last working reference was ${previousLine}; we will use it as a reference and calibrate quickly.` : `Using an experienced-lifter baseline for this movement. ${plan.warmupRequired ? "A short warm-up and ramps will establish today’s working load." : "A brief calibration set will establish today’s working load."}` }; }

function recalibratedTarget(exercise: Exercise, previous: LoggedSet[], latest: LoggedSet) { const baseline = workingWeight(exercise, previous); const effort = latest.rir ?? 2; if (latest.weight < baseline * .75) return baseline; if (effort >= 3 && latest.reps >= 8) return nextPracticalLoad(latest.weight, exercise, "up"); if (effort <= 0) return nextPracticalLoad(latest.weight, exercise, "down"); return practicalLoad(latest.weight, exercise.equipment, exercise.stackIncrement); }
export function evaluateSet(exercise: Exercise, logged: LoggedSet[], feedback = "", previous: LoggedSet[] = [], position = 0): CoachDecision {
  const latest = logged.at(-1); if (!latest) throw new Error("A logged set is required"); const { low, high } = parseRange(exercise.target); const f = feedback.toLowerCase(); const working = logged.filter(s => s.kind === "working"); const hard = (latest.kind === "working" && (latest.rir ?? 2) <= 1) || f.includes("hard") || f.includes("brutal") || f.includes("fatigue"); const base = { repTarget: `${low}–${high}`, restSeconds: restFor(exercise, latest.kind, hard), workingSetsCompleted: working.length };
  if (f.includes("shoulder") || f.includes("pain")) return { ...base, title: "Protect the joint", detail: "Stop this movement today. Use a pain-free substitute rather than pushing through pain.", nextWeight: latest.weight, tone: "reduce", nextKind: "complete", completed: false };
  const plan = startingPrescription(exercise, previous, position); const nonWorking = logged.filter(s => s.kind !== "working"); const baseline = workingWeight(exercise, previous); const target = latest.kind === "working" ? recalibratedTarget(exercise, previous, latest) : latest.weight >= baseline * .8 ? practicalLoad(latest.weight, exercise.equipment, exercise.stackIncrement) : baseline;
  if (latest.kind === "warmup") return { ...base, title: "Warm-up assessed", detail: latest.weight >= plan.work * .8 ? `That was much nearer working weight than planned. Go to ${target}kg for a short ramp, then we will establish work.` : `Go to ${plan.rampOne}kg for 6–8 reps.`, nextWeight: latest.weight >= plan.work * .8 ? target : plan.rampOne, repTarget: "6–8", tone: "hold", nextKind: "ramp", completed: false };
  if (latest.kind === "ramp") { const rampCount = nonWorking.filter(s => s.kind === "ramp").length; const enoughRamp = exercise.purpose === "isolation" || exercise.purpose === "core" || latest.weight >= target * .85 || rampCount >= plan.ramps; if (enoughRamp) return { ...base, title: "Working weight established", detail: `Go to ${target}kg. Working set 1 of ${exercise.sets}: aim for ${low}–${high} controlled reps.`, nextWeight: target, tone: "hold", nextKind: "working", completed: false }; const nextRamp = practicalLoad(Math.max(latest.weight + loadIncrement(exercise.equipment, exercise.stackIncrement), target * .9), exercise.equipment, exercise.stackIncrement); return { ...base, title: "One final ramp", detail: `Go to ${nextRamp}kg for 4–6 reps, then we start working sets.`, nextWeight: nextRamp, repTarget: "4–6", tone: "hold", nextKind: "ramp", completed: false }; }
  if (working.length >= exercise.sets) return { ...base, title: "Exercise complete", detail: `${exercise.sets}/${exercise.sets} working sets completed. Move to the next programmed exercise.`, nextWeight: latest.weight, tone: "hold", nextKind: "complete", completed: true };
  const nextNumber = working.length + 1;
  if (latest.reps >= high && (latest.rir ?? 2) >= 4) return { ...base, title: "Increase load", detail: `Go to ${nextPracticalLoad(latest.weight, exercise, "up")}kg for working set ${nextNumber} of ${exercise.sets}.`, nextWeight: nextPracticalLoad(latest.weight, exercise, "up"), tone: "progress", nextKind: "working", completed: false };
  if (latest.reps < low && (latest.rir ?? 2) <= 1 && working.length > 1) return { ...base, title: "Manage fatigue", detail: `Drop to ${nextPracticalLoad(latest.weight, exercise, "down")}kg and finish with clean reps.`, nextWeight: nextPracticalLoad(latest.weight, exercise, "down"), tone: "reduce", nextKind: "working", completed: false };
  return { ...base, title: "Stay at this load", detail: `Stay at ${latest.weight}kg for working set ${nextNumber} of ${exercise.sets}.`, nextWeight: latest.weight, tone: "hold", nextKind: "working", completed: false };
}
export function cardioRecommendation(workingSets: number, difficultSets: number) { if (difficultSets >= 5) return { duration: 30, incline: 5, speed: 4.6, why: "High weights-session demand today. Keep the cardio duration moderate and avoid excessive intensity." }; if (workingSets >= 16) return { duration: 34, incline: 7, speed: 5, why: "A demanding weights session calls for steady conditioning that protects recovery." }; return { duration: 38, incline: 8, speed: 5, why: "Weights were moderate today, so use a longer steady conditioning block." }; }
