export type DataOrigin = "real" | "test" | "historical";
export type SessionStatus = "planned" | "completed" | "missed" | "rest" | "recovery_rest" | "rescheduled";
export type ChangeReason = "planned_rest" | "missed" | "recovery" | "physical_activity" | "illness_injury" | "user_report";
export type Profile = { id: string; displayName: string; goals: string[]; startWeight?: number };
export type TrainingBlock = { id: string; name: string; startDate: string; endDate: string; weekNumber: number; goals: string[]; progressionFocus: string; status: "active" | "complete" | "proposed"; reviewDate: string; proposedNextBlock?: string };
export type PlannedSession = { id: string; day: number; name: string; status: SessionStatus; reason?: ChangeReason; exerciseIds: string[] };
export type RecoverySnapshot = { id: string; date: string; origin: DataOrigin; source: "manual" | "whoop" | "apple_health"; recoveryScore?: number; sleepHours?: number; strain?: number; hrv?: number; restingHeartRate?: number; steps?: number; activeEnergy?: number };
export type BodyMeasurement = { id: string; date: string; time?: string; origin: DataOrigin; source: "manual" | "apple_health"; bodyweight?: number; waist?: number; chest?: number; hips?: number; thigh?: number; upperArm?: number; neck?: number; note?: string };
export type HistoricalRecord = { id: string; origin: "historical"; exerciseId: string; exerciseName: string; weight: number; reps: number; rir?: string; note?: string; confidence: "high" | "contextual"; date?: string };
export type Integration = { provider: "whoop" | "apple_health"; status: "not_connected" | "connected"; scopes: string[]; lastSyncAt?: string };
export type NutritionDay = { id: string; date: string; origin: DataOrigin; meals: string[]; calories?: number; protein?: number; carbs?: number; fats?: number };
export const currentBlock: TrainingBlock = { id: "current-block", name: "Strength, Quality & Definition", startDate: "2026-08-31", endDate: "2026-10-25", weekNumber: 1, goals: ["strength", "definition", "recovery-aware conditioning"], progressionFocus: "Technique, RIR and quality volume before load", status: "active", reviewDate: "2026-10-25" };
export const currentWeek: PlannedSession[] = [
  { id: "mon", day: 1, name: "Upper Push + Core + Conditioning", status: "planned", exerciseIds: ["incline-db-press", "machine-chest-press", "seated-db-shoulder-press"] }, { id: "tue", day: 2, name: "Lower Body / Knee-Friendly", status: "planned", exerciseIds: ["leg-press", "hack-squat", "rdl", "hamstring-curl", "leg-extension"] }, { id: "wed", day: 3, name: "Pull + Rear Delts", status: "planned", exerciseIds: ["vertical-pull", "barbell-row", "lat-pullover", "leg-press", "hamstring-curl", "calves"] }, { id: "thu", day: 4, name: "Recovery / Rest", status: "rest", reason: "planned_rest", exerciseIds: [] }, { id: "fri", day: 5, name: "Chest / Shoulders / Arms", status: "planned", exerciseIds: ["flat-bench", "incline-machine-press", "cable-fly", "machine-shoulder-press", "lateral-raise", "ez-curl", "rope-pushdown"] }, { id: "sat", day: 6, name: "Back + Legs Accessories", status: "planned", exerciseIds: ["vertical-pull", "barbell-row", "lat-pullover", "leg-press", "hamstring-curl", "calves"] }, { id: "sun", day: 7, name: "Flexible recovery", status: "rest", reason: "planned_rest", exerciseIds: [] }
];
export function weightTrend(items: BodyMeasurement[]) { const weights = items.filter(x => x.bodyweight).sort((a, b) => a.date.localeCompare(b.date)); const current = weights.at(-1)?.bodyweight; const recent = weights.slice(-7); const average = recent.length ? recent.reduce((sum, x) => sum + (x.bodyweight ?? 0), 0) / recent.length : undefined; const previous = weights.at(-2)?.bodyweight; return { current, average, weeklyChange: current && previous ? current - previous : undefined, sinceStart: current && weights[0]?.bodyweight ? current - weights[0].bodyweight : undefined }; }
export function measurementChange(items: BodyMeasurement[], field: "waist" | "chest" | "hips" | "thigh" | "upperArm" | "neck") { const values = items.filter(item => item[field] !== undefined).sort((a, b) => a.date.localeCompare(b.date)); const latest = values.at(-1)?.[field]; const previous = values.at(-2)?.[field]; return { latest, previous, change: latest !== undefined && previous !== undefined ? latest - previous : undefined }; }
