export type DataOrigin = "real" | "test" | "historical";
export type CardioModality = "incline_treadmill" | "stairmaster" | "upright_bike" | "recumbent_bike" | "elliptical" | "rower";
export type ConditioningPrescription = { id: string; modality: CardioModality; duration: number; intensity: "easy" | "steady" | "interval"; placement: "post_workout" | "separate_day" | "recovery"; day?: number; rationale: string };
export type CardioSession = { id: string; modality: CardioModality; duration: number; settings: Record<string, number | string>; completed: boolean; perceivedEffort?: number; pain?: string; source: DataOrigin | "manual"; startedAt: string; completedAt?: string };
export type SessionStatus = "planned" | "completed" | "missed" | "rest" | "recovery_rest" | "rescheduled" | "unplanned_activity" | "illness_injury" | "other";
export type ChangeReason = "planned_rest" | "missed" | "recovery" | "physical_activity" | "illness_injury" | "user_report";
export type Profile = { id: string; displayName: string; goals: string[]; startWeight?: number };
export type TrainingBlock = { id: string; name: string; startDate: string; endDate: string; weekNumber: number; goals: string[]; progressionFocus: string; status: "active" | "complete" | "proposed"; reviewDate: string; proposedNextBlock?: string; totalWeeks?: number; framework?: string };
export type PlannedSession = { id: string; day: number; name: string; status: SessionStatus; reason?: ChangeReason; exerciseIds: string[]; exerciseOverrides?: Record<string, { name?: string; target?: string; sets?: number }> };
export type RecoverySnapshot = { id: string; date: string; origin: DataOrigin; source: "manual" | "whoop" | "apple_health"; recoveryScore?: number; sleepPerformance?: number; sleepHours?: number; strain?: number; hrv?: number; restingHeartRate?: number; steps?: number; activeEnergy?: number; userReported?: boolean; energy?: number; sleepQuality?: number; soreness?: number; motivation?: number; fatigue?: number; providerId?: string; providerTimestamp?: string; syncedAt?: string };
export type BodyMeasurementType = "waist_navel" | "waist_trouser" | "chest" | "shoulders" | "upper_arm_left" | "upper_arm_right" | "thigh_left" | "thigh_right" | "calf_left" | "calf_right";
export type ProgressPhotoView = "front" | "side" | "back";
export type ProgressPhoto = { id: string; date: string; view: ProgressPhotoView; storageReference: string; ownerId?: string };
export type BodyMeasurement = { id: string; date: string; time?: string; origin: DataOrigin; source: "manual" | "apple_health"; bodyweight?: number; measurementType?: BodyMeasurementType; value?: number; unit?: "cm" | "kg"; waist?: number; chest?: number; hips?: number; thigh?: number; upperArm?: number; neck?: number; note?: string };
export type HistoricalRecord = { id: string; origin: "historical"; exerciseId: string; exerciseName: string; weight: number; reps: number; rir?: string; note?: string; confidence: "high" | "contextual"; date?: string };
export type Integration = { provider: "whoop" | "apple_health"; status: "not_connected" | "connected"; scopes: string[]; lastSyncAt?: string };
export type NutritionDay = { id: string; date: string; origin: DataOrigin; meals: string[]; calories?: number; protein?: number; carbs?: number; fats?: number };
export const currentBlock: TrainingBlock = { id: "current-block", name: "Strength, Quality & Definition", startDate: "2026-08-31", endDate: "2026-10-25", weekNumber: 1, goals: ["strength", "definition", "recovery-aware conditioning"], progressionFocus: "Technique, RIR and quality volume before load", status: "active", reviewDate: "2026-10-25" };
export const currentWeek: PlannedSession[] = [
  { id: "mon", day: 1, name: "Push + Core", status: "planned", exerciseIds: ["incline-db-press", "machine-chest-press", "seated-db-shoulder-press", "cable-lateral-raise", "rope-triceps-pushdown", "overhead-cable-triceps-extension", "cable-crunch"] }, { id: "tue", day: 2, name: "Heavy Lower", status: "planned", exerciseIds: ["trap-bar-deadlift", "hack-squat", "leg-press", "rdl", "hamstring-curl", "hoist-roc-it-leg-extension", "hip-thrust", "calves"] }, { id: "wed", day: 3, name: "Back + Biceps + Traps", status: "planned", exerciseIds: ["lat-pulldown", "barbell-row", "rear-delt-fly", "shrug", "incline-db-curl", "hammer-curl", "pull-up-practice"] }, { id: "thu", day: 4, name: "Recovery / Rest", status: "rest", reason: "planned_rest", exerciseIds: [] }, { id: "fri", day: 5, name: "Chest + Shoulders + Arms", status: "planned", exerciseIds: ["flat-bench", "incline-machine-press", "low-to-high-cable-fly", "machine-shoulder-press", "lateral-raise-mechanical-drop-set", "bayesian-cable-curl", "ez-curl", "rope-triceps-pushdown"], exerciseOverrides: { "rope-triceps-pushdown": { target: "3 × 12", sets: 3 } } }, { id: "sat", day: 6, name: "Lat Width + Lower Accessories", status: "planned", exerciseIds: ["cross-body-single-arm-cable-lat-pulldown", "hoist-roc-it-row", "lat-pullover", "bulgarian-split-squat", "leg-extension", "hamstring-curl", "hip-adductor", "hip-abductor", "calves", "cable-shrug"] }, { id: "sun", day: 7, name: "Recovery", status: "rest", reason: "planned_rest", exerciseIds: [] }
];
export function weightTrend(items: BodyMeasurement[]) { const weights = items.filter(x => x.bodyweight).sort((a, b) => a.date.localeCompare(b.date)); const current = weights.at(-1)?.bodyweight; const recent = weights.slice(-7); const average = recent.length ? recent.reduce((sum, x) => sum + (x.bodyweight ?? 0), 0) / recent.length : undefined; const previous = weights.at(-2)?.bodyweight; return { current, average, weeklyChange: current && previous ? current - previous : undefined, sinceStart: current && weights[0]?.bodyweight ? current - weights[0].bodyweight : undefined }; }
export function measurementChange(items: BodyMeasurement[], field: "waist" | "chest" | "hips" | "thigh" | "upperArm" | "neck") { const values = items.filter(item => item[field] !== undefined).sort((a, b) => a.date.localeCompare(b.date)); const latest = values.at(-1)?.[field]; const previous = values.at(-2)?.[field]; return { latest, previous, change: latest !== undefined && previous !== undefined ? latest - previous : undefined }; }
export function latestWhoopSnapshot(items: RecoverySnapshot[], today = new Date().toISOString().slice(0, 10)) { const records = items.filter(item => item.source === "whoop").sort((a, b) => `${b.date}${b.providerTimestamp ?? ""}`.localeCompare(`${a.date}${a.providerTimestamp ?? ""}`)); const latest = records[0]; return latest ? { record: latest, isToday: latest.date === today } : undefined; }
