export type ExerciseKnowledge = { id: string; name: string; aliases: string[]; primaryMuscles: string[]; secondaryMuscles: string[]; movementPattern: string; equipment: string; unilateral: boolean; compound: boolean; stabilityDemand: "low" | "medium" | "high"; jointDemands: string[]; axialLoading: "none" | "low" | "medium" | "high"; kneeDemand: "none" | "low" | "medium" | "high"; hipHingeDemand: "none" | "low" | "medium" | "high"; shoulderDemand: "low" | "medium" | "high"; emphasis: string[]; programmeRole: "primary_compound" | "secondary_compound" | "isolation" | "accessory"; repRange: string; loadingPattern: string; progression: string; substitutions: string[]; cautions: string[]; intent: string[] };
export const exerciseLibrary: ExerciseKnowledge[] = [
  { id: "incline-db-press", name: "Incline DB Press", aliases: ["incline dumbbell press"], primaryMuscles: ["upper chest"], secondaryMuscles: ["front delts", "triceps"], movementPattern: "incline horizontal press", equipment: "dumbbell", unilateral: false, compound: true, stabilityDemand: "medium", jointDemands: ["shoulder", "elbow"], axialLoading: "low", kneeDemand: "none", hipHingeDemand: "none", shoulderDemand: "medium", emphasis: ["upper chest emphasis"], programmeRole: "primary_compound", repRange: "8–10", loadingPattern: "per-dumbbell", progression: "rep quality then practical dumbbell jump", substitutions: ["incline-machine-press", "incline-smith-press", "incline-barbell-press"], cautions: ["shoulder discomfort"], intent: ["upper chest hypertrophy", "progressive overload"] },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", aliases: ["cable side raise"], primaryMuscles: ["lateral delts"], secondaryMuscles: [], movementPattern: "shoulder abduction", equipment: "cable", unilateral: true, compound: false, stabilityDemand: "low", jointDemands: ["shoulder"], axialLoading: "none", kneeDemand: "low", hipHingeDemand: "none", shoulderDemand: "medium", emphasis: ["lateral delt"], programmeRole: "isolation", repRange: "12–15", loadingPattern: "cable stack", progression: "add reps before a small stack jump", substitutions: ["db-lateral-raise"], cautions: ["painful shoulder arc"], intent: ["lateral delt hypertrophy", "high local stimulus / low systemic fatigue"] },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", aliases: ["rear-foot elevated split squat"], primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["adductors"], movementPattern: "unilateral squat", equipment: "dumbbell", unilateral: true, compound: true, stabilityDemand: "high", jointDemands: ["knee", "hip"], axialLoading: "low", kneeDemand: "medium", hipHingeDemand: "low", shoulderDemand: "low", emphasis: ["quad bias", "glute bias", "unilateral stability"], programmeRole: "secondary_compound", repRange: "8–12", loadingPattern: "per-dumbbell", progression: "control and side-to-side quality before load", substitutions: ["reverse-lunge", "supported-split-squat"], cautions: ["knee pain", "balance limitation"], intent: ["unilateral quad/glute loading", "side-to-side control"] },
  { id: "barbell-row", name: "Barbell Row", aliases: ["bent-over row"], primaryMuscles: ["upper back", "lats"], secondaryMuscles: ["biceps", "spinal erectors"], movementPattern: "horizontal pull", equipment: "barbell", unilateral: false, compound: true, stabilityDemand: "high", jointDemands: ["back", "shoulder"], axialLoading: "medium", kneeDemand: "low", hipHingeDemand: "medium", shoulderDemand: "medium", emphasis: ["upper-back thickness"], programmeRole: "primary_compound", repRange: "6–10", loadingPattern: "barbell plates", progression: "small barbell jumps with strict torso position", substitutions: ["chest-supported-db-row", "cable-row"], cautions: ["back discomfort"], intent: ["upper-back thickness"] },
  { id: "overhead-cable-triceps-extension", name: "Overhead Cable Triceps Extension", aliases: ["overhead rope extension"], primaryMuscles: ["triceps long head"], secondaryMuscles: [], movementPattern: "elbow extension", equipment: "cable", unilateral: false, compound: false, stabilityDemand: "low", jointDemands: ["elbow", "shoulder"], axialLoading: "none", kneeDemand: "low", hipHingeDemand: "none", shoulderDemand: "medium", emphasis: ["triceps long head", "lengthened-position"], programmeRole: "isolation", repRange: "10–15", loadingPattern: "cable stack", progression: "add controlled reps before stack jump", substitutions: ["cross-body-cable-extension", "incline-db-extension"], cautions: ["shoulder or elbow irritation"], intent: ["long-head triceps hypertrophy"] },
];
export function exerciseKnowledge(id: string) { return exerciseLibrary.find(item => item.id === id); }
