import type { SupplierCatalogueProduct, SupplierCatalogueStore, ClubSupplier } from "./club-supplier-catalogue";
import { parseCsvRecords } from "./club-csv";
export type GsnImportRow = { brand:string; range:string; name:string; category?:string; subcategory?:string; description?:string; size?:string; retailPriceMinor?:number; estimatedTradePriceExVatMinor?:number; estimatedTradePriceExVat?:number; costSource?:string; sourceUrl?:string; parentImageReference?:string; variantImageReference?:string; nutrition?:Record<string,unknown>; ingredients?:string; allergens?:string; active?:boolean };
export function normaliseGsnRows(rows:GsnImportRow[]): GsnImportRow[] { return rows.filter(r=>r.active!==false&&r.name.trim()).map(r=>({...r,brand:r.brand.trim(),range:r.range.trim(),name:r.name.trim()})); }
export function groupGsnCatalogue(rows:GsnImportRow[], supplier:ClubSupplier): SupplierCatalogueProduct[] { const map=new Map<string,SupplierCatalogueProduct>();for(const r of normaliseGsnRows(rows)){const key=`${r.brand.toLowerCase()}|${r.range.toLowerCase()}`;const p=map.get(key)??{parentKey:key,supplierId:supplier.id,brand:r.brand,name:r.range,category:r.category,variants:[]};p.variants.push({supplierId:supplier.id,parentKey:key,flavour:r.name,size:r.size,stockStatus:"unknown"});map.set(key,p);}return [...map.values()]; }
export function gsnMemberOrderable(){return false;}
/** Maps an accepted GSN row to columns that exist in the base commerce schema. */
export function gsnCommerceProductInsert(row:GsnImportRow){const category=row.range?`GSN: ${row.range}`:(row.category??"GSN");const media:Record<string,unknown>={source:"GSN",range:row.range};const image=row.variantImageReference||row.parentImageReference;if(image){media.url=image;if(row.variantImageReference)media.variantImageReference=row.variantImageReference;if(row.parentImageReference)media.parentImageReference=row.parentImageReference;}if(row.sourceUrl)media.sourceUrl=row.sourceUrl;if(row.costSource)media.costSource=row.costSource;if(row.nutrition&&Object.keys(row.nutrition).length)media.enrichment={nutrition:row.nutrition, ...(row.ingredients?{ingredients:row.ingredients}:{}), ...(row.allergens?{allergens:row.allergens}:{})};return{ name:row.name, brand:row.brand||"GSN", category, description:row.description??null, active:true, stock_tracked:true, sell_price_minor:row.retailPriceMinor??0, cost_price_minor:row.estimatedTradePriceExVatMinor ?? (row.estimatedTradePriceExVat === undefined ? null : Math.round(row.estimatedTradePriceExVat * 100)), currency:"GBP", supplier_reference:null, media };}
export function parseGsnCsv(input:string){const records=parseCsvRecords(input.replace(/^\uFEFF/,""));const errors:Array<{row:number;reason:string}>=[];const rows:GsnImportRow[]=[];records.forEach((r:any,i)=>{const get=(k:string)=>(r[k.toLowerCase()]??"").trim();const name=get("Product / Variant")||get("Product");const range=get("Range");if(!name||!range){errors.push({row:i+2,reason:"Range and Product / Variant are required"});return}if(/signature meals|historical|bundle-only|non-current|excluded/i.test(`${range} ${get("Notes")} ${get("Status")}`)){errors.push({row:i+2,reason:"Historical/non-current product excluded"});return}const price=get("Retail Price");const minor=price?Number(price.replace(/£/g,""))*100:undefined;if(price&&(!Number.isFinite(minor!)||minor!<0)){errors.push({row:i+2,reason:"Invalid retail price"});return}const costMinorRaw=get("Estimated Trade Price Ex VAT Minor");const costRaw=get("Estimated Trade Price Ex VAT");const costMinor=costMinorRaw?Number(costMinorRaw):undefined;const cost=costRaw?Number(costRaw.replace(/£/g,"")):undefined;if((costMinorRaw&&(!Number.isInteger(costMinor)||costMinor!<0))||(costRaw&&(!Number.isFinite(cost!)||cost!<0))){errors.push({row:i+2,reason:"Invalid estimated trade cost"});return}const nutrition:Record<string,unknown>={};for(const [field,key] of [["basis","Nutrition Basis"],["energyKcal","Kcal"],["proteinG","Protein g"],["carbohydrateG","Carbs g"],["sugarsG","Sugars g"],["fatG","Fat g"],["saturatesG","Saturates g"],["fibreG","Fibre g"],["saltG","Salt g"],["servingSize","Serving Size"]] as const){const value=get(key);if(value)nutrition[field]=field==="basis"||field==="servingSize"?value:Number(value);}rows.push({brand:get("Brand"),range,name,category:get("Category")||undefined,size:get("Format")||undefined,retailPriceMinor:minor,estimatedTradePriceExVatMinor:costMinor,estimatedTradePriceExVat:cost,costSource:get("Cost Source")||undefined,sourceUrl:get("Official Product URL")||get("Official Source URL")||undefined,parentImageReference:get("Parent Image URL")||get("Image URL")||undefined,variantImageReference:get("Variant Image URL")||get("Official Image URL")||undefined,nutrition,ingredients:get("Ingredients")||undefined,allergens:get("Allergens")||undefined});});return{rows,errors};}
