import type { Exercise } from "./types";
function increment(exercise: Exercise) { return exercise.equipment === "dumbbell" ? 2 : exercise.equipment === "barbell" ? 2.5 : exercise.stackIncrement ?? (exercise.equipment === "machine" ? 5 : 2.5); }
function practical(value: number, exercise: Exercise, direction: "up" | "down" = "up") { const step = increment(exercise); const units = value / step; return Math.max(step, Math.round((direction === "up" ? Math.ceil(units) : Math.floor(units)) * step * 100) / 100); }
function snap(value: number, exercise: Exercise, direction: "up" | "down" = "up") { const values = exercise.validLoads?.slice().sort((a, b) => a - b); if (!values?.length) return practical(value, exercise, direction); return direction === "up" ? values.find(item => item >= value) ?? values.at(-1)! : [...values].reverse().find(item => item <= value) ?? values[0]; }
function next(value: number, exercise: Exercise) { return snap(value + increment(exercise), exercise, "up"); }
export type ProgressionProfile = { kind: "dumbbell" | "barbell" | "selectorised_machine" | "plate_loaded_machine"; baseIncrement: number; rampStyle: "proportional" | "plate_jump" | "small_step" };
export function progressionProfile(exercise: Exercise): ProgressionProfile { if (exercise.equipment === "dumbbell") return { kind: "dumbbell", baseIncrement: 2, rampStyle: "small_step" }; if (exercise.equipment === "barbell") return { kind: "barbell", baseIncrement: 2.5, rampStyle: "plate_jump" }; if (exercise.loadProfile === "plate_loaded" || exercise.id === "leg-press") return { kind: "plate_loaded_machine", baseIncrement: 20, rampStyle: "plate_jump" }; if (exercise.equipment === "machine") return { kind: "selectorised_machine", baseIncrement: exercise.stackIncrement ?? 5, rampStyle: "small_step" }; return { kind: "selectorised_machine", baseIncrement: exercise.stackIncrement ?? 2.5, rampStyle: "small_step" }; }
export function magnitudeLoad(exercise: Exercise, weight: number, reps: number, targetHigh: number, rir?: number) { const profile = progressionProfile(exercise); if ((rir ?? 2) < 3 || reps < targetHigh) return next(weight, exercise); const excess = Math.max(0, reps - targetHigh); const jumps = profile.kind === "dumbbell" ? Math.min(3, 1 + Math.floor(excess / 4)) : profile.kind === "plate_loaded_machine" ? Math.min(2, 1 + Math.floor(excess / 5)) : 1; let result = weight; for (let i = 0; i < jumps; i++) result = next(result, exercise); return result; }
export function rampLoad(exercise: Exercise, current: number, target: number) { const profile = progressionProfile(exercise); if (profile.rampStyle === "plate_jump") { const distance = Math.max(0, target - current); const jump = distance >= target * .5 ? 40 : distance >= target * .2 ? 20 : distance >= target * .1 ? 10 : 5; return Math.min(target, snap(current + jump, exercise, "up")); } return Math.min(target, next(current, exercise)); }
