import type { PlannedSession, TrainingBlock } from "./domain";
import type { Workout } from "./types";
import { completedWorkouts } from "./training-history";
import type { ProductOccurrence } from "./schedule-resolver";

export type ProgrammeSnapshot = { name: string; goal: string; daysPerWeek: number; totalWeeks: number; sessionsPerWeek: number; completedSessions: number; partialSessions: number; totalSessions: number; progressPercent: number; currentWeek: number; nextSession?: PlannedSession };
export function programmeSnapshot(name: string, block: TrainingBlock, week: PlannedSession[], workouts: Workout[], generated = false, occurrences?: ProductOccurrence[]): ProgrammeSnapshot {
  const completed = completedWorkouts(workouts); const completedIds = new Set(completed.map(item => item.plannedSessionId).filter(Boolean)); const occurrenceList = occurrences?.filter(item => item.session.exerciseIds.length > 0) ?? []; const completedSessions = occurrences ? occurrenceList.filter(item => item.status === "completed").length : week.filter(session => completedIds.has(session.id)).length; const partialSessions = occurrences ? occurrenceList.filter(item => item.status === "partial").length : workouts.filter(item => item.status === "partial" && item.plannedSessionId).length; const totalWeeks = generated ? 4 : Math.max(1, Math.round((new Date(block.endDate).getTime() - new Date(block.startDate).getTime()) / (7 * 86400000))); const sessionsPerWeek = occurrences ? occurrenceList.length : week.filter(session => session.exerciseIds.length > 0).length; const totalSessions = (occurrences ? sessionsPerWeek : week.filter(session => session.exerciseIds.length > 0).length) * totalWeeks; const nextSession = occurrences ? occurrenceList.find(item => item.status === "planned")?.session : week.find(session => session.exerciseIds.length > 0 && !completedIds.has(session.id)); return { name, goal: block.goals[0] ?? "general fitness", daysPerWeek: sessionsPerWeek, totalWeeks, sessionsPerWeek, completedSessions, partialSessions, totalSessions, progressPercent: totalSessions ? Math.round((completedSessions / totalSessions) * 100) : 0, currentWeek: Math.min(totalWeeks, Math.floor(completedSessions / Math.max(1, sessionsPerWeek)) + 1), nextSession };
}
