import type { PlannedSession, TrainingBlock } from "./domain";
import type { Exercise } from "./types";
import { allExercises } from "./workout";
import { exerciseKnowledge } from "./exercise-library";
import type { TrainingProfile } from "./training-profile";
import { prescriptionForExercise } from "./prescription";

export type GeneratedProgramme = { id: string; name: string; profile: TrainingProfile; block: TrainingBlock; week: PlannedSession[]; rationale: string; previousProgrammes?: GeneratedProgramme[] };
const daySets: Record<number, number[]> = { 2: [1, 4], 3: [1, 3, 5], 4: [1, 2, 4, 5], 5: [1, 2, 3, 5, 6], 6: [1, 2, 3, 5, 6, 7] };
const templates: Record<string, string[][]> = {
  full: [["flat-bench", "leg-press", "lat-pulldown", "rdl", "cable-lateral-raise"], ["trap-bar-deadlift", "incline-db-press", "hack-squat", "barbell-row", "hamstring-curl"]],
  upper: [["flat-bench", "barbell-row", "incline-db-press", "lat-pulldown", "cable-lateral-raise"], ["seated-db-shoulder-press", "lat-pulldown", "machine-chest-press", "barbell-row", "rope-triceps-pushdown"]],
  lower: [["trap-bar-deadlift", "leg-press", "hamstring-curl", "calves", "cable-crunch"], ["hack-squat", "rdl", "hip-thrust", "leg-extension", "calves"]],
  ppl: [["flat-bench", "incline-db-press", "cable-lateral-raise", "rope-triceps-pushdown"], ["lat-pulldown", "barbell-row", "rear-delt-fly", "incline-db-curl"], ["trap-bar-deadlift", "leg-press", "hamstring-curl", "calves"]]
};
function compatible(exercise: Exercise, profile: TrainingProfile) { if (profile.environment === "full_gym") return true; if (profile.environment === "limited_gym") return exercise.equipment !== "machine" && exercise.equipment !== "cable" || exercise.id === "lat-pulldown"; if (profile.environment === "home_basic") return exercise.equipment === "dumbbell" || exercise.equipment === "barbell"; return exercise.equipment === "machine" && exercise.loadingProfile === "bodyweight_assisted"; }
function avoided(exercise: Exercise, profile: TrainingProfile) { const text = profile.limitations.concat(profile.dislikedExercises ?? []).join(" ").toLowerCase(); const knowledge = exerciseKnowledge(exercise.id); return (text.includes("knee") && knowledge?.jointDemands.includes("knee")) || (text.includes("shoulder") && knowledge?.jointDemands.includes("shoulder")) || profile.dislikedExercises?.some(item => item.toLowerCase() === exercise.id || item.toLowerCase() === exercise.name.toLowerCase()); }
function prescribe(id: string, profile: TrainingProfile, catalogue: Exercise[], position: number) { const exercise = catalogue.find(item => item.id === id) ?? allExercises().find(item => item.id === id); if (!exercise || !compatible(exercise, profile) || avoided(exercise, profile)) return undefined; const prescription = prescriptionForExercise(exercise, profile, position); return { ...exercise, sets: prescription.sets, target: prescription.target }; }
export function generateTrainingProgramme(profile: TrainingProfile, catalogue: Exercise[] = allExercises(), generationId = "default"): GeneratedProgramme {
  const days = daySets[profile.daysPerWeek] ?? daySets[3]; const split = profile.daysPerWeek >= 5 && profile.experience !== "beginner" ? "ppl" : profile.daysPerWeek >= 4 ? "upper-lower" : "full"; const source = split === "ppl" ? templates.ppl : split === "upper-lower" ? [...templates.upper, ...templates.lower] : templates.full; const programmeId = `generated-${profile.goal}-${profile.daysPerWeek}-${generationId}`; const week: PlannedSession[] = days.map((day, index) => { const selected = source[index % source.length].map((id, position) => prescribe(id, profile, catalogue, position)).filter((item): item is Exercise => Boolean(item)).slice(0, profile.sessionMinutes <= 45 ? 4 : profile.experience === "beginner" ? 5 : 7); const ids = selected.map(item => item.id); const exerciseOverrides = Object.fromEntries(selected.map(item => [item.id, { sets: item.sets, target: item.target }])); return { id: `${programmeId}-day-${day}`, day, name: split === "ppl" ? ["Push", "Pull", "Legs"][index % 3] : split === "upper-lower" ? (index % 2 ? "Lower Body" : "Upper Body") : "Full Body", status: "planned", exerciseIds: ids, exerciseOverrides }; }); const weeks = 4; const block: TrainingBlock = { id: `${programmeId}-block`, name: profile.goal === "muscle_gain" ? "Build Muscle" : profile.goal === "strength" ? "Build Strength" : profile.goal === "fat_loss" ? "Strength & Definition" : "Foundations", startDate: new Date().toISOString().slice(0, 10), endDate: new Date(Date.now() + weeks * 7 * 86400000).toISOString().slice(0, 10), weekNumber: 1, goals: [profile.goal], progressionFocus: "Build consistent quality before adding load", status: "proposed", reviewDate: new Date(Date.now() + weeks * 7 * 86400000).toISOString().slice(0, 10) }; return { id: programmeId, name: block.name, profile, block, week, rationale: `Built around ${profile.daysPerWeek} training days, ${profile.goal.replace("_", " ")}, and ${profile.sessionMinutes}-minute sessions. The plan repeats key movement patterns while keeping volume manageable.` };
}
