import type { PlannedSession } from "./domain";
import type { Workout } from "./types";
import { loadData } from "./storage";
import { resolveWeekSchedule } from "./schedule-resolver";

export function localDateParts(date: Date, timezone: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short" }).formatToParts(date); const get = (type: string) => parts.find(part => part.type === type)?.value ?? ""; const weekday = get("weekday"); const dayMap: Record<string, number> = { Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 }; return { date: `${get("year")}-${get("month")}-${get("day")}`, day: dayMap[weekday] ?? 1, weekday }; }
export function occurrenceKey(sessionId: string, scheduledDate: string, programmeId = "active") { return `${programmeId}:${sessionId}:${scheduledDate}`; }
export function occurrenceDateForDay(referenceDate: Date, timezone: string, day: number) { const local = localDateParts(referenceDate, timezone); const base = new Date(`${local.date}T12:00:00Z`); base.setUTCDate(base.getUTCDate() + day - local.day); return base.toISOString().slice(0, 10); }
export function resolveToday(sessions: PlannedSession[], timezone: string, date = new Date()) { const local = localDateParts(date, timezone); if (typeof window !== "undefined") { const canonical = resolveWeekSchedule(sessions, loadData(), timezone, date).occurrences.find(item => item.active); if (canonical) return { ...local, session: canonical.session, occurrenceId: canonical.occurrenceId, scheduledDate: canonical.scheduledDate }; } return { ...local, session: sessions.find(session => session.day === local.day) ?? sessions[0] }; }
export function upcomingAfterToday(sessions: PlannedSession[], timezone: string, date = new Date(), count = 7) { if (typeof window !== "undefined") { const canonical = resolveWeekSchedule(sessions, loadData(), timezone, date).occurrences.filter(item => item.scheduledDate > localDateParts(date, timezone).date).slice(0, count); if (canonical.length) return canonical.map(item => ({ ...item.session, scheduledDate: item.scheduledDate, occurrenceId: item.occurrenceId, occurrenceStatus: item.status })); } const today = resolveToday(sessions, timezone, date); return Array.from({ length: count }, (_, offset) => { const day = ((today.day - 1 + offset + 1) % 7) + 1; const session = sessions.find(item => item.day === day)!; return { ...session, scheduledDate: occurrenceDateForDay(date, timezone, day + (day <= today.day ? 7 : 0)) }; }); }
export function dayLabel(session: PlannedSession, todayDay: number) { const delta = (session.day - todayDay + 7) % 7; if (delta === 1) return "Tomorrow"; return ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][session.day - 1]; }
export function completedWorkoutsOnDate(workouts: Workout[], date: Date, timezone: string) { const localDate = localDateParts(date, timezone).date; return workouts.filter(workout => workout.origin !== "test" && workout.completedAt && localDateParts(new Date(workout.completedAt), timezone).date === localDate); }
export function selectCompletedWorkout(workouts: Workout[], date: Date, timezone: string, plannedSessionId?: string) { const matches = completedWorkoutsOnDate(workouts, date, timezone).filter(workout => !plannedSessionId || workout.plannedSessionId === plannedSessionId || (!workout.plannedSessionId && plannedSessionId === "mon" && workout.name.toLowerCase().includes("upper push"))); return matches.sort((a, b) => Number(b.sets.some(set => set.kind === "working")) - Number(a.sets.some(set => set.kind === "working")) || b.sets.length - a.sets.length)[0]; }
export function completedWorkoutsInRange(workouts: Workout[], startDate: string, endDate: string, timezone: string) { return workouts.filter(workout => { if (!workout.completedAt || workout.origin === "test" || workout.origin === "historical" || !workout.plannedSessionId || !workout.scheduledDate) return false; const date = workout.scheduledDate; return date >= startDate && date <= endDate; }); }
export function uniqueCompletedSessionCount(workouts: Workout[], startDate: string, endDate: string, timezone: string) { const keys = new Set(completedWorkoutsInRange(workouts, startDate, endDate, timezone).map(workout => `${workout.plannedSessionId}:${workout.scheduledDate}`)); return keys.size; }
