import type { PlannedSession } from "./domain";
import type { Workout } from "./types";

export function localDateParts(date: Date, timezone: string) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short" }).formatToParts(date); const get = (type: string) => parts.find(part => part.type === type)?.value ?? ""; const weekday = get("weekday"); const dayMap: Record<string, number> = { Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 7 }; return { date: `${get("year")}-${get("month")}-${get("day")}`, day: dayMap[weekday] ?? 1, weekday }; }
export function resolveToday(sessions: PlannedSession[], timezone: string, date = new Date()) { const local = localDateParts(date, timezone); return { ...local, session: sessions.find(session => session.day === local.day) ?? sessions[0] }; }
export function upcomingAfterToday(sessions: PlannedSession[], timezone: string, date = new Date(), count = 7) { const today = resolveToday(sessions, timezone, date); return Array.from({ length: count }, (_, offset) => { const day = ((today.day - 1 + offset + 1) % 7) + 1; return sessions.find(session => session.day === day)!; }); }
export function dayLabel(session: PlannedSession, todayDay: number) { const delta = (session.day - todayDay + 7) % 7; if (delta === 1) return "Tomorrow"; return ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"][session.day - 1]; }
export function completedWorkoutsOnDate(workouts: Workout[], date: Date, timezone: string) { const localDate = localDateParts(date, timezone).date; return workouts.filter(workout => workout.completedAt && localDateParts(new Date(workout.completedAt), timezone).date === localDate); }
export function completedWorkoutsInRange(workouts: Workout[], startDate: string, endDate: string, timezone: string) { return workouts.filter(workout => { if (!workout.completedAt) return false; const date = localDateParts(new Date(workout.completedAt), timezone).date; return date >= startDate && date <= endDate; }); }
