/** Server-persistence contract for scheduling state. Disabled until its SQL migration is approved. */
export const SCHEDULE_PERSISTENCE_ENABLED = process.env.NEXT_PUBLIC_SCHEDULE_PERSISTENCE === "true";

export type AvailabilityOverrideRecord = { id?: string; startDate: string; endDate: string; availableDays?: number[]; unavailableDates?: string[]; sessionsPerWeek?: number; sessionMinutes?: number; environment?: string; equipment?: string[]; reason?: string; source?: "user" | "coach" | "scheduler"; };
export type OccurrenceOutcomeRecord = { programmeId?: string; sessionTemplateId: string; occurrenceId: string; scheduledDate: string; outcome: "completed" | "partial" | "missed" | "rescheduled"; reason?: string; originalOccurrenceId?: string; originalScheduledDate?: string; newScheduledDate?: string; source?: "user" | "coach" | "workout"; };
export type OccurrenceAdjustmentRecord = { programmeId?: string; occurrenceId: string; scheduledDate: string; adjustment: Record<string, unknown>; source?: "user" | "coach" | "scheduler"; idempotencyKey?: string; };

export const occurrencePersistenceKey = (userId: string, occurrenceId: string) => `${userId}:${occurrenceId}`;
export const overrideIsActive = (override: Pick<AvailabilityOverrideRecord, "startDate" | "endDate">, date: string) => date >= override.startDate && date <= override.endDate;
export function serializeOverride(value: AvailabilityOverrideRecord) { return { start_date: value.startDate, end_date: value.endDate, available_days: value.availableDays ?? null, unavailable_dates: value.unavailableDates ?? [], sessions_per_week: value.sessionsPerWeek ?? null, session_minutes: value.sessionMinutes ?? null, environment: value.environment ?? null, equipment: value.equipment ?? [], reason: value.reason ?? null, source: value.source ?? "user" }; }
export function deserializeOverride(value: Record<string, unknown>): AvailabilityOverrideRecord { return { id: typeof value.id === "string" ? value.id : undefined, startDate: String(value.start_date), endDate: String(value.end_date), availableDays: Array.isArray(value.available_days) ? value.available_days.filter((day): day is number => typeof day === "number") : undefined, unavailableDates: Array.isArray(value.unavailable_dates) ? value.unavailable_dates.filter((day): day is string => typeof day === "string") : [], sessionsPerWeek: typeof value.sessions_per_week === "number" ? value.sessions_per_week : undefined, sessionMinutes: typeof value.session_minutes === "number" ? value.session_minutes : undefined, environment: typeof value.environment === "string" ? value.environment : undefined, equipment: Array.isArray(value.equipment) ? value.equipment.filter((item): item is string => typeof item === "string") : [], reason: typeof value.reason === "string" ? value.reason : undefined, source: value.source === "coach" || value.source === "scheduler" ? value.source : "user" }; }
