import type { AppData, Workout } from "./types";
const KEY = "road-to-12-data-v1";
const ACTIVE_KEY = "road-to-12-active";
const defaultData = (): AppData => ({ version: 2, workouts: [], bodyMetrics: [], meals: [] });
export function loadData(): AppData { if (typeof window === "undefined") return defaultData(); try { const data = JSON.parse(localStorage.getItem(KEY) || "null") ?? defaultData(); return { ...defaultData(), ...data, version: 2, workouts: data.workouts ?? [], bodyMetrics: data.bodyMetrics ?? [], meals: data.meals ?? [], recoverySnapshots: data.recoverySnapshots ?? [], cardioSessions: data.cardioSessions ?? [], dailyActivity: data.dailyActivity ?? [] }; } catch { return defaultData(); } }
export function saveData(data: AppData) { localStorage.setItem(KEY, JSON.stringify(data)); }
export function saveWorkout(workout: Workout) { const data = loadData(); const record = { ...workout, origin: workout.origin ?? "real" }; const index = data.workouts.findIndex(item => item.id === workout.id); if (index === -1) data.workouts.unshift(record); else data.workouts[index] = record; saveData(data); }
export function saveActiveWorkout(workout: Workout) { saveWorkout({ ...workout, status: workout.completedAt ? "completed" : "active" }); if (typeof window !== "undefined" && !workout.completedAt) localStorage.setItem(ACTIVE_KEY, JSON.stringify({ workoutId: workout.id })); }
export function loadActiveWorkout(): Workout | undefined { if (typeof window === "undefined") return undefined; try { const raw = JSON.parse(localStorage.getItem(ACTIVE_KEY) || "null") as (Workout & { workoutId?: string }) | null; const data = loadData(); if (raw?.workoutId) return data.workouts.find(item => item.id === raw.workoutId && !item.completedAt && item.status !== "completed"); if (raw?.id && !raw.completedAt) { const existing = data.workouts.find(item => item.id === raw.id); if (!existing) saveWorkout({ ...raw, status: "active" }); return existing ?? { ...raw, status: "active" }; } return undefined; } catch { return undefined; } }
export function clearActiveWorkout() { if (typeof window !== "undefined") localStorage.removeItem(ACTIVE_KEY); }
export function discardLocalWorkout(workoutId: string) { const data = loadData(); saveData({ ...data, workouts: data.workouts.filter(workout => workout.id !== workoutId) }); clearActiveWorkout(); }
export function resetTestData() { const data = loadData(); saveData({ ...data, workouts: data.workouts.filter(item => item.origin !== "test"), bodyMetrics: data.bodyMetrics.filter(item => item.origin !== "test"), meals: data.meals.filter(item => item.origin !== "test") }); localStorage.removeItem("road-to-12-active-test"); }
export function mostRecentExerciseSession(exerciseId: string, workouts = loadData().workouts) {
  return workouts.filter(workout => workout.status === "completed" || workout.completedAt).filter(workout => workout.origin !== "test").filter(workout => workout.sets.some(set => set.exerciseId === exerciseId && set.kind === "working")).sort((a, b) => (b.completedAt ?? b.startedAt).localeCompare(a.completedAt ?? a.startedAt)).map(workout => ({ workout, sets: workout.sets.filter(set => set.exerciseId === exerciseId && set.kind === "working") }))[0];
}
export function previousSets(exerciseId: string): import("./types").LoggedSet[] { return mostRecentExerciseSession(exerciseId)?.sets ?? []; }
export function estimate1RM(weight: number, reps: number) { return Math.round(weight * (1 + reps / 30) * 10) / 10; }
