import type { SupabaseClient } from "@supabase/supabase-js";
import type { ClubRepository } from "./club-repository";
import type { ClubProduct, ClubRole, EntitlementGrant, GrantSource, Membership, Organisation, OrganisationBranding, OrganisationLocation, OrganisationMember, ProductEntitlement } from "./club";
import type { ClubAttendanceState, ClubClassAvailability, ClubClassBooking, ClubClassSession, ClubClassSessionStatus, ClubClassSessionVisibility, ClubClassType, ClubCustomer, ClubCustomerStatus, ClubFulfilmentStatus, ClubPaymentStatus, ClubService, ClubServiceTransaction, CreateClubCustomerInput, CreateClubServiceTransactionInput, SaveClubClassSessionInput, SaveClubClassTypeInput, SaveClubServiceInput, UpdateClubServiceTransactionInput } from "./club-operations";
import type { ClubLocationAccessResult, ClubMemberOperationalRead, ClubMemberSummaryRead } from "./club-operational";
import type { ClubBalanceAccount, ClubBalanceEntry, ClubCommerceProduct, ClubOrder, ClubOrderItem, ClubPayment, ClubStockMovement, SaveClubCommerceProductInput } from "./club-commerce";
import type { ClubCashDeclaration, ClubMembershipInitialCharge, ClubPromotion, ClubPromotionEffect, ClubPromotionRedemption, ClubPromotionTarget, ClubServiceCreditEntry } from "./club-commercial-rules";

type Row = Record<string, unknown>;
type SupabaseFailure = { message?: string; code?: string };
export type ClubRepositoryError = Error & { code: "UNAVAILABLE" | "FORBIDDEN" | "NOT_FOUND" | "INVALID" | "FAILED"; operation: string };

const roles: ClubRole[] = ["member", "trainer", "gym_staff", "gym_admin", "owner", "guest"];
const productKinds: ClubProduct["kind"][] = ["membership", "class", "pt", "transformation"];
const billingKinds: ClubProduct["billing"][] = ["one_off", "recurring", "manual"];
const scopes: ProductEntitlement["scope"][] = ["organisation", "locations", "future_locations"];
const allowancePeriods = ["week", "month", "block"] as const;
type AllowancePeriod = typeof allowancePeriods[number];
const sources: GrantSource[] = ["purchase", "subscription", "staff_assignment", "promotion", "migration", "founding"];
const membershipStatuses: Membership["status"][] = ["active", "paused", "expired", "cancelled"];
const customerStatuses: ClubCustomerStatus[] = ["guest", "member", "customer"];
const sessionStatuses: ClubClassSessionStatus[] = ["scheduled", "cancelled", "completed"];
const sessionVisibilities: ClubClassSessionVisibility[] = ["public", "members_only", "private"];
const bookingStatuses: ClubClassBooking["status"][] = ["confirmed", "cancelled", "waitlisted"];
const attendanceStates: ClubAttendanceState[] = ["pending", "checked_in", "attended", "no_show"];
const paymentStatuses: ClubPaymentStatus[] = ["unpaid", "pending", "paid", "waived", "refunded"];
const fulfilmentStatuses: ClubFulfilmentStatus[] = ["pending", "fulfilled", "cancelled", "failed"];

const safeError = (operation: string, failure?: SupabaseFailure | null, code: ClubRepositoryError["code"] = "FAILED"): never => {
  if (failure && process.env.NODE_ENV !== "test") console.error(`[club-repository] ${operation}`, { code: failure.code, message: failure.message });
  const error = new Error(code === "NOT_FOUND" ? "Club record not found" : code === "FORBIDDEN" ? "Club operation is not permitted" : code === "INVALID" ? "Club operation is invalid" : "Club data is unavailable") as ClubRepositoryError;
  error.code = code; error.operation = operation; throw error;
};

const row = (value: unknown): Row => value && typeof value === "object" && !Array.isArray(value) ? value as Row : {};
const rows = (value: unknown): Row[] => Array.isArray(value) ? value.map(row) : [];
const optionalString = (value: unknown) => typeof value === "string" && value.length ? value : undefined;
const mapOperationalProfile = (value: unknown): ClubMemberOperationalRead => { const item = row(value); const member = row(item.member); const home = row(item.home_location); const customer = row(item.customer); return { member: { id: String(member.id), organisationId: String(member.organisation_id), userId: String(member.user_id), role: String(member.role), active: member.active === true }, ...(home.id ? { homeLocation: { id: String(home.id), name: String(home.name), active: home.active === true } } : {}), ...(customer.id ? { customer: { id: String(customer.id), displayName: String(customer.display_name), ...(optionalString(customer.email) ? { email: String(customer.email) } : {}), ...(optionalString(customer.phone) ? { phone: String(customer.phone) } : {}), ...(optionalString(customer.status) ? { status: String(customer.status) } : {}) } } : {}), memberships: rows(item.memberships).map(m => { const x = row(m); return { id: String(x.id), productId: String(x.product_id), ...(optionalString(x.product_name) ? { productName: String(x.product_name) } : {}), status: String(x.status), startsAt: String(x.starts_at), ...(optionalString(x.ends_at) ? { endsAt: String(x.ends_at) } : {}), source: String(x.source), holderUserIds: Array.isArray(x.holder_user_ids) ? x.holder_user_ids.map(String) : [] }; }), entitlements: rows(item.entitlements).map(g => { const x = row(g); return { id: String(x.id), entitlementKey: String(x.entitlement_key), scope: String(x.scope), ...(Array.isArray(x.location_ids) ? { locationIds: x.location_ids.map(String) } : {}), startsAt: String(x.starts_at), ...(optionalString(x.ends_at) ? { endsAt: String(x.ends_at) } : {}), source: String(x.source), ...(x.allowance_quantity != null ? { allowance: { quantity: Number(x.allowance_quantity), period: String(x.allowance_period) } } : {}), ...(x.discount_percent != null ? { discount: { percent: Number(x.discount_percent), ...(optionalString(x.discount_period) ? { period: String(x.discount_period) } : {}), ...(x.discount_max_uses != null ? { maxUses: Number(x.discount_max_uses) } : {}) } } : {}) }; }), serviceCredits: rows(item.service_credits).map(a => { const x = row(a); return { id: String(x.id), creditKey: String(x.credit_key), unit: String(x.unit), status: String(x.status), balanceQuantity: Number(x.balance_quantity ?? 0) }; }) }; };
const safeAsset = (value: unknown) => typeof value === "string" && /^\/[a-zA-Z0-9/_\-.]+$/.test(value) && !value.includes("..") && !value.startsWith("//") ? value : undefined;
const safeColour = (value: unknown) => typeof value === "string" && /^#[0-9a-f]{6}$/i.test(value) ? value : undefined;
const mapOperationalProfileWithAccess = (value: unknown): ClubMemberOperationalRead => { const item = row(value); const access = row(item.access); return { ...mapOperationalProfile(value), ...(access.state ? { access: { state: String(access.state) as "active" | "needs_attention" | "unavailable", ...(optionalString(access.reason) ? { reason: String(access.reason) } : {}), ...(optionalString(access.policy) ? { policy: String(access.policy) } : {}), ...(access.permitted_location_ids === null ? { permittedLocationIds: null } : Array.isArray(access.permitted_location_ids) ? { permittedLocationIds: access.permitted_location_ids.map(String) } : {}), ...(optionalString(access.membership_id) ? { membershipId: String(access.membership_id) } : {}), ...(optionalString(access.source) ? { source: String(access.source) } : {}), ...(optionalString(access.valid_from) ? { validFrom: String(access.valid_from) } : {}), ...(optionalString(access.valid_until) ? { validUntil: String(access.valid_until) } : {}) } } : {}) }; };

export function mapOrganisationBranding(value: unknown): OrganisationBranding {
  const candidate = row(value);
  if (candidate.coBranding !== "co_branded" && candidate.coBranding !== "r12") return { coBranding: "r12" };
  const displayName = typeof candidate.displayName === "string" && candidate.displayName.trim().length <= 80 ? candidate.displayName.trim() || undefined : undefined;
  return {
    coBranding: candidate.coBranding,
    ...(displayName ? { displayName } : {}),
    ...(safeAsset(candidate.logoSrc) ? { logoSrc: safeAsset(candidate.logoSrc) } : {}),
    ...(safeAsset(candidate.logoDarkSrc) ? { logoDarkSrc: safeAsset(candidate.logoDarkSrc) } : {}),
    ...(safeAsset(candidate.logoLightSrc) ? { logoLightSrc: safeAsset(candidate.logoLightSrc) } : {}),
    ...(safeColour(candidate.primaryAccent) ? { primaryAccent: safeColour(candidate.primaryAccent) } : {}),
    ...(safeColour(candidate.secondaryAccent) ? { secondaryAccent: safeColour(candidate.secondaryAccent) } : {}),
    ...(safeAsset(candidate.backgroundSrc) ? { backgroundSrc: safeAsset(candidate.backgroundSrc) } : {}),
  };
}

export function mapOrganisation(value: unknown): Organisation {
  const item = row(value);
  return { id: String(item.id), name: String(item.name), slug: String(item.slug), active: item.active === true, branding: mapOrganisationBranding(item.branding) };
}
export function mapLocation(value: unknown): OrganisationLocation { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), name: String(item.name), active: item.active === true }; }
export function mapMember(value: unknown): OrganisationMember { const item = row(value); const role = String(item.role) as ClubRole; if (!roles.includes(role)) safeError("map_member", undefined, "INVALID"); return { id: String(item.id), organisationId: String(item.organisation_id), userId: String(item.user_id), role, active: item.active === true }; }

export function mapProductEntitlement(value: unknown): ProductEntitlement {
  const item = row(value); const scope = String(item.scope) as ProductEntitlement["scope"];
  if (!scopes.includes(scope)) safeError("map_product_entitlement", undefined, "INVALID");
  const allowancePeriod = optionalString(item.allowance_period) as AllowancePeriod;
  const discountPeriod = optionalString(item.discount_period);
  return {
    productId: String(item.product_id), entitlementKey: String(item.entitlement_key), scope,
    ...(Array.isArray(item.location_ids) ? { locationIds: item.location_ids.map(String) } : {}),
    ...(item.allowance_quantity != null && allowancePeriods.includes(allowancePeriod) ? { allowance: { quantity: Number(item.allowance_quantity), period: allowancePeriod } } : {}),
    ...(item.discount_percent != null ? { discount: { percent: Number(item.discount_percent), ...(discountPeriod === "month" ? { period: "month" as const } : {}), ...(item.discount_max_uses != null ? { maxUses: Number(item.discount_max_uses) } : {}) } } : {}),
  };
}

export function mapProduct(value: unknown, definitions: unknown[] = []): ClubProduct {
  const item = row(value); const kind = String(item.kind) as ClubProduct["kind"]; const billing = String(item.billing) as ClubProduct["billing"];
  if (!productKinds.includes(kind) || !billingKinds.includes(billing)) safeError("map_product", undefined, "INVALID");
  const ordered = [...definitions].sort((a, b) => Number(row(a).position) - Number(row(b).position));
  return { id: String(item.id), organisationId: String(item.organisation_id), name: String(item.name), kind, priceMinor: Number(item.price_minor), currency: String(item.currency), billing, ...(item.duration_days != null ? { durationDays: Number(item.duration_days) } : {}), sellable: item.sellable === true, ...(optionalString(item.archived_at) ? { archivedAt: String(item.archived_at) } : {}), entitlements: ordered.map(mapProductEntitlement) };
}

export function mapGrant(value: unknown): EntitlementGrant {
  const item = row(value); const source = String(item.source) as GrantSource; const scope = String(item.scope) as ProductEntitlement["scope"];
  if (!sources.includes(source) || !scopes.includes(scope)) safeError("map_grant", undefined, "INVALID");
  return {
    id: String(item.id), userId: String(item.user_id), organisationId: String(item.organisation_id), ...(item.membership_id ? { membershipId: String(item.membership_id) } : {}), entitlementKey: String(item.entitlement_key), scope,
    ...(Array.isArray(item.location_ids) && item.location_ids.length ? { locationIds: item.location_ids.map(String) } : {}), validity: { startsAt: String(item.starts_at), ...(item.ends_at ? { endsAt: String(item.ends_at) } : {}) }, source,
    ...(item.allowance_quantity != null && allowancePeriods.includes(item.allowance_period as typeof allowancePeriods[number]) ? { allowance: { quantity: Number(item.allowance_quantity), period: item.allowance_period as typeof allowancePeriods[number] } } : {}),
    ...(item.discount_percent != null ? { discount: { percent: Number(item.discount_percent), ...(item.discount_period === "month" ? { period: "month" as const } : {}), ...(item.discount_max_uses != null ? { maxUses: Number(item.discount_max_uses) } : {}) } } : {}),
  };
}

export function mapCustomer(value: unknown): ClubCustomer { const item = row(value); const status = String(item.status) as ClubCustomerStatus; if (!customerStatuses.includes(status)) safeError("map_customer", undefined, "INVALID"); return { id: String(item.id), organisationId: String(item.organisation_id), ...(optionalString(item.user_id) ? { userId: String(item.user_id) } : {}), displayName: String(item.display_name), ...(optionalString(item.email) ? { email: String(item.email) } : {}), ...(optionalString(item.phone) ? { phone: String(item.phone) } : {}), status, createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapClassType(value: unknown): ClubClassType { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), name: String(item.name), ...(optionalString(item.description) ? { description: String(item.description) } : {}), defaultDurationMinutes: Number(item.default_duration_minutes), ...(item.default_capacity != null ? { defaultCapacity: Number(item.default_capacity) } : {}), active: item.active === true, createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapClassSession(value: unknown): ClubClassSession { const item = row(value); const status = String(item.status) as ClubClassSessionStatus; const visibility = String(item.visibility) as ClubClassSessionVisibility; if (!sessionStatuses.includes(status) || !sessionVisibilities.includes(visibility)) safeError("map_class_session", undefined, "INVALID"); return { id: String(item.id), organisationId: String(item.organisation_id), locationId: String(item.location_id), classTypeId: String(item.class_type_id), ...(optionalString(item.host_user_id) ? { hostUserId: String(item.host_user_id) } : {}), ...(optionalString(item.title) ? { title: String(item.title) } : {}), startsAt: String(item.starts_at), endsAt: String(item.ends_at), ...(item.capacity != null ? { capacity: Number(item.capacity) } : {}), ...(optionalString(item.booking_opens_at) ? { bookingOpensAt: String(item.booking_opens_at) } : {}), ...(optionalString(item.booking_closes_at) ? { bookingClosesAt: String(item.booking_closes_at) } : {}), ...(optionalString(item.cancellation_closes_at) ? { cancellationClosesAt: String(item.cancellation_closes_at) } : {}), visibility, status, ...(item.recurrence_metadata && typeof item.recurrence_metadata === "object" && !Array.isArray(item.recurrence_metadata) ? { recurrenceMetadata: item.recurrence_metadata as Record<string, unknown> } : {}), createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapClassAvailability(value: unknown): ClubClassAvailability { const item = row(value); return { sessionId: String(item.session_id), ...(item.capacity == null ? {} : { capacity: Number(item.capacity) }), confirmedCount: Number(item.confirmed_count), ...(item.spaces_remaining == null ? {} : { spacesRemaining: Number(item.spaces_remaining) }), waitlistedCount: Number(item.waitlisted_count), isFull: item.is_full === true }; }
export function mapClassBooking(value: unknown): ClubClassBooking { const item = row(value); const status = String(item.status) as ClubClassBooking["status"]; const attendanceState = String(item.attendance_state) as ClubAttendanceState; if (!bookingStatuses.includes(status) || !attendanceStates.includes(attendanceState)) safeError("map_class_booking", undefined, "INVALID"); return { id: String(item.id), organisationId: String(item.organisation_id), sessionId: String(item.session_id), customerId: String(item.customer_id), status, bookedAt: String(item.booked_at), ...(optionalString(item.cancelled_at) ? { cancelledAt: String(item.cancelled_at) } : {}), attendanceState, ...(optionalString(item.entitlement_usage_id) ? { entitlementUsageId: String(item.entitlement_usage_id) } : {}), ...(optionalString(item.payment_reference) ? { paymentReference: String(item.payment_reference) } : {}), createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapService(value: unknown): ClubService { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), ...(optionalString(item.location_id) ? { locationId: String(item.location_id) } : {}), name: String(item.name), ...(optionalString(item.description) ? { description: String(item.description) } : {}), category: String(item.category), ...(item.duration_minutes != null ? { durationMinutes: Number(item.duration_minutes) } : {}), ...(item.price_minor != null ? { priceMinor: Number(item.price_minor) } : {}), currency: String(item.currency), active: item.active === true, createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapServiceTransaction(value: unknown): ClubServiceTransaction { const item = row(value); const paymentStatus = String(item.payment_status) as ClubPaymentStatus; const fulfilmentStatus = String(item.fulfilment_status) as ClubFulfilmentStatus; if (!paymentStatuses.includes(paymentStatus) || !fulfilmentStatuses.includes(fulfilmentStatus)) safeError("map_service_transaction", undefined, "INVALID"); return { id: String(item.id), organisationId: String(item.organisation_id), locationId: String(item.location_id), serviceId: String(item.service_id), ...(optionalString(item.customer_id) ? { customerId: String(item.customer_id) } : {}), ...(optionalString(item.staff_user_id) ? { staffUserId: String(item.staff_user_id) } : {}), quantity: Number(item.quantity), unitPriceMinor: Number(item.unit_price_minor), currency: String(item.currency), paymentStatus, ...(optionalString(item.payment_method) ? { paymentMethod: String(item.payment_method) } : {}), ...(optionalString(item.payment_reference) ? { paymentReference: String(item.payment_reference) } : {}), fulfilmentStatus, ...(optionalString(item.external_fulfilment_reference) ? { externalFulfilmentReference: String(item.external_fulfilment_reference) } : {}), occurredAt: String(item.occurred_at), ...(item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? { metadata: item.metadata as Record<string, unknown> } : {}), createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapCommerceProduct(value: unknown): ClubCommerceProduct { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), ...(optionalString(item.sku) ? { sku: String(item.sku) } : {}), ...(optionalString(item.barcode) ? { barcode: String(item.barcode) } : {}), name: String(item.name), ...(optionalString(item.description) ? { description: String(item.description) } : {}), ...(optionalString(item.category) ? { category: String(item.category) } : {}), active: item.active === true, stockTracked: item.stock_tracked === true, sellPriceMinor: Number(item.sell_price_minor), ...(item.cost_price_minor != null ? { costPriceMinor: Number(item.cost_price_minor) } : {}), currency: String(item.currency), ...(optionalString(item.tax_code) ? { taxCode: String(item.tax_code) } : {}), ...(optionalString(item.supplier_reference) ? { supplierReference: String(item.supplier_reference) } : {}), ...(item.media && typeof item.media === "object" && !Array.isArray(item.media) ? { media: item.media as Record<string, unknown> } : {}), createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapOrderItem(value: unknown): ClubOrderItem { const item = row(value); return { id: String(item.id), orderId: String(item.order_id), productId: String(item.product_id), productName: String(item.product_name), ...(optionalString(item.sku) ? { sku: String(item.sku) } : {}), quantity: Number(item.quantity), unitPriceMinor: Number(item.unit_price_minor), lineTotalMinor: Number(item.line_total_minor), stockTracked: item.stock_tracked === true }; }
export function mapOrder(value: unknown, itemRows: unknown[] = []): ClubOrder { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), ...(optionalString(item.location_id) ? { locationId: String(item.location_id) } : {}), ...(optionalString(item.customer_id) ? { customerId: String(item.customer_id) } : {}), ...(optionalString(item.user_id) ? { userId: String(item.user_id) } : {}), channel: String(item.channel) as ClubOrder["channel"], status: String(item.status) as ClubOrder["status"], currency: String(item.currency), subtotalMinor: Number(item.subtotal_minor), discountMinor: Number(item.discount_minor), totalMinor: Number(item.total_minor), ...(optionalString(item.created_by) ? { createdBy: String(item.created_by) } : {}), ...(optionalString(item.idempotency_key) ? { idempotencyKey: String(item.idempotency_key) } : {}), items: itemRows.map(mapOrderItem), createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapPayment(value: unknown): ClubPayment { const item = row(value); return { id: String(item.id), orderId: String(item.order_id), organisationId: String(item.organisation_id), ...(optionalString(item.payment_account_id) ? { paymentAccountId: String(item.payment_account_id) } : {}), method: String(item.method) as ClubPayment["method"], ...(optionalString(item.external_reference) ? { externalReference: String(item.external_reference) } : {}), amountMinor: Number(item.amount_minor), currency: String(item.currency), status: String(item.status) as ClubPayment["status"], createdAt: String(item.created_at), updatedAt: String(item.updated_at) }; }
export function mapBalanceAccount(value: unknown): ClubBalanceAccount { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), ...(optionalString(item.customer_id) ? { customerId: String(item.customer_id) } : {}), ...(optionalString(item.user_id) ? { userId: String(item.user_id) } : {}), currency: String(item.currency), status: String(item.status) as ClubBalanceAccount["status"], balanceMinor: Number(item.balance_minor ?? 0) }; }
export function mapBalanceEntry(value: unknown): ClubBalanceEntry { const item = row(value); return { id: String(item.id), accountId: String(item.account_id), organisationId: String(item.organisation_id), entryType: String(item.entry_type) as ClubBalanceEntry["entryType"], amountDeltaMinor: Number(item.amount_delta_minor), balanceAfterMinor: Number(item.balance_after_minor), ...(optionalString(item.order_id) ? { orderId: String(item.order_id) } : {}), ...(optionalString(item.payment_id) ? { paymentId: String(item.payment_id) } : {}), ...(optionalString(item.actor_user_id) ? { actorUserId: String(item.actor_user_id) } : {}), ...(optionalString(item.reason) ? { reason: String(item.reason) } : {}), ...(optionalString(item.idempotency_key) ? { idempotencyKey: String(item.idempotency_key) } : {}), createdAt: String(item.created_at) }; }
export function mapStockMovement(value: unknown): ClubStockMovement { const item = row(value); return { id: String(item.id), organisationId: String(item.organisation_id), locationId: String(item.location_id), productId: String(item.product_id), movementType: String(item.movement_type) as ClubStockMovement["movementType"], quantityDelta: Number(item.quantity_delta), ...(optionalString(item.order_id) ? { orderId: String(item.order_id) } : {}), ...(optionalString(item.reason) ? { reason: String(item.reason) } : {}), ...(optionalString(item.actor_user_id) ? { actorUserId: String(item.actor_user_id) } : {}), ...(optionalString(item.idempotency_key) ? { idempotencyKey: String(item.idempotency_key) } : {}), occurredAt: String(item.occurred_at) }; }

const rpcEntitlements = (definitions: ProductEntitlement[]) => definitions.map(definition => ({ entitlement_key: definition.entitlementKey, scope: definition.scope, ...(definition.locationIds ? { location_ids: definition.locationIds } : {}), ...(definition.allowance ? { allowance_quantity: definition.allowance.quantity, allowance_period: definition.allowance.period } : {}), ...(definition.discount ? { discount_percent: definition.discount.percent, ...(definition.discount.period ? { discount_period: definition.discount.period } : {}), ...(definition.discount.maxUses !== undefined ? { discount_max_uses: definition.discount.maxUses } : {}) } : {}) }));
const productRpcArguments = (product: Omit<ClubProduct, "id"> | ClubProduct) => ({ p_name: product.name, p_kind: product.kind, p_price_minor: product.priceMinor, p_currency: product.currency, p_billing: product.billing, p_duration_days: product.durationDays ?? null, p_sellable: product.sellable, p_archived_at: product.archivedAt ?? null, p_entitlements: rpcEntitlements(product.entitlements ?? []) });

export class SupabaseClubRepository implements ClubRepository {
  constructor(private readonly client: SupabaseClient) {}

  async listOrganisations() { const { data, error } = await this.client.from("club_organisations").select("*").order("name"); if (error) safeError("list_organisations", error); return rows(data).map(mapOrganisation); }
  async listLocations(organisationId: string) { const { data, error } = await this.client.from("club_locations").select("*").eq("organisation_id", organisationId).order("name"); if (error) safeError("list_locations", error); return rows(data).map(mapLocation); }
  async listMembers(organisationId: string) { const { data, error } = await this.client.from("club_members").select("*").eq("organisation_id", organisationId).order("created_at"); if (error) safeError("list_members", error); return rows(data).map(mapMember); }
  async listMemberSummaries(organisationId: string) { const { data, error } = await this.client.rpc("club_list_member_summaries", { p_organisation_id: organisationId }); if (error) safeError("list_member_summaries", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return rows(data).map(item => { const x = row(item); const home = row(x.home_location); return { id: String(x.id), organisationId, userId: String(x.user_id), role: String(x.role) as ClubMemberSummaryRead["role"], active: x.active === true, displayName: String(x.display_name), ...(optionalString(x.email) ? { email: String(x.email) } : {}), ...(optionalString(x.membership_name) ? { membershipName: String(x.membership_name) } : {}), ...(optionalString(x.membership_status) ? { membershipStatus: String(x.membership_status) } : {}), ...(optionalString(x.membership_ends_at) ? { membershipEndsAt: String(x.membership_ends_at) } : {}), ...(home.id ? { homeLocation: { id: String(home.id), name: String(home.name) } } : {}), accessState: String(x.access_state) as ClubMemberSummaryRead["accessState"] }; }); }
  async getMemberOperationalProfile(organisationId: string, userId: string) { const { data, error } = await this.client.rpc("club_get_member_operational_profile", { p_organisation_id: organisationId, p_user_id: userId }); if (error) safeError("get_member_operational_profile", error, error.code === "42501" ? "FORBIDDEN" : error.code === "P0002" ? "NOT_FOUND" : "FAILED"); return mapOperationalProfileWithAccess(data); }
  async checkMemberLocationAccess(organisationId: string, userId: string, locationId: string, at?: string) { const { data, error } = await this.client.rpc("club_check_member_location_access", { p_organisation_id: organisationId, p_user_id: userId, p_location_id: locationId, p_at: at ?? new Date().toISOString() }); if (error) safeError("check_member_location_access", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); const x = row(data); return { allowed: x.allowed === true, organisationId: String(x.organisation_id), locationId: String(x.location_id), ...(optionalString(x.membership_id) ? { membershipId: String(x.membership_id) } : {}), ...(optionalString(x.source) ? { source: String(x.source) } : {}), ...(optionalString(x.valid_from) ? { validFrom: String(x.valid_from) } : {}), ...(optionalString(x.valid_until) ? { validUntil: String(x.valid_until) } : {}), ...(optionalString(x.access_policy) ? { accessPolicy: String(x.access_policy) } : {}), ...(optionalString(x.reason) ? { reason: String(x.reason) as ClubLocationAccessResult["reason"] } : {}) }; }
  async setMemberHomeLocation(organisationId: string, userId: string, locationId: string) { const { data, error } = await this.client.rpc("club_set_member_home_location", { p_organisation_id: organisationId, p_user_id: userId, p_location_id: locationId }); if (error) safeError("set_member_home_location", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapOperationalProfile(data); }

  async listProducts(organisationId: string, includeArchived = false) {
    let productQuery = this.client.from("club_products").select("*").eq("organisation_id", organisationId).order("name");
    if (!includeArchived) productQuery = productQuery.eq("sellable", true).is("archived_at", null);
    const [productsResult, definitionsResult] = await Promise.all([productQuery, this.client.from("club_product_entitlements").select("*").eq("organisation_id", organisationId).order("product_id").order("position")]);
    if (productsResult.error) safeError("list_products", productsResult.error); if (definitionsResult.error) safeError("list_product_entitlements", definitionsResult.error);
    const definitions = rows(definitionsResult.data); return rows(productsResult.data).map(product => mapProduct(product, definitions.filter(definition => definition.product_id === product.id)));
  }

  async createProduct(product: Omit<ClubProduct, "id">) {
    const { data, error } = await this.client.rpc("club_create_product", { p_organisation_id: product.organisationId, ...productRpcArguments(product) });
    if (error) safeError("create_product", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); const result = row(data); return mapProduct(result.product, rows(result.entitlements));
  }

  async updateProduct(id: string, patch: Partial<ClubProduct>) {
    const { data: currentRow, error: currentError } = await this.client.from("club_products").select("*").eq("id", id).maybeSingle();
    if (currentError) safeError("update_product_lookup", currentError); if (!currentRow) safeError("update_product_lookup", undefined, "NOT_FOUND");
    const currentOrganisation = String((currentRow as Row).organisation_id); if (patch.organisationId !== undefined && patch.organisationId !== currentOrganisation) safeError("update_product", undefined, "INVALID");
    const { data: definitionRows, error: definitionError } = await this.client.from("club_product_entitlements").select("*").eq("product_id", id).order("position");
    if (definitionError) safeError("update_product_lookup", definitionError);
    const current = mapProduct(currentRow, rows(definitionRows)); const intended: ClubProduct = { ...current, ...patch, id, organisationId: currentOrganisation, entitlements: patch.entitlements ?? current.entitlements };
    const { data, error } = await this.client.rpc("club_update_product", { p_product_id: id, ...productRpcArguments(intended) });
    if (error) safeError("update_product", error, error.code === "42501" ? "FORBIDDEN" : error.code === "P0002" ? "NOT_FOUND" : "FAILED"); const result = row(data); return mapProduct(result.product, rows(result.entitlements));
  }

  async assignProduct(input: { organisationId: string; productId: string; userId: string; source: GrantSource; validity: { startsAt: string; endsAt?: string }; holderUserIds?: string[] }) {
    const holderUserIds = input.holderUserIds?.length ? [...new Set(input.holderUserIds)] : [input.userId];
    const { data, error } = await this.client.rpc("club_assign_product", { p_organisation_id: input.organisationId, p_product_id: input.productId, p_holder_user_ids: holderUserIds, p_starts_at: input.validity.startsAt, p_ends_at: input.validity.endsAt ?? null, p_source: input.source });
    if (error) safeError("assign_product", error, error.code === "42501" ? "FORBIDDEN" : error.code === "P0002" ? "NOT_FOUND" : "FAILED");
    const result = row(data); const membershipRow = row(result.membership); const holders = rows(result.holders).map(holder => String(holder.user_id)); const status = String(membershipRow.status) as Membership["status"]; const source = String(membershipRow.source) as GrantSource;
    if (!membershipStatuses.includes(status) || !sources.includes(source)) safeError("map_membership", undefined, "INVALID");
    const membership: Membership = { id: String(membershipRow.id), organisationId: String(membershipRow.organisation_id), productId: String(membershipRow.product_id), ...(membershipRow.billing_group_id ? { billingGroupId: String(membershipRow.billing_group_id) } : {}), status, validity: { startsAt: String(membershipRow.starts_at), ...(membershipRow.ends_at ? { endsAt: String(membershipRow.ends_at) } : {}) }, source, holderUserIds: holders };
    return { membership, grants: rows(result.grants).map(mapGrant) };
  }

  async listCustomers(organisationId: string) { const { data, error } = await this.client.from("club_customers").select("*").eq("organisation_id", organisationId).order("created_at"); if (error) safeError("list_customers", error); return rows(data).map(mapCustomer); }
  async createCustomer(input: CreateClubCustomerInput) { const { data, error } = await this.client.rpc("club_create_customer", { p_organisation_id: input.organisationId, p_user_id: input.userId ?? null, p_display_name: input.displayName, p_email: input.email ?? null, p_phone: input.phone ?? null, p_status: input.status }); if (error) safeError("create_customer", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapCustomer(data); }
  async linkCustomerUser(customerId: string, userId: string) { const { data, error } = await this.client.rpc("club_link_customer_user", { p_customer_id: customerId, p_user_id: userId }); if (error) safeError("link_customer_user", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapCustomer(data); }
  async listClassTypes(organisationId: string) { const { data, error } = await this.client.from("club_class_types").select("*").eq("organisation_id", organisationId).order("name"); if (error) safeError("list_class_types", error); return rows(data).map(mapClassType); }
  async saveClassType(input: SaveClubClassTypeInput) { const { data, error } = await this.client.rpc("club_save_class_type", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_name: input.name, p_description: input.description ?? null, p_default_duration_minutes: input.defaultDurationMinutes, p_default_capacity: input.defaultCapacity ?? null, p_active: input.active }); if (error) safeError("save_class_type", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapClassType(data); }
  async listClassSessions(organisationId: string) { const { data, error } = await this.client.from("club_class_sessions").select("*").eq("organisation_id", organisationId).order("starts_at"); if (error) safeError("list_class_sessions", error); return rows(data).map(mapClassSession); }
  async getClassAvailability(sessionId: string) { const { data, error } = await this.client.rpc("club_get_class_availability", { p_session_id: sessionId }); if (error) safeError("get_class_availability", error, error.code === "42501" ? "FORBIDDEN" : error.code === "P0002" ? "NOT_FOUND" : "FAILED"); return mapClassAvailability(data); }
  async saveClassSession(input: SaveClubClassSessionInput) { const { data, error } = await this.client.rpc("club_save_class_session", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_location_id: input.locationId, p_class_type_id: input.classTypeId, p_host_user_id: input.hostUserId ?? null, p_title: input.title ?? null, p_starts_at: input.startsAt, p_ends_at: input.endsAt, p_capacity: input.capacity ?? null, p_booking_opens_at: input.bookingOpensAt ?? null, p_booking_closes_at: input.bookingClosesAt ?? null, p_cancellation_closes_at: input.cancellationClosesAt ?? null, p_visibility: input.visibility, p_status: input.status, p_recurrence_metadata: input.recurrenceMetadata ?? null }); if (error) safeError("save_class_session", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapClassSession(data); }
  async listClassBookings(organisationId: string, sessionId?: string) { let query = this.client.from("club_class_bookings").select("*").eq("organisation_id", organisationId); if (sessionId) query = query.eq("session_id", sessionId); const { data, error } = await query.order("booked_at"); if (error) safeError("list_class_bookings", error); return rows(data).map(mapClassBooking); }
  async createClassBooking(input: { sessionId: string; customerId: string; status?: "confirmed" | "waitlisted" }) { const { data, error } = await this.client.rpc("club_create_class_booking", { p_session_id: input.sessionId, p_customer_id: input.customerId, p_status: input.status ?? "confirmed" }); if (error) safeError("create_class_booking", error, error.code === "42501" ? "FORBIDDEN" : error.code === "23505" || error.code === "22023" ? "INVALID" : "FAILED"); return mapClassBooking(data); }
  async cancelClassBooking(bookingId: string) { const { data, error } = await this.client.rpc("club_cancel_class_booking", { p_booking_id: bookingId }); if (error) safeError("cancel_class_booking", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapClassBooking(data); }
  async setBookingAttendance(bookingId: string, attendanceState: ClubAttendanceState) { const { data, error } = await this.client.rpc("club_set_booking_attendance", { p_booking_id: bookingId, p_attendance_state: attendanceState }); if (error) safeError("set_booking_attendance", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapClassBooking(data); }
  async listServices(organisationId: string) { const { data, error } = await this.client.from("club_services").select("*").eq("organisation_id", organisationId).order("name"); if (error) safeError("list_services", error); return rows(data).map(mapService); }
  async saveService(input: SaveClubServiceInput) { const { data, error } = await this.client.rpc("club_save_service", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_location_id: input.locationId ?? null, p_name: input.name, p_description: input.description ?? null, p_category: input.category, p_duration_minutes: input.durationMinutes ?? null, p_price_minor: input.priceMinor ?? null, p_currency: input.currency, p_active: input.active }); if (error) safeError("save_service", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapService(data); }
  async listServiceTransactions(organisationId: string) { const { data, error } = await this.client.from("club_service_transactions").select("*").eq("organisation_id", organisationId).order("occurred_at"); if (error) safeError("list_service_transactions", error); return rows(data).map(mapServiceTransaction); }
  async createServiceTransaction(input: CreateClubServiceTransactionInput) { const { data, error } = await this.client.rpc("club_create_service_transaction", { p_organisation_id: input.organisationId, p_location_id: input.locationId, p_service_id: input.serviceId, p_customer_id: input.customerId ?? null, p_quantity: input.quantity, p_unit_price_minor: input.unitPriceMinor, p_currency: input.currency, p_payment_status: input.paymentStatus, p_payment_method: input.paymentMethod ?? null, p_payment_reference: input.paymentReference ?? null, p_fulfilment_status: input.fulfilmentStatus, p_external_fulfilment_reference: input.externalFulfilmentReference ?? null, p_occurred_at: input.occurredAt, p_metadata: input.metadata ?? null }); if (error) safeError("create_service_transaction", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapServiceTransaction(data); }
  async updateServiceTransaction(transactionId: string, input: UpdateClubServiceTransactionInput) { const { data, error } = await this.client.rpc("club_update_service_transaction", { p_transaction_id: transactionId, p_payment_status: input.paymentStatus, p_payment_method: input.paymentMethod ?? null, p_payment_reference: input.paymentReference ?? null, p_fulfilment_status: input.fulfilmentStatus, p_external_fulfilment_reference: input.externalFulfilmentReference ?? null, p_metadata: input.metadata ?? null }); if (error) safeError("update_service_transaction", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapServiceTransaction(data); }
  async listCommerceProducts(organisationId: string) { const { data, error } = await this.client.from("club_commerce_products").select("*").eq("organisation_id", organisationId).order("name"); if (error) safeError("list_commerce_products", error); return rows(data).map(mapCommerceProduct); }
  async saveCommerceProduct(input: SaveClubCommerceProductInput) { const { data, error } = await this.client.rpc("club_save_commerce_product", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_sku: input.sku ?? null, p_barcode: input.barcode ?? null, p_name: input.name, p_description: input.description ?? null, p_category: input.category ?? null, p_active: input.active, p_stock_tracked: input.stockTracked, p_sell_price_minor: input.sellPriceMinor, p_cost_price_minor: input.costPriceMinor ?? null, p_currency: input.currency, p_tax_code: input.taxCode ?? null, p_supplier_reference: input.supplierReference ?? null, p_media: input.media ?? null }); if (error) safeError("save_commerce_product", error, error.code === "42501" ? "FORBIDDEN" : error.code === "P0002" ? "NOT_FOUND" : "FAILED"); return mapCommerceProduct(data); }
  async listOrders(organisationId: string) { const { data, error } = await this.client.from("club_orders").select("*,club_order_items(*)").eq("organisation_id", organisationId).order("created_at", { ascending: false }); if (error) safeError("list_orders", error); return rows(data).map(item => mapOrder(item, rows(item.club_order_items))); }
  async getBalanceAccount(organisationId: string, userId: string) { const { data, error } = await this.client.from("club_balance_accounts").select("*,club_balance_entries(amount_delta_minor)").eq("organisation_id", organisationId).eq("user_id", userId).maybeSingle(); if (error) safeError("get_balance_account", error); if (!data) return undefined; const account = mapBalanceAccount(data); const entries = rows((data as Row).club_balance_entries); return { ...account, balanceMinor: entries.reduce((sum, entry) => sum + Number(entry.amount_delta_minor ?? 0), 0) }; }
  async createCommerceOrder(input: { organisationId: string; locationId?: string; customerId?: string; channel: string; currency: string; items: Array<{ productId: string; quantity: number }>; idempotencyKey?: string }) { const { data, error } = await this.client.rpc("club_create_commerce_order", { p_organisation_id: input.organisationId, p_location_id: input.locationId ?? null, p_customer_id: input.customerId ?? null, p_channel: input.channel, p_currency: input.currency, p_items: input.items.map(item => ({ product_id: item.productId, quantity: item.quantity })), p_idempotency_key: input.idempotencyKey ?? null }); if (error) safeError("create_commerce_order", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); const result = row(data); return mapOrder(result.order, rows(result.items)); }
  async recordCashPayment(orderId: string, amountMinor: number, idempotencyKey?: string) { const { data, error } = await this.client.rpc("club_record_cash_payment", { p_order_id: orderId, p_amount_minor: amountMinor, p_idempotency_key: idempotencyKey ?? null }); if (error) safeError("record_cash_payment", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapPayment(data); }
  async creditBalance(input: { organisationId: string; customerId?: string; userId?: string; currency: string; amountMinor: number; entryType?: string; reason?: string; idempotencyKey?: string; actorRole?: ClubRole }) { const { data, error } = await this.client.rpc("club_credit_balance", { p_organisation_id: input.organisationId, p_customer_id: input.customerId ?? null, p_user_id: input.userId ?? null, p_currency: input.currency, p_amount_minor: input.amountMinor, p_entry_type: input.entryType ?? "top_up", p_reason: input.reason ?? null, p_idempotency_key: input.idempotencyKey ?? null }); if (error) safeError("credit_balance", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapBalanceEntry(data); }
  async spendBalance(orderId: string, amountMinor: number, idempotencyKey: string) { const { data, error } = await this.client.rpc("club_spend_balance", { p_order_id: orderId, p_amount_minor: amountMinor, p_idempotency_key: idempotencyKey }); if (error) safeError("spend_balance", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapBalanceEntry(data); }
  async adjustInventory(input: { organisationId: string; locationId: string; productId: string; movementType: string; quantityDelta: number; reason?: string; idempotencyKey?: string }) { const { data, error } = await this.client.rpc("club_adjust_inventory", { p_organisation_id: input.organisationId, p_location_id: input.locationId, p_product_id: input.productId, p_movement_type: input.movementType, p_quantity_delta: input.quantityDelta, p_reason: input.reason ?? null, p_idempotency_key: input.idempotencyKey ?? null }); if (error) safeError("adjust_inventory", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return mapStockMovement(data); }
  async declareCash(input: Parameters<ClubRepository["declareCash"]>[0]) { const { data, error } = await this.client.rpc("club_declare_cash_payment", { p_organisation_id: input.organisationId, p_location_id: input.locationId ?? null, p_purpose: input.purpose, p_user_id: input.userId ?? null, p_customer_id: input.customerId ?? null, p_order_id: input.orderId ?? null, p_membership_id: input.membershipId ?? null, p_amount_minor: input.amountMinor, p_currency: input.currency, p_idempotency_key: input.idempotencyKey }); if (error) safeError("declare_cash", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubCashDeclaration; }
  async listCashDeclarations(organisationId: string, status?: string) { let query = this.client.from("club_cash_declarations").select("*,club_customers(display_name,email),club_orders(club_order_items(product_name,quantity))").eq("organisation_id", organisationId); if (status) query = query.eq("status", status); const { data, error } = await query.order("declared_at", { ascending: false }); if (error) safeError("list_cash_declarations", error); return rows(data).map(item => { const value = row(item); const customer = row(value.club_customers); const order = row(value.club_orders); const orderItems = rows(order.club_order_items); return { id: String(value.id), organisationId: String(value.organisation_id), ...(value.location_id ? { locationId: String(value.location_id) } : {}), purpose: String(value.purpose) as ClubCashDeclaration["purpose"], ...(value.user_id ? { userId: String(value.user_id) } : {}), ...(value.customer_id ? { customerId: String(value.customer_id) } : {}), ...(customer.display_name ? { memberDisplayName: String(customer.display_name) } : {}), ...(customer.email ? { memberEmail: String(customer.email) } : {}), ...(orderItems.length ? { productSummary: orderItems.map(item => `${String(item.product_name)} × ${Number(item.quantity)}`).join(", ") } : {}), ...(value.order_id ? { orderId: String(value.order_id) } : {}), ...(value.membership_id ? { membershipId: String(value.membership_id) } : {}), declaredAmountMinor: Number(value.declared_amount_minor), currency: String(value.currency), status: String(value.status) as ClubCashDeclaration["status"], declaredAt: String(value.declared_at), ...(value.confirmed_at ? { confirmedAt: String(value.confirmed_at) } : {}), ...(value.confirmed_by ? { confirmedBy: String(value.confirmed_by) } : {}), ...(value.notes ? { notes: String(value.notes) } : {}), ...(value.idempotency_key ? { idempotencyKey: String(value.idempotency_key) } : {}), createdAt: String(value.created_at), updatedAt: String(value.updated_at) } as ClubCashDeclaration; }); }
  async reconcileCash(id: string, status: "confirmed" | "rejected" | "discrepancy", notes?: string, discrepancyMinor?: number) { const { data, error } = await this.client.rpc("club_reconcile_cash_declaration", { p_declaration_id: id, p_status: status, p_notes: notes ?? null, p_discrepancy_minor: discrepancyMinor ?? null }); if (error) safeError("reconcile_cash", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubCashDeclaration; }
  async grantServiceCredit(input: Parameters<ClubRepository["grantServiceCredit"]>[0]) { const { data, error } = await this.client.rpc("club_grant_service_credit", { p_organisation_id: input.organisationId, p_user_id: input.userId ?? null, p_customer_id: input.customerId ?? null, p_credit_key: input.creditKey, p_unit: input.unit, p_quantity: input.quantity, p_entry_type: input.entryType ?? "grant", p_idempotency_key: input.idempotencyKey ?? null }); if (error) safeError("grant_service_credit", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubServiceCreditEntry; }
  async spendServiceCredit(input: Parameters<ClubRepository["spendServiceCredit"]>[0]) { const { data, error } = await this.client.rpc("club_spend_service_credit", { p_account_id: input.accountId, p_quantity: input.quantity, p_service_id: input.serviceId ?? null, p_idempotency_key: input.idempotencyKey }); if (error) safeError("spend_service_credit", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubServiceCreditEntry; }
  async saveMembershipInitialCharge(input: Parameters<ClubRepository["saveMembershipInitialCharge"]>[0]) { const { data, error } = await this.client.rpc("club_save_membership_initial_charge", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_product_id: input.productId, p_charge_type: input.chargeType, p_amount_minor: input.amountMinor, p_currency: input.currency, p_required: input.required, p_active: input.active, p_position: input.position }); if (error) safeError("save_initial_charge", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubMembershipInitialCharge; }
  async savePromotion(input: Parameters<ClubRepository["savePromotion"]>[0]) { const { data, error } = await this.client.rpc("club_save_promotion", { p_id: input.id ?? null, p_organisation_id: input.organisationId, p_name: input.name, p_description: input.description ?? null, p_status: input.status, p_starts_at: input.startsAt, p_ends_at: input.endsAt ?? null, p_location_ids: input.locationIds ?? [], p_eligibility: input.eligibility, p_effects: input.effects ?? [] }); if (error) safeError("save_promotion", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubPromotion; }
  async listPromotionRedemptions(organisationId: string, promotionId?: string) { let query = this.client.from("club_promotion_redemptions").select("*").eq("organisation_id", organisationId); if (promotionId) query = query.eq("promotion_id", promotionId); const { data, error } = await query.order("redeemed_at", { ascending: false }); if (error) safeError("list_promotion_redemptions", error); return rows(data) as unknown as ClubPromotionRedemption[]; }
  async savePromotionTargets(promotionId: string, targets: Omit<ClubPromotionTarget, "id" | "promotionId" | "organisationId">[]) { const { data, error } = await this.client.rpc("club_save_promotion_targets", { p_promotion_id: promotionId, p_targets: targets }); if (error) safeError("save_promotion_targets", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return rows(data) as unknown as ClubPromotionTarget[]; }
  async redeemPromotion(input: Parameters<ClubRepository["redeemPromotion"]>[0]) { const { data, error } = await this.client.rpc("club_redeem_promotion", { p_promotion_id: input.promotionId, p_target_type: input.targetType, p_target_id: input.targetId ?? null, p_category_key: input.categoryKey ?? null, p_charge_type: input.chargeType ?? null, p_location_id: input.locationId ?? null, p_user_id: input.userId ?? null, p_customer_id: input.customerId ?? null, p_order_id: input.orderId ?? null, p_membership_id: input.membershipId ?? null, p_base_amount_minor: input.baseAmountMinor, p_idempotency_key: input.idempotencyKey ?? null }); if (error) safeError("redeem_promotion", error, error.code === "42501" ? "FORBIDDEN" : "FAILED"); return data as ClubPromotionRedemption; }
}
