import type { Exercise } from "./types";
import type { TrainingDiscipline, TrainingExperience, TrainingProfile } from "./training-profile";
import { exerciseKnowledge } from "./exercise-library";

export type CapabilityMaturity = "foundation" | "full" | "advanced";
export type PhaseKind = "accumulation" | "intensification" | "strength" | "hypertrophy" | "technique" | "re_acclimation" | "deload" | "peaking";
export type FrameworkFamily = "full_body" | "full_body_ab" | "upper_lower" | "ppl" | "ppl_plus" | "body_part" | "powerlifting_sbd" | "olympic_technical" | "functional_mixed_modal" | "hybrid_concurrent" | "return_reacclimation";
export type DisciplineContract = { id: TrainingDiscipline; label: string; maturity: CapabilityMaturity; frameworks: FrameworkFamily[]; sessionRoles: string[]; progression: string; conditioning: "integrated" | "supporting" | "minimal" | "specialist"; technicalEligibility?: TrainingExperience; };
const contracts: Record<TrainingDiscipline, DisciplineContract> = {
  general_fitness: { id: "general_fitness", label: "General Fitness", maturity: "full", frameworks: ["full_body", "upper_lower"], sessionRoles: ["balanced resistance", "core", "conditioning"], progression: "quality reps and sustainable load", conditioning: "supporting" },
  fat_loss: { id: "fat_loss", label: "Fat Loss / Body Composition", maturity: "full", frameworks: ["full_body", "upper_lower", "ppl_plus"], sessionRoles: ["muscle retention", "conditioning"], progression: "retain strength while managing fatigue", conditioning: "supporting" },
  hypertrophy: { id: "hypertrophy", label: "Hypertrophy / Bodybuilding", maturity: "full", frameworks: ["upper_lower", "ppl", "body_part"], sessionRoles: ["primary hypertrophy", "targeted accessory", "core"], progression: "double progression with stable movements", conditioning: "minimal" },
  strength: { id: "strength", label: "Strength", maturity: "full", frameworks: ["full_body", "upper_lower"], sessionRoles: ["primary strength", "secondary compound", "accessory"], progression: "repeatable heavy practice and assistance", conditioning: "minimal" },
  powerlifting: { id: "powerlifting", label: "Powerlifting", maturity: "foundation", frameworks: ["powerlifting_sbd", "upper_lower"], sessionRoles: ["competition lift", "variation", "assistance"], progression: "conservative strength exposure", conditioning: "minimal" },
  olympic_weightlifting: { id: "olympic_weightlifting", label: "Olympic Weightlifting", maturity: "foundation", frameworks: ["olympic_technical", "full_body"], sessionRoles: ["technical lift", "pull", "squat", "overhead stability"], progression: "technical consistency before load", conditioning: "minimal", technicalEligibility: "intermediate" },
  functional_fitness: { id: "functional_fitness", label: "Functional Fitness", maturity: "foundation", frameworks: ["functional_mixed_modal", "full_body"], sessionRoles: ["strength", "skill", "work capacity"], progression: "quality movement and controlled density", conditioning: "integrated" },
  hybrid: { id: "hybrid", label: "Hybrid", maturity: "foundation", frameworks: ["hybrid_concurrent", "upper_lower"], sessionRoles: ["strength", "hypertrophy", "conditioning"], progression: "balance concurrent demands", conditioning: "integrated" },
  return_to_training: { id: "return_to_training", label: "Return to Training", maturity: "full", frameworks: ["return_reacclimation", "full_body_ab"], sessionRoles: ["re-acclimation", "technique", "mobility"], progression: "restore tolerance gradually", conditioning: "supporting" },
  accessible_training: { id: "accessible_training", label: "Accessible Training", maturity: "foundation", frameworks: ["full_body", "upper_lower"], sessionRoles: ["supported resistance", "seated option", "adapted conditioning"], progression: "individualised repeatable practice", conditioning: "supporting" },
  strongman: { id: "strongman", label: "Strongman", maturity: "foundation", frameworks: ["full_body", "hybrid_concurrent"], sessionRoles: ["event", "strength", "carry", "loading"], progression: "event practice and controlled loading", conditioning: "specialist" }
};
export const disciplineContracts = contracts;
export function disciplineContract(id: TrainingDiscipline = "general_fitness") { return contracts[id] ?? contracts.general_fitness; }
export function disciplineForProfile(profile: TrainingProfile): TrainingDiscipline { return profile.discipline ?? (profile.goal === "muscle_gain" ? "hypertrophy" : profile.goal); }
export function frameworksForDiscipline(id: TrainingDiscipline) { return disciplineContract(id).frameworks; }
export function frameworkForDiscipline(profile: TrainingProfile): FrameworkFamily { return disciplineContract(disciplineForProfile(profile)).frameworks[0]; }
export function phaseForDiscipline(id: TrainingDiscipline, returning = false): PhaseKind { if (id === "return_to_training" || returning) return "re_acclimation"; if (id === "olympic_weightlifting") return "technique"; if (id === "powerlifting") return "strength"; if (id === "hypertrophy") return "hypertrophy"; return "accumulation"; }

export type EquipmentId = "olympic_barbell" | "standard_barbell" | "trap_bar" | "safety_squat_bar" | "swiss_bar" | "ez_bar" | "axle" | "log" | "dumbbell" | "adjustable_dumbbell" | "kettlebell" | "plates" | "landmine" | "cable_station" | "functional_trainer" | "selectorised_machine" | "plate_loaded_machine" | "smith_machine" | "rack" | "bench" | "band" | "chains" | "medicine_ball" | "sandbag" | "sled" | "farmer_handles" | "yoke" | "rings" | "suspension_trainer" | "pullup_station" | "rower" | "skierg" | "treadmill" | "bike" | "stairmaster" | "elliptical";
export const equipmentOntology = Object.fromEntries(([
  ["olympic_barbell", "Olympic barbell", "free_weight"], ["standard_barbell", "Standard barbell", "free_weight"], ["trap_bar", "Trap bar", "free_weight"], ["safety_squat_bar", "Safety squat bar", "specialist"], ["swiss_bar", "Swiss bar", "specialist"], ["ez_bar", "EZ bar", "free_weight"], ["axle", "Axle", "specialist"], ["log", "Log", "specialist"], ["dumbbell", "Dumbbell", "free_weight"], ["adjustable_dumbbell", "Adjustable dumbbell", "free_weight"], ["kettlebell", "Kettlebell", "free_weight"], ["plates", "Weight plates", "support"], ["landmine", "Landmine", "specialist"], ["cable_station", "Cable station", "cable"], ["functional_trainer", "Functional trainer", "cable"], ["selectorised_machine", "Selectorised machine", "machine"], ["plate_loaded_machine", "Plate-loaded machine", "machine"], ["smith_machine", "Smith machine", "machine"], ["rack", "Rack", "support"], ["bench", "Bench", "support"], ["band", "Resistance band", "support"], ["chains", "Chains", "specialist"], ["medicine_ball", "Medicine ball", "specialist"], ["sandbag", "Sandbag", "specialist"], ["sled", "Sled / prowler", "specialist"], ["farmer_handles", "Farmer handles", "specialist"], ["yoke", "Yoke", "specialist"], ["rings", "Rings", "specialist"], ["suspension_trainer", "Suspension trainer", "support"], ["pullup_station", "Pull-up station", "support"], ["rower", "Rower", "conditioning"], ["skierg", "SkiErg", "conditioning"], ["treadmill", "Treadmill", "conditioning"], ["bike", "Stationary bike", "conditioning"], ["stairmaster", "StairMaster", "conditioning"], ["elliptical", "Elliptical", "conditioning"]] as const).map(([id, label, category]) => [id, { id, label, category }])) as Record<EquipmentId, { id: EquipmentId; label: string; category: "free_weight" | "machine" | "cable" | "conditioning" | "specialist" | "support" }>;

export type MovementFamily = { id: string; label: string; patterns: string[]; defaultRole: string };
export const movementFamilies: Record<string, MovementFamily> = {
  horizontal_push: { id: "horizontal_push", label: "Horizontal push", patterns: ["horizontal press", "incline press"], defaultRole: "compound" }, vertical_push: { id: "vertical_push", label: "Vertical push", patterns: ["vertical press"], defaultRole: "compound" }, horizontal_row: { id: "horizontal_row", label: "Horizontal row", patterns: ["horizontal pull"], defaultRole: "compound" }, vertical_pull: { id: "vertical_pull", label: "Vertical pull", patterns: ["vertical pull"], defaultRole: "compound" }, squat: { id: "squat", label: "Squat / knee dominant", patterns: ["squat", "unilateral squat"], defaultRole: "compound" }, hinge: { id: "hinge", label: "Hinge / hip dominant", patterns: ["hip hinge", "hip extension"], defaultRole: "compound" }, carry: { id: "carry", label: "Loaded carry", patterns: ["carry"], defaultRole: "event" }, olympic_lift: { id: "olympic_lift", label: "Olympic lift", patterns: ["snatch", "clean", "jerk"], defaultRole: "technical" }, trunk: { id: "trunk", label: "Trunk / core", patterns: ["anti-extension", "anti-rotation", "spinal flexion"], defaultRole: "core" }
};
export function movementFamilyFor(exercise: Exercise) { const knowledge = exerciseKnowledge(exercise.id); const pattern = knowledge?.movementPattern ?? ""; return Object.values(movementFamilies).find(f => f.patterns.some(p => pattern.includes(p))) ?? movementFamilies.trunk; }
export type ExerciseVariant = Exercise & { movementFamily: string; disciplineSuitability: TrainingDiscipline[]; accessibility: { seated?: boolean; lowImpact?: boolean; supported?: boolean }; technicalDemand: "low" | "medium" | "high" };
export function exerciseVariant(exercise: Exercise): ExerciseVariant { const family = movementFamilyFor(exercise); const k = exerciseKnowledge(exercise.id); return { ...exercise, movementFamily: family.id, disciplineSuitability: k?.programmeRole === "primary_compound" ? ["strength", "powerlifting", "hypertrophy", "general_fitness"] : ["general_fitness", "hypertrophy", "strength", "functional_fitness"], accessibility: { seated: /seated|machine|chest-supported/i.test(exercise.name), lowImpact: !/jump|run|burpee/i.test(exercise.name), supported: /machine|cable|supported/i.test(exercise.name) }, technicalDemand: k?.stabilityDemand === "high" ? "high" : k?.stabilityDemand === "medium" ? "medium" : "low" };
}
