export type TrainingGoal = "fat_loss" | "muscle_gain" | "strength" | "general_fitness";
export type TrainingExperience = "beginner" | "intermediate" | "experienced";
export type TrainingEnvironment = "full_gym" | "limited_gym" | "home_basic" | "bodyweight";
export type TrainingPriority = "balanced" | "chest" | "upper_chest" | "shoulders" | "arms" | "back_width" | "back_thickness" | "glutes" | "quads" | "hamstrings" | "calves" | "core";
export type ConditioningPreference = "post_workout" | "separate_day" | "mixed";
export type TrainingDiscipline = "general_fitness" | "fat_loss" | "hypertrophy" | "strength" | "powerlifting" | "olympic_weightlifting" | "functional_fitness" | "hybrid" | "return_to_training" | "accessible_training" | "strongman";
export type TrainingProfile = {
  goal: TrainingGoal;
  experience: TrainingExperience;
  daysPerWeek: 2 | 3 | 4 | 5 | 6;
  preferredDays?: number[];
  sessionMinutes: 45 | 60 | 75 | 90;
  environment: TrainingEnvironment;
  limitations: string[];
  dislikedExercises?: string[];
  includeCardio: boolean;
  cardioPreference?: "walking" | "cycling" | "rowing" | "mixed";
  priorities?: TrainingPriority[];
  wantedExercises?: string[];
  avoidedExercises?: string[];
  conditioningPreference?: ConditioningPreference;
  conditioningFrequency?: 0 | 1 | 2 | 3;
  lowImpactConditioning?: boolean;
  dislikedConditioning?: string[];
  discipline?: TrainingDiscipline;
  secondaryGoals?: TrainingGoal[];
  competitiveStatus?: "recreational" | "competitive" | "none";
  trainingAgeYears?: number;
  accessibility?: { seatedOnly?: boolean; reducedStandingTolerance?: boolean; limitedMobility?: boolean; impactConstraint?: boolean; balanceSupport?: boolean; limbLimitations?: string[] };
  availabilityMode?: "fixed_days" | "flexible_week" | "variable_week" | "rotating_pattern" | "work_away";
  availableDays?: number[];
};

export const defaultTrainingProfile: TrainingProfile = { goal: "general_fitness", experience: "beginner", daysPerWeek: 3, sessionMinutes: 60, environment: "full_gym", limitations: [], dislikedExercises: [], includeCardio: true, cardioPreference: "walking" };
