import crypto from "node:crypto";

const authStates = new Map<string, number>();
type Token = { accessToken: string; refreshToken?: string; expiresAt: number; scopes: string[] };
let token: Token | undefined;
export const WHOOP_SCOPES = ["offline", "read:recovery", "read:sleep", "read:cycles", "read:workout"];
export function config() { return { clientId: process.env.WHOOP_CLIENT_ID, clientSecret: process.env.WHOOP_CLIENT_SECRET, redirectUri: process.env.WHOOP_REDIRECT_URI }; }
export function createState() { const state = crypto.randomBytes(16).toString("hex"); authStates.set(state, Date.now() + 10 * 60_000); return state; }
export function consumeState(state: string) { const expires = authStates.get(state); authStates.delete(state); return Boolean(expires && expires > Date.now()); }
export function authorizationUrl(state: string) { const c = config(); if (!c.clientId || !c.redirectUri) return undefined; const params = new URLSearchParams({ client_id: c.clientId, redirect_uri: c.redirectUri, response_type: "code", scope: WHOOP_SCOPES.join(" "), state }); return `https://api.prod.whoop.com/oauth/oauth2/auth?${params}`; }
export function storeToken(next: Token) { token = next; }
export function clearToken() { token = undefined; }
export function connectionStatus() { return token ? { connected: true, expiresAt: token.expiresAt, scopes: token.scopes } : { connected: false }; }
export function tokenForServer() { return token; }
export async function exchangeCode(code: string) { const c = config(); if (!c.clientId || !c.clientSecret || !c.redirectUri) throw new Error("WHOOP is not configured"); const response = await fetch("https://api.prod.whoop.com/oauth/oauth2/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", code, client_id: c.clientId, client_secret: c.clientSecret, redirect_uri: c.redirectUri }) }); if (!response.ok) throw new Error(`WHOOP token exchange failed (${response.status})`); const body = await response.json(); storeToken({ accessToken: body.access_token, refreshToken: body.refresh_token, expiresAt: Date.now() + Number(body.expires_in ?? 3600) * 1000, scopes: String(body.scope ?? WHOOP_SCOPES.join(" ")).split(" ") }); return connectionStatus(); }
export async function accessToken() { if (!token) throw new Error("WHOOP is not connected"); if (token.expiresAt > Date.now() + 60_000) return token.accessToken; if (!token.refreshToken) throw new Error("WHOOP access expired; reconnect required"); const c = config(); const response = await fetch("https://api.prod.whoop.com/oauth/oauth2/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: token.refreshToken, client_id: c.clientId ?? "", client_secret: c.clientSecret ?? "" }) }); if (!response.ok) { clearToken(); throw new Error("WHOOP refresh failed; reconnect required"); } const body = await response.json(); storeToken({ accessToken: body.access_token, refreshToken: body.refresh_token ?? token.refreshToken, expiresAt: Date.now() + Number(body.expires_in ?? 3600) * 1000, scopes: token.scopes }); return token.accessToken; }
export function normalizeWhoop(input: any) { const score = input.score ?? {}; return { id: String(input.cycle_id ?? input.id ?? crypto.randomUUID()), date: String(input.created_at ?? new Date().toISOString()).slice(0, 10), origin: "real" as const, source: "whoop" as const, recoveryScore: score.recovery_score, hrv: score.hrv_ms, restingHeartRate: score.resting_heart_rate_milli ?? score.resting_heart_rate, strain: input.strain ?? input.score?.strain, providerId: input.cycle_id ?? input.id, syncedAt: new Date().toISOString() }; }
