import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";

export const WHOOP_SCOPES = ["offline", "read:recovery", "read:sleep", "read:cycles", "read:workout"];
export type StoredToken = { accessToken: string; refreshToken?: string; expiresAt: number; scopes: string[] };
export class WhoopStageError extends Error { constructor(public stage: string, message: string) { super(message); this.name = "WhoopStageError"; } }
export const WHOOP_CONNECTION_WRITE = { table: "whoop_connections", conflictTarget: "user_id", columns: ["user_id", "access_token_encrypted", "refresh_token_encrypted", "expires_at", "scopes", "connected_at", "updated_at"] as const };
function safeDiagnosticText(value?: string) { if (!value) return value; return value.replace(/(access|refresh|client|service|encryption)[ _-]?(token|secret|key)?\s*[:=]\s*[^\s,;]+/gi, "$1: [redacted]").slice(0, 500); }
export function sanitizedPersistenceDiagnostic(error: { code?: string; message?: string; details?: string; hint?: string }) { return { stage: "connection_persistence_failed", operation: "upsert", table: WHOOP_CONNECTION_WRITE.table, code: error.code ?? "unknown", message: safeDiagnosticText(error.message) ?? "Supabase write failed", details: safeDiagnosticText(error.details), hint: safeDiagnosticText(error.hint) }; }
export function config() { return { clientId: process.env.WHOOP_CLIENT_ID, clientSecret: process.env.WHOOP_CLIENT_SECRET, redirectUri: process.env.WHOOP_REDIRECT_URI }; }
export function createState() { return crypto.randomBytes(24).toString("base64url"); }
export function consumeState(state: string) { return state.length >= 16; }
export function statesMatch(expected: string, received: string) { const left = Buffer.from(expected); const right = Buffer.from(received); return left.length === right.length && crypto.timingSafeEqual(left, right); }
export function connectionStatus() { return { connected: false }; }
export function authorizationUrl(state: string) { const c = config(); if (!c.clientId || !c.redirectUri) return undefined; const params = new URLSearchParams({ client_id: c.clientId, redirect_uri: c.redirectUri, response_type: "code", scope: WHOOP_SCOPES.join(" "), state }); return `https://api.prod.whoop.com/oauth/oauth2/auth?${params}`; }
function key() { const raw = process.env.WHOOP_TOKEN_ENCRYPTION_KEY; if (!raw) { if (process.env.NODE_ENV === "production") throw new WhoopStageError("token_encryption_failed", "WHOOP encryption is not configured"); return crypto.createHash("sha256").update("development-only-key").digest(); } if (/^[0-9a-f]{64}$/i.test(raw)) return Buffer.from(raw, "hex"); return crypto.createHash("sha256").update(raw).digest(); }
export function encryptToken(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", key(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; }
export function decryptToken(value: string) { const [iv, tag, payload] = value.split("."); const decipher = crypto.createDecipheriv("aes-256-gcm", key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(payload, "base64url")), decipher.final()]).toString("utf8"); }
function admin() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const service = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !service) throw new Error("Supabase server storage is not configured"); return createClient(url, service, { auth: { persistSession: false, autoRefreshToken: false } }); }
export async function getConnection(userId: string) { const { data, error } = await admin().from("whoop_connections").select("user_id,access_token_encrypted,refresh_token_encrypted,expires_at,scopes,connected_at,last_sync_at").eq("user_id", userId).maybeSingle(); if (error) throw error; return data; }
export async function saveConnection(userId: string, token: StoredToken) { let accessTokenEncrypted: string; let refreshTokenEncrypted: string | null = null; try { accessTokenEncrypted = encryptToken(token.accessToken); if (token.refreshToken) refreshTokenEncrypted = encryptToken(token.refreshToken); } catch { throw new WhoopStageError("token_encryption_failed", "WHOOP token encryption failed"); } const now = new Date().toISOString(); try { const { error } = await admin().from(WHOOP_CONNECTION_WRITE.table).upsert({ user_id: userId, access_token_encrypted: accessTokenEncrypted, refresh_token_encrypted: refreshTokenEncrypted, expires_at: new Date(token.expiresAt).toISOString(), scopes: token.scopes, connected_at: now, updated_at: now }, { onConflict: WHOOP_CONNECTION_WRITE.conflictTarget }); if (error) { console.error("[whoop] persistence", sanitizedPersistenceDiagnostic(error)); throw new WhoopStageError("connection_persistence_failed", "WHOOP connection could not be saved"); } } catch (error) { if (error instanceof WhoopStageError) throw error; console.error("[whoop] persistence", sanitizedPersistenceDiagnostic(error as { message?: string })); throw new WhoopStageError("connection_persistence_failed", "WHOOP connection could not be saved"); } }
export async function clearConnection(userId: string) { const { error } = await admin().from("whoop_connections").delete().eq("user_id", userId); if (error) throw error; }
export async function markSynced(userId: string, timestamp = new Date().toISOString()) { const { error } = await admin().from("whoop_connections").update({ last_sync_at: timestamp, updated_at: timestamp }).eq("user_id", userId); if (error) throw error; return timestamp; }
export async function exchangeCode(code: string, userId: string) { const c = config(); if (!c.clientId || !c.clientSecret || !c.redirectUri) throw new WhoopStageError("token_exchange_failed", "WHOOP is not configured"); const response = await fetch("https://api.prod.whoop.com/oauth/oauth2/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", code, client_id: c.clientId, client_secret: c.clientSecret, redirect_uri: c.redirectUri }) }); if (!response.ok) throw new WhoopStageError("token_exchange_failed", "WHOOP token exchange failed"); const body = await response.json(); if (!body || typeof body.access_token !== "string") throw new WhoopStageError("token_response_invalid", "WHOOP returned an invalid token response"); const token = { accessToken: body.access_token, refreshToken: typeof body.refresh_token === "string" ? body.refresh_token : undefined, expiresAt: Date.now() + Number(body.expires_in ?? 3600) * 1000, scopes: String(body.scope ?? WHOOP_SCOPES.join(" ")).split(" ") }; await saveConnection(userId, token); return token;
}
export async function accessToken(userId: string) { const row = await getConnection(userId); if (!row) throw new Error("WHOOP is not connected"); const current: StoredToken = { accessToken: decryptToken(row.access_token_encrypted), refreshToken: row.refresh_token_encrypted ? decryptToken(row.refresh_token_encrypted) : undefined, expiresAt: Date.parse(row.expires_at), scopes: row.scopes ?? [] }; if (current.expiresAt > Date.now() + 60_000) return current.accessToken; if (!current.refreshToken) throw new Error("WHOOP access expired; reconnect required"); const c = config(); const response = await fetch("https://api.prod.whoop.com/oauth/oauth2/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: current.refreshToken, client_id: c.clientId ?? "", client_secret: c.clientSecret ?? "" }) }); if (!response.ok) { await clearConnection(userId); throw new Error("WHOOP refresh failed; reconnect required"); } const body = await response.json(); const next = { accessToken: body.access_token, refreshToken: body.refresh_token ?? current.refreshToken, expiresAt: Date.now() + Number(body.expires_in ?? 3600) * 1000, scopes: current.scopes }; await saveConnection(userId, next); return next.accessToken; }
export async function persistRecords(userId: string, records: ReturnType<typeof normalizeWhoop>[]) { if (!records.length) return; const rows = records.map(record => ({ user_id: userId, provider_id: record.providerId || record.id, record_type: "recovery", provider_timestamp: record.providerTimestamp, payload: record, synced_at: record.syncedAt })); const { error } = await admin().from("whoop_records").upsert(rows, { onConflict: "user_id,provider_id,record_type" }); if (error) throw error; }
export async function latestRecord(userId: string) { const { data, error } = await admin().from("whoop_records").select("payload").eq("user_id", userId).eq("record_type", "recovery").order("provider_timestamp", { ascending: false }).limit(1).maybeSingle(); if (error) throw error; return data?.payload ?? null; }
export function normalizeWhoop(input: any) { const score = input.score ?? {}; const timestamp = input.created_at ?? input.updated_at ?? input.start ?? new Date().toISOString(); return { id: String(input.cycle_id ?? input.id ?? crypto.randomUUID()), date: String(timestamp).slice(0, 10), origin: "real" as const, source: "whoop" as const, recoveryScore: input._recoveryScore ?? score.recovery_score, sleepPerformance: input._sleepPerformance ?? input.sleep_performance_percentage ?? score.sleep_performance_percentage ?? input.sleep?.score?.sleep_performance_percentage ?? input.sleep?.sleep_performance_percentage, hrv: input._recoveryHrv ?? score.hrv_ms, restingHeartRate: input._recoveryRestingHeartRate ?? (score.resting_heart_rate_milli ? score.resting_heart_rate_milli / 1000 : score.resting_heart_rate), strain: input._cycleStrain ?? input.strain ?? score.strain, providerId: String(input.cycle_id ?? input.id ?? ""), providerTimestamp: timestamp, syncedAt: new Date().toISOString() }; }
