"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
import type { ClubClassBooking } from "@/lib/club-operations";
type Result = { ok: true; booking: ClubClassBooking } | { ok: false; error: string };
async function context() { const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return undefined; const organisation = await resolveClubOrganisationContext(client, user.id); return organisation ? { ...organisation, userId: user.id } : undefined; }
export async function bookMemberClassAction(input: { sessionId: string; customerId?: string }): Promise<Result> { try { const resolved = await context(); if (!resolved || !input.customerId) return { ok: false, error: "Your Club account is not ready for class bookings." }; const profile = await resolved.repository.getMemberOperationalProfile(resolved.organisation.id, resolved.userId); if (profile.customer?.id !== input.customerId) return { ok: false, error: "That class booking could not be confirmed." }; const booking = await resolved.repository.createClassBooking({ sessionId: input.sessionId, customerId: input.customerId }); revalidatePath("/club"); revalidatePath("/club/classes"); return { ok: true, booking }; } catch (error) { const code = error instanceof Error ? error.message : ""; return { ok: false, error: code.includes("capacity") ? "This class is full." : code.includes("duplicate") ? "You are already booked for this class." : "This class could not be booked." }; } }
export async function cancelMemberClassAction(input: { bookingId: string }): Promise<Result> { try { const resolved = await context(); if (!resolved) return { ok: false, error: "Sign in to manage your bookings." }; const booking = await resolved.repository.cancelClassBooking(input.bookingId); revalidatePath("/club"); revalidatePath("/club/classes"); return { ok: true, booking }; } catch { return { ok: false, error: "This booking could not be cancelled." }; } }
