"use server";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOperationalContext } from "@/lib/club-server-context";
type Input={organisationId:string;userId:string;locationId:string};
async function staffContext(input:Input){const client=await serverSupabase();const{data:{user}}=await client.auth.getUser();if(!user)return null;const context=await resolveClubOperationalContext(client,user.id,input.organisationId);if(!context||!["owner","gym_admin","gym_staff"].includes(context.role))return null;return{client};}
export async function getGlowBalanceAction(input:{organisationId:string;userId:string}){const c=await serverSupabase();const{data,error}=await c.rpc("club_glow_balance",{p_organisation_id:input.organisationId,p_user_id:input.userId});if(error)return{ok:false as const,error:"Balance unavailable"};return{ok:true as const,balance:data as{minutes:number;next_expiry:string|null}};}
export async function getGlowAgeAction(input:{organisationId:string;userId:string}){const s=await staffContext({organisationId:input.organisationId,userId:input.userId,locationId:""});if(!s)return{ok:false as const};const{data,error}=await s.client.from("club_glow_age_verifications").select("date_of_birth,status").eq("organisation_id",input.organisationId).eq("user_id",input.userId).maybeSingle();if(error)return{ok:false as const};return{ok:true as const,age:data as {date_of_birth:string|null;status:string}|null};}
export async function verifyGlowAgeAction(input:Input&{dateOfBirth:string;method?:string}){const s=await staffContext(input);if(!s)return{ok:false as const,error:"Staff permission required"};const{data,error}=await s.client.rpc("club_glow_record_age_verification",{p_organisation_id:input.organisationId,p_user_id:input.userId,p_date_of_birth:input.dateOfBirth,p_method:input.method??"staff_sight_of_acceptable_id"});if(error)return{ok:false as const,error:error.message};return{ok:true as const,verification:data};}
export async function recordSunbedUseAction(input:Input&{minutes:number;idempotencyKey:string}){const s=await staffContext(input);if(!s||!Number.isInteger(input.minutes)||input.minutes<=0)return{ok:false as const,error:"Usage could not be recorded"};const{data,error}=await s.client.rpc("club_glow_spend",{p_organisation_id:input.organisationId,p_user_id:input.userId,p_location_id:input.locationId,p_minutes:input.minutes,p_idempotency_key:input.idempotencyKey});if(error)return{ok:false as const,error:error.message};return{ok:true as const,usage:data};}
export async function adjustGlowMinutesAction(input:Input&{minutes:number;reason:string;idempotencyKey:string}){const s=await staffContext(input);if(!s||!Number.isInteger(input.minutes)||input.minutes<=0||!input.reason.trim())return{ok:false as const,error:"Adjustment requires a positive amount and reason"};const{data,error}=await s.client.rpc("club_glow_grant_manual",{p_organisation_id:input.organisationId,p_user_id:input.userId,p_location_id:input.locationId,p_minutes:input.minutes,p_reason:input.reason,p_idempotency_key:input.idempotencyKey});if(error)return{ok:false as const,error:error.message};return{ok:true as const,lot:data};}
export async function removeGlowMinutesAction(input:Input&{minutes:number;reason:string;idempotencyKey:string}){const s=await staffContext(input);if(!s||!Number.isInteger(input.minutes)||input.minutes<=0||!input.reason.trim())return{ok:false as const,error:"Removal requires a positive amount and reason"};const{data,error}=await s.client.rpc("club_glow_adjust_remove",{p_organisation_id:input.organisationId,p_user_id:input.userId,p_location_id:input.locationId,p_minutes:input.minutes,p_reason:input.reason,p_idempotency_key:input.idempotencyKey});if(error)return{ok:false as const,error:error.message};return{ok:true as const,adjustment:data};}
export async function getGlowHistoryAction(input:{organisationId:string;userId:string}){const c=await serverSupabase();const{data,error}=await c.rpc("club_glow_history",{p_organisation_id:input.organisationId,p_user_id:input.userId});if(error)return{ok:false as const,history:[]};return{ok:true as const,history:(data??[]) as Array<Record<string,unknown>>};}
export async function getGlowLoyaltyAction(input:{organisationId:string;userId:string}){const c=await serverSupabase();const{data,error}=await c.rpc("club_glow_loyalty",{p_organisation_id:input.organisationId,p_user_id:input.userId});if(error)return{ok:false as const,qualifyingSessions:0,rewardEarned:false};const x=data as{qualifying_sessions?:number;reward_earned?:boolean};return{ok:true as const,qualifyingSessions:x.qualifying_sessions??0,rewardEarned:x.reward_earned===true};}
export async function searchGlowCustomersAction(input:{organisationId:string;query:string}){const s=await staffContext({organisationId:input.organisationId,userId:"",locationId:""});if(!s||input.query.trim().length<2)return{ok:false as const,results:[]};const ctx=await resolveClubOperationalContext(s.client,(await s.client.auth.getUser()).data.user!.id,input.organisationId);const results=(await ctx!.repository.listMemberSummaries(input.organisationId)).filter(x=>`${x.displayName} ${x.email??""}`.toLowerCase().includes(input.query.trim().toLowerCase())).slice(0,8).map(x=>({userId:x.userId,name:x.displayName,email:x.email??""}));return{ok:true as const,results};}
export async function completeGlowSaleAction(input:Input&{packageId:string;minutes:number;tenderType:"cash"|"external_card";idempotencyKey:string}){const s=await staffContext(input);if(!s)return{ok:false as const,error:"Staff permission required"};const{data,error}=await s.client.rpc("club_glow_complete_sale",{p_organisation_id:input.organisationId,p_location_id:input.locationId,p_user_id:input.userId,p_package_id:input.packageId,p_minutes:input.minutes,p_tender_type:input.tenderType,p_idempotency_key:input.idempotencyKey});if(error)return{ok:false as const,error:error.message};return{ok:true as const,sale:data};}
