"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";

type Result = { ok: true; status: string; orderId: string } | { ok: false; error: string };
async function context(organisationId: string) { const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return undefined; const resolved = await resolveClubOrganisationContext(client, user.id, organisationId); return resolved ? { ...resolved, userId: user.id } : undefined; }
export async function purchaseAction(input: { organisationId: string; productId: string; locationId?: string; quantity: number; payment: "balance" | "cash_box" }): Promise<Result> {
  try { const value = await context(input.organisationId); if (!value || !Number.isInteger(input.quantity) || input.quantity < 1 || input.payment === "cash_box" && !input.locationId) return { ok: false, error: input.payment === "cash_box" ? "Choose a location for cash-box payment." : "This purchase isn’t available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, userId: value.userId, channel: "member_app", currency: "GBP", items: [{ productId: input.productId, quantity: input.quantity }], idempotencyKey: crypto.randomUUID() }); if (input.payment === "balance") await value.repository.spendBalance(order.id, order.totalMinor, crypto.randomUUID()); else await value.repository.declareCash({ organisationId: value.organisation.id, locationId: input.locationId, purpose: "commerce_order", userId: value.userId, orderId: order.id, amountMinor: order.totalMinor, currency: order.currency, idempotencyKey: crypto.randomUUID() }); revalidatePath("/club/shop"); return { ok: true, status: input.payment === "balance" ? "paid" : "awaiting_cash_verification", orderId: order.id }; } catch (error) { console.error("[club-shop] purchase failed", { operation: error instanceof Error && "operation" in error ? error.operation : "purchase" }); return { ok: false, error: "Purchase couldn’t be completed." }; }
}

export async function staffCashSaleAction(input: { organisationId: string; productId: string; locationId: string; quantity: number; customerId?: string }): Promise<Result> {
  try { const value = await context(input.organisationId); if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "payments.record_cash")) || !input.productId || !input.locationId || !Number.isInteger(input.quantity) || input.quantity < 1) return { ok: false, error: "Check the sale details and your cash permissions." }; if (input.customerId && !(await value.repository.listCustomers(input.organisationId)).some(customer => customer.id === input.customerId)) return { ok: false, error: "That customer is not available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, customerId: input.customerId, channel: "staff_checkout", currency: "GBP", items: [{ productId: input.productId, quantity: input.quantity }], idempotencyKey: crypto.randomUUID() }); await value.repository.recordCashPayment(order.id, order.totalMinor, crypto.randomUUID()); await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: "payment.cash_recorded", targetType: "order", targetId: order.id }); revalidatePath("/club/shop"); return { ok: true, status: "paid", orderId: order.id }; } catch (error) { console.error("[club-shop] staff sale failed", { operation: "staff_cash_sale" }); return { ok: false, error: "Cash sale couldn’t be completed." }; }
}

export async function reconcileCashAction(input: { organisationId: string; declarationId: string; status: "confirmed" | "rejected" | "discrepancy"; notes?: string; discrepancyMinor?: number }): Promise<{ ok: true } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "cash.reconcile"))) return { ok: false, error: "You don’t have permission to reconcile cash." }; const declaration = await value.repository.reconcileCash(input.declarationId, input.status, input.notes, input.discrepancyMinor); await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: input.status === "confirmed" ? "cash.declaration_confirmed" : input.status === "discrepancy" ? "cash.discrepancy_recorded" : "cash.declaration_rejected", targetType: "cash_declaration", targetId: declaration.id, reason: input.notes }); revalidatePath("/club/shop"); revalidatePath("/club/reception"); return { ok: true }; } catch (error) { console.error("[club-shop] cash reconciliation failed", { operation: "reconcile_cash" }); return { ok: false, error: "Cash declaration couldn’t be updated." }; }
}

export async function adjustStockAction(input: { organisationId: string; locationId: string; productId: string; quantityDelta: number; reason: string }): Promise<{ ok: true } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "inventory.adjust"))) return { ok: false, error: "You don’t have permission to adjust stock." };
    if (!Number.isInteger(input.quantityDelta) || input.quantityDelta === 0 || !input.locationId || !input.productId || !input.reason.trim()) return { ok: false, error: "Enter a quantity and reason for this stock movement." };
    await value.repository.adjustInventory({ organisationId: value.organisation.id, locationId: input.locationId, productId: input.productId, movementType: "manual_adjustment", quantityDelta: input.quantityDelta, reason: input.reason.trim(), idempotencyKey: crypto.randomUUID() });
    await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: "inventory.adjusted", targetType: "commerce_product", targetId: input.productId, reason: input.reason.trim() });
    revalidatePath("/club/shop");
    return { ok: true };
  } catch (error) { console.error("[club-shop] stock adjustment failed", { operation: "adjust_inventory" }); return { ok: false, error: "Stock couldn’t be updated." }; }
}
