"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
import { parseMinorUnits } from "@/lib/club-money";
import { normalizeBarcode, OpenFoodFactsBarcodeProvider } from "@/lib/club-barcode";

type Result = { ok: true; status: string; orderId: string } | { ok: false; error: string };
async function context(organisationId: string) { const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return undefined; const resolved = await resolveClubOrganisationContext(client, user.id, organisationId); return resolved ? { ...resolved, userId: user.id } : undefined; }
async function locationAuthorized(organisationId: string, locationId: string) { const client = await serverSupabase(); const { data, error } = await client.rpc("club_location_authorized", { p_organisation_id: organisationId, p_location_id: locationId }); return !error && data === true; }
export async function purchaseAction(input: { organisationId: string; productId?: string; items?: Array<{ productId: string; quantity: number }>; locationId?: string; quantity?: number; payment: "balance" | "cash_box"; idempotencyKey?: string }): Promise<Result> {
  try { const value = await context(input.organisationId); const items = input.items ?? (input.productId && input.quantity ? [{ productId: input.productId, quantity: input.quantity }] : []); const key = input.idempotencyKey?.trim() || crypto.randomUUID(); if (!value || !items.length || input.quantity !== undefined && (!Number.isInteger(input.quantity) || input.quantity < 1) || items.some(item => !Number.isInteger(item.quantity) || item.quantity < 1) || input.payment === "cash_box" && !input.locationId) return { ok: false, error: input.payment === "cash_box" ? "Choose a location for cash-box payment." : "This purchase isn’t available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, userId: value.userId, channel: "member_app", currency: "GBP", items, idempotencyKey: key }); if (input.payment === "balance") await value.repository.spendBalance(order.id, order.totalMinor, `${key}:balance`); else await value.repository.declareCash({ organisationId: value.organisation.id, locationId: input.locationId, purpose: "commerce_order", userId: value.userId, orderId: order.id, amountMinor: order.totalMinor, currency: order.currency, idempotencyKey: `${key}:cash` }); revalidatePath("/club/shop"); return { ok: true, status: input.payment === "balance" ? "paid" : "awaiting_cash_verification", orderId: order.id }; } catch (error) { console.error("[club-shop] purchase failed", { operation: error instanceof Error && "operation" in error ? error.operation : "purchase" }); return { ok: false, error: "Purchase couldn’t be completed." }; }
}

export async function beginExternalPaymentAttemptAction(input: { organisationId: string; items: Array<{ productId: string; quantity: number }>; locationId?: string; balanceAmountMinor: number; externalMethod: "card" | "klarna" | "clearpay" | "paypal"; idempotencyKey: string }) : Promise<{ ok: true; orderId: string; attempt: unknown } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    if (!value || !input.items.length || !Number.isInteger(input.balanceAmountMinor) || input.balanceAmountMinor < 0) return { ok: false, error: "This payment isn’t available." };
    return { ok: false, error: "External payment is not configured yet. Your basket is unchanged." };
  } catch { return { ok: false, error: "Payment couldn’t be started." }; }
}

export async function cancelPaymentAttemptAction(attemptId: string, reason = "Customer cancelled") {
  try { const client = await serverSupabase(); const { data, error } = await client.rpc("club_release_payment_attempt", { p_attempt_id: attemptId, p_reason: reason }); if (error) return { ok: false, error: "Payment attempt could not be cancelled." }; return { ok: true, result: data }; } catch { return { ok: false, error: "Payment attempt could not be cancelled." }; }
}

export async function staffCashSaleAction(input: { organisationId: string; productId?: string; items?: Array<{ productId: string; quantity: number }>; locationId: string; customerId?: string; idempotencyKey?: string }): Promise<Result> {
  try { const value = await context(input.organisationId); const items = input.items ?? (input.productId ? [{ productId: input.productId, quantity: 1 }] : []); const key = input.idempotencyKey?.trim() || crypto.randomUUID(); const client = await serverSupabase(); const { data: locationAllowed } = await client.rpc("club_location_authorized", { p_organisation_id: input.organisationId, p_location_id: input.locationId }); if (!value || !locationAllowed || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "payments.record_cash")) || !input.locationId || !items.length || items.some(item => !item.productId || !Number.isInteger(item.quantity) || item.quantity < 1)) return { ok: false, error: "Check the basket and your cash permissions." }; if (input.customerId && !(await value.repository.listCustomers(input.organisationId)).some(customer => customer.id === input.customerId)) return { ok: false, error: "That customer is not available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, customerId: input.customerId, channel: "staff_checkout", currency: "GBP", items, idempotencyKey: key }); await value.repository.recordCashPayment(order.id, order.totalMinor, `${key}:cash`); await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: "payment.cash_recorded", targetType: "order", targetId: order.id }); revalidatePath("/club/shop"); return { ok: true, status: "paid", orderId: order.id }; } catch { return { ok: false, error: "Cash sale couldn’t be completed." }; }
}

export async function topUpBalanceAction(input: { organisationId: string; locationId: string; customerId: string; amount: string; notes?: string }): Promise<{ ok: true; balanceMinor: number } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); const amountMinor = parseMinorUnits(input.amount); if (!value || !(await locationAuthorized(input.organisationId, input.locationId)) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "payments.record_cash")) || !input.customerId || !input.locationId || amountMinor === undefined || amountMinor <= 0) return { ok: false, error: "Choose a member, location and valid amount." }; const entry = await value.repository.recordBalanceCashTopUp({ organisationId: value.organisation.id, locationId: input.locationId, customerId: input.customerId, amountMinor, currency: "GBP", idempotencyKey: crypto.randomUUID(), notes: input.notes }); const customer = (await value.repository.listCustomers(value.organisation.id)).find(item => item.id === input.customerId); const account = customer?.userId ? await value.repository.getBalanceAccount(value.organisation.id, customer.userId) : undefined; revalidatePath("/club/shop"); return { ok: true, balanceMinor: account?.balanceMinor ?? entry.balanceAfterMinor }; } catch { return { ok: false, error: "Balance top-up couldn’t be completed." }; }
}

export async function staffBalanceSaleAction(input: { organisationId: string; locationId: string; customerId: string; items: Array<{ productId: string; quantity: number }>; idempotencyKey?: string }): Promise<Result> {
  try { const value = await context(input.organisationId); const key = input.idempotencyKey?.trim() || crypto.randomUUID(); if (!value || !(await locationAuthorized(input.organisationId, input.locationId)) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "payments.take")) || !input.customerId || !input.locationId || !input.items.length) return { ok: false, error: "Select a member and add products." }; const customer = (await value.repository.listCustomers(value.organisation.id)).find(item => item.id === input.customerId); if (!customer) return { ok: false, error: "That member is not available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, customerId: customer.id, userId: customer.userId, channel: "staff_checkout", currency: "GBP", items: input.items, idempotencyKey: key }); await value.repository.staffSpendBalance(order.id, order.totalMinor, `${key}:balance`); revalidatePath("/club/shop"); return { ok: true, status: "paid", orderId: order.id }; } catch { return { ok: false, error: "Balance payment couldn’t be completed." }; }
}

export async function searchStaffCustomersAction(input: { organisationId: string; query: string }): Promise<{ ok: true; customers: Array<{ id: string; displayName: string; email?: string; phone?: string }> } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    const query = input.query.trim().toLocaleLowerCase();
    if (!value || !(await value.repository.hasCapability(value.organisation.id, value.userId, "members.view"))) return { ok: false, error: "Customer search is not available." };
    if (query.length < 2) return { ok: true, customers: [] };
    const [customers, members] = await Promise.all([value.repository.listCustomers(value.organisation.id), value.repository.listMemberSummaries(value.organisation.id)]);
    const memberByUser = new Map(members.map(member => [member.userId, member]));
    const results = customers.filter(customer => { const member = customer.userId ? memberByUser.get(customer.userId) : undefined; return [member?.displayName, member?.email, customer.displayName, customer.email, customer.phone].some(field => field?.toLocaleLowerCase().includes(query)); }).slice(0, 20).map(customer => { const member = customer.userId ? memberByUser.get(customer.userId) : undefined; return { id: customer.id, displayName: member?.displayName ?? customer.displayName, ...(member?.email ?? customer.email ? { email: member?.email ?? customer.email } : {}), ...(customer.phone ? { phone: customer.phone } : {}) }; });
    return { ok: true, customers: results };
  } catch { return { ok: false, error: "Customer search could not be completed." }; }
}

export async function recordMembershipCashPaymentAction(input: { organisationId: string; obligationId: string; locationId: string; amountMinor: number; currency?: string; idempotencyKey?: string }): Promise<{ ok: true } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    if (!value || !input.obligationId || !input.locationId || !Number.isInteger(input.amountMinor) || input.amountMinor <= 0 || !(await value.repository.hasCapability(value.organisation.id, value.userId, "payments.record_cash"))) return { ok: false, error: "You don’t have permission to record membership cash." };
    const { error } = await (await serverSupabase()).rpc("club_record_membership_cash_payment", { p_organisation_id: value.organisation.id, p_obligation_id: input.obligationId, p_location_id: input.locationId, p_amount_minor: input.amountMinor, p_currency: input.currency ?? "GBP", p_idempotency_key: input.idempotencyKey?.trim() || crypto.randomUUID() });
    if (error) return { ok: false, error: "Membership cash payment could not be recorded." };
    revalidatePath("/club/members"); revalidatePath("/club/membership-billing"); revalidatePath("/club/payments"); revalidatePath("/club");
    return { ok: true };
  } catch { return { ok: false, error: "Membership cash payment could not be recorded." }; }
}

export async function reconcileCashAction(input: { organisationId: string; declarationId: string; status: "confirmed" | "rejected" | "discrepancy"; notes?: string; discrepancyMinor?: number }): Promise<{ ok: true } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "cash.reconcile"))) return { ok: false, error: "You don’t have permission to reconcile cash." }; const declaration = await value.repository.reconcileCash(input.declarationId, input.status, input.notes, input.discrepancyMinor); await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: input.status === "confirmed" ? "cash.declaration_confirmed" : input.status === "discrepancy" ? "cash.discrepancy_recorded" : "cash.declaration_rejected", targetType: "cash_declaration", targetId: declaration.id, reason: input.notes }); revalidatePath("/club/shop"); revalidatePath("/club/reception"); return { ok: true }; } catch (error) { console.error("[club-shop] cash reconciliation failed", { operation: "reconcile_cash" }); return { ok: false, error: "Cash declaration couldn’t be updated." }; }
}

export async function adjustStockAction(input: { organisationId: string; locationId: string; productId: string; quantityDelta?: number; countedQuantity?: number; reason: string }): Promise<{ ok: true } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "inventory.adjust"))) return { ok: false, error: "You don’t have permission to adjust stock." };
    const counted = input.countedQuantity !== undefined;
    const countedQuantity = input.countedQuantity;
    if ((!counted && (!Number.isInteger(input.quantityDelta) || input.quantityDelta === 0)) || (counted && (countedQuantity === undefined || !Number.isInteger(countedQuantity) || countedQuantity < 0)) || !input.locationId || !input.productId || !input.reason.trim()) return { ok: false, error: "Enter a valid stock quantity and reason." };
    let quantityDelta = input.quantityDelta ?? 0;
    if (counted) { const current = (await value.repository.listStockBalances(value.organisation.id, input.locationId)).find(item => item.productId === input.productId)?.onHand; quantityDelta = input.countedQuantity! - (current ?? 0); if (quantityDelta === 0) return { ok: true }; }
    await value.repository.adjustInventory({ organisationId: value.organisation.id, locationId: input.locationId, productId: input.productId, movementType: counted ? "stocktake_adjustment" : "manual_adjustment", quantityDelta, reason: input.reason.trim(), idempotencyKey: crypto.randomUUID() });
    await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: "inventory.adjusted", targetType: "commerce_product", targetId: input.productId, reason: input.reason.trim() });
    revalidatePath("/club/shop");
    return { ok: true };
  } catch (error) { console.error("[club-shop] stock adjustment failed", { operation: "adjust_inventory" }); return { ok: false, error: "Stock couldn’t be updated." }; }
}

export async function recordStockRemovalAction(input: { organisationId: string; locationId: string; productId: string; quantity: number; reason: string; note?: string; idempotencyKey?: string }): Promise<{ ok: true } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); const key = input.idempotencyKey?.trim() || crypto.randomUUID(); if (!value || !(await value.repository.hasCapability(value.organisation.id, value.userId, "commerce.stock_remove")) || !input.locationId || !input.productId || !Number.isInteger(input.quantity) || input.quantity < 1 || !input.reason.trim()) return { ok: false, error: "Check the removal details and your permission." }; const { error } = await (await serverSupabase()).rpc("club_record_stock_removal", { p_organisation_id: value.organisation.id, p_location_id: input.locationId, p_product_id: input.productId, p_quantity: input.quantity, p_reason: input.reason, p_note: input.note?.trim() || null, p_idempotency_key: key }); if (error) return { ok: false, error: "Stock could not be removed." }; revalidatePath("/club/shop"); return { ok: true }; } catch { return { ok: false, error: "Stock could not be removed." }; }
}

export async function receiveDeliveryAction(input: { organisationId: string; locationId: string; supplierName?: string; supplierReference?: string; receivedAt?: string; notes?: string; lines: Array<{ productId: string; quantityReceived: number; unitCost?: string }> }): Promise<{ ok: true } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); if (!value || !(await locationAuthorized(input.organisationId, input.locationId)) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "supplier.receive"))) return { ok: false, error: "You don’t have permission to receive deliveries." }; if (!input.locationId || !input.lines.length || input.lines.some(line => !Number.isInteger(line.quantityReceived) || line.quantityReceived <= 0 || line.unitCost !== undefined && parseMinorUnits(line.unitCost) === undefined)) return { ok: false, error: "Add a venue and at least one valid delivery line." }; await value.repository.receiveInventoryDelivery({ organisationId: value.organisation.id, locationId: input.locationId, supplierName: input.supplierName, supplierReference: input.supplierReference, receivedAt: input.receivedAt, notes: input.notes, lines: input.lines.map(line => ({ productId: line.productId, quantityReceived: line.quantityReceived, ...(line.unitCost?.trim() ? { unitCostMinor: parseMinorUnits(line.unitCost)! } : {}) })), idempotencyKey: crypto.randomUUID() }); revalidatePath("/club/shop"); return { ok: true }; } catch { return { ok: false, error: "Delivery couldn’t be received." }; }
}

export async function saveCatalogueProductAction(input: { organisationId: string; id?: string; name: string; brand?: string; category?: string; price: string; costPrice?: string; barcode?: string; sku?: string; stockTracked: boolean; active: boolean; mediaUrl?: string }): Promise<{ ok: true; productName: string } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId); const priceMinor = parseMinorUnits(input.price); const costPriceMinor = input.costPrice?.trim() ? parseMinorUnits(input.costPrice) : undefined;
    if (!value || !["gym_admin", "owner"].includes(value.member.role)) return { ok: false, error: "Catalogue editing is limited to Club administrators." };
    if (!input.name.trim() || priceMinor === undefined || costPriceMinor === undefined && input.costPrice?.trim()) return { ok: false, error: "Enter a product name and valid GBP prices." };
    const product = await value.repository.saveCommerceProduct({ id: input.id, organisationId: value.organisation.id, name: input.name.trim(), brand: input.brand?.trim() || undefined, category: input.category?.trim() || undefined, sellPriceMinor: priceMinor, ...(costPriceMinor !== undefined ? { costPriceMinor } : {}), currency: "GBP", barcode: input.barcode?.trim() || undefined, sku: input.sku?.trim() || undefined, stockTracked: input.stockTracked, active: input.active, ...(input.mediaUrl?.trim() ? { media: { url: input.mediaUrl.trim() } } : {}) });
    await value.repository.appendAuditEvent({ organisationId: value.organisation.id, action: input.id ? "catalogue.product_updated" : "catalogue.product_created", targetType: "commerce_product", targetId: product.id });
    revalidatePath("/club/shop"); return { ok: true, productName: product.name };
  } catch (error) { console.error("[club-shop] catalogue save failed", { operation: "save_commerce_product" }); return { ok: false, error: "Product couldn’t be saved." }; }
}

export async function lookupBarcodeAction(barcode: string) { const normalized = normalizeBarcode(barcode); if (!normalized) return { ok: false as const, error: "Enter an 8–14 digit barcode." }; const candidate = await new OpenFoodFactsBarcodeProvider().lookup(normalized); return candidate ? { ok: true as const, candidate } : { ok: false as const, error: "Couldn’t identify this product online. You can still add it manually." }; }

export async function importSupplierCatalogueAction(input: { organisationId: string; supplierName: string; fileName: string; rows: unknown[] }): Promise<{ ok: true; created: number; updated: number } | { ok: false; error: string }> {
  try {
    const value = await context(input.organisationId);
    if (!value || !["gym_admin", "owner"].includes(value.member.role) || !(await value.repository.hasCapability(value.organisation.id, value.userId, "supplier.catalogue_manage"))) return { ok: false, error: "You don’t have permission to import supplier products." };
    if (!Array.isArray(input.rows) || !input.supplierName.trim() || input.supplierName.length > 160 || input.rows.length > 10000) return { ok: false, error: "Check the supplier name and import size." };
    const safe = input.rows.filter((row): row is Record<string, unknown> => Boolean(row && typeof row === "object")).map(row => ({ supplierSku: typeof row.supplierSku === "string" ? row.supplierSku.trim().slice(0, 160) : "", barcode: typeof row.barcode === "string" ? row.barcode.replace(/\s/g, "").slice(0, 32) : "", brand: typeof row.brand === "string" ? row.brand.trim().slice(0, 120) : "", name: typeof row.name === "string" ? row.name.trim().slice(0, 240) : "", variant: typeof row.variant === "string" ? row.variant.trim().slice(0, 160) : "", size: typeof row.size === "string" ? row.size.trim().slice(0, 80) : "", description: typeof row.description === "string" ? row.description.slice(0, 2000) : "", category: typeof row.category === "string" ? row.category.trim().slice(0, 120) : "", wholesaleCostMinor: Number.isInteger(row.wholesaleCostMinor) && Number(row.wholesaleCostMinor) >= 0 ? row.wholesaleCostMinor : undefined, rrpMinor: Number.isInteger(row.rrpMinor) && Number(row.rrpMinor) >= 0 ? row.rrpMinor : undefined, availability: Number.isInteger(Number(row.availability)) && Number(row.availability) >= 0 ? Number(row.availability) : undefined, imageUrl: typeof row.imageUrl === "string" ? row.imageUrl.slice(0, 1000) : "", supplierUrl: typeof row.supplierUrl === "string" ? row.supplierUrl.slice(0, 1000) : "", discontinued: row.discontinued === true }));
    if (safe.length !== input.rows.length || safe.some(row => !row.name || row.barcode && !/^\d{8,18}$/.test(row.barcode))) return { ok: false, error: "One or more supplier rows is invalid." };
    const { data, error } = await (await serverSupabase()).rpc("club_import_supplier_catalogue", { p_organisation_id: value.organisation.id, p_supplier_name: input.supplierName, p_file_name: input.fileName, p_rows: safe });
    if (error) return { ok: false, error: "Supplier catalogue could not be imported." };
    revalidatePath("/club/shop"); return { ok: true, created: Number(data?.created ?? 0), updated: Number(data?.updated ?? 0) };
  } catch { return { ok: false, error: "Supplier catalogue could not be imported." }; }
}
