"use server";
import { revalidatePath } from "next/cache";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";

type Result = { ok: true; status: string; orderId: string } | { ok: false; error: string };
async function context(organisationId: string) { const client = await serverSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) return undefined; const resolved = await resolveClubOrganisationContext(client, user.id, organisationId); return resolved ? { ...resolved, userId: user.id } : undefined; }
export async function purchaseAction(input: { organisationId: string; productId: string; locationId?: string; quantity: number; payment: "balance" | "cash_box" }): Promise<Result> {
  try { const value = await context(input.organisationId); if (!value || !Number.isInteger(input.quantity) || input.quantity < 1 || input.payment === "cash_box" && !input.locationId) return { ok: false, error: input.payment === "cash_box" ? "Choose a location for cash-box payment." : "This purchase isn’t available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, userId: value.userId, channel: "member_app", currency: "GBP", items: [{ productId: input.productId, quantity: input.quantity }], idempotencyKey: crypto.randomUUID() }); if (input.payment === "balance") await value.repository.spendBalance(order.id, order.totalMinor, crypto.randomUUID()); else await value.repository.declareCash({ organisationId: value.organisation.id, locationId: input.locationId, purpose: "commerce_order", userId: value.userId, orderId: order.id, amountMinor: order.totalMinor, currency: order.currency, idempotencyKey: crypto.randomUUID() }); revalidatePath("/club/shop"); return { ok: true, status: input.payment === "balance" ? "paid" : "awaiting_cash_verification", orderId: order.id }; } catch (error) { console.error("[club-shop] purchase failed", { operation: error instanceof Error && "operation" in error ? error.operation : "purchase" }); return { ok: false, error: "Purchase couldn’t be completed." }; }
}

export async function staffCashSaleAction(input: { organisationId: string; productId: string; locationId: string; quantity: number; customerId?: string }): Promise<Result> {
  try { const value = await context(input.organisationId); if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role) || !input.productId || !input.locationId || !Number.isInteger(input.quantity) || input.quantity < 1) return { ok: false, error: "Check the sale details and try again." }; if (input.customerId && !(await value.repository.listCustomers(input.organisationId)).some(customer => customer.id === input.customerId)) return { ok: false, error: "That customer is not available." }; const order = await value.repository.createCommerceOrder({ organisationId: value.organisation.id, locationId: input.locationId, customerId: input.customerId, channel: "staff_checkout", currency: "GBP", items: [{ productId: input.productId, quantity: input.quantity }], idempotencyKey: crypto.randomUUID() }); await value.repository.recordCashPayment(order.id, order.totalMinor, crypto.randomUUID()); revalidatePath("/club/shop"); return { ok: true, status: "paid", orderId: order.id }; } catch (error) { console.error("[club-shop] staff sale failed", { operation: "staff_cash_sale" }); return { ok: false, error: "Cash sale couldn’t be completed." }; }
}

export async function reconcileCashAction(input: { organisationId: string; declarationId: string; status: "confirmed" | "rejected" | "discrepancy"; notes?: string; discrepancyMinor?: number }): Promise<{ ok: true } | { ok: false; error: string }> {
  try { const value = await context(input.organisationId); if (!value || !["gym_staff", "gym_admin", "owner"].includes(value.member.role)) return { ok: false, error: "You don’t have permission to reconcile cash." }; await value.repository.reconcileCash(input.declarationId, input.status, input.notes, input.discrepancyMinor); revalidatePath("/club/shop"); return { ok: true }; } catch (error) { console.error("[club-shop] cash reconciliation failed", { operation: "reconcile_cash" }); return { ok: false, error: "Cash declaration couldn’t be updated." }; }
}
