#!/usr/bin/env tsx
/** Local, read-only Active Sports image enrichment and matching audit. */
import { access, readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import { parseCsvRecords } from "../lib/club-csv";

type Row = Record<string, string>;
type Source = { title: string; url: string; imageUrl?: string; imageAlt?: string; brand?: string; category?: string; stock?: string; tradePrice?: string; srp?: string };
const clean = (v: unknown) => String(v ?? "").replace(/\s+/g, " ").trim();
const norm = (v: unknown) => clean(v).toLocaleLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "");
const esc = (v: unknown) => { const s = clean(v); return /[",\n\r]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s; };
const attr = (tag: string, name: string) => tag.match(new RegExp(`\\b${name}\\s*=\\s*["']([^"']+)`, "i"))?.[1];
const absolute = (value: string | undefined, base: string) => { try { const u = new URL(value ?? "", base); return /^https?:$/.test(u.protocol) ? u.href : undefined; } catch { return undefined; } };
let rawLinksScanned = 0;
const htmlText = (value: string) => clean(value.replace(/<[^>]+>/g, " ").replace(/&amp;/gi, "&").replace(/&#39;/gi, "'").replace(/&quot;/gi, '"'));
function imageFromTag(tag: string, base: string) { for (const name of ["src", "data-src", "data-original", "data-lazy-src"]) { const url = absolute(attr(tag, name), base); if (url && !/logo|icon|sprite|placeholder|avatar/i.test(url)) return url; } for (const name of ["srcset", "data-srcset"]) { const value = attr(tag, name); const url = absolute(value?.split(",").pop()?.trim().split(/\s+/)[0], base); if (url && !/logo|icon|sprite|placeholder|avatar/i.test(url)) return url; } return undefined; }
function cleanTitle(value: string) { return htmlText(value).replace(/^go to\s+/i, "").replace(/[.]+$/, "").trim(); }
type Rejected = Source & { rejectionReason: string };
const brandAliases: Record<string,string> = { "strom sports": "Strom Sports Nutrition", "naughty boy": "Naughty Boy Lifestyle", "per4m": "Per4m Nutrition" };
function inferBrand(title: string, brands: string[]) { const lower = title.toLocaleLowerCase(); const found = brands.filter(Boolean).sort((a,b) => b.length-a.length).find(brand => lower.startsWith(brand.toLocaleLowerCase()) || lower.includes(`${brand.toLocaleLowerCase()} `)); if (found) return found; const alias = Object.entries(brandAliases).find(([key]) => lower.startsWith(`${key} `) || lower.includes(`${key} `)); return alias?.[1]; }
function pageSources(html: string, pageUrl: string, rejected: Rejected[], brands: string[]): Source[] { const out: Source[] = []; const anchors = [...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)]; const reject = /^(home|about us|contact us|my account|view basket|basket|checkout|login|register|featured products|thawte secured|privacy|terms|cookies|delivery|returns|brands?|supplement needs|strom sports nutrition|trained by jp|ufit|vitamin well|xtend)$/i; for (const match of anchors) { const url = absolute(match[1], pageUrl); if (!url || /\/account|\/login|\/register|\/basket|\/checkout/i.test(url)) continue; const inner = match[2]; const start = Math.max(0, match.index! - 900); const block = html.slice(start, Math.min(html.length, match.index! + match[0].length + 1200)); const innerImage = [...inner.matchAll(/<(?:img|source)\b[^>]*>/gi)].map(m => imageFromTag(m[0], pageUrl)).find(Boolean); const imageTag = inner.match(/<(?:img|source)\b[^>]*>/i)?.[0]; const imageUrl = innerImage ?? (imageTag ? imageFromTag(imageTag, pageUrl) : undefined); const title = cleanTitle(inner.replace(/<(?:img|source)\b[^>]*>/gi, " ")) || cleanTitle(attr(match[0], "aria-label") ?? attr(match[0], "title") ?? attr(imageTag ?? "", "alt") ?? block.match(/<(?:h2|h3|h4)\b[^>]*>([\s\S]*?)<\//i)?.[1] ?? ""); const inferred = inferBrand(title, brands); const reason = reject.test(title) ? "navigation/category/footer/security title" : !imageUrl ? "no product image in card" : !title || title.length < 5 ? "missing product title" : !/(?:product|shop|catalogue|\/(?:p|product|item)\/)/i.test(url) && !/\b(?:kg|g|ml|servings|sachet|can|tub|case|box)\b/i.test(title) ? "non-product URL/title" : ""; if (reason) { rejected.push({ title, url, imageUrl, imageAlt: imageTag ? attr(imageTag, "alt") : undefined, rejectionReason: reason }); continue; } out.push({ title, url, imageUrl, imageAlt: imageTag ? attr(imageTag, "alt") : undefined, brand: inferred ?? (htmlText(block.match(/(?:brand|vendor)["']?\s*[:=]\s*["']([^"']+)/i)?.[1] ?? "") || undefined) }); } return [...new Map(out.map(item => [`${norm(item.title)}|${item.imageUrl ?? ""}|${item.url}`, item])).values()]; }
async function fetchHtml(url: string) { const response = await fetch(url, { headers: { "user-agent": "R12 Active Sports image audit/1.1" } }); return response.ok ? response.text() : undefined; }
function crawlPriority(url: string) { const path = (() => { try { return new URL(url).pathname.toLocaleLowerCase(); } catch { return url.toLocaleLowerCase(); } })(); if (/account|login|register|basket|checkout|privacy|terms|cookie|returns|delivery/.test(path)) return 100; if (/product|catalogue|shop|category|brand|collections|page=|page\//.test(path)) return 0; return 10; }
function sizeNorm(value: string) { let v = norm(value); v = v.replace(/(\d+(?:\.\d+)?)kg/g, (_, n) => `${Math.round(Number(n) * 1000)}g`); v = v.replace(/(\d+)servings?/g, "$1servings").replace(/capsules?/g, "caps").replace(/tablets?/g, "tabs"); return v.replace(/singleserving/g, "sachet"); }
function workbookKeys(row: Row) { const brand = clean(row.Brand); const parent = clean(row["Parent Product"] || row.Product); const product = clean(row.Product || row["Parent Product"]); const supplierName = clean(row["Supplier Product"] || row["Supplier Product Name"] || row["Product Name"]); const size = clean(row["Size / Format"]); const suffix = size ? ` ${size}` : ""; return [...new Set([`${brand} ${parent}`, `${brand} ${product}`, `${brand} ${supplierName}`, `${brand} ${parent}${suffix}`, `${brand} ${product}${suffix}`, `${parent}${suffix}`, `${product}${suffix}`].map(norm).filter(Boolean))]; }
function matchScore(row: Row, source: Source) { const keys = workbookKeys(row); const title = norm(source.title); const brand = norm(row.Brand); const sourceBrand = norm(source.brand); const size = sizeNorm(row["Size / Format"] ?? ""); const sourceSize = sizeNorm(source.title); let score = 0; const keyHit = keys.find(key => title.includes(key)); if (keyHit) score += keyHit.includes(size) ? .72 : .55; else { const tokens = norm(`${row["Parent Product"] ?? ""} ${row.Product ?? ""}`).match(/[a-z0-9]{3,}/g) ?? []; score += Math.min(.45, tokens.filter(token => title.includes(token)).length * .12); } if (brand && (title.includes(brand) || (sourceBrand && sourceBrand === brand))) score += .3; if (size && sourceSize.includes(size)) score += .2; return Math.min(score, 1); }
function args() { const maxIndex = process.argv.indexOf("--max-pages"); const maxPages = maxIndex >= 0 ? Math.max(1, Number(process.argv[maxIndex + 1]) || 25) : 250; return { input: process.argv[2], outputDir: process.argv[3] ?? "./data/active-sports/enriched", baseUrl: process.argv[4], maxPages }; }
async function main() { console.log("argv:", JSON.stringify(process.argv, null, 2)); const { input, outputDir, baseUrl, maxPages } = args(); if (!input) throw new Error("Usage: active-sports-image-enrichment.ts input.csv output-dir base-url [--max-pages 25]"); const inputPath = resolve(input); const outputPath = resolve(outputDir); console.log(`Input CSV: ${inputPath}`); console.log(`Output directory: ${outputPath}`); console.log(`Base URL: ${baseUrl ?? ""}`); await mkdir(outputPath, { recursive: true }); try { await access(inputPath); } catch { throw new Error(`Input CSV does not exist: ${inputPath}`); } const csv = await readFile(inputPath, "utf8"); const rows: Row[] = (parseCsvRecords(csv, true) as Row[]).map(row => ({ ...row, Supplier: row.supplier ?? "", Brand: row.brand ?? "", "Parent Product": row["parent product"] ?? "", "Variant / Flavour": row["variant / flavour"] ?? "", "Size / Format": row["size / format"] ?? "", "Source URL": row["source url"] ?? "", "Parent Image URL": row["parent image url"] ?? "", "Variant Image URL": row["variant image url"] ?? "" })) as Row[]; const brands = [...new Set(rows.map(row => row.Brand).filter(Boolean))]; const queue = [...new Set([baseUrl, ...rows.map(row => row["Source URL"]).filter(Boolean)].filter(Boolean))]; const seen = new Set<string>(); const discoveredProductUrls = new Set<string>(); const sources: Source[] = []; const rejected: Rejected[] = []; while (queue.length && seen.size < maxPages) { queue.sort((a, b) => crawlPriority(a) - crawlPriority(b)); const url = queue.shift()!; if (seen.has(url)) continue; seen.add(url); const html = await fetchHtml(url).catch(() => undefined); if (!html) continue; const pageRecords = pageSources(html, url, rejected, brands); sources.push(...pageRecords); for (const record of pageRecords) discoveredProductUrls.add(record.url); const links = [...html.matchAll(/<a\b[^>]*href=["']([^"']+)["']/gi)].map(m => absolute(m[1], url)).filter((v): v is string => Boolean(v)); rawLinksScanned += links.length; for (const link of links) { try { if (new URL(link).hostname === new URL(url).hostname && !seen.has(link) && !/\/(?:account|login|register|basket|checkout)(?:[/?#]|$)/i.test(link)) queue.push(link); } catch { /* ignore malformed links */ } } }
 const uniqueSources = [...new Map(sources.map(source => [`${source.url}|${source.title}`, source])).values()]; if (seen.size >= 25 && (!uniqueSources.length || !uniqueSources.some(source => source.imageUrl))) console.warn("WARNING: after 25 crawled pages no product image records were found. Examples:\n" + uniqueSources.slice(0, 5).map(source => `${source.title} | ${source.url}`).join("\n"));
 const attempts: Row[] = []; const used = new Set<string>(); let matched = 0; let parentPopulated = 0; let variantPopulated = 0;
 const rankedFor = (row: Row) => uniqueSources.map(source => ({ source, score: matchScore(row, source) })).sort((a,b) => b.score-a.score);
 const enriched = rows.map((row, index) => { const ranked = rankedFor(row); const best = ranked[0]; const second = ranked[1]; const confident = Boolean(best && best.score >= .6 && (!second || best.score - second.score >= .05)); const reason = !best ? "no source candidates" : !confident ? "below confidence threshold or ambiguous" : "matched"; if (index < 100) ranked.slice(0,5).forEach(candidate => attempts.push({ rawSourceTitle: candidate.source.title, cleanedTitle: cleanTitle(candidate.source.title), sourceTitleNormalised: norm(candidate.source.title), sourceUrl: candidate.source.url, imageUrl: candidate.source.imageUrl ?? "", sourceBrand: candidate.source.brand ?? "", sourceCategory: candidate.source.category ?? "", workbookProductName: row["Parent Product"] ?? row.Product ?? "", workbookProductNormalised: norm(row["Parent Product"] ?? row.Product ?? ""), workbookBrand: row.Brand ?? "", workbookSize: row["Size / Format"] ?? "", workbookFlavour: row["Variant / Flavour"] ?? "", combinedWorkbookKey: workbookKeys(row).join(" | "), matchScore: candidate.score.toFixed(3), accepted: confident && candidate === best ? "true" : "false", rejectionReason: confident && candidate === best ? "matched" : reason } as Row)); if (confident) { used.add(`${best.source.url}|${best.source.title}`); matched++; } const next: Row = { ...row, "Parent Image URL": row["Parent Image URL"] || (confident ? best.source.imageUrl ?? "" : ""), "Variant Image URL": row["Variant Image URL"] || "", "Image Match Status": confident ? "matched" : "unmatched", "Image Match Score": best?.score.toFixed(3) ?? "0", "Image Match Source": confident ? best.source.url : "" }; if (!row["Parent Image URL"] && next["Parent Image URL"]) parentPopulated++; if (!row["Variant Image URL"] && next["Variant Image URL"]) variantPopulated++; return next; });
 const allHeaders = [...new Set([...Object.keys(rows[0] ?? {}), "Image Match Status", "Image Match Score", "Image Match Source"])]; const csvOut = (items: Row[], headers = allHeaders) => [headers.join(","), ...items.map(row => headers.map(header => esc(row[header])).join(","))].join("\n") + "\n"; await writeFile(resolve(outputPath, "enriched.csv"), csvOut(enriched));
 const sampleHeaders = ["rawSourceTitle","cleanedTitle","sourceTitleNormalised","sourceUrl","imageUrl","sourceBrand","sourceCategory","workbookProductName","workbookProductNormalised","workbookBrand","workbookSize","workbookFlavour","combinedWorkbookKey","matchScore","accepted","rejectionReason"]; await writeFile(resolve(outputPath, "extracted-source-sample.csv"), csvOut(uniqueSources.slice(0,100).map(source => ({ rawSourceTitle: source.title, cleanedTitle: cleanTitle(source.title), normalisedSourceTitle: norm(source.title), sourceUrl: source.url, imageUrl: source.imageUrl ?? "", rejectionStatus: "accepted", rejectionReason: "", accepted: "true" })), ["rawSourceTitle","cleanedTitle","normalisedSourceTitle","sourceUrl","imageUrl","rejectionStatus","rejectionReason","accepted"])); await writeFile(resolve(outputPath, "rejected-source-sample.csv"), csvOut(rejected.slice(0,100).map(source => ({ rawSourceTitle: source.title, cleanedTitle: cleanTitle(source.title), normalisedSourceTitle: norm(source.title), sourceUrl: source.url, imageUrl: source.imageUrl ?? "", rejectionStatus: "rejected", rejectionReason: source.rejectionReason, accepted: "false" })), ["rawSourceTitle","cleanedTitle","normalisedSourceTitle","sourceUrl","imageUrl","rejectionStatus","rejectionReason","accepted"])); await writeFile(resolve(outputPath, "workbook-row-sample.csv"), csvOut(rows.slice(0,100).map(row => ({ workbookProductName: row["Parent Product"] ?? row.Product ?? "", normalisedWorkbookProductName: norm(row["Parent Product"] ?? row.Product ?? ""), size: row["Size / Format"] ?? "", flavour: row["Variant / Flavour"] ?? "", sourceBrand: row.Brand ?? "" })), ["workbookProductName","normalisedWorkbookProductName","sourceBrand","size","flavour"])); await writeFile(resolve(outputPath, "match-attempt-sample.csv"), csvOut(attempts.slice(0,500), sampleHeaders));
 const unmatchedRows = enriched.filter(row => row["Image Match Status"] !== "matched"); await writeFile(resolve(outputPath, "unmatched-workbook-products.csv"), csvOut(unmatchedRows, ["Parent Product","Brand","Variant / Flavour","Size / Format","Image Match Status","Image Match Score"])); await writeFile(resolve(outputPath, "unmatched-source-products.csv"), csvOut(uniqueSources.filter(source => !used.has(`${source.url}|${source.title}`)).map(source => ({ title: source.title, brand: source.brand ?? "", category: source.category ?? "", url: source.url, imageUrl: source.imageUrl ?? "", imageAlt: source.imageAlt ?? "" })), ["title","brand","category","url","imageUrl","imageAlt"]));
 const summary = { pagesCrawled: seen.size, rawLinksScanned, uniqueProductUrlsDiscovered: discoveredProductUrls.size, candidateProductCardsBeforeFiltering: sources.length + rejected.length, rejectedNavFooterCategoryRecords: rejected.length, productCardsExtracted: uniqueSources.length, uniqueProductRecordsAccepted: uniqueSources.length, sourceRecordsWithImages: uniqueSources.filter(source => source.imageUrl).length, workbookParentFormatGroupsMatched: new Set(enriched.filter(row => row["Image Match Status"] === "matched").map(row => `${row.Brand}|${row["Parent Product"]}|${row["Size / Format"]}`)).size, workbookRowsMatched: matched, parentImageUrlsPopulated: parentPopulated, variantImageUrlsPopulated: variantPopulated, unmatchedSourceProducts: uniqueSources.filter(source => !used.has(`${source.url}|${source.title}`)).slice(0,20).map(source => source.title), unmatchedWorkbookGroups: unmatchedRows.slice(0,20).map(row => `${row.Brand ?? ""} ${row["Parent Product"] ?? row.Product ?? ""} ${row["Size / Format"] ?? ""}`), topRejectionReasons: Object.entries(rejected.reduce<Record<string, number>>((counts, item) => { counts[item.rejectionReason] = (counts[item.rejectionReason] ?? 0) + 1; return counts; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 10) }; await writeFile(resolve(outputPath, "audit-summary.json"), JSON.stringify(summary, null, 2) + "\n"); if (seen.size >= 25 && (!uniqueSources.length || !uniqueSources.some(source => source.imageUrl) || matched === 0)) console.warn("WARNING: enrichment remains unmatched after 25 pages. Extracted examples:\n" + uniqueSources.slice(0,5).map(source => `${source.title} | ${source.imageUrl ?? "no image"}`).join("\n")); console.log(JSON.stringify(summary, null, 2)); }
main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
