/* eslint-disable react-hooks/error-boundaries */
import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { AppShell, BackButton, EmptyState, PageHeader, Surface } from "@/components/ui";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext, isClubStaffRole } from "@/lib/club-server-context";
import { entitlementLabel, memberAccessState, orderStateLabel } from "@/lib/club-operational";
import type { EntitlementGrant, Membership, EntitlementUsage } from "@/lib/club";

export default async function ClubMemberProfilePage({ params, searchParams }: { params: Promise<{ userId: string }>; searchParams?: Promise<{ org?: string }> }) {
  const supabase = await serverSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account?mode=signIn");
  const { userId } = await params; const context = await resolveClubOrganisationContext(supabase, user.id, (await searchParams)?.org);
  if (!context || !isClubStaffRole(context.role)) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Member" description="This member profile is not available." /><EmptyState title="Club access required">Ask an organisation owner to confirm your operational role.</EmptyState><BackButton href="/club">Back to Club</BackButton><AppNav /></AppShell>;
  try {
    const member = context.members.find(item => item.userId === decodeURIComponent(userId)); if (!member) return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Member" description="Member profile." /><EmptyState title="Member not found">This member is not part of the selected organisation.</EmptyState><BackButton href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`}>Back to members</BackButton><AppNav /></AppShell>;
    const [customers, orders, declarations, balance] = await Promise.all([context.repository.listCustomers(context.organisation.id), context.repository.listOrders(context.organisation.id), context.repository.listCashDeclarations(context.organisation.id), context.repository.getBalanceAccount(context.organisation.id, member.userId)]);
    const customer = customers.find(item => item.userId === member.userId); const memberOrders = orders.filter(order => order.userId === member.userId || (customer && order.customerId === customer.id)); const memberDeclarations = declarations.filter(item => item.userId === member.userId || (customer && item.customerId === customer.id)); const memberMemberships: Membership[] = []; const grants: EntitlementGrant[] = []; const usage: EntitlementUsage[] = []; const access = memberAccessState(grants, memberMemberships);
    const current = undefined;
    return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · MEMBER" title={customer?.displayName ?? "Club member"} description={customer?.email ?? "Operational member profile"} /><Surface><span className="eyebrow">MEMBERSHIP</span><h2>No current membership data</h2><p className="muted">Membership detail reads are not enabled by the installed repository contract yet.</p></Surface><Surface><span className="eyebrow">ACCESS</span><h2>{access === "active" ? "Gym access active" : access === "needs_attention" ? "Membership needs attention" : "Gym access unavailable"}</h2><p className="muted">Eligibility is shown only when entitlement records are available. No access hardware action is performed here.</p></Surface><Surface><span className="eyebrow">ENTITLEMENTS</span><p className="muted">No entitlement detail reads are available in this operational surface.</p></Surface><Surface><span className="eyebrow">ACCOUNT CONTEXT</span><p className="muted">Madhouse Balance and recent Club activity</p><div className="club-detail-row"><span>Balance</span><span>{balance ? `£${(balance.balanceMinor / 100).toFixed(2)} ${balance.currency}` : "No balance account"}</span></div>{memberOrders.slice(0, 5).map(order => <div className="club-detail-row" key={order.id}><span>{order.items.map(item => item.productName).join(", ") || "Club order"}</span><span>{orderStateLabel(order.status)} · £{(order.totalMinor / 100).toFixed(2)}</span></div>)}{memberDeclarations.filter(item => item.status === "declared" || item.status === "discrepancy").map(declaration => <div className="club-detail-row" key={declaration.id}><span>Cash declaration</span><span>{declaration.status === "declared" ? "Awaiting cash verification" : "Cash needs review"}</span></div>)}</Surface><BackButton href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`}>Back to members</BackButton><AppNav /></AppShell>;
  } catch { return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB" title="Member" description="Operational profile." /><EmptyState title="Member profile couldn’t be loaded.">Try again shortly.</EmptyState><BackButton href={`/club/members?org=${encodeURIComponent(context.organisation.id)}`}>Back to members</BackButton><AppNav /></AppShell>; }
}
