-- Owner-operated ClubManager staging and reconciliation. This migration stores
-- untrusted source evidence and never creates auth users, payment history or
-- access grants during staging.
alter table public.club_staff_permission_overrides drop constraint if exists club_staff_permission_overrides_capability_check;
alter table public.club_staff_permission_overrides add constraint club_staff_permission_overrides_capability_check check (capability in ('members.view','members.create','members.link_account','memberships.assign','memberships.end_immediately','payments.take','payments.record_cash','refunds.issue','refunds.approve','cash.reconcile','inventory.adjust','commerce.stock_remove','members.import','staff.permissions_manage','induction.manage_policy','classes.manage','services.manage','supplier.catalogue_manage','supplier.orders_manage','supplier.receive','commerce.pricing_manage','commerce.collections_manage'));
-- Owner/admin import authority is explicit; staff, trainers and members do not
-- receive it through their role presets.
create or replace function public.club_capability_allowed(p_organisation_id uuid,p_user_id uuid,p_capability text)
returns boolean language sql stable security definer set search_path=pg_catalog,public as $$
  select case when auth.uid() is null or p_user_id is distinct from auth.uid() then false when p_capability not in ('members.view','members.create','members.link_account','memberships.assign','memberships.end_immediately','payments.take','payments.record_cash','refunds.issue','refunds.approve','cash.reconcile','inventory.adjust','commerce.stock_remove','members.import','staff.permissions_manage','induction.manage_policy','classes.manage','services.manage','supplier.catalogue_manage','supplier.orders_manage','supplier.receive','commerce.pricing_manage','commerce.collections_manage') then false when exists(select 1 from public.club_members m where m.organisation_id=p_organisation_id and m.user_id=auth.uid() and m.active and m.role='owner' and p_capability='staff.permissions_manage') then true when exists(select 1 from public.club_staff_permission_overrides o where o.organisation_id=p_organisation_id and o.user_id=auth.uid() and o.capability=p_capability and o.decision='deny') then false when exists(select 1 from public.club_staff_permission_overrides o where o.organisation_id=p_organisation_id and o.user_id=auth.uid() and o.capability=p_capability and o.decision='allow') then true else exists(select 1 from public.club_members m where m.organisation_id=p_organisation_id and m.user_id=auth.uid() and m.active and ((m.role='owner' and p_capability in ('members.view','members.create','members.link_account','memberships.assign','memberships.end_immediately','payments.take','payments.record_cash','refunds.issue','refunds.approve','cash.reconcile','inventory.adjust','commerce.stock_remove','members.import','staff.permissions_manage','induction.manage_policy','classes.manage','services.manage','supplier.catalogue_manage','supplier.orders_manage','supplier.receive','commerce.pricing_manage','commerce.collections_manage')) or (m.role='gym_admin' and p_capability in ('members.view','members.create','members.link_account','memberships.assign','memberships.end_immediately','payments.take','payments.record_cash','refunds.issue','refunds.approve','cash.reconcile','inventory.adjust','commerce.stock_remove','members.import','induction.manage_policy','classes.manage','services.manage','supplier.catalogue_manage','supplier.orders_manage','supplier.receive','commerce.pricing_manage','commerce.collections_manage')) or (m.role='gym_staff' and p_capability in ('members.view','members.create','members.link_account','payments.take','payments.record_cash','cash.reconcile','supplier.receive','commerce.collections_manage')) or (m.role='trainer' and p_capability='members.view'))) end;
$$;
revoke all on function public.club_capability_allowed(uuid,uuid,text) from public,anon;
grant execute on function public.club_capability_allowed(uuid,uuid,text) to authenticated;
create or replace function public.club_save_staff_permission(p_organisation_id uuid,p_user_id uuid,p_capability text,p_decision text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare r public.club_staff_permission_overrides%rowtype;
begin
 if auth.uid() is null or not public.club_has_active_role(p_organisation_id,array['owner']) then raise exception 'Staff permissions require owner access' using errcode='42501'; end if;
 if p_decision not in ('allow','deny') or p_capability not in ('members.view','members.create','members.link_account','memberships.assign','memberships.end_immediately','payments.take','payments.record_cash','refunds.issue','refunds.approve','cash.reconcile','inventory.adjust','commerce.stock_remove','members.import','staff.permissions_manage','induction.manage_policy','classes.manage','services.manage','supplier.catalogue_manage','supplier.orders_manage','supplier.receive','commerce.pricing_manage','commerce.collections_manage') then raise exception 'Invalid permission' using errcode='22023'; end if;
 if p_capability='staff.permissions_manage' and p_decision='allow' and not exists(select 1 from public.club_members where organisation_id=p_organisation_id and user_id=p_user_id and active and role='owner') then raise exception 'Owner capability cannot be granted to non-owner' using errcode='42501'; end if;
 if p_capability='staff.permissions_manage' and p_decision='deny' and p_user_id=auth.uid() then raise exception 'Owner administration cannot be denied' using errcode='42501'; end if;
 if not exists(select 1 from public.club_members where organisation_id=p_organisation_id and user_id=p_user_id and active and role in ('gym_staff','gym_admin','owner')) then raise exception 'Operational staff member not found' using errcode='P0002'; end if;
 insert into public.club_staff_permission_overrides(organisation_id,user_id,capability,decision,created_by) values(p_organisation_id,p_user_id,p_capability,p_decision,auth.uid()) on conflict(organisation_id,user_id,capability) do update set decision=excluded.decision,created_by=excluded.created_by,created_at=now() returning * into r;
 return to_jsonb(r);
end; $$;
revoke all on function public.club_save_staff_permission(uuid,uuid,text,text) from public,anon;
grant execute on function public.club_save_staff_permission(uuid,uuid,text,text) to authenticated;
create table if not exists public.club_member_import_batches (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  source_system text not null check(source_system='clubmanager'), original_filename text not null, source_checksum text,
  uploaded_by uuid not null references auth.users(id) on delete restrict, status text not null default 'uploaded' check(status in ('uploaded','mapping_required','validating','review_required','ready','importing','completed','failed','cancelled')),
  headers jsonb not null default '[]'::jsonb check(jsonb_typeof(headers)='array'), mapping jsonb not null default '{}'::jsonb check(jsonb_typeof(mapping)='object'), row_count integer not null default 0 check(row_count>=0), valid_count integer not null default 0 check(valid_count>=0), warning_count integer not null default 0 check(warning_count>=0), blocking_count integer not null default 0 check(blocking_count>=0), imported_count integer not null default 0 check(imported_count>=0), linked_count integer not null default 0 check(linked_count>=0), failed_count integer not null default 0 check(failed_count>=0), created_at timestamptz not null default now(), import_started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now(), unique(organisation_id,id,source_system), unique(id,organisation_id)
);
create table if not exists public.club_member_import_rows (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, batch_id uuid not null references public.club_member_import_batches(id) on delete cascade, source_row_number integer not null check(source_row_number>1), raw_values jsonb not null check(jsonb_typeof(raw_values)='object'), normalized_values jsonb not null default '{}'::jsonb check(jsonb_typeof(normalized_values)='object'), warnings jsonb not null default '[]'::jsonb check(jsonb_typeof(warnings)='array'), blockers jsonb not null default '[]'::jsonb check(jsonb_typeof(blockers)='array'), action text not null default 'new' check(action in ('new','exact_match','possible_match','invalid','skip')), match_candidates jsonb not null default '[]'::jsonb check(jsonb_typeof(match_candidates)='array'), imported_customer_id uuid, imported_member_id uuid, imported_membership_id uuid, outcome text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(batch_id,source_row_number), foreign key(batch_id,organisation_id) references public.club_member_import_batches(id,organisation_id) on delete cascade, foreign key(imported_customer_id,organisation_id) references public.club_customers(id,organisation_id) on delete set null, foreign key(imported_member_id,organisation_id) references public.club_members(id,organisation_id) on delete set null, foreign key(imported_membership_id,organisation_id) references public.club_memberships(id,organisation_id) on delete set null
);
create table if not exists public.club_member_import_package_mappings (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, batch_id uuid not null references public.club_member_import_batches(id) on delete cascade, source_package text not null, club_product_id uuid, status text not null default 'unmapped' check(status in ('unmapped','mapped','manual')), reason text, created_at timestamptz not null default now(), unique(batch_id,source_package), foreign key(club_product_id,organisation_id) references public.club_products(id,organisation_id) on delete restrict
);
create table if not exists public.club_member_import_identities (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, source_system text not null check(source_system='clubmanager'), source_member_reference text not null, customer_id uuid not null, first_seen_batch_id uuid not null references public.club_member_import_batches(id) on delete restrict, created_at timestamptz not null default now(), unique(organisation_id,source_system,source_member_reference), foreign key(customer_id,organisation_id) references public.club_customers(id,organisation_id) on delete restrict
);
alter table public.club_member_import_batches enable row level security; alter table public.club_member_import_rows enable row level security; alter table public.club_member_import_package_mappings enable row level security; alter table public.club_member_import_identities enable row level security;
revoke all on public.club_member_import_batches,public.club_member_import_rows,public.club_member_import_package_mappings,public.club_member_import_identities from public,anon,authenticated;

create or replace function public.club_create_member_import_batch(p_organisation_id uuid,p_filename text,p_checksum text,p_headers jsonb,p_mapping jsonb,p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare b public.club_member_import_batches%rowtype; item jsonb; n integer:=0; valid integer:=0; warnings integer:=0; blockers integer:=0; candidate_count integer; candidate_id uuid; row_action text;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'members.import') then raise exception 'Member import is not permitted' using errcode='42501'; end if;
 if nullif(btrim(p_filename),'') is null or jsonb_typeof(p_headers)<>'array' or jsonb_typeof(p_mapping)<>'object' or jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)>10000 then raise exception 'Invalid member import batch' using errcode='22023'; end if;
 insert into public.club_member_import_batches(organisation_id,source_system,original_filename,source_checksum,uploaded_by,status,headers,mapping) values(p_organisation_id,'clubmanager',left(btrim(p_filename),255),nullif(btrim(p_checksum),''),auth.uid(),'validating',p_headers,p_mapping) returning * into b;
 for item in select value from jsonb_array_elements(p_rows) loop n:=n+1; candidate_count:=0; candidate_id:=null; row_action:=coalesce(item->>'action','new'); if jsonb_typeof(item->'raw')<>'object' then blockers:=blockers+1; insert into public.club_member_import_rows(organisation_id,batch_id,source_row_number,raw_values,blockers,action) values(p_organisation_id,b.id,n+1,'{}'::jsonb,jsonb_build_array('Raw source row is invalid'),'invalid'); else if jsonb_array_length(coalesce(item->'blockers','[]'::jsonb))>0 then blockers:=blockers+1; else if nullif(btrim(item->'normalized'->>'legacyReference'),'') is not null then select customer_id into candidate_id from public.club_member_import_identities where organisation_id=p_organisation_id and source_system='clubmanager' and source_member_reference=btrim(item->'normalized'->>'legacyReference'); if candidate_id is not null then row_action:='exact_match'; candidate_count:=1; end if; end if; if candidate_id is null and nullif(btrim(item->'normalized'->>'email'),'') is not null then select count(*),min(c.id) into candidate_count,candidate_id from public.club_customers c where c.organisation_id=p_organisation_id and lower(c.email)=lower(btrim(item->'normalized'->>'email')); if candidate_count=1 then row_action:='exact_match'; elsif candidate_count>1 then row_action:='possible_match'; blockers:=blockers+1; end if; end if; valid:=valid+1; end if; warnings:=warnings+jsonb_array_length(coalesce(item->'warnings','[]'::jsonb)); insert into public.club_member_import_rows(organisation_id,batch_id,source_row_number,raw_values,normalized_values,warnings,blockers,action,match_candidates,imported_customer_id) values(p_organisation_id,b.id,coalesce((item->>'row_number')::integer,n+1),item->'raw',coalesce(item->'normalized','{}'::jsonb),coalesce(item->'warnings','[]'::jsonb),coalesce(item->'blockers','[]'::jsonb),row_action,case when candidate_id is null then '[]'::jsonb else jsonb_build_array(candidate_id) end,candidate_id); end if; end loop;
 update public.club_member_import_batches set row_count=n,valid_count=valid,warning_count=warnings,blocking_count=blockers,status=case when blockers>0 then 'review_required' else 'ready' end,updated_at=now() where id=b.id returning * into b;
 insert into public.club_audit_events(organisation_id,actor_user_id,action,target_type,target_id,metadata) values(p_organisation_id,auth.uid(),'member_import.batch_created','member_import_batch',b.id,jsonb_build_object('source_system','clubmanager','row_count',n,'blocking_count',blockers));
 return to_jsonb(b);
end; $$;

create or replace function public.club_list_member_import_batch(p_organisation_id uuid,p_batch_id uuid)
returns jsonb language sql security definer set search_path=pg_catalog,public as $$
 select jsonb_build_object('batch',to_jsonb(b),'rows',coalesce((select jsonb_agg(to_jsonb(r) order by r.source_row_number) from public.club_member_import_rows r where r.batch_id=b.id and r.organisation_id=p_organisation_id),'[]'::jsonb),'package_mappings',coalesce((select jsonb_agg(to_jsonb(m) order by m.source_package) from public.club_member_import_package_mappings m where m.batch_id=b.id and m.organisation_id=p_organisation_id),'[]'::jsonb)) from public.club_member_import_batches b where b.id=p_batch_id and b.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'members.import');
$$;

create or replace function public.club_map_member_import_package(p_organisation_id uuid,p_batch_id uuid,p_source_package text,p_club_product_id uuid,p_status text default 'mapped')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare r public.club_member_import_package_mappings%rowtype;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'members.import') then raise exception 'Member import is not permitted' using errcode='42501'; end if;
 if nullif(btrim(p_source_package),'') is null or p_status not in ('mapped','manual') or not exists(select 1 from public.club_member_import_batches where id=p_batch_id and organisation_id=p_organisation_id) then raise exception 'Invalid package mapping' using errcode='22023'; end if;
 if p_status='mapped' and not exists(select 1 from public.club_products where id=p_club_product_id and organisation_id=p_organisation_id and kind='membership' and archived_at is null) then raise exception 'Membership package is not available' using errcode='22023'; end if;
 insert into public.club_member_import_package_mappings(organisation_id,batch_id,source_package,club_product_id,status) values(p_organisation_id,p_batch_id,btrim(p_source_package),p_club_product_id,p_status) on conflict(batch_id,source_package) do update set club_product_id=excluded.club_product_id,status=excluded.status returning * into r;
 return to_jsonb(r);
end; $$;

create or replace function public.club_confirm_member_import_batch(p_organisation_id uuid,p_batch_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare b public.club_member_import_batches%rowtype;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'members.import') then raise exception 'Member import is not permitted' using errcode='42501'; end if;
 select * into b from public.club_member_import_batches where id=p_batch_id and organisation_id=p_organisation_id for update;
 if not found or b.blocking_count>0 or exists(select 1 from public.club_member_import_rows r where r.batch_id=b.id and r.organisation_id=p_organisation_id and nullif(btrim(r.normalized_values->>'membershipName'),'') is not null and not exists(select 1 from public.club_member_import_package_mappings m where m.batch_id=b.id and m.organisation_id=p_organisation_id and lower(m.source_package)=lower(btrim(r.normalized_values->>'membershipName')) and m.status in ('mapped','manual'))) then raise exception 'Resolve blocking import issues first' using errcode='22023'; end if;
 update public.club_member_import_batches set status='ready',updated_at=now() where id=b.id returning * into b;
 insert into public.club_audit_events(organisation_id,actor_user_id,action,target_type,target_id,metadata) values(p_organisation_id,auth.uid(),'member_import.authorised','member_import_batch',b.id,jsonb_build_object('row_count',b.row_count));
 return to_jsonb(b);
end; $$;

-- Execution is deliberately customer-first: imported people without an R12
-- account are retained as customers; memberships remain reviewable until an
-- account/package is explicitly linked. No auth users, payments or access are created.
create or replace function public.club_execute_member_import_batch(p_organisation_id uuid,p_batch_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare b public.club_member_import_batches%rowtype; r record; customer public.club_customers%rowtype; ref text; created integer:=0; linked integer:=0;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'members.import') then raise exception 'Member import is not permitted' using errcode='42501'; end if;
 select * into b from public.club_member_import_batches where id=p_batch_id and organisation_id=p_organisation_id for update;
 if not found or b.status not in ('ready','importing') or b.blocking_count>0 then raise exception 'Batch is not ready to import' using errcode='22023'; end if;
 update public.club_member_import_batches set status='importing',import_started_at=coalesce(import_started_at,now()),updated_at=now() where id=b.id;
 for r in select * from public.club_member_import_rows where batch_id=b.id and organisation_id=p_organisation_id and action<>'skip' and imported_customer_id is null order by source_row_number for update loop
   ref:=nullif(btrim(r.normalized_values->>'legacyReference'),'');
   if ref is not null then select customer_id into customer.id from public.club_member_import_identities where organisation_id=p_organisation_id and source_system='clubmanager' and source_member_reference=ref; end if;
   if customer.id is null then insert into public.club_customers(organisation_id,display_name,email,phone,status) values(p_organisation_id,coalesce(nullif(btrim(r.normalized_values->>'fullName'),''),concat_ws(' ',nullif(btrim(r.normalized_values->>'firstName'),''),nullif(btrim(r.normalized_values->>'lastName'),'')),'Imported member'),nullif(btrim(r.normalized_values->>'email'),''),nullif(btrim(r.normalized_values->>'phone'),''),'member') returning * into customer; created:=created+1; if ref is not null then insert into public.club_member_import_identities(organisation_id,source_system,source_member_reference,customer_id,first_seen_batch_id) values(p_organisation_id,'clubmanager',ref,customer.id,b.id) on conflict do nothing; end if; else linked:=linked+1; end if;
   update public.club_member_import_rows set imported_customer_id=customer.id,outcome='customer_staged',updated_at=now() where id=r.id;
   customer.id:=null;
 end loop;
 update public.club_member_import_rows set outcome='linked_existing',updated_at=now() where batch_id=b.id and organisation_id=p_organisation_id and imported_customer_id is not null and outcome is null;
 select count(*) into linked from public.club_member_import_rows where batch_id=b.id and organisation_id=p_organisation_id and outcome='linked_existing';
 update public.club_member_import_batches set status='completed',completed_at=now(),imported_count=created,linked_count=linked,updated_at=now() where id=b.id returning * into b;
 insert into public.club_audit_events(organisation_id,actor_user_id,action,target_type,target_id,metadata) values(p_organisation_id,auth.uid(),'member_import.completed','member_import_batch',b.id,jsonb_build_object('created',created,'linked',linked));
 return to_jsonb(b);
end; $$;

revoke all on function public.club_create_member_import_batch(uuid,text,text,jsonb,jsonb,jsonb),public.club_list_member_import_batch(uuid,uuid),public.club_map_member_import_package(uuid,uuid,text,uuid,text),public.club_confirm_member_import_batch(uuid,uuid),public.club_execute_member_import_batch(uuid,uuid) from public,anon;
grant execute on function public.club_create_member_import_batch(uuid,text,text,jsonb,jsonb,jsonb),public.club_list_member_import_batch(uuid,uuid),public.club_map_member_import_package(uuid,uuid,text,uuid,text),public.club_confirm_member_import_batch(uuid,uuid),public.club_execute_member_import_batch(uuid,uuid) to authenticated;
