-- Supplier catalogue and order-to-collection domain. Review and execute in a controlled environment.
create table if not exists public.club_suppliers (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  name text not null, active boolean not null default true, ordering_config jsonb not null default '{}'::jsonb,
  delivery_config jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index if not exists club_suppliers_org_name_uq on public.club_suppliers(organisation_id, lower(name));
create table if not exists public.club_supplier_products (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  supplier_id uuid not null references public.club_suppliers(id) on delete cascade, club_product_id uuid references public.club_commerce_products(id) on delete set null, supplier_sku text, barcode text, brand text,
  name text not null, variant text, size text, description text, category text, wholesale_cost_minor integer, supplied_vat_rate numeric,
  supplier_rrp_minor integer, supplier_availability integer, image_url text, supplier_url text, discontinued boolean not null default false,
  sellable boolean not null default false, fulfilment_type text not null default 'supplier_order_for_collection', retail_price_minor integer,
  source_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint club_supplier_products_fulfilment_ck check (fulfilment_type in ('stocked_at_location','supplier_order_for_collection','dropship'))
);
create unique index if not exists club_supplier_products_sku_uq on public.club_supplier_products(organisation_id,supplier_id,supplier_sku) where supplier_sku is not null;
-- Barcodes identify canonical Club products; multiple suppliers may offer one barcode.
create table if not exists public.club_supplier_import_batches (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  supplier_id uuid not null references public.club_suppliers(id) on delete cascade, file_name text not null, imported_by uuid not null,
  row_count integer not null default 0, created_count integer not null default 0, updated_count integer not null default 0,
  skipped_count integer not null default 0, invalid_count integer not null default 0, conflict_count integer not null default 0, created_at timestamptz not null default now()
);
create table if not exists public.club_supplier_demand (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  supplier_id uuid not null references public.club_suppliers(id), supplier_product_id uuid not null references public.club_supplier_products(id),
  order_id uuid not null references public.club_orders(id) on delete restrict, order_item_id uuid references public.club_order_items(id) on delete restrict, user_id uuid, collection_location_id uuid references public.club_locations(id) on delete restrict,
  quantity_required integer not null check (quantity_required > 0), quantity_received integer not null default 0 check (quantity_received >= 0),
  quantity_allocated integer not null default 0 check (quantity_allocated >= 0), status text not null default 'outstanding', ordered_at timestamptz,
  received_at timestamptz, ready_at timestamptz, collected_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint club_supplier_demand_status_ck check (status in ('outstanding','ordered','awaiting_delivery','received','ready_for_collection','collected','cancelled'))
);
create unique index if not exists club_supplier_demand_order_item_uq on public.club_supplier_demand(order_item_id) where order_item_id is not null;
create table if not exists public.club_notification_events (
  id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
  user_id uuid not null, event_type text not null, order_id uuid, state text not null default 'queued', payload jsonb not null default '{}'::jsonb,
  scheduled_at timestamptz, attempted_at timestamptz, provider text, provider_reference text, created_at timestamptz not null default now(),
  constraint club_notification_events_state_ck check (state in ('queued','sent','delivered','failed','retrying','manual_review'))
);
create unique index if not exists club_notification_ready_once_uq on public.club_notification_events(order_id,event_type) where event_type='order_ready_for_collection';
create table if not exists public.club_supplier_order_batches (
 id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade,
 supplier_id uuid not null references public.club_suppliers(id) on delete restrict, status text not null default 'draft' check (status in ('draft','ordered')),
 reference text not null unique, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
 ordered_by uuid references auth.users(id), ordered_at timestamptz, exported_at timestamptz, notes text, updated_at timestamptz not null default now()
);
create table if not exists public.club_supplier_order_batch_lines (
 id uuid primary key default gen_random_uuid(), batch_id uuid not null references public.club_supplier_order_batches(id) on delete restrict,
 supplier_product_id uuid not null references public.club_supplier_products(id) on delete restrict, quantity_ordered integer not null check(quantity_ordered>0),
 created_at timestamptz not null default now(), unique(batch_id,supplier_product_id)
);
alter table public.club_supplier_demand add column if not exists batch_id uuid references public.club_supplier_order_batches(id) on delete restrict;
alter table public.club_supplier_order_batch_lines enable row level security; alter table public.club_supplier_order_batches enable row level security;
revoke all on public.club_supplier_order_batches,public.club_supplier_order_batch_lines from anon,authenticated;

create or replace function public.club_create_supplier_order_batch(p_organisation_id uuid,p_supplier_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_batch public.club_supplier_order_batches%rowtype; v_d record; v_line record; v_ref text;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if;
 if not exists(select 1 from public.club_suppliers where id=p_supplier_id and organisation_id=p_organisation_id and active) then raise exception 'Supplier not found' using errcode='P0002'; end if;
 v_ref := 'SUP-'||to_char(now(),'YYYYMMDD')||'-'||lpad((select count(*)+1 from public.club_supplier_order_batches where organisation_id=p_organisation_id)::text,3,'0');
 insert into public.club_supplier_order_batches(organisation_id,supplier_id,reference,created_by) values(p_organisation_id,p_supplier_id,v_ref,auth.uid()) returning * into v_batch;
 for v_line in select supplier_product_id,sum(quantity_required)::integer quantity from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null group by supplier_product_id loop
   insert into public.club_supplier_order_batch_lines(batch_id,supplier_product_id,quantity_ordered) values(v_batch.id,v_line.supplier_product_id,v_line.quantity);
   update public.club_supplier_demand set batch_id=v_batch.id,updated_at=now() where organisation_id=p_organisation_id and supplier_id=p_supplier_id and supplier_product_id=v_line.supplier_product_id and status='outstanding' and batch_id is null;
 end loop;
 if not exists(select 1 from public.club_supplier_order_batch_lines where batch_id=v_batch.id) then delete from public.club_supplier_order_batches where id=v_batch.id; raise exception 'No outstanding supplier demand' using errcode='P0002'; end if;
 return to_jsonb(v_batch);
end; $$;
revoke all on function public.club_create_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_create_supplier_order_batch(uuid,uuid) to authenticated;
-- Replace the batching body with row locking so concurrent staff clicks cannot
-- claim the same outstanding demand into two batches.
create or replace function public.club_create_supplier_order_batch(p_organisation_id uuid,p_supplier_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare b public.club_supplier_order_batches%rowtype; l record; ref text; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if; perform 1 from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null for update; if not found then raise exception 'No outstanding supplier demand' using errcode='P0002'; end if; ref:='SUP-'||to_char(now(),'YYYYMMDD')||'-'||lpad((select count(*)+1 from public.club_supplier_order_batches where organisation_id=p_organisation_id)::text,3,'0'); insert into public.club_supplier_order_batches(organisation_id,supplier_id,reference,created_by) values(p_organisation_id,p_supplier_id,ref,auth.uid()) returning * into b; for l in select supplier_product_id,sum(quantity_required)::integer quantity from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null group by supplier_product_id loop insert into public.club_supplier_order_batch_lines(batch_id,supplier_product_id,quantity_ordered) values(b.id,l.supplier_product_id,l.quantity); update public.club_supplier_demand set batch_id=b.id,updated_at=now() where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null and supplier_product_id=l.supplier_product_id; end loop; return to_jsonb(b); end; $$;
revoke all on function public.club_create_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_create_supplier_order_batch(uuid,uuid) to authenticated;

create or replace function public.club_list_supplier_order_batches(p_organisation_id uuid)
returns jsonb language sql security definer set search_path=pg_catalog,public as $$
select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'reference',b.reference,'supplier',s.name,'status',b.status,'created_at',b.created_at,'ordered_at',b.ordered_at,'lines',(select count(*) from public.club_supplier_order_batch_lines bl where bl.batch_id=b.id),'units',(select coalesce(sum(bl.quantity_ordered),0) from public.club_supplier_order_batch_lines bl where bl.batch_id=b.id)) order by b.created_at desc),'[]'::jsonb) from public.club_supplier_order_batches b join public.club_suppliers s on s.id=b.supplier_id where b.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage');
$$;
revoke all on function public.club_list_supplier_order_batches(uuid) from public,anon; grant execute on function public.club_list_supplier_order_batches(uuid) to authenticated;

create or replace function public.club_mark_supplier_ordered(p_organisation_id uuid,p_batch_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_batch public.club_supplier_order_batches%rowtype;
begin
 if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if;
 select * into v_batch from public.club_supplier_order_batches where id=p_batch_id and organisation_id=p_organisation_id for update;
 if not found then raise exception 'Supplier order not found' using errcode='P0002'; end if;
 if v_batch.status='ordered' then return to_jsonb(v_batch); end if;
 update public.club_supplier_order_batches set status='ordered',ordered_by=auth.uid(),ordered_at=now(),updated_at=now() where id=p_batch_id returning * into v_batch;
 update public.club_supplier_demand set status='ordered',ordered_at=v_batch.ordered_at,updated_at=now() where batch_id=p_batch_id and status='outstanding';
 return to_jsonb(v_batch);
end; $$;
revoke all on function public.club_mark_supplier_ordered(uuid,uuid) from public,anon; grant execute on function public.club_mark_supplier_ordered(uuid,uuid) to authenticated;
alter table public.club_suppliers enable row level security; alter table public.club_supplier_products enable row level security;
alter table public.club_supplier_import_batches enable row level security; alter table public.club_supplier_demand enable row level security; alter table public.club_notification_events enable row level security;
-- Access is intentionally via capability-checked server functions; no browser table grants are added here.
revoke all on public.club_suppliers, public.club_supplier_products, public.club_supplier_import_batches, public.club_supplier_demand, public.club_notification_events from anon, authenticated;

create or replace function public.club_import_supplier_catalogue(p_organisation_id uuid, p_supplier_name text, p_file_name text, p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_supplier uuid; v_batch uuid; v_row jsonb; v_product uuid; v_created integer:=0; v_updated integer:=0; v_conflicts integer:=0;
begin
  if auth.uid() is null or not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.catalogue_manage') then raise exception 'Supplier catalogue import is not permitted' using errcode='42501'; end if;
  if p_organisation_id is null or nullif(btrim(p_supplier_name),'') is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) > 10000 then raise exception 'Invalid supplier import' using errcode='22023'; end if;
  insert into public.club_suppliers(organisation_id,name) values(p_organisation_id,btrim(p_supplier_name)) on conflict (organisation_id,lower(name)) do update set active=true,updated_at=now() returning id into v_supplier;
  insert into public.club_supplier_import_batches(organisation_id,supplier_id,file_name,imported_by,row_count) values(p_organisation_id,v_supplier,coalesce(nullif(btrim(p_file_name),''),'supplier.csv'),auth.uid(),jsonb_array_length(coalesce(p_rows,'[]'::jsonb))) returning id into v_batch;
  for v_row in select value from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) loop
    if nullif(btrim(v_row->>'name'),'') is null then update public.club_supplier_import_batches set invalid_count=invalid_count+1 where id=v_batch; continue; end if;
    v_product := null;
    if nullif(btrim(v_row->>'supplierSku'),'') is not null then select id into v_product from public.club_supplier_products where organisation_id=p_organisation_id and supplier_id=v_supplier and supplier_sku=btrim(v_row->>'supplierSku') limit 1; end if;
    if v_product is null then insert into public.club_supplier_products(organisation_id,supplier_id,supplier_sku,barcode,brand,name,variant,size,description,category,wholesale_cost_minor,supplier_rrp_minor,supplier_availability,image_url,supplier_url,discontinued) values(p_organisation_id,v_supplier,nullif(btrim(v_row->>'supplierSku'),''),nullif(btrim(v_row->>'barcode'),''),nullif(btrim(v_row->>'brand'),''),btrim(v_row->>'name'),nullif(btrim(v_row->>'variant'),''),nullif(btrim(v_row->>'size'),''),nullif(v_row->>'description',''),nullif(btrim(v_row->>'category'),''),nullif(v_row->>'wholesaleCostMinor','')::integer,nullif(v_row->>'rrpMinor','')::integer,nullif(v_row->>'availability','')::integer,nullif(v_row->>'imageUrl',''),nullif(v_row->>'supplierUrl',''),coalesce((v_row->>'discontinued')::boolean,false)) returning id into v_product; v_created:=v_created+1;
    else update public.club_supplier_products set barcode=nullif(btrim(v_row->>'barcode'),''),brand=nullif(btrim(v_row->>'brand'),''),name=btrim(v_row->>'name'),variant=nullif(btrim(v_row->>'variant'),''),size=nullif(btrim(v_row->>'size'),''),description=nullif(v_row->>'description',''),category=nullif(btrim(v_row->>'category'),''),wholesale_cost_minor=nullif(v_row->>'wholesaleCostMinor','')::integer,supplier_rrp_minor=nullif(v_row->>'rrpMinor','')::integer,supplier_availability=nullif(v_row->>'availability','')::integer,image_url=nullif(v_row->>'imageUrl',''),supplier_url=nullif(v_row->>'supplierUrl',''),discontinued=coalesce((v_row->>'discontinued')::boolean,false),updated_at=now() where id=v_product; v_updated:=v_updated+1; end if;
  end loop;
  update public.club_supplier_import_batches set created_count=v_created,updated_count=v_updated where id=v_batch;
  return jsonb_build_object('batchId',v_batch,'created',v_created,'updated',v_updated);
end; $$;
revoke all on function public.club_import_supplier_catalogue(uuid,text,text,jsonb) from public,anon;
grant execute on function public.club_import_supplier_catalogue(uuid,text,text,jsonb) to authenticated;

create or replace function public.club_create_supplier_demand_for_order(p_order_id uuid)
returns integer language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_order record; v_item record; v_offer record; v_count integer:=0;
begin
  select o.* into v_order from public.club_orders o where o.id=p_order_id and o.status in ('paid','fulfilled');
  if not found then return 0; end if;
  for v_item in select i.* from public.club_order_items i where i.order_id=p_order_id loop
    select count(*) as count into v_count from public.club_supplier_products sp where sp.organisation_id=v_order.organisation_id and sp.club_product_id=v_item.product_id and sp.sellable and not sp.discontinued and sp.fulfilment_type='supplier_order_for_collection';
    if v_count <> 1 then continue; end if;
    select sp.* into v_offer from public.club_supplier_products sp where sp.organisation_id=v_order.organisation_id and sp.club_product_id=v_item.product_id and sp.sellable and not sp.discontinued and sp.fulfilment_type='supplier_order_for_collection' limit 1;
    insert into public.club_supplier_demand(organisation_id,supplier_id,supplier_product_id,order_id,order_item_id,user_id,collection_location_id,quantity_required)
    values(v_order.organisation_id,v_offer.supplier_id,v_offer.id,v_order.id,v_item.id,v_order.user_id,v_order.location_id,v_item.quantity)
    on conflict (order_item_id) do nothing;
  end loop;
  return 1;
end; $$;
revoke all on function public.club_create_supplier_demand_for_order(uuid) from public,anon,authenticated;
create or replace function public.club_after_payment_supplier_demand() returns trigger language plpgsql security definer set search_path=pg_catalog,public as $$ begin if new.status='paid' then perform public.club_create_supplier_demand_for_order(new.order_id); end if; return new; end; $$;
drop trigger if exists club_payments_supplier_demand on public.club_payments;
create trigger club_payments_supplier_demand after insert or update of status on public.club_payments for each row execute function public.club_after_payment_supplier_demand();

create or replace function public.club_list_supplier_demand(p_organisation_id uuid)
returns jsonb language sql security definer set search_path=pg_catalog,public as $$
select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'supplier',s.name,'supplier_sku',sp.supplier_sku,'barcode',sp.barcode,'product',coalesce(cp.name,sp.name),'brand',coalesce(cp.brand,sp.brand),'variant',sp.variant,'quantity_required',d.quantity_required,'quantity_received',d.quantity_received,'quantity_allocated',d.quantity_allocated,'status',d.status,'order_reference',left(d.order_id::text,8),'collection_location',l.name) order by s.name,sp.name), '[]'::jsonb)
from public.club_supplier_demand d join public.club_suppliers s on s.id=d.supplier_id join public.club_supplier_products sp on sp.id=d.supplier_product_id left join public.club_commerce_products cp on cp.id=sp.club_product_id left join public.club_locations l on l.id=d.collection_location_id
where d.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage');
$$;
revoke all on function public.club_list_supplier_demand(uuid) from public,anon;
grant execute on function public.club_list_supplier_demand(uuid) to authenticated;
-- Include supplier_id for trusted batch creation while retaining the human name.
create or replace function public.club_list_supplier_demand(p_organisation_id uuid) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select coalesce(jsonb_agg(jsonb_build_object('id',d.id,'supplier_id',d.supplier_id,'supplier',s.name,'supplier_sku',sp.supplier_sku,'barcode',sp.barcode,'product',coalesce(cp.name,sp.name),'brand',coalesce(cp.brand,sp.brand),'variant',sp.variant,'quantity_required',d.quantity_required,'quantity_received',d.quantity_received,'quantity_allocated',d.quantity_allocated,'status',d.status,'order_reference',left(d.order_id::text,8),'collection_location',l.name) order by s.name,sp.name),'[]'::jsonb) from public.club_supplier_demand d join public.club_suppliers s on s.id=d.supplier_id join public.club_supplier_products sp on sp.id=d.supplier_product_id left join public.club_commerce_products cp on cp.id=sp.club_product_id left join public.club_locations l on l.id=d.collection_location_id where d.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage'); $$;
revoke all on function public.club_list_supplier_demand(uuid) from public,anon; grant execute on function public.club_list_supplier_demand(uuid) to authenticated;

create table if not exists public.club_supplier_order_batches (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, supplier_id uuid not null references public.club_suppliers(id) on delete restrict, status text not null default 'draft' check(status in ('draft','ordered')), reference text not null unique, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), ordered_by uuid references auth.users(id), ordered_at timestamptz, updated_at timestamptz not null default now());
alter table public.club_supplier_order_batches drop constraint if exists club_supplier_order_batches_status_check;
alter table public.club_supplier_order_batches add constraint club_supplier_order_batches_status_check check(status in ('draft','ordered','partially_received','received'));
create table if not exists public.club_supplier_order_batch_lines (id uuid primary key default gen_random_uuid(), batch_id uuid not null references public.club_supplier_order_batches(id) on delete restrict, supplier_product_id uuid not null references public.club_supplier_products(id) on delete restrict, quantity_ordered integer not null check(quantity_ordered>0), unique(batch_id,supplier_product_id));
alter table public.club_supplier_demand add column if not exists batch_id uuid references public.club_supplier_order_batches(id) on delete restrict;
alter table public.club_supplier_order_batches enable row level security; alter table public.club_supplier_order_batch_lines enable row level security;
revoke all on public.club_supplier_order_batches,public.club_supplier_order_batch_lines from anon,authenticated;

create or replace function public.club_create_supplier_order_batch(p_organisation_id uuid,p_supplier_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare b public.club_supplier_order_batches%rowtype; l record; ref text;
begin
 if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if;
 if not exists(select 1 from public.club_suppliers where id=p_supplier_id and organisation_id=p_organisation_id and active) then raise exception 'Supplier not found' using errcode='P0002'; end if;
 ref:='SUP-'||to_char(now(),'YYYYMMDD')||'-'||lpad((select count(*)+1 from public.club_supplier_order_batches where organisation_id=p_organisation_id)::text,3,'0');
 insert into public.club_supplier_order_batches(organisation_id,supplier_id,reference,created_by) values(p_organisation_id,p_supplier_id,ref,auth.uid()) returning * into b;
 for l in select supplier_product_id,sum(quantity_required)::integer quantity from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null group by supplier_product_id loop
  insert into public.club_supplier_order_batch_lines(batch_id,supplier_product_id,quantity_ordered) values(b.id,l.supplier_product_id,l.quantity);
  update public.club_supplier_demand set batch_id=b.id,updated_at=now() where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null and supplier_product_id=l.supplier_product_id;
 end loop;
 if not exists(select 1 from public.club_supplier_order_batch_lines where batch_id=b.id) then delete from public.club_supplier_order_batches where id=b.id; raise exception 'No outstanding supplier demand' using errcode='P0002'; end if;
 return to_jsonb(b);
end; $$;
revoke all on function public.club_create_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_create_supplier_order_batch(uuid,uuid) to authenticated;

create or replace function public.club_list_supplier_order_batches(p_organisation_id uuid) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'reference',b.reference,'supplier',s.name,'status',b.status,'created_at',b.created_at,'ordered_at',b.ordered_at,'lines',(select count(*) from public.club_supplier_order_batch_lines x where x.batch_id=b.id),'units',(select coalesce(sum(x.quantity_ordered),0) from public.club_supplier_order_batch_lines x where x.batch_id=b.id)) order by b.created_at desc),'[]'::jsonb) from public.club_supplier_order_batches b join public.club_suppliers s on s.id=b.supplier_id where b.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage'); $$;
revoke all on function public.club_list_supplier_order_batches(uuid) from public,anon; grant execute on function public.club_list_supplier_order_batches(uuid) to authenticated;

create or replace function public.club_mark_supplier_ordered(p_organisation_id uuid,p_batch_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare b public.club_supplier_order_batches%rowtype; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if; select * into b from public.club_supplier_order_batches where id=p_batch_id and organisation_id=p_organisation_id for update; if not found then raise exception 'Supplier order not found' using errcode='P0002'; end if; if b.status='ordered' then return to_jsonb(b); end if; update public.club_supplier_order_batches set status='ordered',ordered_by=auth.uid(),ordered_at=now(),updated_at=now() where id=p_batch_id returning * into b; update public.club_supplier_demand set status='ordered',ordered_at=b.ordered_at,updated_at=now() where batch_id=p_batch_id and status='outstanding'; return to_jsonb(b); end; $$;
revoke all on function public.club_mark_supplier_ordered(uuid,uuid) from public,anon; grant execute on function public.club_mark_supplier_ordered(uuid,uuid) to authenticated;

create or replace function public.club_get_supplier_order_batch(p_organisation_id uuid,p_batch_id uuid) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select jsonb_build_object('batch',to_jsonb(b),'supplier',s.name,'lines',coalesce((select jsonb_agg(jsonb_build_object('supplier_sku',sp.supplier_sku,'barcode',sp.barcode,'brand',sp.brand,'product',sp.name,'variant',sp.variant,'size',sp.size,'quantity',bl.quantity_ordered) order by sp.name) from public.club_supplier_order_batch_lines bl join public.club_supplier_products sp on sp.id=bl.supplier_product_id where bl.batch_id=b.id),'[]'::jsonb)) from public.club_supplier_order_batches b join public.club_suppliers s on s.id=b.supplier_id where b.id=p_batch_id and b.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage'); $$;
revoke all on function public.club_get_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_get_supplier_order_batch(uuid,uuid) to authenticated;
create or replace function public.club_list_member_supplier_fulfilment(p_organisation_id uuid,p_user_id uuid) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select coalesce(jsonb_agg(jsonb_build_object('order_id',d.order_id,'status',case when d.status='ordered' then 'awaiting_delivery' when d.status='ready_for_collection' then 'ready_for_collection' else d.status end,'quantity_required',d.quantity_required,'quantity_allocated',d.quantity_allocated) order by d.created_at desc),'[]'::jsonb) from public.club_supplier_demand d where d.organisation_id=p_organisation_id and d.user_id=p_user_id and auth.uid()=p_user_id; $$;
revoke all on function public.club_list_member_supplier_fulfilment(uuid,uuid) from public,anon; grant execute on function public.club_list_member_supplier_fulfilment(uuid,uuid) to authenticated;

create table if not exists public.club_supplier_order_counters (organisation_id uuid primary key references public.club_organisations(id) on delete cascade, next_value integer not null default 1);
create table if not exists public.club_supplier_receipts (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, batch_id uuid not null references public.club_supplier_order_batches(id) on delete restrict, supplier_id uuid not null references public.club_suppliers(id) on delete restrict, received_by uuid not null references auth.users(id), received_at timestamptz not null default now(), idempotency_key text not null, notes text, created_at timestamptz not null default now(), unique(organisation_id,idempotency_key));
create table if not exists public.club_supplier_receipt_lines (id uuid primary key default gen_random_uuid(), receipt_id uuid not null references public.club_supplier_receipts(id) on delete restrict, batch_line_id uuid not null references public.club_supplier_order_batch_lines(id) on delete restrict, quantity_received integer not null check(quantity_received>0), notes text, created_at timestamptz not null default now());
create table if not exists public.club_supplier_allocations (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.club_organisations(id) on delete cascade, receipt_line_id uuid not null references public.club_supplier_receipt_lines(id) on delete restrict, demand_id uuid not null references public.club_supplier_demand(id) on delete restrict, quantity_allocated integer not null check(quantity_allocated>0), allocated_by uuid not null references auth.users(id), allocated_at timestamptz not null default now());
alter table public.club_supplier_order_counters enable row level security; alter table public.club_supplier_receipts enable row level security; alter table public.club_supplier_receipt_lines enable row level security; alter table public.club_supplier_allocations enable row level security;
revoke all on public.club_supplier_order_counters,public.club_supplier_receipts,public.club_supplier_receipt_lines,public.club_supplier_allocations from anon,authenticated;

create or replace function public.club_create_supplier_order_batch(p_organisation_id uuid,p_supplier_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare b public.club_supplier_order_batches%rowtype; l record; n integer; ref text; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage') then raise exception 'Supplier ordering is not permitted' using errcode='42501'; end if; perform 1 from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null for update; if not found then raise exception 'No outstanding supplier demand' using errcode='P0002'; end if; insert into public.club_supplier_order_counters(organisation_id,next_value) values(p_organisation_id,2) on conflict(organisation_id) do update set next_value=club_supplier_order_counters.next_value+1 returning next_value-1 into n; ref:='SUP-'||to_char(now(),'YYYYMMDD')||'-'||lpad(n::text,4,'0'); insert into public.club_supplier_order_batches(organisation_id,supplier_id,reference,created_by) values(p_organisation_id,p_supplier_id,ref,auth.uid()) returning * into b; for l in select supplier_product_id,sum(quantity_required)::integer quantity from public.club_supplier_demand where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null group by supplier_product_id loop insert into public.club_supplier_order_batch_lines(batch_id,supplier_product_id,quantity_ordered) values(b.id,l.supplier_product_id,l.quantity); update public.club_supplier_demand set batch_id=b.id,updated_at=now() where organisation_id=p_organisation_id and supplier_id=p_supplier_id and status='outstanding' and batch_id is null and supplier_product_id=l.supplier_product_id; end loop; return to_jsonb(b); end; $$;
revoke all on function public.club_create_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_create_supplier_order_batch(uuid,uuid) to authenticated;

create or replace function public.club_receive_supplier_delivery(p_organisation_id uuid,p_batch_id uuid,p_idempotency_key text,p_lines jsonb,p_notes text default null) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare b public.club_supplier_order_batches%rowtype; r public.club_supplier_receipts%rowtype; line jsonb; bl public.club_supplier_order_batch_lines%rowtype; remaining integer; qty integer; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.receive') then raise exception 'Supplier receiving is not permitted' using errcode='42501'; end if; if nullif(btrim(p_idempotency_key),'') is null or jsonb_typeof(p_lines)<>'array' then raise exception 'Invalid receipt' using errcode='22023'; end if; select * into b from public.club_supplier_order_batches where id=p_batch_id and organisation_id=p_organisation_id for update; if not found or b.status='draft' then raise exception 'Supplier order is not receivable' using errcode='P0002'; end if; select * into r from public.club_supplier_receipts where organisation_id=p_organisation_id and idempotency_key=p_idempotency_key; if found then return to_jsonb(r); end if; insert into public.club_supplier_receipts(organisation_id,batch_id,supplier_id,received_by,idempotency_key,notes) values(p_organisation_id,b.id,b.supplier_id,auth.uid(),p_idempotency_key,p_notes) returning * into r; for line in select value from jsonb_array_elements(p_lines) loop qty:=coalesce((line->>'quantityReceived')::integer,0); select * into bl from public.club_supplier_order_batch_lines where id=(line->>'batchLineId')::uuid and batch_id=b.id for update; if not found or qty<1 then raise exception 'Invalid receipt line' using errcode='22023'; end if; select bl.quantity_ordered-coalesce(sum(rl.quantity_received),0) into remaining from public.club_supplier_receipt_lines rl where rl.batch_line_id=bl.id; if qty>remaining then raise exception 'Receipt exceeds ordered quantity' using errcode='22023'; end if; insert into public.club_supplier_receipt_lines(receipt_id,batch_line_id,quantity_received,notes) values(r.id,bl.id,qty,line->>'notes'); end loop; update public.club_supplier_order_batches set status=case when not exists(select 1 from public.club_supplier_order_batch_lines bl where bl.batch_id=b.id and bl.quantity_ordered>coalesce((select sum(quantity_received) from public.club_supplier_receipt_lines rl where rl.batch_line_id=bl.id),0)) then 'received' when exists(select 1 from public.club_supplier_receipt_lines rl join public.club_supplier_order_batch_lines bl on bl.id=rl.batch_line_id where bl.batch_id=b.id) then 'partially_received' else 'ordered' end,updated_at=now() where id=b.id; return to_jsonb(r); end; $$;
revoke all on function public.club_receive_supplier_delivery(uuid,uuid,text,jsonb,text) from public,anon; grant execute on function public.club_receive_supplier_delivery(uuid,uuid,text,jsonb,text) to authenticated;

create or replace function public.club_allocate_supplier_units(p_organisation_id uuid,p_receipt_line_id uuid,p_demand_id uuid,p_quantity integer) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare rl public.club_supplier_receipt_lines%rowtype; d public.club_supplier_demand%rowtype; allocated integer; order_ready boolean; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.receive') then raise exception 'Supplier allocation is not permitted' using errcode='42501'; end if; if p_quantity<1 then raise exception 'Invalid allocation' using errcode='22023'; end if; select * into rl from public.club_supplier_receipt_lines where id=p_receipt_line_id for update; select * into d from public.club_supplier_demand where id=p_demand_id and organisation_id=p_organisation_id for update; if not found or rl.id is null then raise exception 'Allocation target not found' using errcode='P0002'; end if; if not exists(select 1 from public.club_supplier_order_batch_lines bl join public.club_supplier_receipts r on r.batch_id=bl.batch_id where bl.id=rl.batch_line_id and r.organisation_id=p_organisation_id) or not exists(select 1 from public.club_supplier_order_batch_lines bl where bl.id=rl.batch_line_id and bl.supplier_product_id=d.supplier_product_id and d.batch_id=bl.batch_id) then raise exception 'Allocation product or batch mismatch' using errcode='22023'; end if; select coalesce(sum(a.quantity_allocated),0) into allocated from public.club_supplier_allocations a where a.receipt_line_id=rl.id; if p_quantity+allocated>rl.quantity_received then raise exception 'Allocation exceeds received quantity' using errcode='22023'; end if; if p_quantity+d.quantity_allocated>d.quantity_required then raise exception 'Allocation exceeds demand' using errcode='22023'; end if; insert into public.club_supplier_allocations(organisation_id,receipt_line_id,demand_id,quantity_allocated,allocated_by) values(p_organisation_id,rl.id,d.id,p_quantity,auth.uid()); update public.club_supplier_demand set quantity_allocated=quantity_allocated+p_quantity,quantity_received=greatest(quantity_received,quantity_allocated+p_quantity),updated_at=now() where id=d.id returning * into d; if d.quantity_allocated>=d.quantity_required and d.quantity_received>=d.quantity_required then update public.club_supplier_demand set status='ready_for_collection',ready_at=coalesce(ready_at,now()),updated_at=now() where id=d.id; end if; select not exists(select 1 from public.club_supplier_demand x where x.order_id=d.order_id and x.status not in ('ready_for_collection','collected','cancelled')) into order_ready; if order_ready then insert into public.club_notification_events(organisation_id,user_id,event_type,order_id,payload) values(p_organisation_id,d.user_id,'order_ready_for_collection',d.order_id,jsonb_build_object('state','queued')) on conflict(order_id,event_type) do nothing; end if; return to_jsonb(d); end; $$;
revoke all on function public.club_allocate_supplier_units(uuid,uuid,uuid,integer) from public,anon; grant execute on function public.club_allocate_supplier_units(uuid,uuid,uuid,integer) to authenticated;
create or replace function public.club_get_supplier_order_batch(p_organisation_id uuid,p_batch_id uuid) returns jsonb language sql security definer set search_path=pg_catalog,public as $$ select jsonb_build_object('batch',to_jsonb(b),'supplier',s.name,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',bl.id,'supplier_sku',sp.supplier_sku,'barcode',sp.barcode,'brand',sp.brand,'product',sp.name,'variant',sp.variant,'size',sp.size,'quantity',bl.quantity_ordered,'received',(select coalesce(sum(quantity_received),0) from public.club_supplier_receipt_lines where batch_line_id=bl.id)) order by sp.name) from public.club_supplier_order_batch_lines bl join public.club_supplier_products sp on sp.id=bl.supplier_product_id where bl.batch_id=b.id),'[]'::jsonb)) from public.club_supplier_order_batches b join public.club_suppliers s on s.id=b.supplier_id where b.id=p_batch_id and b.organisation_id=p_organisation_id and public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.orders_manage'); $$;
revoke all on function public.club_get_supplier_order_batch(uuid,uuid) from public,anon; grant execute on function public.club_get_supplier_order_batch(uuid,uuid) to authenticated;
-- Correct demand accounting: allocated units contribute to that demand's received share.
create or replace function public.club_allocate_supplier_units(p_organisation_id uuid,p_receipt_line_id uuid,p_demand_id uuid,p_quantity integer) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$ declare rl public.club_supplier_receipt_lines%rowtype; d public.club_supplier_demand%rowtype; used integer; ready boolean; begin if not public.club_capability_allowed(p_organisation_id,auth.uid(),'supplier.receive') or p_quantity<1 then raise exception 'Supplier allocation is not permitted' using errcode='42501'; end if; select * into rl from public.club_supplier_receipt_lines where id=p_receipt_line_id for update; select * into d from public.club_supplier_demand where id=p_demand_id and organisation_id=p_organisation_id for update; if not found then raise exception 'Allocation target not found' using errcode='P0002'; end if; if not exists(select 1 from public.club_supplier_order_batch_lines bl join public.club_supplier_receipts r on r.batch_id=bl.batch_id where bl.id=rl.batch_line_id and r.organisation_id=p_organisation_id and bl.supplier_product_id=d.supplier_product_id and d.batch_id=bl.batch_id) then raise exception 'Allocation product or batch mismatch' using errcode='22023'; end if; select coalesce(sum(quantity_allocated),0) into used from public.club_supplier_allocations where receipt_line_id=rl.id; if used+p_quantity>rl.quantity_received or d.quantity_allocated+p_quantity>d.quantity_required then raise exception 'Allocation exceeds available quantity' using errcode='22023'; end if; insert into public.club_supplier_allocations(organisation_id,receipt_line_id,demand_id,quantity_allocated,allocated_by) values(p_organisation_id,rl.id,d.id,p_quantity,auth.uid()); update public.club_supplier_demand set quantity_allocated=quantity_allocated+p_quantity,quantity_received=quantity_received+p_quantity,updated_at=now() where id=d.id returning * into d; if d.quantity_allocated>=d.quantity_required then update public.club_supplier_demand set status='ready_for_collection',ready_at=coalesce(ready_at,now()),updated_at=now() where id=d.id; end if; select not exists(select 1 from public.club_supplier_demand x where x.order_id=d.order_id and x.status not in ('ready_for_collection','collected','cancelled')) into ready; if ready then insert into public.club_notification_events(organisation_id,user_id,event_type,order_id,payload) values(p_organisation_id,d.user_id,'order_ready_for_collection',d.order_id,jsonb_build_object('state','queued')) on conflict(order_id,event_type) do nothing; end if; return to_jsonb(d); end; $$;
revoke all on function public.club_allocate_supplier_units(uuid,uuid,uuid,integer) from public,anon; grant execute on function public.club_allocate_supplier_units(uuid,uuid,uuid,integer) to authenticated;

-- Collection handover: customer allocation is reserved stock, never a free-stock movement.
alter table public.club_supplier_demand add column if not exists collected_by uuid references auth.users(id) on delete restrict;
create or replace function public.club_list_ready_collections(p_organisation_id uuid,p_location_id uuid default null)
returns jsonb language sql security definer set search_path=pg_catalog,public as $$
select coalesce(jsonb_agg(jsonb_build_object('order_id',x.order_id,'order_reference',left(x.order_id::text,8),'member_name',coalesce(c.display_name,'Member'),'collection_location',coalesce(l.name,'Collection desk'),'ready_at',x.ready_at,'items_summary',x.items_summary) order by x.ready_at),'[]'::jsonb)
from (select d.order_id,d.user_id,d.collection_location_id,min(d.ready_at) ready_at,string_agg((coalesce(cp.name,sp.name)||' × '||d.quantity_required::text),', ' order by sp.name) items_summary
      from public.club_supplier_demand d join public.club_supplier_products sp on sp.id=d.supplier_product_id left join public.club_commerce_products cp on cp.id=sp.club_product_id
      where d.organisation_id=p_organisation_id and d.status='ready_for_collection' and (p_location_id is null or d.collection_location_id=p_location_id) group by d.order_id,d.user_id,d.collection_location_id) x
left join public.club_customers c on c.organisation_id=p_organisation_id and c.user_id=x.user_id
left join public.club_locations l on l.id=x.collection_location_id and l.organisation_id=p_organisation_id
where public.club_capability_allowed(p_organisation_id,auth.uid(),'commerce.collections_manage')
  and not exists (select 1 from public.club_supplier_demand pending where pending.organisation_id=p_organisation_id and pending.order_id=x.order_id and pending.status not in ('ready_for_collection','collected','cancelled'));
$$;
revoke all on function public.club_list_ready_collections(uuid,uuid) from public,anon; grant execute on function public.club_list_ready_collections(uuid,uuid) to authenticated;

create or replace function public.club_confirm_collection(p_organisation_id uuid,p_order_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_user uuid:=auth.uid(); v_count integer; v_ready integer; v_now timestamptz:=now();
begin
 if v_user is null or not public.club_capability_allowed(p_organisation_id,v_user,'commerce.collections_manage') then raise exception 'Collection access is not permitted' using errcode='42501'; end if;
 perform 1 from public.club_supplier_demand where organisation_id=p_organisation_id and order_id=p_order_id for update;
 select count(*) filter (where status in ('ready_for_collection','collected')), count(*) filter (where status='ready_for_collection') into v_count,v_ready from public.club_supplier_demand where organisation_id=p_organisation_id and order_id=p_order_id;
 if v_count=0 then raise exception 'Collection order not found' using errcode='P0002'; end if;
 if exists(select 1 from public.club_supplier_demand where organisation_id=p_organisation_id and order_id=p_order_id and status not in ('ready_for_collection','collected','cancelled')) then raise exception 'Order is not ready for collection' using errcode='22023'; end if;
 if v_ready=0 then return jsonb_build_object('status','already_collected','order_id',p_order_id); end if;
 update public.club_supplier_demand set status='collected',collected_at=coalesce(collected_at,v_now),collected_by=coalesce(collected_by,v_user),updated_at=v_now where organisation_id=p_organisation_id and order_id=p_order_id and status='ready_for_collection';
 return jsonb_build_object('status','collected','order_id',p_order_id,'collected_at',v_now,'collected_by',v_user);
end; $$;
revoke all on function public.club_confirm_collection(uuid,uuid) from public,anon; grant execute on function public.club_confirm_collection(uuid,uuid) to authenticated;

create or replace function public.club_list_member_supplier_fulfilment(p_organisation_id uuid,p_user_id uuid)
returns jsonb language sql security definer set search_path=pg_catalog,public as $$
select coalesce(jsonb_agg(jsonb_build_object('order_id',d.order_id,'status',case when bool_and(d.status='collected') then 'collected' when bool_and(d.status in ('ready_for_collection','collected')) then 'ready_for_collection' when bool_or(d.status='ordered') then 'awaiting_delivery' else 'order_confirmed' end,'ready_at',max(d.ready_at)) order by max(d.created_at) desc),'[]'::jsonb)
from public.club_supplier_demand d where d.organisation_id=p_organisation_id and d.user_id=p_user_id and auth.uid()=p_user_id group by d.order_id;
$$;
revoke all on function public.club_list_member_supplier_fulfilment(uuid,uuid) from public,anon; grant execute on function public.club_list_member_supplier_fulfilment(uuid,uuid) to authenticated;
