import { redirect } from "next/navigation";
import { AppNav } from "@/components/app-nav";
import { AppShell, BackButton, EmptyState, PageHeader, Surface } from "@/components/ui";
import { ClubSectionNav } from "@/components/club-shell";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOperationalContext } from "@/lib/club-server-context";
import { resolveClubCapabilities } from "@/lib/club-capabilities";

const groups = [{ label: "Members & memberships", match: ["members.", "memberships."] }, { label: "Payments & cash", match: ["payments.", "cash.", "refunds."] }, { label: "Inventory", match: ["inventory."] }, { label: "Classes & services", match: ["classes.", "services."] }, { label: "Administration", match: ["staff.", "induction."] }];
const humanCapability = (value: string) => ({ "members.view": "View members", "members.create": "Add members", "memberships.assign": "Assign memberships", "payments.record_cash": "Record cash", "cash.reconcile": "Reconcile cash", "inventory.adjust": "Adjust stock", "classes.manage": "Manage classes", "services.manage": "Manage services", "induction.manage_policy": "Manage induction", "staff.permissions_manage": "Manage staff permissions" } as Record<string, string>)[value] ?? value.replace(/[._]/g, " ");

export default async function ClubStaffPage({ searchParams }: { searchParams?: Promise<{ org?: string }> }) {
  const supabase = await serverSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/account?mode=signIn");
  const context = await resolveClubOperationalContext(supabase, user.id, (await searchParams)?.org);
  if (!context || !["gym_admin", "owner"].includes(context.role)) return <AppShell className="module-page club-page"><PageHeader title="Staff" description="Staff management is restricted to organisation managers." /><EmptyState title="Management access required">Ask an owner to review your Club role.</EmptyState><AppNav /></AppShell>;
  const members = await context.repository.listMembers(context.organisation.id); const staff = members.filter(member => ["gym_staff", "gym_admin", "owner"].includes(member.role)); const capabilities = resolveClubCapabilities(context.role);
  return <AppShell className="module-page club-page"><PageHeader eyebrow="R12 CLUB · STAFF" title="Staff" description="Review who can operate this Club and what they can do." /><ClubSectionNav organisation={context.organisation} role={context.role} contexts={context.availableContexts} /><Surface><div className="section-header"><div><span className="eyebrow">STAFF PROFILES</span><h2>People with Club access</h2></div></div>{staff.length ? staff.map(member => <div className="club-detail-row staff-row" key={member.id}><div><strong>{member.role === "owner" ? "Owner / Manager" : member.role === "gym_admin" ? "Manager" : "Staff"}</strong><span className="muted">{member.active ? "Active" : "Inactive"} · {member.userId === user.id ? "You" : "Club account"}</span></div><span className="muted">{capabilities.length} permissions</span><button type="button" className="secondary" disabled={member.role === "owner"}>Manage permissions</button></div>) : <p className="muted">No operational staff profiles are configured.</p>}</Surface><Surface><span className="eyebrow">YOUR PERMISSIONS</span><p className="muted">Grouped for quick review. Security remains enforced by the server.</p><div className="permission-groups">{groups.map(group => { const items = capabilities.filter(capability => group.match.some(prefix => capability.startsWith(prefix))); return <div className="permission-group" key={group.label}><strong>{group.label}</strong><span>{items.length ? items.map(humanCapability).join(" · ") : "None enabled"}</span></div>; })}</div></Surface><BackButton href={`/club?org=${encodeURIComponent(context.organisation.id)}`}>Back to overview</BackButton><AppNav /></AppShell>;
}
