import { redirect } from "next/navigation";
import { AppShell, PageHeader, Surface } from "@/components/ui";
import { AppNav } from "@/components/app-nav";
import { serverSupabase } from "@/lib/supabase-server";
import { resolveClubOrganisationContext } from "@/lib/club-server-context";
import { GLOW_ZONE_LOCATION, glowZoneHours, glowZonePackages, glowZoneSafety } from "@/lib/glow-zone";
import { getGlowBalanceAction } from "@/app/club/sunbeds/actions";
import { GlowZoneActivity } from "@/components/glow-zone-activity";
export default async function GlowZonePage({searchParams}:{searchParams?:Promise<{org?:string}>}){const c=await serverSupabase();const{data:{user}}=await c.auth.getUser();if(!user)redirect("/account?mode=signIn");const ctx=await resolveClubOrganisationContext(c,user.id,(await searchParams)?.org);if(!ctx)return <AppShell><PageHeader title="GLOW ZONE"/><p>Connect your gym to view GLOW ZONE.</p></AppShell>;const profile=await ctx.repository.getMemberOperationalProfile(ctx.organisation.id,user.id);const balance=await getGlowBalanceAction({organisationId:ctx.organisation.id,userId:user.id});const minutes=balance.ok?balance.balance.minutes:profile.serviceCredits.filter(x=>x.creditKey==="sunbed_minutes").reduce((n,x)=>n+x.balanceQuantity,0);const member=profile.memberships.some(x=>x.status==="active");return <AppShell className="module-page member-area-page"><PageHeader eyebrow="GLOW ZONE" title="GLOW ZONE" description={`Sunbeds at ${GLOW_ZONE_LOCATION}.`}/><Surface><span className="eyebrow">MY GLOW</span><h2>{minutes} minutes available</h2>{balance.ok&&balance.balance.next_expiry?<p className="muted">Next expiry: {new Date(balance.balance.next_expiry).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</p>:null}<p className="muted">Reception can find your account by name. Glow Pass is coming soon.</p><button className="primary" type="button" disabled>Glow Pass — coming soon</button></Surface><GlowZoneActivity organisationId={ctx.organisation.id} userId={user.id}/><Surface><span className="eyebrow">BUY MINUTES</span>{glowZonePackages.filter(p=>member||!p.membersOnly).map(p=><div className="club-detail-row" style={{padding:"14px 0",gap:16}} key={p.id}><span style={{display:"grid",gap:4}}><strong>{p.name}</strong><small>{p.minutes} minutes{p.membersOnly?" · Member price":""}</small></span><strong>£{(p.priceMinor/100).toFixed(2)}</strong></div>)}<p className="muted">Purchase at reception.</p></Surface><Surface><span className="eyebrow">OPENING HOURS</span>{glowZoneHours.map(x=><p key={x} className="muted">{x}</p>)}</Surface><Surface><span className="eyebrow">BEFORE YOU TAN</span>{glowZoneSafety().map(x=><p key={x} className="muted">{x}</p>)}</Surface><AppNav/></AppShell>}
