import { redirect } from "next/navigation";
import { serverSupabase } from "@/lib/supabase-server";
import { clubRepository } from "@/lib/club-repository";
import { memberOrderStateLabel } from "@/lib/club-operational";
import { AppShell, EmptyState, PageHeader, Surface, BackButton } from "@/components/ui";

const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
type RefundLine={productName:string;quantity:number;amountMinor:number};
type Refund={id:string;amountMinor:number;createdAt:string;lines:RefundLine[]};

export default async function MemberOrders({searchParams}:{searchParams?:Promise<{org?:string;order?:string}>}) {
 const client=await serverSupabase(); const {data:{user}}=await client.auth.getUser(); if(!user)redirect("/account?mode=signIn&next=%2Fmember-hub%2Forders");
 const params=await searchParams; const {data}=await client.rpc("club_list_my_memberships"); const rows=Array.isArray(data)?data as Array<Record<string,unknown>>:[]; const row=rows.find(value=>String((value.organisation as Record<string,unknown>|undefined)?.id)===params?.org)??rows[0];
 if(!row)return <AppShell className="module-page member-area-page"><PageHeader title="Order history"/><EmptyState title="Connect your gym first">Your orders will appear once a membership is linked.</EmptyState><BackButton href="/member-hub">Back to Member Area</BackButton></AppShell>;
 const org=row.organisation as Record<string,unknown>; const organisationId=String(org.id); const repository=clubRepository(client);
 const [profile,allOrders,creditResult,supplierResult]=await Promise.all([repository.getMemberOperationalProfile(organisationId,user.id),repository.listOrders(organisationId),client.rpc("club_list_my_service_credit_balances",{p_organisation_id:organisationId}),client.rpc("club_list_member_supplier_fulfilment",{p_organisation_id:organisationId,p_user_id:user.id})]);
 const orders=allOrders.filter(order=>order.userId===user.id||(profile.customer?.id&&order.customerId===profile.customer.id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); const selected=params?.order?orders.find(order=>order.id===params.order):undefined;
 const creditRows=Array.isArray(creditResult.data)?(creditResult.data as Array<Record<string,unknown>>).filter(item=>String(item.credit_key)!=="sunbed_minutes"):[];
 const supplierRows=Array.isArray(supplierResult.data)?supplierResult.data as Array<Record<string,unknown>>:[];
 const fulfilment=new Map(supplierRows.map(item=>[String(item.order_id),String(item.status)]));
 const serviceIds=[...new Set(creditRows.map(item=>String(item.credit_key).replace("pt_sessions:","")).filter(id=>/^[0-9a-f-]{36}$/i.test(id)))];
 const {data:serviceRows}=serviceIds.length?await client.from("club_services").select("id,name").eq("organisation_id",organisationId).in("id",serviceIds):{data:[]};
 const serviceNames=new Map((Array.isArray(serviceRows)?serviceRows:[]).map(service=>[String(service.id),String(service.name)]));
 const refundResult=selected?await client.rpc("club_list_my_order_refunds",{p_organisation_id:organisationId,p_order_id:selected.id}):null;
 const refunds=Array.isArray(refundResult?.data)?refundResult.data as Refund[]:[];
 const memberStatus=(order:{id:string;status:string})=>order.status==="refunded"||order.status==="cancelled"?memberOrderStateLabel(order.status):fulfilment.has(order.id)?memberOrderStateLabel(fulfilment.get(order.id)!):memberOrderStateLabel(order.status);
 return <AppShell className="module-page club-page member-area-page"><PageHeader title={selected?"Order receipt":"Order history"} description={String(org.name)}/>{creditResult.error?<Surface className="member-order-history"><span className="eyebrow">YOUR SERVICES</span><h2>Service balances unavailable</h2><p className="muted">Your current credits couldn’t be loaded right now. Please try again later or ask your gym.</p></Surface>:creditRows.length?<Surface className="member-order-history"><span className="eyebrow">YOUR SERVICES</span><h2>Packages &amp; credits</h2>{creditRows.map((item,index)=>{const key=String(item.credit_key);const serviceId=key.replace("pt_sessions:","");const expiry=item.expires_at?String(item.expires_at):undefined;const remaining=Number(item.remaining_quantity);const unit=String(item.unit);return <div className="club-detail-row" key={`${key}-${expiry??"open"}-${index}`}><span><strong>{serviceNames.get(serviceId)??serviceCreditLabel(key,unit)}</strong>{expiry?<small>Valid until {date(expiry)}</small>:null}</span><b>{remaining} {serviceCreditUnit(key,unit,remaining)} left</b></div>})}</Surface>:null}
 {selected?<Surface className="member-order-receipt"><p className="eyebrow">ORDER {selected.id.slice(0,8).toUpperCase()}</p><p className="muted">{date(selected.createdAt)} · {memberStatus(selected)}</p>{selected.items.map(item=><div className="club-detail-row" key={item.id}><span><strong>{item.productName}</strong><small>{item.quantity} × {money(item.unitPriceMinor,selected.currency)}</small></span><strong>{money(item.lineTotalMinor,selected.currency)}</strong></div>)}<div className="club-detail-row"><span>Total</span><strong>{money(selected.totalMinor,selected.currency)}</strong></div>{refundResult?.error?<p className="muted">Refund details are temporarily unavailable.</p>:refunds.length?<section aria-label="Refund history"><h2>{refunds.reduce((sum,refund)=>sum+refund.amountMinor,0)>=selected.totalMinor?"Fully refunded":"Partially refunded"}</h2><p className="muted">Total refunded: {money(refunds.reduce((sum,refund)=>sum+refund.amountMinor,0),selected.currency)}</p>{refunds.map(refund=><div className="member-refund-entry" key={refund.id}><div className="club-detail-row"><span><strong>Refunded</strong><small>{date(refund.createdAt)}</small></span><b>−{money(refund.amountMinor,selected.currency)}</b></div>{refund.lines.map((line,index)=><p className="muted" key={`${refund.id}-${index}`}>{line.productName}{line.quantity>0?` · ${line.quantity} ${line.quantity===1?"unit":"units"}`:""} · {money(line.amountMinor,selected.currency)}</p>)}</div>)}</section>:null}<BackButton href={`/member-hub/orders?org=${encodeURIComponent(organisationId)}`}>Back to Order History</BackButton></Surface>:orders.length?<Surface className="member-order-history"><span className="eyebrow">PREVIOUS PURCHASES</span>{orders.map(order=><a className="navigation-row" key={order.id} href={`/member-hub/orders?org=${encodeURIComponent(organisationId)}&order=${encodeURIComponent(order.id)}`}><span><strong>{date(order.createdAt)} · {memberStatus(order)}</strong><small>{order.items.map(item=>`${item.productName} ×${item.quantity}`).join(", ")}{fulfilment.has(order.id)?` · Supplier order: ${memberOrderStateLabel(fulfilment.get(order.id)!)}`:""}</small></span><b>{money(order.totalMinor,order.currency)}</b></a>)}<BackButton href="/member-hub">Back to Member Area</BackButton></Surface>:<><EmptyState title="No orders yet">Completed and pending purchases will appear here.</EmptyState><BackButton href="/member-hub">Back to Member Area</BackButton></>}</AppShell>;
}

function serviceCreditLabel(key:string,unit:string){return ({sunbed_minutes:"GLOW Zone",class_sessions:"Class credit",transformation_sessions:"Transformation package"} as Record<string,string>)[key]??(unit==="minute"?"Service minutes":"Service credit");}
function serviceCreditUnit(key:string,unit:string,quantity:number){if(key==="sunbed_minutes"||unit==="minute")return quantity===1?"minute":"minutes";if(unit==="session")return quantity===1?"session":"sessions";if(unit==="class")return quantity===1?"class":"classes";return quantity===1?"credit":"credits";}
