import { redirect } from "next/navigation";
import { serverSupabase } from "@/lib/supabase-server";
import { clubRepository } from "@/lib/club-repository";
import { AppShell, EmptyState, PageHeader, Surface, BackButton } from "@/components/ui";

const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(minor/100);
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));

export default async function MemberOrders({searchParams}:{searchParams?:Promise<{org?:string;order?:string}>}) {
 const client=await serverSupabase(); const {data:{user}}=await client.auth.getUser(); if(!user)redirect("/account?mode=signIn&next=%2Fmember-hub%2Forders");
 const params=await searchParams; const {data}=await client.rpc("club_list_my_memberships"); const rows=Array.isArray(data)?data as Array<Record<string,unknown>>:[]; const row=rows.find(value=>String((value.organisation as Record<string,unknown>|undefined)?.id)===params?.org)??rows[0];
 if(!row)return <AppShell className="module-page member-area-page"><PageHeader title="Order history"/><EmptyState title="Connect your gym first">Your orders will appear once a membership is linked.</EmptyState><BackButton href="/member-hub">Back to Member Area</BackButton></AppShell>;
 const org=row.organisation as Record<string,unknown>; const organisationId=String(org.id); const repository=clubRepository(client);
 const [profile,allOrders,packageResult]=await Promise.all([repository.getMemberOperationalProfile(organisationId,user.id),repository.listOrders(organisationId),client.rpc("club_list_my_pt_package_balances",{p_organisation_id:organisationId})]);
 const orders=allOrders.filter(order=>order.userId===user.id||(profile.customer?.id&&order.customerId===profile.customer.id)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)); const selected=params?.order?orders.find(order=>order.id===params.order):undefined;
 const packageRows=Array.isArray(packageResult.data)?packageResult.data as Array<Record<string,unknown>>:[];
 const serviceIds=[...new Set(packageRows.map(item=>String(item.credit_key).replace("pt_sessions:","")).filter(id=>/^[0-9a-f-]{36}$/i.test(id)))];
 const {data:serviceRows}=serviceIds.length?await client.from("club_services").select("id,name").eq("organisation_id",organisationId).in("id",serviceIds):{data:[]};
 const serviceNames=new Map((Array.isArray(serviceRows)?serviceRows:[]).map(service=>[String(service.id),String(service.name)]));
 return <AppShell className="module-page club-page member-area-page"><PageHeader title={selected?"Order receipt":"Order history"} description={String(org.name)}/>{packageRows.length?<Surface className="member-order-history"><span className="eyebrow">YOUR PT SESSIONS</span><h2>Packages & credits</h2>{packageRows.map((item,index)=>{const id=String(item.credit_key).replace("pt_sessions:","");const expiry=item.expires_at?String(item.expires_at):undefined;const remaining=Number(item.remaining_quantity);return <div className="club-detail-row" key={`${id}-${expiry??"open"}-${index}`}><span><strong>{serviceNames.get(id)??"PT package"}</strong>{expiry?<small>Valid until {date(expiry)}</small>:null}</span><b>{remaining} {remaining===1?"session":"sessions"} left</b></div>})}</Surface>:null}{selected?<Surface className="member-order-receipt"><p className="eyebrow">ORDER {selected.id.slice(0,8).toUpperCase()}</p><p className="muted">{date(selected.createdAt)} · {selected.status}</p>{selected.items.map(item=><div className="club-detail-row" key={item.id}><span><strong>{item.productName}</strong><small>{item.quantity} × {money(item.unitPriceMinor,selected.currency)}</small></span><strong>{money(item.lineTotalMinor,selected.currency)}</strong></div>)}<div className="club-detail-row"><span>Total</span><strong>{money(selected.totalMinor,selected.currency)}</strong></div><p className="muted">Payment and fulfilment status: {selected.status}.</p><BackButton href={`/member-hub/orders?org=${encodeURIComponent(organisationId)}`}>Back to Order History</BackButton></Surface>:orders.length?<Surface className="member-order-history"><span className="eyebrow">PREVIOUS PURCHASES</span>{orders.map(order=><a className="navigation-row" key={order.id} href={`/member-hub/orders?org=${encodeURIComponent(organisationId)}&order=${encodeURIComponent(order.id)}`}><span><strong>{date(order.createdAt)}</strong><small>{order.items.map(item=>`${item.productName} ×${item.quantity}`).join(", ")}</small></span><b>{money(order.totalMinor,order.currency)}</b></a>)}<BackButton href="/member-hub">Back to Member Area</BackButton></Surface>:<><EmptyState title="No orders yet">Completed and pending purchases will appear here.</EmptyState><BackButton href="/member-hub">Back to Member Area</BackButton></>}</AppShell>;
}
